### ISSUE TITLE
PDF generation fails for Large HTML files.

### ISSUE THREAD

**Issue by varshluck** [danfickle/openhtmltopdf#102]
When trying to Convert large size html file to pdf ..Jsoup returns a null document.
I'm taking 4-9 MB file size html with a table of 10k-50k & table rows with 3-6 columns.

How to resolve this issue?
I works fine for smaller datasets. 
[Customer_Balance.zip](https://github.com/danfickle/openhtmltopdf/files/1052142/Customer_Balance.zip)
ns

**Comment by danfickle** [comment]
Hi @varshluck 

You could try [JTidy instead](https://github.com/danfickle/openhtmltopdf/issues/85#issuecomment-300192346)

**Comment by danfickle** [comment]
I'm closing this as appears to be a problem with Jsoup rather than us. Reopen if needed.
