### ISSUE TITLE
Rupee symbol rendering is failing 

### ISSUE THREAD

**Issue by revoorunischal** [danfickle/openhtmltopdf#106]
Hi ,

   the rupee symbol rendering is failing and is not able to convert the hex code nor the decimal value . It is able to render other symbols but rupee its not able to render and shows a # .

Reference 

with rupee symbol 

![image](https://user-images.githubusercontent.com/10596777/27943950-ec0e5b94-6300-11e7-92eb-672c02e39aff.png)

Rupee hex code &#8377; `&#8377;`

with euro 

![image](https://user-images.githubusercontent.com/10596777/27943977-24c17fac-6301-11e7-8ef6-0722c790bf4b.png)

euro hex code   &#8364; `&#8364;`

**Comment by danfickle** [comment]
Hi @revoorunischal 
Did you solve this? I think you just have to provide a font with the appropriate character glyph. Embedding fonts in covered in the template authors guide, linked to from the README.
