### ISSUE TITLE
I sometimes see this: Finalizer,org.apache.pdfbox.cos.COSDocument,o.a.p.c.COSDocument,WARN ,  Warning: You did not close a PDF Document

### ISSUE THREAD

**Issue by dtrucken** [danfickle/openhtmltopdf#109]
Finalizer,org.apache.pdfbox.cos.COSDocument,o.a.p.c.COSDocument,WARN ,  Warning: You did not close a PDF Document

Looking through the code, it does appear that things are properly closed.  The only thing I can think of is the order is wrong somewhere, and the COSDocument isn't closed soon enough (thus this finalizer kicks in)

Maybe since I'm streaming this to the browser (not saving to disk first), if the connection is interrupted, there is a missing try-finally block?

**Comment by danfickle** [comment]
Thanks, you're right! ````PDDocument::close```` is not being called in a ````finally```` block. I'll have to think about where to put it.

**Comment by danfickle** [comment]
Should be fixed with above commit. Closing.
