### ISSUE TITLE
Not rendering Cyrillic content of html to pdf

### ISSUE THREAD

**Issue by UmeshRajani** [danfickle/openhtmltopdf#114]
Hello,

I have html page which contains Cyrillic alphabets, I'm able to convert html to pdf using this library but when html contains Cyrillic alphabets it just created with '###################', 

I was trying same since many days with different java library but didn't success. itextpdf is there but that is not for free.

So anybody faced the issue like this, please suggest me.

Thank you,
Umesh

**Comment by Jugen** [comment]
Hi Umesh

Try using the openhtmltopdf-jsoup-dom-converter to convert the html to a dom first and then converting that to pdf. Something like so:

    org.w3c.dom.Document  doc = DOMBuilder.jsoup2DOM( Jsoup.parse( html, baseURI ) );
    PdfRendererBuilder  builder = new PdfRendererBuilder();
    builder.withW3cDocument( doc, baseURI );

regards
Jurgen

**Comment by danfickle** [comment]
Assumed solved. Please see the fonts wiki page. Reopen if required.

**Comment by Alexander-Bolotov** [comment]
I have the same problem with Cyrillic. Jugen's advice doesn't help. Is there any other solution

**Comment by danfickle** [comment]
Which font are you using? The built in fonts will not cover Cyrillic.

**Comment by Alexander-Bolotov** [comment]
my code:

**Comment by Alexander-Bolotov** [comment]
```
try {
            final org.w3c.dom.Document w3cDoc = DOMBuilder.jsoup2DOM(Jsoup.parse(readMultipartFile(file), "/"));
            final OutputStream outStream = new FileOutputStream("test11.pdf");
            final PdfRendererBuilder pdfBuilder = new PdfRendererBuilder();
            pdfBuilder.useFastMode();
            pdfBuilder.useFont(new File("/fonts/Times.ttf"), "Times");
            pdfBuilder.withW3cDocument(w3cDoc, "/");
            pdfBuilder.toStream(outStream);
            pdfBuilder.run();
            outStream.close();
        } catch (Exception e) {
            System.out.println("PDF could not be created: " + e.getMessage());
        }
        System.out.println("Finish.");
        return "Ok";
```

```
public String readMultipartFile(MultipartFile file) throws IOException {
        String createdFile = createFile(file);
        FileInputStream fileOutputStream = new FileInputStream(new File(String.valueOf(createdFile)));
        final StringBuilder sb = new StringBuilder();
        final Reader r = new InputStreamReader(Objects.requireNonNull(fileOutputStream));
        char[] buf = new char[1024];
        int amt = r.read(buf);
        while(amt > 0) {
            sb.append(buf, 0, amt);
            amt = r.read(buf);}
        fileOutputStream.close();
        return sb.toString();
    }
```

**Comment by Alexander-Bolotov** [comment]
how to connect fonts correctly?

**Comment by danfickle** [comment]
In your css `font-family: 'Times';` 

It could also be a char set problem. You should specify a char set in the `InputStreamReader` constructor so you know what charset rather than the system default which can vary between machines. Same in your createfile method.

Also, be very careful when using untrusted user provided Html with this library.
