### ISSUE TITLE
pdf Garbled ，  If you support GDk and UTF-8

### ISSUE THREAD

**Issue by githublaohu** [danfickle/openhtmltopdf#115]
# html
``` html
<head>
    <meta HTTP-EQUIV="Content-Type" CONTENT="text/html;" charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Examples</title>
</head>
<body>
    <div >
        <h1>  你好！   <small>Subtext for header</small></h1>
    </div>
</body>
</html>
```
# java code
``` java
PdfRendererBuilder builder = new PdfRendererBuilder( ) ;
builder.withHtmlContent( new String( baos.toByteArray( ) ) , "./" ).				
toStream( os ) .
useFont( new FontFileFontSupplier("verdana.ttf") , "UTF-8" ).
run( ) ;
````
Sorry for the inconvenience，

**Comment by danfickle** [comment]
Hi @githublaohu 

+ You should use the two argument String constructor with "UTF-8".
+ The second argument of ````useFont```` is the CSS name of the font such as "verdana".
+ The font won't be automatically be used but must be referenced from CSS:
````html
<html>
<head>
<style>
* {
  font-family: 'verdana';
}
</style>
</head>
<body>
Some text
</body>
</html>
````
+ If the previous ideas don't work, please make sure the font file has glyphs for the text you are trying to output.

Thanks for using this project and my apologies for not responding in a timely manner.

**Comment by githublaohu** [comment]
thank you. comment.
So sorry ，no realization。
Maybe it's a lack of personal ability. Can you give me an example?  Forgive me for such a brazen request, but I really can't make up my mind。Supporting UTF-8 is a very important thing

**Comment by danfickle** [comment]
Code:
````java
public static void main(String[] args) throws Exception {
		OutputStream os = new FileOutputStream("/Users/me/Documents/pdftests/mytest-115.pdf");
		PdfRendererBuilder builder = new PdfRendererBuilder();
		builder.withUri("file:///Users/me/Documents/pdftests/issue-115.htm");
		builder.toStream(os);
		builder.run();
	}
````
HTML:
````html
<html>
<head>
<title>Examples</title>
<style>
@font-face {
    font-family: 'cjk';
    src: url(NotoSansCJKtc-Regular.ttf);
}
* {
  font-family: 'cjk', sans-serif;
}
</style>
</head>
<body>
    <div>
        <h1>  你好！   <small>Subtext for header</small></h1>
    </div>
</body>
</html>
````
Result:
![screenshot-115](https://user-images.githubusercontent.com/1415728/30237676-6bcd15ae-957a-11e7-95bb-13eb4d21078c.png)

See #46 for the CJK font I used.

**Comment by danfickle** [comment]
Assumed solved, re-open if required.
