### ISSUE TITLE
Support running elements in page headers and footers

### ISSUE THREAD

**Issue by dbellingroth** [danfickle/openhtmltopdf#118]
Currently there is no support to place any html elements into repeating headers and footers of the generated pages. That makes it impossible to use things like links or texts with different font weights. A nice solution for this would be to support CSS _running elements_ as specified [here](https://www.w3.org/TR/css-gcpm-3/#running-elements). This would allow for an arbitrary html element to be used as the content of a margin box.

**Comment by Bigdatha** [comment]
Hello dbellingroth,

this already works (at least for me), see [Template.html.txt](https://github.com/danfickle/openhtmltopdf/files/1245428/Template.html.txt) and the corresponding result [Template.pdf](https://github.com/danfickle/openhtmltopdf/files/1245429/Template.pdf).

Regards,
Bigdatha

**Comment by dbellingroth** [comment]
Thank you very much. There was a misunderstanding on my side.

**Comment by DemeSteve** [comment]
This doesn't work for me if I feed the html directly like this:

var pdf = Pdf
                .From(<the input html from Bigdatha's comment>)
                .OfSize(PaperSize.A3)
                .WithoutOutline()
                .EncodedWith("UTF-8")
                .Landscape()
                .WithMargins(1.25.Centimeters())
                .Comressed()
                .Content();
