### ISSUE TITLE
Image in pdf is tiny

### ISSUE THREAD

**Issue by jayrich78** [danfickle/openhtmltopdf#124]
Hi,

I write a pdf-File from html. There is an inline image in it, with a given size. In the generated pdf the image is much smaller as it should. Is it a bug, or is a mistake of mine?

This is the code for generating the pdf:

`			OutputStream os = new FileOutputStream(selectedFile));
			PdfRendererBuilder builder = new PdfRendererBuilder();
			builder.withW3cDocument(DOMBuilder.jsoup2DOM(getDOMFromEditor()), "xxx");
			builder.toStream(os);
			builder.run();
`

This is a snipped from the html source. The html image tag I want to convert (I shortened the image data, because its too long):
 
   ` <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAACRCAIAAAAJu2D2AACAAElEQVR42jS8B3Qc2Xmty3V15ZEl28/3KTlIlmTLSrZkpZGsOJoZjUajyXkYZpgzCQIgciAAggRJMA5zAEEwgACInIHOOeccqquqc6ycuhsg/U6D9631r7MK1dXVi11f773[...]etQ3Xld3Vo724uAB/v/AOF+QKQf54M/AAAAAElFTkSuQmCC" width="200px">`

It looks like this:
![openhtml](https://user-images.githubusercontent.com/31685645/30099623-930db4e8-92e6-11e7-986d-b36f8271cf83.PNG)

And this is the result:
[openhtml.pdf](https://github.com/danfickle/openhtmltopdf/files/1280193/openhtml.pdf)
Looks like this:
![openhtml2](https://user-images.githubusercontent.com/31685645/30099707-d4d909d6-92e6-11e7-91f7-22f2cdf94110.PNG)

Maybe an userguide would help, but I did not found one that helps me.

Thanks for any help.

Juliane

**Comment by danfickle** [comment]
Hi @jayrich78 

I couldn't replicate this. My code:
````java
	public static void main(String[] args) throws Exception {
		String html = FileUtils.readFileToString(new File("/Users/me/Documents/pdftests/test-124.htm"), "UTF-8");
		
		OutputStream os = new FileOutputStream("/Users/me/Documents/pdftests/mytest-124.pdf");
		PdfRendererBuilder builder = new PdfRendererBuilder();
		Document doc = DOMBuilder.jsoup2DOM(Jsoup.parse(html));
		builder.withW3cDocument(doc, "xxx");
		builder.toStream(os);
		builder.run();
	}
````
My html:
````html
<html>
<head>
</head>
<body>
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUg ..."  alt="map" width="200px"/>Some text.
</body>
</html>
````
The data uri was generated from your first screenshot at:
[Data URI Generator](https://dopiaza.org/tools/datauri/index.php).

If you are still having problems I would suggest posting the original map image here as a file (if copyright permits). Also what version of OpenHTMLtoPDF are you using?

**Comment by jayrich78** [comment]
Hi @danfickle 

I tried to put the imagedirectly under the body-tag, in original code is in some divs wrapped, but it makes no difference here.
 
Here is the one image which does not work for me, it is from OSM.
![img20171209065628](https://user-images.githubusercontent.com/31685645/30312781-4700dfe4-979b-11e7-8046-57897b36cfc7.png)

I use version 0.0.1-RC11
Could this be a problem with the stylesheet? There are lots of warnings. And when I remove the stylesheet it works. 

Here is my test html:
[htmlex.txt](https://github.com/danfickle/openhtmltopdf/files/1295037/htmlex.txt)

**Comment by jayrich78** [comment]
I tested it i little more. It is maybe a problem with the stylesheet and our proxy.
In the distributed version, we use a local stylesheet and it looks good. 
I have the problem only in my IDE, so I will stop spending time with this.

Sorry for wasting your time, I should have done all these test steps before I wrote here
