### ISSUE TITLE
Can we generate a horizontally scrollable pdf using this library.What would be the steps?

### ISSUE THREAD

**Issue by varshluck** [danfickle/openhtmltopdf#126]

**Comment by danfickle** [comment]
If you mean a multi-page PDF document that scrolls horizontally, I don't believe the PDF specification allows that:
https://forums.adobe.com/thread/2084640

However, if you mean layout the pages as normal but render them horizontally to a single page which could be scrolled left to right, that should be doable.

It would be done by replicating the ````writePDF```` method in ````PdfBoxRenderer```` with appropriate changes. I could have a crack at this if you like.

Out of interest, what is your use case for this functionality?

**Comment by varshluck** [comment]
We are using this for our reporting framework .
When number of columns of our report exceed beyond a certain number the generated html has that table going out of bounds which generates a pdf with columns getting excluded.

**Comment by danfickle** [comment]
I think this is a generic problem, all content outside the page margin will be silently discarded. I think better behavior would be to insert a page with the clipped content. This would be behind a CSS flag to avoid backwards compatibility problems.

**Comment by danfickle** [comment]
I have added a page on [cut-off page support on the wiki](https://github.com/danfickle/openhtmltopdf/wiki/Cut-off-page-support).

Here is a sample PDF:

[overflow.pdf](https://github.com/danfickle/openhtmltopdf/files/2948071/overflow.pdf)
