### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by banifou** [danfickle/openhtmltopdf#133]
Just tried to export a very simple xhtml file to pdf following the steps (minimal usage) in the guide. Unfortunately I'm getting a  **NullPointerException**. Here is the stacktrace:
```
Schwerwiegend:   java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3023)
	at java.net.URI.<init>(URI.java:595)
	at com.openhtmltopdf.swing.NaiveUserAgent$DefaultUriResolver.resolveURI(NaiveUserAgent.java:471)
	at com.openhtmltopdf.swing.NaiveUserAgent.getXMLResource(NaiveUserAgent.java:352)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.loadDocument(PdfBoxRenderer.java:323)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.setDocumentP(PdfBoxRenderer.java:335)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:261)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:106)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:84)

```
So it seems that bold line in the run function of PdfRendererBuilder is throwing an exception

     ```     
    public void run() throws Exception {
        PdfBoxRenderer renderer = null;
        try {
            **renderer = this.buildPdfRenderer();**
            renderer.layout();
            renderer.createPDF();
        } finally {
            if (renderer != null)
                renderer.cleanup();
        }
    }
```

Thanks

**Comment by danfickle** [comment]
Hi @banifou 

As a guess, I’d say that you are using a null base uri with relative linked resources in your document. If this is not the case can you provide a minimal example of builder code and HTML?

**Comment by banifou** [comment]
Hi @danfickle 

I'm not sure what you mean with null base uri.
I copied the exportToPdfBox in my class and I'm calling it like in the integration-guide:
`exportToPdfBox("/opt/myDir/myFile.xhtml", "/opt/myDir/myFile.pdf");`
I'm using a Linux machine. Besides the exception, the pdf file is generated but is empty.

**Comment by PascalGit1** [comment]
not sure if i should make a sepperate post but im getting the same error, this is the code I use:

```
OutputStream os = null;
		 try {
		os = new FileOutputStream("output.pdf");

		try {
			// There are more options on the builder than shown below.
			PdfRendererBuilder builder = new PdfRendererBuilder();

			builder.withUri("C:/Programs/eclipse Neon/workspace/cucumber/index.html");
			builder.toStream(os);
			builder.run();

		} catch (Exception e) {
			e.printStackTrace();
			// LOG exception
		}    finally {
            try {
                os.close();
         } catch (IOException e) {
                // swallow
         }
		}
    }
  catch (IOException e1) {
         e1.printStackTrace();
         // LOG exception.
  }
```

**Comment by danfickle** [comment]
I believe both of you need to use proper uris rather than a raw path. So perpend with ````file:///```` on Windows and one less slash on Mac/Linux.

**Comment by banifou** [comment]
Yes it's working now. But the generated pdf file looks completely different from the one generated from wkhtmltopdf. When will the first release version be ready?
thanks

**Comment by danfickle** [comment]
It will probably never match WebKit/Blink or even Trident due to the number of developers working on those projects. This means the template author must write HTML with the limitations of the renderer in mind. Notable limitations include no flex support and no support for newer units such as rem, vh and vw.

As to a release version, probably not any time soon, but many people are using it successfully anyway.

**Comment by danfickle** [comment]
I believe a null base uri no longer causes a NPE so closing.
