### ISSUE TITLE
Dotted and dashed table border styles cause errors in Adobe Reader

### ISSUE THREAD

**Issue by tapple** [danfickle/openhtmltopdf#135]
Tables with cell borders styled dotted or dashed render fine in most pdf viewers, but generate an error or render as a blank page when viewer id Adobe Reader DC. Attached are two html files (one dotted, one dashed), and the pdf files they generate

[dashed-border-bug.html.txt](https://github.com/danfickle/openhtmltopdf/files/1342171/dashed-border-bug.html.txt)
[dashed-border-bug.pdf](https://github.com/danfickle/openhtmltopdf/files/1342168/dashed-border-bug.pdf)

[dotted-border-bug.html.txt](https://github.com/danfickle/openhtmltopdf/files/1342172/dotted-border-bug.html.txt)
[dotted-border-bug.pdf](https://github.com/danfickle/openhtmltopdf/files/1342169/dotted-border-bug.pdf)

**Comment by tapple** [comment]
Adobe reader details:
Installed Acrobat: C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe
    Version: 17.12.20098.240878
    Creation Date: 2017/08/24
    Creation Time: 5:10:06 AM
Installed Acrobat: C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe
    Version: 17.12.20098.240878
    Creation Date: 2017/08/24
    Creation Time: 5:10:04 AM

**Comment by rototor** [comment]
@tapple I can reproduce the problem with Acrobat Reader on Mac OS X. I took a quick look into the document using the PDFBox debugger and pre-flight. With the debugger everything seems (and renders) fine.

Preflight reports some errors:
```
The file dotted-border-bug.pdf is not a valid PDF/A-1b file, error(s) :
2.4.1 : Invalid Color space, The operator "RG" can't be used with CMYK Profile on page 1
2.4.1 : Invalid Color space, The operator "RG" can't be used with CMYK Profile on page 1
2.4.1 : Invalid Color space, The operator "RG" can't be used with CMYK Profile on page 1
2.4.1 : Invalid Color space, The operator "RG" can't be used with CMYK Profile on page 1
2.4.1 : Invalid Color space, The operator "rg" can't be used with CMYK Profile on page 1
3.1.1 : Invalid Font definition, Times-Roman: some required fields are missing from the Font dictionary: firstChar, lastChar, widths.
3.1.3 : Invalid Font definition, Times-Roman: FontFile entry is missing from FontDescriptor
7.1 : Error on MetaData, Missing Metadata Key in catalog
```

The reported errors are extra strict, as preflight validates against PDF/A-1b. I think the colorspace stuff should not matter, also the font warnings should not cause that behavior. But it would make sense to fix this warnings.

I don't get any error message from Acrobat Reader. @tapple What exact errors are reported to you by Acrobat Reader?

**Comment by rototor** [comment]
@tapple The problem here was a invalid MiterLimit value of 0. All other PDF viewers just ignore that value, Acrobat Reader stops to render anything  ... #137  fixes this.

I had a similar problem in PDFBoxGraphics2D, which was [found and fixed](https://github.com/rototor/pdfbox-graphics2d/pull/1) by @FabioVassallo
