### ISSUE TITLE
CSS { text-decoration: line-through; } doesn't work properly

### ISSUE THREAD

**Issue by izhenka** [danfickle/openhtmltopdf#136]
CSS property { text-decoration: line-through; } (and "del" tag) doesn't work properly both in sandbox and in actual generated PDF. See picture
![image](https://user-images.githubusercontent.com/16900099/31214943-d90dd5f8-a9ad-11e7-9ade-53628f8d232c.png)

[test case](https://github.com/danfickle/openhtmltopdf/blob/eb69d4ecde6f886705bfcf747e56ae639078d396/tests/diff/fonts/text-decoration/all.xhtml)

**Comment by danfickle** [comment]
Should be fixed. I'll try to do a release tomorrow.
