### ISSUE TITLE
How do you agree that the HTML content starts from the next page? Or paging?

### ISSUE THREAD

**Issue by baihuibo** [danfickle/openhtmltopdf#149]
example html:
```html
<html>
...
<body>
   <div>page1</div>
   <div>page2</div>
   <div>page3</div>
   <div>page4</div>
</body>
</html>
```

The output PDF should have 4 pages, each corresponding to the div.

So what should I do?

**Comment by Jugen** [comment]
Use either: `<div style="page-break-after: always">` or `<div style="page-break-before: always">`

    <html>
    ...
    <body>
       <div>page1</div>
       <div style="page-break-before: always">page2</div>
       <div style="page-break-before: always">page3</div>
       <div style="page-break-before: always">page4</div>
    </body>
    </html>

**Comment by baihuibo** [comment]
Thank you very much
