### ISSUE TITLE
Stream closed exception in String html to pdf generation is occurring 

### ISSUE THREAD

**Issue by revoorunischal** [danfickle/openhtmltopdf#152]
Hi ,
    I have been using String html to pdf generator in generating pdf receipts and it was working fine from long time but from past 20 days in one server among 4 the pdf file generation fails with the following exception stack trace

> java.lang.InternalError: java.io.IOException: Stream closed
>         at sun.util.locale.provider.BreakIteratorProviderImpl.getBreakInstance(BreakIteratorProviderImpl.java:178)
>         at sun.util.locale.provider.BreakIteratorProviderImpl.getLineInstance(BreakIteratorProviderImpl.java:106)
>         at java.text.BreakIterator.createBreakInstance(BreakIterator.java:571)
>         at java.text.BreakIterator.createBreakInstance(BreakIterator.java:553)
>         at java.text.BreakIterator.getBreakInstance(BreakIterator.java:544)
>         at java.text.BreakIterator.getLineInstance(BreakIterator.java:483)
>         at com.openhtmltopdf.layout.SharedContext.<init>(SharedContext.java:133)
>         at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:197)
>         at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:106)
>         at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:84)
>         at com.fonepaisa.fpportal.util.PDFGenerator.generateConsReportFile(PDFGenerator.java:140)
>         at com.fonepaisa.fpportal.service.UIService.sendConsRepNotif(UIService.java:2558)
>         at com.fonepaisa.fpportal.service.UIService$$FastClassBySpringCGLIB$$7a50f9e5.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
>         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
>         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
>         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
>         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
>         at com.fonepaisa.fpportal.service.UIService$$EnhancerBySpringCGLIB$$325cff1e.sendConsRepNotif(<generated>)
>         at com.fonepaisa.fpportal.service.AsyncCallerService.sendConsRepNotif(AsyncCallerService.java:53)
>         at com.fonepaisa.fpportal.service.AsyncCallerService$$FastClassBySpringCGLIB$$206803ca.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
>         at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:108)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.IOException: Stream closed
>         at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
>         at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
>         at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
>         at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
>         at java.io.FilterInputStream.read(FilterInputStream.java:107)
>         at sun.util.locale.provider.RuleBasedBreakIterator.readFile(RuleBasedBreakIterator.java:462)
>         at sun.util.locale.provider.RuleBasedBreakIterator.readTables(RuleBasedBreakIterator.java:375)
>         at sun.util.locale.provider.RuleBasedBreakIterator.<init>(RuleBasedBreakIterator.java:321)
>         at sun.util.locale.provider.BreakIteratorProviderImpl.getBreakInstance(BreakIteratorProviderImpl.java:169)
>         ... 29 more
> 

 This is deployed in tomcat server which is not restarted from nov 8th . The same issue had occured few months ago and had fixed as soon as we restarted the tomcat. So this time before restart i want your help in fixing it fully and not temporarily. 

The following is the code to generate 

```
 public static boolean generateReciptFile(String filePath) {
		OutputStream os = null;
		try {
			os = new FileOutputStream(filePath);
			XRLog.setLoggingEnabled(true);
			XRLog.setLoggerImpl(new Log4JXRLogger()); 
			PdfRendererBuilder builder = new PdfRendererBuilder();
			String feeRecipt = "<html>"
					+ "<head>"
					+ "</head>"
					+ "<body style='font-size : 16px'>"
					+ "        <div style='font-size: 1em;line-height: 1.3;margin: 0 auto ;font-family: sans-serif;width :650px; border:1px solid black;margin-top:20px;padding:15px '>"
					+ "        </div>" 
					+ "</body>" 
					+ "</html>";
			logger.info("fee Data \n"+feeRecipt+"\n dkkbv");
			builder.withHtmlContent(feeRecipt, "");
			builder.toStream(os);
			builder.run();
			os.close();
			return true;
		} catch (Exception e) {
			e.printStackTrace();
			try {
				if (os != null) {
					os.close();
				}
			} catch (IOException e1) {
				e1.printStackTrace();
			}
			return false;
		}
	}
```

**Comment by danfickle** [comment]
This seems to be a common problem with BreakIterator. I googled "breakiterator stream close" and came up with two possible causes:
+ Running out of file descriptors[1]
+ Java being updated[2]

1. https://netbeans.org/bugzilla/show_bug.cgi?id=232823
2. https://issues.collectionspace.org/plugins/servlet/mobile#issue/UCBG-318

You could try listing open file handles on the server that is failing. That would give us an idea if 1 is the cause and also possibly implicate what code is responsible by the files that are open.

**Comment by revoorunischal** [comment]
i guess this is an issue with java update because at 10:30 on  nov 8th the java security update has happened and only one pdf was generated after this and it was failing always after this until the restart which we did yesterday ..

Thanks for the supoprt
