### ISSUE TITLE
Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'

### ISSUE THREAD

**Issue by estevandiedrich** [danfickle/openhtmltopdf#154]
Hi everybody, we are trying to use openhtml2pdf and we had some problems with xalan. After some bug we found where the exception has been thrown, and it was in 'openhtmltopdf-core/src/main;java/com/openhtmltopdf/resource/XMLResource.java' in line 222 aproximadetly, we just add a try/catch to ignore when the attribute XMLConstants.ACCESS_EXTERNAL_DTD is not supported by the xalan. Probably its not the best solucion for this problem, but its a workaround that solves the problem.

**Comment by LaercioMetzner** [comment]
Regards to this issue, openhtmltopdf worked flawlessly when executed only with JSE8, but failed when executed with WildFly and Arquillian in a JEE7 application.

**Comment by dilworks** [comment]
Same case here. After patching XMLResource.java for bypassing #54, I'm now hitting this.

Been a rough testride so far under JBoss containers :/

WildFly 10.1 running on OpenJDK 8 (131-b11) on Debian Jessie.

**Comment by LaercioMetzner** [comment]
Pull Request  #155 had been submitted to fix this  issue. Waiting for merge.

**Comment by danfickle** [comment]
This should be fixed by above commit. I'll close this issue and we can continue JBoss discussion in #54 (hopefully it should all work now). Thanks everyone.

**Comment by Nabarun** [comment]
@danfickle in this solution you are swallowing the exception every time it throws. Will it help in preventing the xxe attacks. I saw a similar bug at https://github.com/ModelDriven/fUML-Reference-Implementation/issues/26 which might be a cause for this issue too
