### ISSUE TITLE
How to make the hyperlinks of table not appear in the generated pdf

### ISSUE THREAD

**Issue by johnny1952** [danfickle/openhtmltopdf#156]
Hi:
My html source :
```html
<tr>
	<td rowspan="1" colspan="1"><a href="/resource?key=com.cibfintech.sonar:analysis&amp;days=14" shape="rect">
		<span>analysis</span>
		</a>
	</td>
	<td rowspan="1" colspan="1">21</td>
	<td rowspan="1" colspan="1">1</td>
	<td rowspan="1" colspan="1">0</td>
	<td rowspan="1" colspan="1">59</td>
	<td rowspan="1" colspan="1">0</td>
	<td rowspan="1" colspan="1">2017-11-27 09:27:16</td>
</tr>
```

And  the generated  pdf file contains the superlink text "/resource?key=com.cibfintech.sonar:analysis&amp;days=14", but I don't hope that. 

The pdf file content like belows:
[pdf contains href text](https://drive.google.com/open?id=1x4T1wC20Tzc2kVLl8NQBOI5olFo4ENMo)

How to avoid this?

Thanks very much.

**Comment by rototor** [comment]
Why do you output the link at the first place if you don't want it? If you get the HTML from some service where you can not control the HTML you could just replace '<a ' and '<\/a>' with '<span ' and '<\/span>'.

**Comment by danfickle** [comment]
Assumed resolved. Thanks @rototor. Please reopen if required.
