### ISSUE TITLE
HTML to PDF not rendered properly/completely

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#166]
Hi,

I'm using your lib to generate PDF out of HTML (both attached [pdf+html.zip](https://github.com/danfickle/openhtmltopdf/files/1611445/pdf.html.zip)). Can you take a look and let me know why the html is not completely rendered in the PDF?

My code is as follows:
` private void createPDFwithOpenPDF(String content, String pdf) throws Exception {

        PdfRendererBuilder builder = new PdfRendererBuilder();
        OutputStream os = new FileOutputStream(pdf);

        org.jsoup.nodes.Document doc = Jsoup.parse(content);

        Document d = DOMBuilder.jsoup2DOM(doc);
        builder.withW3cDocument(d, "http://localhost:8080");
        builder.toStream(os);
        builder.run();
    }`

Thanks

**Comment by mnenchev** [comment]
doc.fromHTML and i'm passing the html as string directly to it.

**Comment by rototor** [comment]
@mnenchev  You mean: Why is the table truncated?

You are using 900px for the width. I don't know the factor for pixel to inch/cm by mind, but there is a certain factor.  And 900px is wider than A4 portrait minus 20 % margin (left+right). You should use cm or in (for inch) here. 
Or maybe you want to use 100% instead of 900px?

**Comment by NewWorldNewCode** [comment]
> Hi,
> 
> I'm using your lib to generate PDF out of HTML (both attached [pdf+html.zip](https://github.com/danfickle/openhtmltopdf/files/1611445/pdf.html.zip)). Can you take a look and let me know why the html is not completely rendered in the PDF?
> 
> My code is as follows:
> ` private void createPDFwithOpenPDF(String content, String pdf) throws Exception {
> 
> ```
>     PdfRendererBuilder builder = new PdfRendererBuilder();
>     OutputStream os = new FileOutputStream(pdf);
> 
>     org.jsoup.nodes.Document doc = Jsoup.parse(content);
> 
>     Document d = DOMBuilder.jsoup2DOM(doc);
>     builder.withW3cDocument(d, "http://localhost:8080");
>     builder.toStream(os);
>     builder.run();
> }`
> ```
> 
> Thanks

Hi，can you help me why "中文字符"displays #，how can I render html to pdf normally?

**Comment by danfickle** [comment]
@sungmore please see fonts page on wiki.
