### ISSUE TITLE
White line between image

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#169]
Hi,

I'm converting html to pdf, which is working fine, but there are some vertical white lines appearing between images. Please see pdf and html attached.
Can you let me know how to fix that or is it a bug in the lib?

[reviews.zip](https://github.com/danfickle/openhtmltopdf/files/1615216/reviews.zip)

**Comment by rototor** [comment]
I don't really know what you exactly mean with "white lines". A screenshot with a arrow to point out your problem would help.

But at least your tables do not page break correctly. 

You should set
```css
	-fs-table-paginate: paginate;
```
on the table and put 
```css
	display: table-header-group;
```
on the first row (i.e. the header row). And as you may guess from this info: Convert all your div rows to table rows and use a table per Review. If you want a clean and nice output here with correct page breaks you must use a table... 

You can look at [this sample](https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-examples/src/main/resources/testcases/RepeatedTableSample.html) how to do tables with repeated headers.

**Comment by danfickle** [comment]
I can no longer see white lines on the provided PDF in Chrome or Acrobat, so closing as I think this was a viewer issue.
