### ISSUE TITLE
Problem with Tags

### ISSUE THREAD

**Issue by fabioebner** [danfickle/openhtmltopdf#178]
In my case I have tags like "<br>" without "</br>" than I got the error:

> ERROR:  'The element type "br" must be terminated by the matching end-tag "</br>".'

and "&nbsp;" so  I got the error:

> ERROR:  'The entity "nbsp" was referenced, but not declared.' 

how can I fix this without change all HTML code? (it's from my user)

**Comment by rototor** [comment]
Sorry, you can't.... you must feed it into JTidy or using JSoup. The normal XML parser won't parse a br which is not terminated correctly (i.e. ```<br/>```).

In my projects I use JTidy to cleanup the HTML and make it wellformed:
```java
	public static String tidyHtml(String htmlString) {
		Tidy tidy = new Tidy();
		tidy.setDocType("omit");
		tidy.setXmlOut(true);
		tidy.setQuiet(true);
		tidy.setTidyMark(false);
		tidy.setWraplen(100_000);
		StringWriter swError = new StringWriter();
		tidy.setErrout(new PrintWriter(swError));
		StringWriter sw = new StringWriter();
		tidy.parse(new StringReader(htmlString), sw);
		String tidyHtml = sw.getBuffer().toString();
		tidyHtml = tidyHtml.replaceAll("(\r\n|\n|\r)+\\s*<", "<");
		return tidyHtml;
	}
```

using this JTidy dependency:
```xml
		<dependency>
			<groupId>net.sf.jtidy</groupId>
			<artifactId>jtidy</artifactId>
			<version>r938</version>
		</dependency>
```

The resulting HTML is then feed to OpenHTMLToPdf.
