### ISSUE TITLE
center aligned data or images in the HTML are moving to the left in PDF

### ISSUE THREAD

**Issue by Bhavaroop** [danfickle/openhtmltopdf#181]
Hello 
I have a HTML in which we have images and text that are center aligned. The HTML renders good in the browser but when we are trying to convert the HTML into PDF we are seeing that the images and the text are moving to the left side of the table. We have seen similar behavior in Flyingsaucer too. Is there any solution that can fix this issue??

THanks

**Comment by danfickle** [comment]
Hi @Bhavaroop 

I tried the following simple example:
````html
<html>
<head>
<style>
table {
	width: 100%;
}
td {
	text-align: center;
}
</style>
</head>
<body>
<table>
<tr>
<td>
Some long text to push out td
</td>
<td>
Some text.
</td>
</tr>
<tr>
  <td>
   Centered
  </td>
  <td>
    Also
  </td>
</tr>
<tr><td><img src="./images/image.png" alt="image"/></td><td>Center</td></tr>
</table>
</body>
</html>
````
and this result:
![issue-181](https://user-images.githubusercontent.com/1415728/37872698-3753ad22-3059-11e8-86b1-65390cf21d13.png)

Could you provide a minimal example that illustrates the problem you are having? Thanks.

**Comment by Bhavaroop** [comment]
Here is the sample html that i was using

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="EN">
<head>
	<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<meta content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0" name="viewport">
	<body>
		<table bgcolor="#EAEBED" cellspacing="0" cellpadding="0" align="center" border="0" width="100%">
			<tr>
				<td>
					<table cellpadding="0" cellspacing="0" align="center" border="0 width="640">
						<tr>
							<td valign="top" align="center">
								<table cellpadding="0" cellspacing="0" border="0 width="640">
									<tr>
										<td bgcolor="#F6F3F2" valign="top" align="center">
											<table cellspacing="0" cellpadding="0" border="0">
												<div style="padding-left: 30px; padding-right: 30px; font-family: Arial, Helvetica, sans-serif">
													<div style="font-style: 14px; line-height: 23px; color: #3F3F3F; font-weight: normal;">
														<img style="display: block; outline: none;" border="0" alt="Apple_Images" height="80" width="90" src="file:///Users/Bhavaroop/Desktop/apple.jpg">
													</div>
												</div>
											</table>
										</td>
									</tr>
								</table>
							</td>	
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</body>
</head>

**Comment by Bhavaroop** [comment]
- <?xml version="1.0" encoding="UTF-8"?>
- <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
- <html lang="EN">
- <head>
- 	<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
- 	<meta charset="utf-8">
- 	<meta content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0" name="viewport">
- 	<body>
- 		<table bgcolor="#EAEBED" cellspacing="0" cellpadding="0" align="center" border="0" width="100%">
- 			<tr>
- 				<td>
- 					<table cellpadding="0" cellspacing="0" align="center" border="0 width="640">
- 						<tr>
- 							<td valign="top" align="center">
- 								<table cellpadding="0" cellspacing="0" border="0 width="640">
- 									<tr>
- 										<td bgcolor="#F6F3F2" valign="top" align="center">
- 											<table cellspacing="0" cellpadding="0" border="0">
- 												<div style="padding-left: 30px; padding-right: 30px; font-family: Arial, Helvetica, sans-serif">
- 													<div style="font-style: 14px; line-height: 23px; color: #3F3F3F; font-weight: normal;">
- 														<img style="display: block; outline: none;" border="0" alt="Apple_Images" height="80" width="90" src="">
- 													</div>
- 												</div>
- 											</table>
- 										</td>
- 									</tr>
- 								</table>
- 							</td>	
- 						</tr>
- 					</table>
- 				</td>
- 			</tr>
- 		</table>
- 	</body>
- </head>
