### ISSUE TITLE
No support for non-English languages.

### ISSUE THREAD

**Issue by elfwine** [danfickle/openhtmltopdf#184]
It would be great if it can process non-English languages like Japanese/Korean/Chinese texts.

**Comment by danfickle** [comment]
It should work with the appropriate fonts. Please [see here for CJK example](https://github.com/danfickle/openhtmltopdf/issues/115#issuecomment-328257858). Let me know if you have any issues getting it working. NOTE: The sandbox doesn't have any CJK fonts installed presently.

**Comment by danfickle** [comment]
Assumed resolved, please reopen if required.
