### ISSUE TITLE
Generate navigation with links

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#185]
Hi,

I implemented a logic with anchorlinks to be able to navigate to each element of the navigation in pdf. But now I have the problem to receive the correct page number of each element. Maybe I could implement a JS-logic to iterate over navigation elements and check on which page the anchorlink-id is.

But how I can check the exact position of the anchorlink-id in the pdf?

**Comment by danfickle** [comment]
Hi @Kuhlware 

Currently there is no stable API to get an element's page in the PDF. However, you shouldn't need one as the project supports both internal links and the PDF concept of bookmarks, presented as a table of contents in many PDF readers. Following is an example demonstrating both features:

````html
<html>
<head>
<style>
div {
	page-break-after: always;
}
</style>
<bookmarks>
  <bookmark name="Title of element on page 1" href="#page-1"/>
  <bookmark name="Title of element on page 2" href="#page-2"/>
  <bookmark name="Title of element on page 3" href="#page-3"/>
  <bookmark name="Title of element on page 4" href="#page-4"/>
</bookmarks>
</head>
<body>
<h1>Bookmarks and TOC example</h1>

<h2>TOC</h2>
<ul>
  <li><a href="#page-1">Title of element on page 1</a></li>
  <li><a href="#page-2">Title of element on page 2</a></li>
  <li><a href="#page-3">Title of element on page 3</a></li>
  <li><a href="#page-4">Title of element on page 4</a></li>
</ul>

<div id="page-1">Page 1</div>
<div id="page-2">Page 2</div>
<div id="page-3">Page 3</div>
<div id="page-4">Page 4</div>

</body>
</html>
````

EDIT: Upon reading your message again, you may wish to link from an external document. If this is the case, please reply and we'll try to work something out.

**Comment by ghost** [comment]
Hi and thank you for the answer,

I do this actually with anchor links and the functionality is working correctly. But I want to **output** the page number where each anchorlink is on and I don't know how to get this information.

Best regards,
Fabian

**Comment by danfickle** [comment]
Hi @Kuhlware 

I have some good news and bad news. The good news is that someone already thought of needing the page number of an arbitrary element (although the element must have a ID) and it is implemented in this project with the ````target-counter```` function which can be used in the ````content```` property.

The bad news is that our calculation of the area of a link containing multiple boxes (such as the main box and an ````::after```` box with the page number) appears to be broken.

So, you can use the page number, but not in a link until this is fixed. Example below, which puts the target page number in a separate table column):
````html
<html>
<head>
<style>
div {
	page-break-after: always;
}
#toc {
    width: 100%;
    border-collapse: collapse;
}
#toc .page-number::after {
  /* SPECIAL STUFF HERE! */
  content: target-counter(attr(href), page);
  width: 30px;
}
</style>
<bookmarks>
  <bookmark name="Title of element on page 1" href="#page-1"/>
  <bookmark name="Title of element on page 2" href="#page-2"/>
  <bookmark name="Title of element on page 3" href="#page-3"/>
  <bookmark name="Title of element on page 4" href="#page-4"/>
</bookmarks>
</head>
<body>
<h1>Bookmarks and TOC example</h1>

<h2>TOC</h2>
<table id="toc">
  <tr><td><a href="#page-1">Title of element on page</a></td><td class="page-number" href="#page-1"></td></tr>
  <tr><td><a href="#page-2">Title of element on page</a></td><td class="page-number" href="#page-2"></td></tr>
  <tr><td><a href="#page-3">Title of element on page</a></td><td class="page-number" href="#page-3"></td></tr>
  <tr><td><a href="#page-4">Title of element on page</a></td><td class="page-number" href="#page-4"></td></tr>
</table>

<div id="page-1">Page 1</div>
<div id="page-2">Page 2</div>
<div id="page-3">Page 3</div>
<div id="page-4">Page 4</div>

</body>
</html>
````

**Comment by ghost** [comment]
Hi,

very nice. Thank you for your introduction. This works very finde with my code. Could you send me a message, if this logic is working inside a link? :)

Best regards,
Fabian

**Comment by jesselong** [comment]
@danfickle Is this the correct issue to watch to be notified of when the link bug is resolved?

Thanks for your work on this project btw.

**Comment by danfickle** [comment]
@Kuhlware @jesselong 
Yes, I’ll comment here when link boxes issue is fixed.

**Comment by danfickle** [comment]
@Kuhlware @jesselong 

I've just pushed fixed code. The problem was in the ```add``` method combining two rectangles of links. I'm planning a release in about a week.

**Comment by jesselong** [comment]
@danfickle Brilliant, thanks for that

**Comment by ghost** [comment]
Yeah thank you!
