### ISSUE TITLE
any reason why this won't work on App Engine Java8?

### ISSUE THREAD

**Issue by Rob46** [danfickle/openhtmltopdf#190]
I see that it says it won't work for Google App Engine, but I assume that is for the older Java 7 which only allowed white listed jars. Java 8 allows any jar, and use openjdk8

Any proof it won't work in that environment?

**Comment by danfickle** [comment]
Thanks @Rob46 

I'll close this in favor of #179 - we can continue discussion there.

**Comment by Rob46** [comment]
What is the minimal list of jars I need?

I've tried to figure this out via maven (not something I use) but I'm still missing stuff:
com.google.apphosting.runtime.jetty9.JettyLogger warn: Error for /testservlet
java.lang.NoClassDefFoundError: de/rototor/pdfbox/graphics2d/PdfBoxGraphics2DFontTextDrawer
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:180)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:106)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:84)

**Comment by Rob46** [comment]
I found the missing lib. In initial testing on GAE Std Java 8 I am not getting any exceptions.

**Comment by Rob46** [comment]
With my basic HTML test it works on Google App Engine Standard Java 8! :-)
