### ISSUE TITLE
HTML to PDF transform with orientation

### ISSUE THREAD

**Issue by PaulJayP** [danfickle/openhtmltopdf#191]
Before transforming a HTML document to PDF i wish to add a style to the whole document, the style does one thing, rotates the document from portrait to landscape. 
This works when manipulating the HTML yourself and rendering within a browser, but after transformation to a pdf occurs, the style is completely lost. Instead the style is rendered as a string within the new pdf.

For instance:
```
content = content.replaceAll("...example String..."), ("<style type=\"text/css\">\n" +
                    "body{\n" +
                    "    -webkit-transform: translateY(-100%) rotate(90deg); /* Safari */\n" +
                    "    -moz-transform: translateY(-100%) rotate(90deg); /* Firefox 3.6 Firefox 4 */\n" +
                    "    /*-moz-transform-origin: right top; */\n" +
                    "    -ms-transform: translateY(-100%) rotate(90deg); /* IE9 */\n" +
                    "    -o-transform: translateY(-100%) rotate(90deg); /* Opera */\n" +
                    "    transform: translateY(-100%) rotate(90deg); /* W3C */  \n" +
                    "    -webkit-transform-origin: left bottom;\n" +
                    "    -moz-transform-origin: left bottom;\n" +
                    "    -ms-transform-origin: left bottom;\n" +
                    "    -o-transform-origin: left bottom;\n" +
                    "    transform-origin: left bottom;\n" +
                    "} \n" +
                    "</style>");) 
```
This works for rendering a new HTML document but is lost while creating a pdf document. Unless I am completely missing something. 
Also if there is a much easier way to create a pdf with landscape or portrait orientation from an existing html document with this library then any solution would be more than helpful.

Example:
------------------------------------------------------------------------------------------------------------------
![test](https://user-images.githubusercontent.com/8971357/38419103-07fd5ef0-3997-11e8-8f38-61dfa5a8701b.png)

**Comment by Jugen** [comment]
You could try the @page command like so:

    <head>
       <style>
          @page { A4 landscape; }
       </style>
    </head>

**Comment by PaulJayP** [comment]
Same thing occurs, a string value of the required style returns rather than the actual transformation.

![image](https://user-images.githubusercontent.com/8971357/38420238-fc7cf780-399a-11e8-9901-54381edd547b.png)

body{transform: rotate(90deg);} has the same issue.

@page {transform: rotate(90deg);}  does nothing at all.

Edit: I realised @page wont render in a browser and I have been trying to use @page within body rather than head, i will re-test and update. Thanks

**Comment by PaulJayP** [comment]
For anyone stuck on the same issue, firstly ensure if you are using a whitelist and Jsoup clean, remember that the head tag does not survive.
Use Jsoup.parseBody instead of buffered reader to manipulate the head tag.
Secondly, @page did not work for me, but using any other tag did, such as 
```
<head>   
        body{
		transform: rotate(90deg)
	} 
</head> 
```
This will ensure the rotation survives the transformation  .
