### ISSUE TITLE
custom UserAgent / PdfBoxUserAgent

### ISSUE THREAD

**Issue by delafer** [danfickle/openhtmltopdf#196]
I am Alex and I'm trying to move my project to openhtmltopdf & openbox instead of using itext | fop based flyingsaurcer.
 

- **Сoncretely:**

I don't see any handsomely set & use own custom **UserAgent / PdfBoxUserAgent** , like I have this already done in flyingsaurcer in oder to load some resources (images, css) directly from classpath. Of course, I can use URLStreamHandlerFactory, but It's tricky and not always possible in AS like BEA/Oracle WL.

- **Little philosophy & critics:**

I see a lot of design problems in this library. IMHO architecture of this library comparitevly to flyingsaurcer/neoFlyingSaurcer has not improved, but sometimes was even worsened. Constructors with >= 18 parameters, huge methods & consturctor intitializers, sometimes unreasoned method & fields modifiers, its looks like procedural  instead of object-oriented programming,because of lack of factories, I don't even say about other patterns like decorators, adapters, etc. -> to make the code cleaner & expendable.
It's works of course, while walking straight and not trying to do something special, something except "hello world" ;-)
 

- **Finally my praise and compliments:**

Your working hardly, I see a lot of pull/push request in git, I like SVG support (_and it works, BTW: I have done something similar with flyingsaurcer using batik & ReplacementElementFactory_), I like the rate of new versions release.
Idea behind flyingsaurcer was genial, for reports generation I have used before Jasper, BIRT, and pure iText libraries.
I thank you for your work and with use a good luck.
 
_P.S. think a little bit not only about a new features, but also about design and extensibility of openhtmltopdf. About clean and well-structured code.
I can do a pull request to git to allow use/setting of custom PdfBoxUserAgent, but I am not sure, that will you accept this / third party code / changes._

Kindly regards,
Alexandr

![example](https://user-images.githubusercontent.com/5951449/38465731-dabe3eac-3b1f-11e8-90ab-b935a0b11669.png)

This code doesn't work as expected, because 
**builder.buildPdfRenderer()** instantiates ->  **new PdfBoxRenderer(...)** instance and during instantiation in constructor **new PdfBoxUserAgent()** instance will be created and in the same place in constructor document will be parsed and method private void **setDocumentP(Document doc, String url, NamespaceHandler nsh)** will be called during initialization and following line in this method ->
**_sharedContext.getCss().setDocumentContext(_sharedContext, _sharedContext.getNamespaceHandler(), doc, new NullUserInterface());**
calles created default **PdfBoxUserAgent** instance and your new custom instance could be created only later, after **PdfBoxRenderer** intialization and recieving **SharedContext**. Where is no way to do this reasonable and in elegant way, because of poor library design / architecture.

_P.S. honestly, have never seen such a poorly thought-out architecture and application design.  Looks like a student trying to learn programming, but don't understand OOP and common design patterns._

**Comment by rototor** [comment]
Please see my comments on #198. For your use case just setting a URI Resolver on the builder should be fine, you should not need to override the UserAgent:

```
builder.useUriResolver(new DefaultUriResolver() {
   @Override
   public String resolveURI(String baseUri, String uri) {
      if (uri.contains(":"))
         return super.resolveURI(baseUri, uri);
      URL url = PdfServiceBase.this.getClass().getResource(uri);
      if (url != null)
         return url.toExternalForm();
      url = PdfServiceBase.class.getResource(uri);
      if (url != null)
         return url.toExternalForm();
      return super.resolveURI(baseUri, uri);
   }
});
```

```PdfServiceBase``` in this sample code is a base class I use for all my reports. Using ```PdfServiceBase.this.getClass().getResource(...)``` looks up the resources in the derived class class loader, and ```PdfServiceBase.class.getResource(...)``` looks up resources in my base class library. This is especially needed if you want to use relative URLs for you resources.

P.S.: I don't want to offend you, but please be so kind and spare such comparsions. FlyingSaucer and it's more or less successor OpenHTMLToPDF are very old libraries written in over a decade by many people. I'm very happy that @danfickle  took the step and ported the library over to PDFBox and also tries to modernize it. Cleaning and refactoring such a big library without breaking everything is something which takes a long time. Just saying "you are stupid" is not helping.

*Why do you look at the speck of sawdust in your brother's eye and pay no attention to the plank in your own eye?* (*cough* ThreadLocal, singletons *cough*)

**Comment by delafer** [comment]
>  I don't want to offend you, but please be so kind and spare such comparsions.

You are right, I'am a little bit emotional. I need to avoid such comparsions.

> Why do you look at the speck of sawdust in your brother's eye and pay no attention to the plank in your own eye? (cough ThreadLocal, singletons cough)
1) You are the first developer, who without any reasonable explanations, hates classical wide used programming patterns like "Singleton"'s. Absolutely unreasoned.
2) Relatively ThreadLocal we could debate / dispute about them, you are not completely wrong, but problems with ThreadLocal is not a ThreadLocal problem, but a certain implementation of servlet container like Tomcat. And even this doesn't means that tomcat doesn't clears them at all, it means only in certain circumstances it doesn't work as expected.
 
```
PdfBoxRenderer renderer = null;
    try {
        builder.getPdfBoxUserAgentFactory().registerGlobalPdfBoxUserAgentFactory(new PdfBoxUserAgentFactory.UserAgentFactory() {
            @Override
            public PdfBoxUserAgent getPdfBoxUserAgent(PdfBoxOutputDevice pdfBoxOutputDevice) {
                return new ExtendedPdfBoxUserAgent(pdfBoxOutputDevice);
            }
        });
        renderer = builder.buildPdfRenderer();
        //customUserAgent(renderer);
        renderer.layout();
        renderer.createPDF();
    } finally {
        if (renderer != null)
            renderer.close();
    }
```

> rototor an hour ago  Contributor
> @delafer Sorry, but where is the unregisterPdfBoxUserAgentFactory() call? Oh, you forgot it. So a class loader leak is incoming on WAR reload ... This is what I mean by bad API design, if it's easy to forget something you will forget to do it... and the problem will only manifest after the n-th reload of the WAR..

No. I haven't forgot it. I shouldn't unregister it, because I called "**registerGlobalPdfBoxUserAgentFactory**" method and it's not stored in ThreadLocal. So it's not a memory leak.

> Method chaining means: builder.setXY().setAbc().setWhatever().build(). For another example look here: 

I know what a method chaining means. It's widely used e.G. from selenium tests in Selenium Test Framework, or e.G. REST api Calls. I was not born yesterday. 
You do not like insulting comparisons, but you self answer me, as if I were an idiot, and you are the only experienced expert. Let's respect each other. "_**a bad peace, better than a good war**_" 
do you know such a Russian proverb?

**Comment by rototor** [comment]
@delafer To be honest I got triggered as well... sorry for that, @danfickle is right, we should try to be nice and professional.

As with any patterns "singletons" are good when used in the right spot and a anti-pattern when used at the wrong spot. The builder pattern (no idea if this is the official right name for it) allows to parameterize a class with maybe many parameters just using method chaining. E.g. guava is also using it all over the place for more complex objects like  [caches](https://github.com/google/guava/wiki/CachesExplained). You can add additional parameters to your API without breaking existing clients. The parameters are built locally without affecting any other thread etc. 

You're usage of a singleton (with and without ThreadLocals) in #198 breaks the builder pattern by introducing global state for no obvious gain. Suddenly you can have problems with threads and servlet containers. And the parameter state is not contained in one object any more, but spilled in different places.

Using this singleton to avoid adding another parameter to the *Renderer classes is the wrong way to fix the problem with the ever-growing constructors. I think/hope that #199 is the right way. So from my point of view the singleton is just the wrong solution here.

From my experience singletons should either be complete immutable (like e.g. Collections.EMPTY_LIST) or be made explicit thread safe and CDI injected. Everything else is going to cause problems in the long term.  

Sorry for not explaining that good enough, it was fully obvious for me why using a singleton is not a good idea here...

**Comment by danfickle** [comment]
OK, as discussed in #198, I have gone ahead and allowed the user to register a stream factory for any set of protocols. Use would be something like this (very quick and dirty example):
````java
private static class MyStream implements HttpStream {
		private final String response;
		
		private String getContent(String url) {
			try {
				URI urlObj = new URI(url);
				
				System.out.println("Requesting: " + urlObj.getPath());
				
				return urlObj.getPath().equals("/stylesheet") ?
					"body { font-size: 50px; }" : 
					"<html><head><link rel=\"stylesheet\" href=\"myprotocol:/stylesheet\"/></head><body>Some large text</body></html>"; 
			} catch (Exception e) {
				e.printStackTrace();
			}
			return "";
		}
		
		public MyStream(String url) {
			this.response = this.getContent(url);
		}

		@Override
		public InputStream getStream() {
			try {
				return new ByteArrayInputStream(response.getBytes("UTF-8"));
			} catch (UnsupportedEncodingException e) {
				e.printStackTrace();
			}
			return null;
		}

		@Override
		public Reader getReader() {
			return new StringReader(response);
		}
		
	}
	
	private static class StreamFactory implements HttpStreamFactory {

		@Override
		public HttpStream getUrl(String url) {
			return new MyStream(url);
		}
		
	}
	
	public static void main(String... args) throws Exception {
		OutputStream os = new FileOutputStream("/Users/me/Documents/pdf-issues/output/mytest-196.pdf");
		PdfRendererBuilder builder = new PdfRendererBuilder();
		builder.useProtocolsStreamImplementation(new StreamFactory(), "myprotocol");
		builder.withUri("myprotocol:/page");
		builder.toStream(os);
		builder.run();
		os.close();
	}
````

**Comment by delafer** [comment]
> OK, as discussed in #198, I have gone ahead and allowed the user to register a stream factory for any set of protocols. Use would be something like this (very quick and dirty example):

**if briefly: I like it.**

**Comment by delafer** [comment]
> From my experience singletons should either be complete immutable (like e.g. Collections.EMPTY_LIST) or be made explicit thread safe and CDI injected. Everything else is going to cause problems in the long term.

Believe me this is more a philosophical question, what is a right way and how to use singletons in a right way. It's really nothing except a philosophy.
A completely different example
Some people says that e.G. an interface is a good place to define constants , other saying not , it's wrong, whey should be defined in a java class with private constructor.. and you can talk hours and hours, which is more correct.
Singletons have nothing with immutability to do.  I have created completelly thread safe, lazy singleton and I don't see any disadvantages of such approach except of developer preferences.
DI / CDI this is a completely different world, I working a lot with CDI and singletons used there to define bean scopes. It's still singletons ("one instance" per JVM .. not quite correct., but pro JVM and classloader) and simultaneously not quite the same... So , I don''t want to hold now long discussions about singletons, but I can. You can trust me )

**Comment by syjer** [comment]
Hi @danfickle , sorry to bother you,  do you have an ETA for the next release (RC14 I guess?). The commit https://github.com/danfickle/openhtmltopdf/commit/b661420596ee98e550525329383cd2fe3f261b8b is really something that I would need, as the `URL.setURLStreamHandlerFactory` plan didn't work out as I expected due to some application server shenanigans.

Thank you :)

**Comment by danfickle** [comment]
Hold me to a release by the end of next weekend (8 July). There is only inline blocks for the fast renderer and a solution to #215 needed.

**Comment by danfickle** [comment]
Finally released RC18 with the fast renderer ready for use.
