### ISSUE TITLE
Issue with Czech language characters

### ISSUE THREAD

**Issue by mundas** [danfickle/openhtmltopdf#200]
Hi,

i have problem with some of czech characters č ř which are not displayed correctly in generated pdf file. As a html, everything works fine but in pdf I see '#'.  I tried to use diffrent enconding and even html symbol entity, but still nothing ;/

Except these symbols, the rest of czech character works fine. Do you knowhow i can fix that? Can someone test that?

**Comment by danfickle** [comment]
Hi @mundas 

You need to embed a correct font, as described in the template author's guide linked on the readme document. Let us know if that doesn't work. The default PDF fonts don't support many languages.

**Comment by mundas** [comment]
Ok i will try to check it but, as I said, rest of special czech characters are working. So that is weird for me that only two ot them are not working;/

**Comment by danfickle** [comment]
Closing, as I think this was a font issue. Reopen if needed.

**Comment by hussaintamboli** [comment]
@danfickle I couldn't find a way to embed fonts in Readme. I am currently having issues with Thai language. Can you help in pointing at the correct resource please?

**Comment by danfickle** [comment]
Hi @hussaintamboli,

Did you check out the fonts wiki page?

https://github.com/danfickle/openhtmltopdf/wiki/Fonts

This seems to be a good source of Thai fonts:

https://github.com/lannainnovation/thai-font-collection/tree/master/downloadable-free-thai-fonts

**Comment by hussaintamboli** [comment]
Thanks. How do I decide which ttf to use? e.g. I just want to render - วรรณยุกต์ or วรรณยุต.

Also do I need to use [html5 parser support](https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/docs/integration-guide.md#html5-parser-support) because I have html files that need to be converted to pdf.

**Comment by danfickle** [comment]
Just pick the font that you like the look of and has needed characters.

As for html5, if you have valid xhtml you can just use the builder. Otherwise, you can try the jsoup to dom module (you may need to file issues as it is not tested very well) or try the tag soup or jtidy libraries.
