### ISSUE TITLE
Unable to disable XML External Entities

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#207]
I can generate a PDF file with any problem.

However, I'm getting the following errors in my stack trace.  The PDF generates but thought I would ask about this.  I am running Wildfly (JBoss) with Java 8.  I have NO XML in my HTML file.  My HTML is pretty simple, just a few lines of code.

```
SAX XMLReader in use (parser): __redirected.__XMLReaderFactory
Unable to disable XML External Entities, which might put you at risk to XXE attacks: org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
        at org.apache.xerces.parsers.AbstractSAXParser.setFeature(AbstractSAXParser.java:1655)
        at __redirected.__XMLReaderFactory.setFeature(__XMLReaderFactory.java:132)
        at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.setXmlReaderSecurityFeatures(XMLResource.java:178)
        at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:237)
        at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.access$100(XMLResource.java:168)
        at com.openhtmltopdf.resource.XMLResource.load(XMLResource.java:85)
```

Please advise and thank you for a great product.

**Comment by rototor** [comment]
@rhysryan This library always parses the HTML as XHTML. In fact it can only parse valid XML, to parse "sloppy" HTML you need to use JTidy or JSoup first to convert it to valid XHTML.

The Java XML parser your application is using does not support the XMLConstants.FEATURE_SECURE_PROCESSING feature. Maybe you should try to upgrade the XML parser used in your application? I think you may have a old Xerces version laying around in the class path, or even have it embedded in JBoss .... You can set the "xr.load.xml-reader" system property to the class name of the XML reader you want to use.

As long as you don't let users inject HTML for the report you should be safe to ignore this warning. It just tries to prevent XXE attacks when possible, if it's not possible (as in your case) it just gives out a warning and continues to run without problem.

**Comment by ghost** [comment]
Thank you.  I don't really understand how to do any of that and since the injection isn't possible and I don't care about the message, I'll leave it be.
