### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by lucheng** [danfickle/openhtmltopdf#209]
When bulk HTML is transferred to PDF.
prompt :"Too many open files"

com.openhtmltopdf.pdfboxout.PdfRendererBuilder.useFont
com.openhtmltopdf.pdfboxout.PdfBoxFontResolver
/**
	 * Add a font using a existing file. If the file is a TrueTypeCollection, it
	 * will be handled as such.
	 */
	public void addFont(File fontFile, final String fontFamilyNameOverride, final Integer fontWeightOverride,
			final IdentValue fontStyleOverride, final boolean subset) throws IOException {
		/*
		 * Specialcase for TrueTypeCollections
		 */
		if (fontFile.getName().toLowerCase(Locale.US).endsWith(".ttc")) {
                        //one
			addFontCollection(fontFile, fontFamilyNameOverride, fontWeightOverride, fontStyleOverride, subset);
			return;
		}

		/*
		 * We load the font using the file.
		 */
                //two
		addFont(PDType0Font.load(_doc, fontFile), fontFamilyNameOverride, fontWeightOverride, fontStyleOverride, subset);
	}

At one and two ,Resources are not closed.

**Comment by rototor** [comment]
I got the same problem and made a pullrequest with a fix #215

**Comment by rototor** [comment]
If you need a workaround, you can just use a FSSupplier<InputStream> to provide the font as InputStream. The bug only happens with font files.
