### ISSUE TITLE
Builder error

### ISSUE THREAD

**Issue by etcware** [danfickle/openhtmltopdf#210]
Sorry if I use issues for this, but I have this includes in my gradle
	// https://mvnrepository.com/artifact/com.openhtmltopdf/openhtmltopdf-core
	compile group: 'com.openhtmltopdf', name: 'openhtmltopdf-core', version: '0.0.1-RC13'
	// https://mvnrepository.com/artifact/com.openhtmltopdf/openhtmltopdf-pdfbox
	compile group: 'com.openhtmltopdf', name: 'openhtmltopdf-pdfbox', version: '0.0.1-RC13'
	// https://mvnrepository.com/artifact/com.openhtmltopdf/openhtmltopdf-java2d
	compile group: 'com.openhtmltopdf', name: 'openhtmltopdf-java2d', version: '0.0.1-RC13'

And this error:
Unresolved requirement: Import-Package: de.rototor.pdfbox.graphics2d

Do I need to include also this library?

**Comment by danfickle** [comment]
Hi @etcware 

I'm not familiar with Gradle, but Maven pulls in transitive dependencies automatically. If Gradle does not, you will indeed need to include the pdfbox graphics2d library.

**Comment by etcware** [comment]
Thanks Dan 
I'm using OSGI with gradle and my configuration is:

        // https://mvnrepository.com/artifact/com.openhtmltopdf/openhtmltopdf-core
	compile group: 'com.openhtmltopdf', name: 'openhtmltopdf-core', version: '0.0.1-RC13'
	// https://mvnrepository.com/artifact/com.openhtmltopdf/openhtmltopdf-pdfbox
	compile group: 'com.openhtmltopdf', name: 'openhtmltopdf-pdfbox', version: '0.0.1-RC13'
	// https://mvnrepository.com/artifact/com.openhtmltopdf/openhtmltopdf-java2d
	compile group: 'com.openhtmltopdf', name: 'openhtmltopdf-java2d', version: '0.0.1-RC13'
	// https://mvnrepository.com/artifact/de.rototor.pdfbox/graphics2d
	compile group: 'de.rototor.pdfbox', name: 'graphics2d', version: '0.14'
	// https://mvnrepository.com/artifact/org.apache.pdfbox/fontbox
	compile group: 'org.apache.pdfbox', name: 'fontbox', version: '2.0.9'
	// https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox
	compile group: 'org.apache.pdfbox', name: 'pdfbox', version: '2.0.9'
	// https://mvnrepository.com/artifact/com.itextpdf/html2pdf
	compile group: 'com.itextpdf', name: 'html2pdf', version: '2.0.1'
