### ISSUE TITLE
html to png, css Rotation not used

### ISSUE THREAD

**Issue by mapleLeat** [danfickle/openhtmltopdf#220]
```
<html>
 <head>
  <style>@page {size: 520px 820px;margin: 0px;padding: 0px;}body {margin: 0;}</style>
 </head>
 <body>
    <div style="left:0px;top:0px;width:50px;transform: rotate(50deg);">
      asdasdasd
    </div>
 </body>
</html>
```

PDF TO PNG 
`transform: rotate(50deg) ` not use

**Comment by mapleLeat** [comment]
@rototor Excuse me, does the conversion of images have not added rotation support?

**Comment by rototor** [comment]
@mapleLeat Sorry, i don't understand what you mean. Rotation seems to work fine for me for this test case, both for PDF and PNG output. Of course, the PNG output is truncated, as the div is only as high as the div needs to be to draw the untransformed text. CSS transform is visual only and does not affect the layout (as per spec). You may just need to add more height to your div to not get it truncated when writing as a PNG. 

![simplerotate](https://user-images.githubusercontent.com/711674/39956127-f504948e-55da-11e8-992c-0a04cc33f6c0.png)

[simplerotate.pdf](https://github.com/danfickle/openhtmltopdf/files/1997483/simplerotate.pdf)

What version of OpenHTMLToPDF do you use?

**Comment by mapleLeat** [comment]
@rototor hello
thanks,Now that I use the RC13 version, there is no problem
