### ISSUE TITLE
Wrong absolute positioning

### ISSUE THREAD

**Issue by BbIKTOP** [danfickle/openhtmltopdf#223]
Hi,

Absolute positioned div has wrong position: I see it  inside a4 page both on screen and browser print preview, but in the converted PDF version it is out of the page - moved about 5mm right.

http://base.etogo.net/_generated.html

**Comment by danfickle** [comment]
Hi @BbIKTOP 

I think this might be the page margin?

You can set the page margin to zero if desired:
````css
@page {
  size: A4;
  margin: 0;
}
````

**Comment by BbIKTOP** [comment]
I know I'm looking a bit stupid, but not so much ) Sure, I've set margin to 0 and margin and padding for both html and body to 0 as well. I observe the same behavior in all itext-derived libraries (flying saucer, open) except itext 7 - it renders the same html/css correctly. Moreover, when I try to print this page from the browser, the sizing is correct.
Tried this as well (to set exact size, not a4) - result is the same as if "a4" is set
@page
{
    size: 210mm 297mm;
    margin: 0;
}

**Comment by danfickle** [comment]
I had a play with your page markup. Please note that the ```box sizing``` is not supported, which may change your calculations. Shouldn't a ```left``` value of ```210mm``` be out of the page? Also ```absolute``` positioning with ```top``` and ```bottom``` set seems to be broken. Instead use a ```top``` and a ```height```. You could also set ```right``` to zero instead.

P.S I couldn't see the ruler in Chrome (Mac) on screen or in print preview.

**Comment by BbIKTOP** [comment]
I removed "top" and "bottom", as well as all "box-sizing"s, and now it works just fine. The problem is, that I didn't make a backup and cannot get it back as it was, when position was wrong.
Well, thank you anyway, will avoid "top", "bottom" and "box-sizing" usage then.

P.S. Probably due to "display: none" in media print? I don't have a backup copy to check /

**Comment by danfickle** [comment]
Closing this now, but please note that ```box-sizing``` should now be supported.
