### ISSUE TITLE
CSS letter-spacing not working

### ISSUE THREAD

**Issue by vfelberg** [danfickle/openhtmltopdf#228]
Hello,

I'm using following HTML:

```
<!DOCTYPE html>
<html>
<head>
    <style type="text/css">
        @page {
            size: 297mm 210mm;
            margin: 0;
        }

        html, body, div, span {
            margin: 0;
        }

        #main_container {
            position: relative;
            width: 297mm;
            height: 210mm;
        }

        #container1 {
            position: absolute;
            bottom: 0;
            left: 0;
            width: 150mm;
            height: 105mm;
        }
    </style>
</head>
<body>
<div id="main_container">
    <div id="container1" style="font-family: Helvetica, sans-serif; font-size: 14px; letter-spacing: 1mm;">
        <div style="position: absolute; top: 22mm; left: 4mm;">ABCDEF GHIJKLMN</div>
        <div style="position: absolute; top: 30mm; left: 4mm;">01234567890123456789</div>
        <div style="position: absolute; top: 38mm; left: 4mm;">ABCDEFGHIJKLMN</div>
        <div style="position: absolute; top: 55mm; left: 4mm;">0123456789</div>
    </div>
</div>
</body>
</html>
```

Rendered by Chrome:
![screen shot 2018-06-12 at 10 02 28](https://user-images.githubusercontent.com/40957/41278153-68582ba6-6e29-11e8-9c71-dfac5eb1e26a.png)

Rendered by HtmlToPdf:
![screen shot 2018-06-12 at 10 17 37](https://user-images.githubusercontent.com/40957/41278322-e9def312-6e29-11e8-8a03-1e1d0b111148.png)

Is letter-spacing not supported?

**Comment by mapleLeat** [comment]
Encountered the same problem and the log does not remind

**Comment by danfickle** [comment]
No, not currently supported.

**Comment by mapleLeat** [comment]
@danfickle 
Whether to consider adding this support, because this is important for my project
Thank you very much

**Comment by danfickle** [comment]
The CSS ```letter-spacing``` property is now implemented in RC15.

Limitations are:
+ Can't use percent units.
+ Can't be used with text justification.

Thanks everyone for requesting support.

**Comment by danmaidesenling** [comment]
Is there any alternative css style ?
