### ISSUE TITLE
Add support for SVG images

### ISSUE THREAD

**Issue by ngns** [danfickle/openhtmltopdf#23]
Currently, SVG images are not supported. PDFBox does not "draw" SVGs natively. Best practice is, to use apache batik to transcode SVGs to PDFs and embed these as PDFFormXObject via PDFBox. 

_See also _
- SVGs via batic in PDFBox: https://www.mail-archive.com/users@pdfbox.apache.org/msg06998.html
- Transcoding SVGs with batic: http://stackoverflow.com/questions/6875807/convert-svg-to-pdf

**Comment by danfickle** [comment]
I decided to create our own transcoder rather than the transcoder provided by FOP. This gives the benefits that it can output to Java2D as well as pdf and can use our user agent, font resolver, etc. However, it is a bit more work so I'm still debugging it and will commit something tomorrow for testing.

**Comment by ngns** [comment]
Should we keep the transcoder to use flexible? Batik is very mature, and will likely be quicker to implement for complex SVGs.
If your are going for Java2D target, maybe it could be built upon existing solutions like Flamingo SVG Transcoder (also batik-based)? http://ebourg.github.io/flamingo-svg-transcoder/

**Comment by danfickle** [comment]
This is a screen shot showing simple SVG graphics in a PDF.
![openhtmltopdf-screenshot](https://cloud.githubusercontent.com/assets/1415728/15985052/54e06146-3024-11e6-9c59-50dd6d84cd51.png)

**Comment by danfickle** [comment]
Todo for proper SVG output:
- [x] Basic fill and draw operations
- [x] Basic text output
- [x] Inline SVG in HTML document
- [ ] External SVG in image
- [ ] Linear gradient support
- [ ] Alpha support
- [x] Custom font support
- [ ] Insert raster image in SVG
- [x] SVG transform support
- [ ] SVG clipping support
- [ ] Testing

**Comment by danfickle** [comment]
With commit bb586a9 you can output custom fonts in SVG like this (text color is still wrong and gradients aren't implemented):

![svg-custom-font](https://cloud.githubusercontent.com/assets/1415728/16080350/b60c19a4-334b-11e6-9bda-d7718f681045.png)

``` html
<html>
<head>
<meta charset="UTF-8"/>
<style>
@font-face {
  font-family: 'handwriting';
  src: url(JustAnotherHand.ttf);
}
svg {
    display: block;
}
body {
    font-size: 50px;
}
</style>
</head>
<body>
<svg height="130" width="500" xmlns="http://www.w3.org/2000/svg" version="1.1"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
      <stop offset="100%" style="stop-color:rgb(255,0,0);stop-opacity:1" />
    </linearGradient>
  </defs>
  <ellipse cx="100" cy="70" rx="85" ry="55" fill="url(#grad1)" />
  <text fill="#ffffff" font-size="45" font-family="handwriting" x="50" y="86">SVG</text>
</svg>
</body>
</html>
```

**Comment by rototor** [comment]
@danfickle I am not sure if the current approach is the right one. Instead of retrofitting a Graphics2D on a OutputDevice it should just be possible to get a Graphics2D to draw on. Like "createGraphics(rectangle)".

This was possible with iText, but is currently not possible with PdfBox. After I finish #38 I will implement such a PdfBoxGraphics2D, as I need that for some reports where we have Java2D drawing code for some diagrams. And I need text support including the ability to render text as vector paths. But if you want to build such a PdfBoxGraphics2D feel free to do so. The PdfBox seems not interested in such a graphics 2d...

**Comment by danfickle** [comment]
@rototor - I think you have a good point. In fact a standalone Graphics2D implementation which output to PDF would be useful for many projects, not just this one.

I found an old attempt and found some of our code is identical. I don't know who copied who. The old attempt would be useful for some of the maths, etc. It is also licensed under the LGPL.

http://gnujpdf.cvs.sourceforge.net/viewvc/gnujpdf/gnujpdf-1.7/src/gnu/jpdf/PDFGraphics.java?revision=1.6&view=markup

**Comment by brettclark** [comment]
Just curious, is any other image format supported by openhtmltopdf right now?  For example, I have a PNG which I need to render.

**Comment by danfickle** [comment]
Hi @brettclark 
PNG should work fine. Generally, any image format supported by Java's ImageIO should work including PNG, JPEG and GIF.

**Comment by rototor** [comment]
Just for your information: I started a Graphics2D for PDFBox (https://github.com/rototor/pdfbox-graphics2d) but it seems not to be that simple. I choose the Apache 2.0 Licence, cause maybe PDFBox may want to integrate it when its finished.

**Comment by rototor** [comment]
FYI: I've just created a pull request #66 which implements the SVG rendering using my Graphics2D adapter. It just does the placement of the final XForm wrong at the moment.

**Comment by danfickle** [comment]
Thanks to awesome library and work by @rototor SVG support is largely done.
Current known limitations:
+ Raster image URIs in SVGs (````<image>```` tag) are not going through the URI resolver so only absolute URIs can be used.
+ External SVG images are not loaded yet.
+ Security is not yet assured (do scripts run in any circumstances?) so do not use user provided markup for SVGs (or HTML for that matter).

**Comment by pilami** [comment]
Can this be released to maven repo?

**Comment by danfickle** [comment]
@pilami 
Hi, RC10 has been released to Maven now.

**Comment by jmsalcido** [comment]
@danfickle this can be closed now?
