### ISSUE TITLE
Custom font section CSS is not working

### ISSUE THREAD

**Issue by mapleLeat** [danfickle/openhtmltopdf#235]
HI
I used a custom font after
CSS section properties are not working:
Font-style: italic; font-weight: bold;

```
<html>
 <head>
  <style>
    @page {size: 520px 820px;margin: 0px;padding: 0px;}body {margin: 0;}
    @font-face { font-family: 'Ghouly Caps';src:url('/data/lukisdata/fontfamily/font1/Ghouly_Caps.TTF');}
  </style>
</head>
 <body>
  <div style="font-family: &quot;Ghouly Caps&quot; !important;font-size: 50px;     font-style: italic; font-weight: bold;">
    asdasdsfgfdgghf
  </div>
 </body>
</html>
```
html:
![html](https://user-images.githubusercontent.com/20888798/41835376-ed3f9f10-7889-11e8-85c2-1f3c598bc9eb.PNG)

Generated picture:
![image](https://user-images.githubusercontent.com/20888798/41835421-1af8e5b0-788a-11e8-8b0e-59616f90b5ac.png)

If you do not use custom font everything is normal.
HTML to PDF also the same

**Comment by danfickle** [comment]
I think this is a duplicate of #231

**Comment by danfickle** [comment]
Should be fixed in RC-14 with bold and italic emulation.
