### ISSUE TITLE
A DUPLICATE text created when the text is somewhere at the the end of the page

### ISSUE THREAD

**Issue by prsp20** [danfickle/openhtmltopdf#236]
We rely on this library for conversion of so many of our documents from html to pdf. Currently we are facing an strange issue in few of the documents.

The issue is that when there is a text (eg. in <span> tag) that is somewhere at the end of the page, the library renders the text on the next page. The rendering is completely fine. The pdf document looks fine. However, the text which was overflown from the previous page seem to be present in the previous page as well. It is not rendered, but is there.

Our application search the occurrence of the text, and returns the coordinates of the text. Based on the coordinate, another application does additional pdf processing. So when the library is producing duplicate text (one visible, and another invisible), it is causing us problem.

Here is our code for doing the conversion:
```
String cleanedHtml = doHtmlCleanup(input);
            PdfRendererBuilder builder = new PdfRendererBuilder();

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.CAVEAT_REGULAR.getFontPath()),
                    AvailableFont.CAVEAT_REGULAR.getHtmlFontName());


            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.LORA.getFontPath()),
                    AvailableFont.LORA.getHtmlFontName(), 400, FontStyle.NORMAL, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.LORA_ITALIC.getFontPath()),
                    AvailableFont.LORA_ITALIC.getHtmlFontName(), 400, FontStyle.ITALIC, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.LORA_BOLD.getFontPath()),
                    AvailableFont.LORA_BOLD.getHtmlFontName(), 700, FontStyle.NORMAL, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.LORA_BOLD_ITALIC.getFontPath()),
                    AvailableFont.LORA_BOLD_ITALIC.getHtmlFontName(), 700, FontStyle.ITALIC, true);


            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TINOS.getFontPath()),
                    AvailableFont.TINOS.getHtmlFontName(), 400, FontStyle.NORMAL, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TINOS_ITALIC.getFontPath()),
                    AvailableFont.TINOS_ITALIC.getHtmlFontName(), 400, FontStyle.ITALIC, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TINOS_BOLD.getFontPath()),
                    AvailableFont.TINOS_BOLD.getHtmlFontName(), 700, FontStyle.NORMAL, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TINOS_BOLD_ITALIC.getFontPath()),
                    AvailableFont.TINOS_BOLD_ITALIC.getHtmlFontName(), 700, FontStyle.ITALIC, true);


            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TIMESNEWROMAN.getFontPath()),
                    AvailableFont.TIMESNEWROMAN.getHtmlFontName(), 400, FontStyle.NORMAL, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TIMESNEWROMAN_ITALIC.getFontPath()),
                    AvailableFont.TIMESNEWROMAN_ITALIC.getHtmlFontName(), 400, FontStyle.ITALIC, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TIMESNEWROMAN_BOLD.getFontPath()),
                    AvailableFont.TIMESNEWROMAN_BOLD.getHtmlFontName(), 700, FontStyle.NORMAL, true);

            builder.useFont(() -> this.getClass().getResourceAsStream(AvailableFont.TIMESNEWROMAN_BOLD_ITALIC.getFontPath()),
                    AvailableFont.TIMESNEWROMAN_BOLD_ITALIC.getHtmlFontName(), 700, FontStyle.ITALIC, true);

            builder.withHtmlContent(cleanedHtml, "");
            builder.useDefaultPageSize(pageSize.getWidth(RocketPDFUnit.INCH), pageSize.getHeight(RocketPDFUnit.INCH),
                    PdfRendererBuilder.PageSizeUnits.INCHES);
            builder.useUnicodeBidiSplitter(new ICUBidiSplitter.ICUBidiSplitterFactory());
            builder.useUnicodeBidiReorderer(new ICUBidiReorderer());
            builder.defaultTextDirection(PdfRendererBuilder.TextDirection.LTR);
            builder.toStream(output);
            builder.run();
```

Four files attached:
First two files: HTML and PDF generated. Where html element fits in the page normally and conversion is done normally.
[document-without-problem.html.txt](https://github.com/danfickle/openhtmltopdf/files/2132774/document-without-problem.html.txt)
[document-without-problem.pdf](https://github.com/danfickle/openhtmltopdf/files/2132772/document-without-problem.pdf)

Second two files:
HTML where one component gets overflown to next page, and the text s_f85eec34-279d-44af-9d84-9bac84e191ad_ gets duplicated in the generated pdf. 
[document-with-problem.html.txt](https://github.com/danfickle/openhtmltopdf/files/2132774/document-with-problem.html.txt)
[document-with-problem.pdf](https://github.com/danfickle/openhtmltopdf/files/2132771/document-with-problem.pdf)

Version we are using: 0.0.1-RC12

**Comment by danfickle** [comment]
Hi @prsp20,

Firstly, sorry for the time it has taken me to get to this (it has been sitting in my email favorites). Unfortunately, you have given me all that I need to reproduce except the page size you are using. I did spend some time playing with page sizes and margins but couldn't get a line box to go over two pages unless line height was greater than the page height.

If you are still in a position to, could you provide the page size so I can reproduce? The behavior you describe is a serious bug.

Thanks.

**Comment by prsp20** [comment]
Thank you for the reply, @danfickle. My apologies for late reply.

We are using the page size: width: 612, height: 792 px.

If you are still unable to reproduce the issue, here is more info about how it could be reproduced:
Create a html file which fits in one page when converted to PDF. Keep filling items until the point when the last element gets overflown to next page. When that happens, remove the element which was overflown. Then keep increasing height of previous element. When the previous element's height is large enough to go below the page size, the text on this element will be duplicated.

I was using <span> html element which contained the text that got duplicated, so you could also test with the same.

Many thanks!

**Comment by danfickle** [comment]
I believe this is now fixed. Please reopen as required.
