### ISSUE TITLE
Processing HTML with SVG image from remote URL throws IOException: Unrecognized Image format

### ISSUE THREAD

**Issue by mcbeelen** [danfickle/openhtmltopdf#237]
I have a HTML-file, which contains an img with public URL to an SVG-image.

```
<p><img src="https://docs.chef.io/_images/start_chef.svg" alt="Chef Flow" /></p>
```

The PdfRendererBuilder is configured with the BatikSVGDrawer.

```
 builder.useSVGDrawer(BatikSVGDrawer())
```
When I try to create the PDF I get:
```
WARNING: Can't read image file; unexpected problem for URI 'https://docs.chef.io/_images/start_chef.svg'
java.io.IOException: Unrecognized Image format
	at com.openhtmltopdf.pdfboxout.PdfBoxImage.<init>(PdfBoxImage.java:53)
	at com.openhtmltopdf.pdfboxout.PdfBoxUserAgent.getImageResource(PdfBoxUserAgent.java:103)
	at com.openhtmltopdf.pdfboxout.PdfBoxReplacedElementFactory.createReplacedElement(PdfBoxReplacedElementFactory.java:59)
```

**Comment by syjer** [comment]
Hi @mcbeelen 

Currently, you cannot link a svg from a img tag.

You need to embed the svg directly. And in this case,  you will need to add 

```
<dependency>
  <groupId>org.apache.xmlgraphics</groupId>
  <artifactId>batik-codec</artifactId>
  <version>1.9</version>
</dependency>
```

as the svg contains a base64 encoded image.

**Comment by taras19921** [comment]
Hi all! My svg image is not displayed on PDF file. I have svg image on my html template. This is a snippet of my code:

`PdfRendererBuilder builder = new PdfRendererBuilder();
			builder.defaultTextDirection(BaseRendererBuilder.TextDirection.LTR);
			builder.useSVGDrawer(new BatikSVGDrawer());
			builder.useMathMLDrawer(new MathMLDrawer());
			builder.addDOMMutator(LaTeXDOMMutator.INSTANCE);
			builder.useDefaultPageSize(210, 297, BaseRendererBuilder.PageSizeUnits.MM);
			builder.withHtmlContent(html, "");
			builder.toStream(os);
			builder.run();` 

What I'm doing wrong or what I'm missing?

**Comment by syjer** [comment]
hi @taras19921 , could you provide the html file?

The code seems ok.

**Comment by taras19921** [comment]
Also I'm getting the following error: 

> java.io.IOException: The TrueType font null does not contain a 'cmap' table

I'm using 0.0.1-RC14 openhtmltopdf version.

**Comment by danfickle** [comment]
As of RC15 (just released) you can use a SVG image in a the ```<img>``` tag, so closing this issue. Thanks again @syjer.

**Comment by taras19921** [comment]
I can not find the RC15 repository: https://mvnrepository.com/artifact/com.openhtmltopdf/openhtmltopdf-pdfbox

**Comment by syjer** [comment]
@taras19921 it's up https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-core/0.0.1-RC15/  mvnrepository.com has a strong cache it seems :)

**Comment by taras19921** [comment]
Many thanks for help!!! It works)
