### ISSUE TITLE
Non-breaking space (nbsp) is not being replaced correctly under some conditions

### ISSUE THREAD

**Issue by nullquery** [danfickle/openhtmltopdf#247]
For some reason, the "nbsp" entity is not being replaced by a space in this case.

HTML input:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 9999.0//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html> 
 <head> 
 </head> 
 <body> 
  <p><img src="https://www.atsc.nl/images/cmsatsc/logo.png" /></p>
  <p>&euro; &#8364; &#x20ac; 39,00&nbsp;!</p> 
 </body>
</html>
```

Output shows "€ € 39,00!" so I'm missing 1 euro sign and the nbsp entity. 

The problem does NOT occur when I add a custom DOCTYPE like this:
```
<!DOCTYPE html [
  <!ENTITY nbsp "&#160;">
  <!ENTITY euro "&#8364;">
]>
```

I need to include the "euro" entity. If I remove all DOCTYPE declarations the converter throws an exception that the "euro" entity was not found.

This leads me to surmise that the missing euro sign in my output is not &amp;euro; and therefore the "xhtml-special.ent" file provided by the "xhtml1-strict.dtd" file is being included correctly.

But for some reason, the "xhtml-lat1.ent" file is not being included correctly. I don't know where to continue debugging this, which is why I'm submitting this issue.

**Comment by danfickle** [comment]
Hi @nullquery 

Did you see [this link](https://github.com/danfickle/openhtmltopdf/blob/19828ff579863fdbd0ffe28108d3b14626ec64da/openhtmltopdf-examples/src/main/resources/documentation/documentation.md#character-entities)

Sorry about the poor documentation.

**Comment by danfickle** [comment]
Finally, it's in the integration guide!
