### ISSUE TITLE
rc14 no longer working on app engine

### ISSUE THREAD

**Issue by Rob46** [danfickle/openhtmltopdf#253]
I just tried using the latest libraries ... the third line of code below throws the exception below it:

PdfRendererBuilder builder = new PdfRendererBuilder();
ByteArrayOutputStream baos = new ByteArrayOutputStream();
builder.withHtmlContent(sourceHtml, baseUri);
		
java.lang.NoSuchMethodError: com.openhtmltopdf.pdfboxout.PdfRendererBuilder.withHtmlContent(Ljava/lang/String;Ljava/lang/String;)Lcom/openhtmltopdf/outputdevice/helper/BaseRendererBuilder;

**Comment by danfickle** [comment]
This usually happen when the correct jar(s) are not on the classpath at runtime. Can you check your App Engine setup to make sure this is not the case? Thanks.

**Comment by Rob46** [comment]
Does rc14 have more mandatory dependencies than rc12?

**Comment by danfickle** [comment]
Only updated versions.

**Comment by danfickle** [comment]
Assumed resolved, please reopen if required.
