### ISSUE TITLE
Checkbox checked not work

### ISSUE THREAD

**Issue by smeligrana** [danfickle/openhtmltopdf#257]
Hello,
   I'm trying to turn a html page into pdf but it does not work with checkedboxes.
For the tests I'm using https://sandbox.openhtmltopdf.com/
When I enter
`<input type="checkbox" name="check" value="1" checked="checked" />&#160;Check Description`
I get a check that is not selected

Thanks

**Comment by smeligrana** [comment]
I solved my problem it was enough to add the form tag to the outside of the checkbox
```
<form>
<input type="checkbox" name="check" value="1" checked="checked" />&#160;Check Description
</form>
```

**Comment by danfickle** [comment]
Thanks @smeligrana, I’ve added a note to the [form controls documentation](
https://github.com/danfickle/openhtmltopdf/wiki/Form-Controls).

Also note that the sandbox is currently using an out of date version.

**Comment by faisalferoz** [comment]
For this to work properly every checkbox needs to be in a separate form tag like:
```
<form>
  <input type="checkbox" name="check1" value="1" checked="checked" />&#160;Check Description 1
</form>

<form>
  <input type="checkbox" name="check2" value="1" checked="checked" />&#160;Check Description 2
</form>
```
