### ISSUE TITLE
My svg image is not displayed on PDF file.

### ISSUE THREAD

**Issue by taras19921** [danfickle/openhtmltopdf#258]
Hi all! My svg image is not displayed on PDF file. I have svg image on my html template (see attached file)
 file). This is a snippet of my code:

`PdfRendererBuilder builder = new PdfRendererBuilder();
			builder.defaultTextDirection(BaseRendererBuilder.TextDirection.LTR);
			builder.useSVGDrawer(new BatikSVGDrawer());
			builder.useMathMLDrawer(new MathMLDrawer());
			builder.addDOMMutator(LaTeXDOMMutator.INSTANCE);
			builder.useDefaultPageSize(210, 297, BaseRendererBuilder.PageSizeUnits.MM);
			builder.withHtmlContent(html, "");
			builder.toStream(os);
			builder.run();` 

What I'm doing wrong or what I'm missing?

[circle_html.txt](https://github.com/danfickle/openhtmltopdf/files/2257500/circle_html.txt)

**Comment by syjer** [comment]
hi @taras19921 ,  `<img src="cbof9-4931t.svg"/>` is supported from the (still unreleased) version 0.0.1-RC15 .

If you are using the RC14, you need to inline the svg in your html.

**Comment by taras19921** [comment]
Hi @syjer . Thank you for a quick reply. Yes I am using RC14 version.
I've added to inline svg in my html (see attached) but I don't see svg image on PDF file(see attached)

[circle_html.txt](https://github.com/danfickle/openhtmltopdf/files/2257735/circle_html.txt)

[circle.pdf](https://github.com/danfickle/openhtmltopdf/files/2257736/circle.pdf)

**Comment by danfickle** [comment]
Hi @taras19921 

You just need to add the XML namespace on the ```svg``` element:
````html
<!DOCTYPE html>
<html>
<body>

<svg xmlns="http://www.w3.org/2000/svg" height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg> 
 
</body>
</html>
````

**Comment by danfickle** [comment]
I've started a [SVG wiki page](https://github.com/danfickle/openhtmltopdf/wiki/Plugins:-SVG-Images). If you find any other quirks in our implementation (or tips for use), feel free to mention them here so I can add to that page or edit the wiki page directly.

**Comment by taras19921** [comment]
Many thanks for help!!! It works after upgrading to latest version : 0.0.1-RC15
