### ISSUE TITLE
bug : transform rotate, Picture is cut

### ISSUE THREAD

**Issue by mapleLeat** [danfickle/openhtmltopdf#260]
```
<html>
<head>
	<title></title>
</head>
<body>
	<div style="position: relative;    width: 520px;height: 820px;">
		<div style="width: 900px; top: 244px; left: 40px; z-index: 1; transform: rotate(49deg); position: absolute;height: 1px;    background-color: #000000;z-index: 1;"></div>
		<div style="position: absolute;width: 600px;height: 600px;top: 44px; left: 40px;z-index: 2;">
			<img src="111.jpg" style="width: 100%;height: 100%;" />

		</div>
	</div>
</body>
</html>
```

html result:
![1](https://user-images.githubusercontent.com/20888798/43702772-5bc673cc-998d-11e8-9d18-9b809ac3f33c.png)

pdf result:
![2](https://user-images.githubusercontent.com/20888798/43702781-617835b2-998d-11e8-8083-cf113b6a9b8d.png)

Line rotation causes the picture to be incomplete

**Comment by danfickle** [comment]
Hi @mapleLeat,

The bad news:
Transforms in the old (and slow) renderer are hopelessly broken, at least for anything that is not very simple.

The good news:
Transform support in the new fast renderer is shaping up much better. Indeed, both #259 and #260 work fine with the fast renderer.

More bad news:
The fast renderer is not quite finished, although I am working on it.

**Comment by mapleLeat** [comment]
@danfickle 
Thank you for your reply, I am looking forward to the new fast renderer, I wish you an early completion.

**Comment by danfickle** [comment]
Hi @mapleLeat,

I've added your test cases from #260 and #259 to the tests for the fast renderer, so I think we can close these issues now.
