### ISSUE TITLE
Input fields not being written to the PDF

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#263]
First, let me say this works in the test cases-- both with your forms file and my test file.  For some reason its not working in my project.  I verified I have the same code version, same PDFBox libraries, etc.  The HTML is not that complex, it has input fields of type text, radio, and checkbox.  It also has a select and a textarea.  The select and textarea are written to the PDF.  Although the select is written with what I assume is two appearance streams.

I've done my best to narrow down the problem.  I'm fairly certain it is in the layout process of PdfBoxRenderer.layout().  I'm a little lost on where to look.  There are no errors warnings.  If someone with better knowledge of the openhtmltopdf project can tell me where the best place to inject a breakpoint and observe the renderer, I'll dig into what the problem is.

Thanks

**Comment by danfickle** [comment]
Hi @dmartineau99,

It sounds like you have some custom css that is preventing input elements from creating a box, and thus the widget annotation is not generated. For example, controls must be ```block``` or ```inline-block```. If that doesn’t work, try giving the control a border and background color to see if the box is actually being created. I’ll add a note in the docs about ```block/inline-block```.

**Comment by ghost** [comment]
Hi @danfickle 

The html is pretty simple.  No CSS/Style.`<html><head><title>x</title></head><body><input type='text' name='xyz' value='xxx'/></body></html>`

The only thing I can think of is some second level libraries are different.  I can't imagine a w3c.dom.Document is different.

**Comment by danfickle** [comment]
Controls need to be inside a ```<form>``` element. You should be getting a warning in the log!?

**Comment by ghost** [comment]
@danfickle 
Sorry about that. The sample I gave was just to show there is no style.  Here is the actual DOM structure including the form tag:

(I'll attach as a file.  Haven't figured out how to do the inline code here in github).
[forms.txt](https://github.com/danfickle/openhtmltopdf/files/2302985/forms.txt)

**Comment by danfickle** [comment]
I haven’t tested it, but try getting rid of the ```xmlns``` attribute. I think we are running into an issue described in:
https://stackoverflow.com/questions/13882433/java-getnodename-and-namespaces

So a bug on our part, but widespread throughout the code.

**Comment by ghost** [comment]
Removing the namespace did not change anything.  And like I said above, this works in the test harness (TestcaseRunner).

Attaching the two ouput pdfs.  good.pdf is generated using the TestcaseRunner.  bad, from my project.
[bad.pdf](https://github.com/danfickle/openhtmltopdf/files/2308310/bad.pdf)
[good.pdf](https://github.com/danfickle/openhtmltopdf/files/2308311/good.pdf)

**Comment by syjer** [comment]
@dmartineau99 , could you provide a list of dependencies of your project? How are you running it ? Inside an application server?

I've tried to add xerces, as sometimes it cause issues in the xml parsing, but it was not the good pick.

**Comment by ghost** [comment]
@syjer , there are over a hundred libraries that the project depends on.  It is running inside an application server.  I removed xerces and xalan but no change.  We use xerces, but for this particular process the document factory is picking the same default implementation from rt.jar that the openhtmltopdf is.  If you look at the "good.pdf", the margins are different.  Its the same HTML so I'm confused why there is a difference.  Its almost like there is a default style being applied.  I have commented builder.addDOMMutator(LaTeXDOMMutator.INSTANCE); and otherwise made the code in testcaserunner as close to the same as my project code as possible.

**Comment by ghost** [comment]
OK- I'm getting closer.  In the success path, Matcher line 369 has a result with cascadeProperties (TreeMap) with dozens of what I assume are default properties for the input element.  In my project, there is only one property- display:inline-block.  So I assume the difference between the two is some pre-loader that has all the default attributes of an element.  I'll keep hunting.

**Comment by ghost** [comment]
I found the problem.  We had used flyingsaucer before and have a XhtmlNamespaceHandler.css file in our project which XhtmlCssOnlyNamespaceHandler was finding instead of the one you provide.

**Comment by syjer** [comment]
@dmartineau99 that was quite a ride :)

**Comment by msuvarna-web** [comment]
I  am facing the same challenge if anyone can help.
