### ISSUE TITLE
Background image is not being sized correctly.

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#268]
It appears from stepping into the code that an image referenced as a background image does not get the same resizing as an inline image.  It ends up with its original height and width attributes and is not scaled to the coordinate system.  So it shows up in the PDF as a tiny image.

Some code:
`        <style>
            #header{
            height:120px;
            line-height:100px;
            text-align:right; 
            font-size:15px;
            color:#FAD9C5;
            background: url(../Images/bg.png) no-repeat 0 center;
            }
        </style>`

**Comment by ghost** [comment]
Using a background-size takes care of it, so I don't know if this is really an issue.
`background-size: 300px 100px;`

**Comment by danfickle** [comment]
According to mdn this is correct behaviour:
https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

So closing for now.
