### ISSUE TITLE
Support right-to-left un/ordered lists with bulletpoints

### ISSUE THREAD

**Issue by sandre1** [danfickle/openhtmltopdf#270]
Hello. Right now i am trying to render a pdf containing unordered lists with arabic text, but the bullet points of the list items are rendered left-to-right mode.
I am using css style like so :
ul {
  direction: rtl;
}
ul  li {
  direction: rtl;
}`
but this is not working.

Any ideas? thanks

**Comment by ieugen** [comment]
Could you please make a short HTML sample + PDF output that allows to reproduce the issue.

**Comment by sandre1** [comment]
This is an example code
```
<html>
<head>
<style>
  
ul.rtl-unordered-list {
  direction: rtl;
}

ul.rtl-unordered-list li {
  direction: rtl;
}

</style>
</head>
<body>
<h3 dir="rtl">Right-to-left title</h3>
  <ul class="rtl-unordered-list" dir="rtl">
    <li>List item - right-to-left direction</li>
    <li>List item - right-to-left direction</li>
  </ul>
</body>
</html>
```

and the pdf output is 
![bulletpoints-rtl](https://user-images.githubusercontent.com/33352772/44573368-1a683900-a78f-11e8-9f8e-0e8e3bcbb485.png)

The expected result is having bulletpoints on the right-side of the unordered list.

**Comment by syjer** [comment]
@sandre1 from the code of https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-core/src/main/java/com/openhtmltopdf/render/ListItemPainter.java it don't take the RTL information when paiting the "list decoration". So, it's currently a missing feature.
