### ISSUE TITLE
CSS property "overflow: hidden;" not supported

### ISSUE THREAD

**Issue by mapleLeat** [danfickle/openhtmltopdf#273]
Whether to consider adding this support?

**Comment by Jugen** [comment]
I would like to have this supported please.
Currently I've "hacked" com.openhtmltopdf.render.LineBox for my needs. 
See issue #117 
Thanks

**Comment by danfickle** [comment]
```overflow:hidden``` should be supported. Could you provide a minimal example?

**Comment by mapleLeat** [comment]
@Jugen @danfickle 
sorry~
I show an example

```
<!DOCTYPE HTML>    
<html>    
<head> 
	 <style>@page {size:  500px 500px;margin: 0px;padding: 0px;}body {margin: 0;}</style>
</head>
<title></title>
<body>
	<div style="width: 500px;height: 500px;background-color: green;">
		<div style="position: relative;overflow: hidden;width: 400px;height: 400px;top: 50px;left: 50px;border: 1px solid;">
			<div style="width: 200;height: 50px;position: absolute;top: 100px;left: -10px;font-size: 50px">sdfsdgfhgfhg</div>
		</div>
	</div>
</body>    
</html>
```

html:
![11](https://user-images.githubusercontent.com/20888798/44964765-c9adc880-af64-11e8-909f-b2deba98f361.png)

pdf:
![pdf](https://user-images.githubusercontent.com/20888798/44964771-d03c4000-af64-11e8-8930-8c830b08cf6f.png)


this is HTML to PDF
The HTML to Picture is the same

**Comment by mapleLeat** [comment]
@Jugen 
Thank you~
I think your method should not suit me.

**Comment by Jugen** [comment]
@mapleLeat Yes, I see that you are looking for horizontal overflow to be hidden while my implementation only caters for vertical overflow if it's at the bottom of a page.

**Comment by danfickle** [comment]
Thanks @mapleLeat for the sample code. I have incorporated it into a test and can confirm ```overflow:hidden``` is not working when ```position``` is anything other than ```static``` or ```transform``` is anything other than ```none```.

I think it has to be left that way in the old (slow) renderer for backwards compatibility but I'll certainly work on it in the new (fast) renderer.

@Jugen 
For your issue, you may be able to workaround it with a custom property:
````css
  /* Similar to the orphans property, this property allows the author
    * to specify how much of the block must show before a page-break.
    * If the constraint is violated, a page break is added before the element.
    * Very useful on elements not made of lines, such as tables, etc.
    */
    -fs-page-break-min-height: 100px;
````
