### ISSUE TITLE
Start pagination with counter 1 from second page 

### ISSUE THREAD

**Issue by sandre1** [danfickle/openhtmltopdf#274]
in my project i designed the first page as a cover, and i want to skip it from being countered when using pagination. Is there any way to start pagination 1/total,  but  from the second page? 
I used a different footer on @page:first (set the content: " ";) but for no use: the first page was not paginated any more but the second page was paginated as 2/total. 

Example code:
`<html>`
`<head>`
`<style>`
`@page:first {`
  `@bottom-right {`
   ` content: '';`
 ` }`
`}`
`@page {`
  @bottom-right {
    content: counter(page) "/" counter(pages);
   }
```
}
.page-breaker-after {
    page-break-after: always;
}
</style>
</head>
<body>
<div class="page-breaker-after page1">Cover</div>
<div class="page-breaker-after page2">this page has pagination 1/3 </div>
<div class="page-breaker-after page3">this page has pagination 2/3</div>
<div class="page-breaker-after page4">this page has pagination 3/3/div>
</body>
</html>`
```

**Comment by danfickle** [comment]
Hi @sandre1,

Try this:
````html
<html>
<head>
<style>
@page {
   @bottom-center {
      content: 'Page ' counter(page);
   }
}
@page:first {
   @bottom-center {
      content: '';
   }
}
 </style>
 </head>
 <body>
 <div style="">COVER</div>
 <div style="page-break-before: always;-fs-page-sequence: start;">REST 1</div>
 <div style="page-break-before: always;">REST 2</div>
 <div style="page-break-before: always;">REST 3</div>
 <div style="page-break-before: always;">REST 4</div>
 </body>
 </html>
````

The magic is the ```-fs-page-sequence: start``` where you want the page counter to restart. You should also be able to do this with ```counter-reset: page``` but that appears not to work.

I found this info at:
https://stackoverflow.com/questions/29136505/flying-saucer-page-count-with-css

**Comment by sandre1** [comment]
It worked as a charm. Thank you very much for offering to help, and for your time with this project Daniel.
