### ISSUE TITLE
Move to Java 8 requirement?

### ISSUE THREAD

**Issue by danfickle** [danfickle/openhtmltopdf#280]
We were thinking of moving to a minimum of java 8. This would give us streams/lambdas and other modern goodies. It’s been several years since java 8 was released. If you object, here is your chance to say why.

**Comment by achuinard** [comment]
No objection. Great work with this open source library, @danfickle. Sustain its future with a move to Java 8.

**Comment by Fancellu2** [comment]
Agreed. Java8 has been out for 4 years.

If someone is stuck at jdk 7, they can always use an older release

**Comment by dilworks** [comment]
No problem here - been on Java 8 for a while without incidents. in fact now that J2EE 8 is a thing, I'm looking forward to move to Java 9 (or whatever is the latest version for this week - this new versioning scheme is really awful, thanks Google!)

If you're stuck with Java 7, hope you're paying those megabuckos to Oracle for that support contract!

**Comment by danfickle** [comment]
RC18 is Java 8 all the way, so closing this.
