### ISSUE TITLE
Underline seems to not take space expansion into account

### ISSUE THREAD

**Issue by koritakoa** [danfickle/openhtmltopdf#281]
In a paragraph with 'text-align: justify', I have a span that is underlined. The line does not extend to the full width of the span. About 1.8 characters at the end are not underlined. I think this is due to the span being expanded in width due to the justified alignment.

0.0.1-RC15

**Comment by danfickle** [comment]
Hi @koritakoa,

Yes, you were right. We were adjusting the position of the enclosing boxes but not their width.

Before:
![issue-281-before](https://user-images.githubusercontent.com/1415728/46620253-f78fb980-cb6f-11e8-9ada-8c559bb45d33.png)

After:
![issue-281-after](https://user-images.githubusercontent.com/1415728/46620260-fd859a80-cb6f-11e8-9d59-e8da803e2bee.png)

I think I can close this now. Thanks for reporting. I wish all bugs were as easy to find!

**Comment by koritakoa** [comment]
Thank you for resolving this so quickly.
