### ISSUE TITLE
Any idea why there is a big grey box at the end?

### ISSUE THREAD

**Issue by Fancellu2** [danfickle/openhtmltopdf#282]
[Test data message to demo all possible links.pdf](https://github.com/danfickle/openhtmltopdf/files/2469874/Test.data.message.to.demo.all.possible.links.pdf)

If I view it in acrobat reader DC, it looks fine

However if I view it in firefox or chrome I see a big grey box at the end

Any idea why? Is this a known issue?

Is there a good GUI tool to examine PDF to see what PDF elements are present?

Thanks

**Comment by Fancellu2** [comment]
Ok, found out reason.

CSS was setting html {background-color}

Was not seen in modern acrobat, but was in older

Got around it by slipping this into head

``` 
<style>
   html {
    background-color: transparent;
   }
  </style>
```

**Comment by danfickle** [comment]
Glad you solved it. Thank you for coming back with the solution.
