### ISSUE TITLE
Img disappears after the bottom overflows

### ISSUE THREAD

**Issue by mapleLeat** [danfickle/openhtmltopdf#283]
```
<html>
 <head>
  <style>@page {size:  520px 320px;margin: 0px;padding: 0px;}body {margin: 0;}@font-face { font-family: 'Agency FB';src:url('/data/lukisdata/fontfamily/font1/Agency_FB_Bold.TTF');}</style>
 </head>
 <body>
    <div style="width:520px;height:320px;border: 1px solid;">
      <div  style="position: absolute;width: 100px;height: 100px;left:50px;top:230px;"><img src="bb.jpg" style="width: 100%;height: 100%;" /></div>
    </div>
 </body>
</html>
```
No overflow can be converted normally:
![11](https://user-images.githubusercontent.com/20888798/46862570-bdf8d000-ce47-11e8-8a3f-3246fb0fc7f4.png)

If you move the position of img down.
When the bottom of the picture overflows, the picture that has been turned out disappears.
![22](https://user-images.githubusercontent.com/20888798/46862677-f7314000-ce47-11e8-8a27-1c308d530463.png)

May I ask what is the reason

**Comment by danfickle** [comment]
Is it moving to the next page? Try using ```display: block``` on the ```img```.

https://github.com/danfickle/openhtmltopdf/issues/117

**Comment by mapleLeat** [comment]
@danfickle 
Your method is correct, thank you
