### ISSUE TITLE
Justified text background is rendered incorrectly

### ISSUE THREAD

**Issue by allartammik** [danfickle/openhtmltopdf#286]
When text alignment is justified (text-align: justify) and background color is set (span style="background-color:#1abc9c"), the background is rendered incorrectly. I'm using version 0.0.1-RC16 of the library.

I made a simple test case for you https://bitbucket.org/allar/openhtmltopdftestcase/src/master/
I also found a closed issue #281 that might be related.

Thanks

**Comment by allartammik** [comment]
Hi again!

I took the source code of latest open-dev-v1 (commit b545b1) and built the openhtmltopdf-core, and I am glad to confirm, that the fix you made with #281 works with background color as well. 

I'm looking forward to the release now. Can you predict when the next release will take place?

**Comment by danfickle** [comment]
Hi, I’m planning a release for the weekend. Thanks for the test case, I’ll add it to the visual regression tests shortly.

**Comment by danfickle** [comment]
RC17 just released with fix. Thanks @allartammik, @koritakoa.
