### ISSUE TITLE
 Could not load @font-face font: data:application/x-font-truetype;base64

### ISSUE THREAD

**Issue by arocker1000** [danfickle/openhtmltopdf#290]
"com.openhtmltopdf.exception WARNING:: Could not load @font-face font: data:application/x-font-truetype;base64,AAEAAAANAIAAAwBQT1MvMlXy0soAAADcAAAAYGNtYXBW4lqxAAABPAAAAqJjdnQgAOMA3wAAA......."
and it throw exception 
Exception in thread "main" java.lang.NullPointerException
	at com.openhtmltopdf.pdfboxout.PdfBoxTextRenderer.getWidth(PdfBoxTextRenderer.java:300)

[demo-support.zip](https://github.com/danfickle/openhtmltopdf/files/2541401/demo-support.zip)

I can't figure out what's wrong.

**Comment by danfickle** [comment]
We currently do not support data uris in the font-face block. I’ll try to fix this as part of the Java 8 upgrade but I want to finish the fast renderer first so could be a few weeks. In the mean time there are several other ways to load a font.

**Comment by danfickle** [comment]
This is now implemented. Hang out for the next release!
