### ISSUE TITLE
Image url (<img src=url>) doesn't work but base64 works

### ISSUE THREAD

**Issue by hussaintamboli** [danfickle/openhtmltopdf#292]
I might be missing some key information from the documentation. I tried rendering a HTML that has `<img src=url>` and I got "HTTP error fetching URL" error. I searched similar issues here and everybody seems to be either using svg image or base64 of the image. 

Please clarify.

**Comment by danfickle** [comment]
The url needs to be absolute or if relative, you may need to specify a correct base url. Could you post a minimal builder and HTML sample if you can’t get it to work?

I’ve got tests with file urls at least.

**Comment by hussaintamboli** [comment]
I tried a different image url and it gets rendered in pdf. I think the image I was trying previously had an issue. So, false alarm! Sorry.
