### ISSUE TITLE
New page for every data

### ISSUE THREAD

**Issue by mctdi** [danfickle/openhtmltopdf#293]
I use openHtmlToPdf with an template in html, that work fine. 

I need now to pass a list of object and for every object that need to be on a new page in the final pdf.

**Comment by danfickle** [comment]
Use ```page-break-before: always``` or ```page-break-after: always``` css properties.

https://github.com/danfickle/openhtmltopdf/wiki/Page-features

**Comment by mctdi** [comment]
in all case there will have a useless page created, no?

**Comment by marccollin** [comment]
you can use js to detect if you are on the last item... and change class name

**Comment by danfickle** [comment]
We don’t support JavaScript, but you can use ```:first-child``` or ```:last-child``` pseudo selectors if automatic pruning of empty pages is not working for you.
