### ISSUE TITLE
Does this project support css grid-areas?

### ISSUE THREAD

**Issue by hussaintamboli** [danfickle/openhtmltopdf#294]
I have a HTML that uses grid-areas. The generated PDF is very different from it. I am wondering is it because of grid-areas.

https://developer.mozilla.org/en-US/docs/Glossary/grid_areas

**Comment by danfickle** [comment]
No support for css grid or flex-box. Hopefully you can achieve reasonable layouts with tables and floats.

**Comment by hussaintamboli** [comment]
Okay. Thank you for this project.
