### ISSUE TITLE
Keep an element together with the next paragraph, avoiding a page break

### ISSUE THREAD

**Issue by borgogelli** [danfickle/openhtmltopdf#295]
We have tried to use the <div> tag to keep together a table and a text 

```
<div>
<p>Description</p>
<table>
…
</table>
</div>

```

...but it doesn't work as expected, and sometimes the description is on one page and the table on the next one.

(@danielemontesi)

**Comment by danfickle** [comment]
Are you using ```page-break-inside: avoid``` on the div?

**Comment by borgogelli** [comment]
Thank you, it works. It's the solution I was looking for.
