### ISSUE TITLE
Border not printed with "overflow: hidden"

### ISSUE THREAD

**Issue by maresja1** [danfickle/openhtmltopdf#297]
In RC-17 there is a problem with rendering span with overflow: hidden and border. For following HTML:
```html
<!DOCTYPE HTML>
<html>
<head>
	<style>
		@page {size:  500px 500px;}body {margin: 0;}

		.letterField {
			border: 2px solid #008e7e;
			border-right: 0;
			border-left-width: 1px;
			float: left;
			padding: 2px 3px;
			font-size: 10px;
			display: inline-block;
			color: #000;
			font-weight: bold;
			width: 6px;
			overflow: hidden;
		}

		.letterField:first-child {
			border-left: 2px solid #008e7e;
		}

		.letterField:last-child {
			border-right: 2px solid #008e7e;
		}

	</style>
</head>
<title></title>
<body>
<span class="letterField">AASLKDJ</span>
</body>
</html>
```

I get this on RC-17:
![image](https://user-images.githubusercontent.com/1552179/48973429-58e7eb00-f03f-11e8-9f83-c7ef6be616f5.png)
And this on RC-16:
![image](https://user-images.githubusercontent.com/1552179/48973431-62715300-f03f-11e8-9c87-122382f3006f.png)

See attached PDF files.
[border-overflow-RC16.pdf](https://github.com/danfickle/openhtmltopdf/files/2612626/border-overflow-RC16.pdf)
[border-overflow-RC17.pdf](https://github.com/danfickle/openhtmltopdf/files/2612627/border-overflow-RC17.pdf)

**Comment by maresja1** [comment]
Also noticed now, that I can see very very thin border when displaying the PDF inside the browser, but not at all with gnome's evince.

**Comment by danfickle** [comment]
Hi @maresja1,

Thanks for the concise example and expected images.

I could replicate your behavior (very thin border in Mac Preview, none in Acrobat), but only when I used the fast mode renderer, which is not ready for production use yet. The output was equivalent to RC16 image when using this builder code:

````java
    public static void main(String... args) throws Exception { 
        try (OutputStream os = new FileOutputStream("/Users/me/Documents/pdf-issues/output/issue-297.pdf")) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.withUri("file:///Users/me/Documents/pdf-issues/issue-297.htm");
            builder.toStream(os);
            builder.testMode(true);
            //builder.useFastMode(); // Could only replicate by uncommenting this line!
            builder.run();
        }
    }
````

I can confirm this is still an issue in head in the fast mode renderer and will add a test now. If by any chance you are not using the fast mode, could you post your builder code so I can replicate?

**Comment by danfickle** [comment]
It appears the problem only appears with floated elements with overflow hidden and a border. I never would have found that so thanks for reporting.
