### ISSUE TITLE
font tag with face attribute is not working in openhtml2pdf could someone please help me below is the sample code where i want to load segoescb.ttf font file but it is not applying in the pdf.

### ISSUE THREAD

**Issue by nagababuballa** [danfickle/openhtmltopdf#298]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
            "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<style type="text/css">

@font-face {
  src: url(fonts/segoescb.ttf);
  font-family: 'Segoe Script';
}
</style>
</head>
<body>
<table>
<tr>
<td><p>BLACK (default)</p></td>
<td style="color: #ff0000;background-color:#62b7c4">RED (hex)</td>
<td style="color: #0f0;background-color:#62b7c4">GREEN (short hex)</td>
<td style="color: blue;background-color:#62b7c4">BLUE (name)</td>
<td style="color: rgb(255, 0, 0);background-color:#62b7c4">RED (rgb number)</td>
<td style="color: rgb(0, 100%, 0);background-color:#62b7c4">GREEN (rgb percent)</td>
<td style="color: cmyk(100%, 0, 0, 0);background-color:#62b7c4">CYAN (cmyk percent)</td>
<td style="color: cmyk(0,1,0,0);background-color:#62b7c4">MAGENTA (cmyk number)</td>
<td>TODO: hsl, hsla, rgba, etc</td>
<td style="color: cmyk(0,1,0,0);background-color:blue;font-family: Arial, Helvetica, sans-serif;">naga babu</td>
<td style="color: cmyk(0,1,0,0);background-color:green;font-family: Courier New, Monospace, sans-serif;">Nanaji</td>
</tr>
</table>
<p><font face="Segoe Script">Test Comments by Nagababu</font></p>
</body>
</html>

**Comment by danfickle** [comment]
Here is a complete example:
````html
<html>
<head>
<style>
@font-face {
src: url(fonts/segoescb.ttf);
font-family: 'Segoe Script';
}
.segoe {
  font-family: 'Segoe Script', serif;
}
</style>
</head>
<body>
<p class="segoe">This is some Segoe Script!</p>
</body>
</html>
````
The ```<style>``` tag must appear inside the ```<head>```. You must have set a correct base url or  use a complete url in the builder so that the font file can be resolved.

**Comment by danfickle** [comment]
Assumed solved, please reopen if required. Thanks.
