### ISSUE TITLE
white-space: nowrap cutting off instead of wrapping

### ISSUE THREAD

**Issue by zimmi** [danfickle/openhtmltopdf#302]
Running the following snippet:

```html
<html>
    <head>
        <style>
            @page {
                size: A4;
                margin: 72pt;
            }
            .heading {
                text-align: center;
                font-size: 20pt;
            }
            .nowrap {
                white-space: nowrap;
                background-color: yellow;
            }
        </style>
    </head>
    <body>
        <div class="heading">heading heading heading heading heading heading <span class="nowrap">should wrap together</span> heading heading heading</div>
    </body>
</html>
```

... produces this output: [white_space_nowrap_bug.pdf](https://github.com/danfickle/openhtmltopdf/files/2653245/white_space_nowrap_bug.pdf)

I expected all text to be displayed and a line break before `should wrap together`. Am I doing something wrong? My HTML skills are admittedly pretty rusty.

**Comment by danfickle** [comment]
Yes, seems to be a significant bug. The inline boxing functionality needs a rewrite to address this issue, #113 and #39. However it is a 300 line monster so I need a lot more tests around it before attempting. I’m starting to write text tests at the moment so there is hope.

**Comment by zimmi** [comment]
Thanks for doing this! It's probably best to clean up the foundation first, it's not super critical for my project at the moment anyway.
I think I touched that code slightly in https://github.com/danfickle/openhtmltopdf/pull/304 to fix another bug / annoyance.

**Comment by danfickle** [comment]
Thank for reminding me that we need to keep min/max width functions in sync with inline boxing function.

**Comment by jaylemur** [comment]
Any news concerning this Ticket ?
Is there meanwhile a workaround to avoid this cutting off ?

Thanks in advance.

**Comment by vipcxj** [comment]
I need a workaround, too.
