### ISSUE TITLE
white-space: pre-wrap; is not working in openhtml2pdf

### ISSUE THREAD

**Issue by nagababuballa** [danfickle/openhtmltopdf#305]
Could please someone provide me the solution for this

**Comment by danfickle** [comment]
Hi @nagababuballa,

In my simple test, ```pre-wrap``` works perfectly. Could you provide some html where it is not working as specified?

**Comment by nagababuballa** [comment]
Thanks for your prompt response danfickle.
I am pasting the sample content where i am getting the problem
<table>
<tbody>
            <tr>
                <td class="preForm" colspan="4">Select the overall rating that best reflects this employeeӳ overall performance based on section A (Goal Accomplishments), Section B (Development Accomplishments), and Section C (Competency) across the review period using the drop-down rating list. Provide comments with examples where possible to the information provided by the employee.

OUTSTANDING:
Employee consistently excels performing in the role, making significant impact to Inphiӳ goals.  Employee delivers high quality results based on objectives and expectations. Employee demonstrates exemplary behavior aligned with Inphi culture.

EXCEEDS:
Employee performance on goals and other job requirements exceed the expected results.  Requirements are exceeded on even the most difficult and complex tasks. Employee demonstrates strong alignment with Inphi culture.

SUCCESSFUL: 
Employee is successful consistently achieving expectations performing in the role. Employee demonstrates solid behaviors aligned with Inphi culture.

MEETS:
Employee is meeting basic expectations performing in the role.  Employee demonstrates basic behaviors aligned with Inphi culture.

NEEDS IMPROVEMENT:
Employee requires improvement to perform in the role and meet expectations.  Employee may or does not demonstrate some behaviors aligned with Inphi culture.</td>
</tr>
</table>
and my preform class is like 
.preForm{
   word-wrap: break-word;
    text-align: justify;
    white-space:pre-wrap;
}
I am expecting some prespace should exists in between the labels like EXCEEDS:,SUCCESSFUL:  etc..
but i am not getting it in the pdf but while rendering the html in browser engine it is rendering as expected.could you please provide me the update

**Comment by nagababuballa** [comment]
Sorry it's working fine there is a small problem in my code.Thanks for your help
