### ISSUE TITLE
Symbols ✔ and ▢ are not rendered

### ISSUE THREAD

**Issue by rahimlis** [danfickle/openhtmltopdf#306]

**Comment by zimmi** [comment]
What font are you using? I just tried it with [DejaVuSans.ttf](https://dejavu-fonts.github.io/) and both (`&#x2713;` and `&#x25A2;`) work. You need to make sure that your font includes the required glyphs, the standard PDF fonts are very basic. To find out what fonts include which glyphs, I used [this site](https://www.fileformat.info/info/unicode/char/2713/fontsupport.htm), but I'm sure there are other/better ways.

**Comment by danfickle** [comment]
Thanks @zimmi, I think we can close this one.
