### ISSUE TITLE
Html file containig data employee's is showing as employee#s in pdf while openeed using acrobat reader.

### ISSUE THREAD

**Issue by nagababuballa** [danfickle/openhtmltopdf#307]
Html file containig data employee's is showing as employee#s in pdf while openeed using acrobat reader.
Could someone please give the solution

**Comment by zimmi** [comment]
Can you create a minimal HTML file that reproduces the issue? I just tried it and it works on my machine (although I'm using Evince, not Acrobat Reader).

Edit: What font are you using? Does it actually contain the `'` glyph?

**Comment by danfickle** [comment]
Also, check that you are using a standard apostrophe and not a smart quote.

https://practicaltypography.com/straight-and-curly-quotes.html

Of course you can use smart quotes if your font includes them.

**Comment by danfickle** [comment]
Thanks @zimmi. Assumed solved. Please reopen if required.
