### ISSUE TITLE
Will openhtmltopdf support auto page break?

### ISSUE THREAD

**Issue by matchleg** [danfickle/openhtmltopdf#308]
Thanks for this great tool!

I face an issue on printing the pdf. If a component is big enough and near the bottom of page,
its layout will cross over 2 pages.

Will openhtmltopdf support auto page break when faced this issue?

![image](https://user-images.githubusercontent.com/45838266/49913673-73d4af00-fec9-11e8-96f0-d9f299f0efd9.png)

Daniel

**Comment by danfickle** [comment]
Hi @matchleg,

Yes, auto page break is the default. You can avoid it with ```page-break-inside: avoid``` css property if needed. You can try your HTML (excluding images and fonts) at the sandbox, linked to from the readme.

**Comment by matchleg** [comment]
Thx, it works!
