### ISSUE TITLE
ClassCastException AnonymousBlockBox cannot be cast to TableCellBox on TD: float-left

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#309]
We see this exception:
java.lang.ClassCastException: com.openhtmltopdf.render.AnonymousBlockBox cannot be cast to com.openhtmltopdf.newtable.TableCellBox

With HTML
`            <table>
                <tr>
                    <td style="float:left">something</td>
                    <td>xx</td>
                </tr>
            </table>
`
Granted float:left on a td doesn't make sense but a warning to the log is preferable to an exception if possible.

**Comment by sandre1** [comment]
The same thing happens when using Html : 
`<td><img src="/img/regular/address-card.svg" width="20" /></td>`

**Comment by danfickle** [comment]
Thanks again @syjer for fix. Closing for now.
