### ISSUE TITLE
Table border line thickness is inconsistent

### ISSUE THREAD

**Issue by Ox2d** [danfickle/openhtmltopdf#310]
I have a problem when rendering html to PDF using openhtmltopdf.  As below picture, The border color of the first column and the last column of the table is lighter than other columns. Has anyone encountered this problem?
![image](https://user-images.githubusercontent.com/4818999/49994846-94822f00-ffc5-11e8-8232-7361b7cb78f9.png)

**Comment by zimmi** [comment]
I haven't run into that yet. Could you create a minimal HTML template that reproduces this behavior? Then it's easier to write a test.

**Comment by stephanebarbey** [comment]
We have provided a  minimal example for that behaviour in https://github.com/danfickle/openhtmltopdf/issues/752
