### ISSUE TITLE
Including fonts affects line spacing in PDF 

### ISSUE THREAD

**Issue by hussaintamboli** [danfickle/openhtmltopdf#312]
My PDF is going to have English, Chines and Thai text. So I included that in my HTML file.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <style>
        @font-face {
            font-family: 'noto';
            src: url('file:///tmp/fonts/NotoSerifThai-Regular.ttf');
            font-weight: normal;
            font-style: normal;
        }
        @font-face {
            font-family: 'zawgyi';
            src: url('file:///tmp/fonts/ZawgyiOne2008.ttf');
            font-weight: normal;
            font-style: normal;
        }

        * {
            font-family: sans-serif, "noto", "zawgyi";
        }
    </style>
</head>
<body>
   My content goes here.
</body>
</html>
```

When I generate PDF, the line spacing when fonts are not included and when included is different. Why is this happening?

I want it to be consistent and look like when fonts are not included.

**Comment by danfickle** [comment]
Hi @hussaintamboli,

The line spacing should be based on the maximum height of all the specified fonts. This is so we can guarantee that the text will fit on a line. Is this what you are seeing?

Alternatively, you can set the line height explicitly in pixels with CSS:
```line-height: 14px;```

**Comment by hussaintamboli** [comment]
Yes, that's the issue. Adding fonts changed `line-height`. 

Defining `line-height` in CSS works okay.

```
* {
    font-family: sans-serif, "noto", "mingo", "zawgyi";
    line-height: 1.2;
}
```

Thanks
