### ISSUE TITLE
Any setting to skips the TRaX transformer checking?

### ISSUE THREAD

**Issue by matchleg** [danfickle/openhtmltopdf#314]
Hi sir,

I am trying to convert a HTML with the following Google Map Link to PDF.

https://www.google.com/maps?q=22.363625999999954,114.13253000000006&z=17&hl=en_US

Unluckily, the google map url does not a valid html5 format. So the tool throws Exception during convertion... I listed the exception below. Are there any ways to config 'openhtmltopdf' to skip the url checking?

_com.openhtmltopdf.load INFO:: The reference to entity "z" must end with the ';' delimiter.
ERROR:  'The reference to entity "z" must end with the ';' delimiter.'
com.openhtmltopdf.exception WARNING:: Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 73; columnNumber: 87; The reference to entity "z" must end with the ';' delimiter._

Many Thanks,
Daniel

**Comment by danfickle** [comment]
Hi @matchleg,

The link, like all content, must be XML escaped. Ie. ```&``` becomes ```&amp;```.

**Comment by matchleg** [comment]
Thank @danfickle.
