### ISSUE TITLE
It's low memory usage ?

### ISSUE THREAD

**Issue by danmaidesenling** [danfickle/openhtmltopdf#316]
Hi ,
   I just want to know if it has a low memory usage if the html has 100,000 rows.
thanks

**Comment by danfickle** [comment]
Hi @danmaidesenling,

Currently, with the slow renderer, performance and memory usage scales with the square of the number of pages. Obviously, this makes it useless for very large documents.

Fortunately, I have been working on a fast renderer (#180) that I hope to release in the next month. This scales proportionally to the number of pages. If you like, you can download and build (```mvn install```) and try it with your use case. Remember to use ```builder.useFastMode()```.

**Comment by danmaidesenling** [comment]
Hi danfickle,
     thanks your answer, and i look forward your new version about fast renderer

**Comment by danmaidesenling** [comment]
Hi @danfickle ,
     It takes 263334ms when I test a big html to pdf file 
     here is my code 
`PdfRendererBuilder builder = new PdfRendererBuilder();
   builder.withHtmlContent(htmlContent,null);
     builder.useFastMode();
       builder.toStream(outputStream);
      builder.run();`
Below is the big html file (html is not allowed to upload, i convert it to txt)
[30000_ar-openItems.txt](https://github.com/danfickle/openhtmltopdf/files/2781722/30000_ar-openItems.txt)
Now as an aside, does the project support dense merge pdf files

**Comment by danfickle** [comment]
Hi @danmaidesenling,

I haven’t profiled yet (will do so once finished pdf/ua work) but it may be the auto table layout which is taking a long time. Since you seem to have predictable length data, you could try ```table-layout: fixed;``` on the table along with specific widths for the table and each column.

If you like, you could also fire up JVisualVM and find the bottlenecks with sampling.

**Comment by danmaidesenling** [comment]
Hi @danfickle ,
     Thank you for taking your time to answer the question.
      Actually, the html is rendered with data via thymeleaf. It was blocked for several hours when I test 50,000 rows(30000_ar-openItems.txt  is 30,000 rows)

**Comment by danfickle** [comment]
Hi @danmaidesenling,

I just did some profiling on table rows. I found a couple of places with n squared algorithms. After fixing these, table rows seem to render at a speed proportional to the total amount of rows. My ageing Mac was able to render your document in about 90 seconds.

I'm planning a release for this Sunday (10th March).

**Comment by danfickle** [comment]
OK, closing, please reopen if you're still having problems.
