### ISSUE TITLE
html convert to pdf, table miss part of the last column

### ISSUE THREAD

**Issue by danmaidesenling** [danfickle/openhtmltopdf#317]
![f39943ae33a43694192471327d9743a](https://user-images.githubusercontent.com/7588416/51739288-1046bf80-20cc-11e9-99f3-b8297183eac8.png)

column : Reason code. 
below is html code about table (thymeleaf template )
![8abfd9ed189ee13a5c9aa9f99d74ce1](https://user-images.githubusercontent.com/7588416/51739341-34a29c00-20cc-11e9-94ce-771d121510a0.png)

**Comment by danfickle** [comment]
That's right, if the minimum width of a table (or any element for that matter) is greater than the page width it will ordinarily be cut off silently.

However, I have spent a lot of time and effort with the fast renderer implementing a system where pages can be inserted with the cut-off content. See sample below:
````html
<html>
<head>
<style>
@page {
  size: 140px 50px;
  margin: 10px;
  -fs-max-overflow-pages: 10; /* This is the magic page property. */
  -fs-overflow-pages-direction: ltr;
}
body {
  margin: 0;
}
table {
  border: 1px solid black;
  background-color: red;
  min-height: 20px;
}
td {
  min-height: 15px;
  min-width: 50px;
  box-sizing: border-box;
}
</style>
</head>
<body>
<!-- Both table and pink td should be visible on inserted shadow page. -->
<table>
  <tr><td style="background-color: blue;"></td><td style="background-color: orange;"></td><td style="background-color: pink;"></td></tr>
</table>
</body>
</html>
````
At the moment, there is no way to label inserted cut-off pages as such, but I'm thinking of adding something like the following:
````
@page {
  -fs-max-overflow-pages: 10;
  @top-center {
    content: "Page " counter(page) -fs-if-inserted(" continued") " of " counter(pages);
  }
}
````


P.S I thought about your situation, and thought you may be better off dividing your content into lots of tables if possible. This may solve the table auto layout speed problem.

**Comment by danmaidesenling** [comment]
Thanks for your reply and your hard work @danfickle,
          Could you give me some advice to avoid such issue ? Maybe table width or td width or even font-size(the content of the table will change)

**Comment by danmaidesenling** [comment]
A temporary solution:  I set the @page to B4 from A4, and it works

**Comment by danfickle** [comment]
Clsoing this as the official solution (cut-off pages) is released with RC18.
