### ISSUE TITLE
ImageInputstream not closing when Exception

### ISSUE THREAD

**Issue by mariohb** [danfickle/openhtmltopdf#323]
When calling the function "PdfBoxImage(byte[] image, String uri)" it creates an ImageInputStream before entering the try-finally. So when an exception occurs, the stream is never closed.

```
public PdfBoxImage(byte[] image, String uri) throws IOException {
     _bytes = image;
    _uri = uri;

    ImageInputStream in = ImageIO
            .createImageInputStream(new ByteArrayInputStream(_bytes));
    ImageReader reader = null;

    try {
         ...
    } finally {
         if (in != null)
             in.close();
         if (reader != null)
         reader.dispose();
    }
```

A simple solution will be moving the call of the function inside the try block:

```
    ImageInputStream in = null;
    ImageReader reader = null;
        
    try {
        in = ImageIO.createImageInputStream(new ByteArrayInputStream(_bytes));
        ...
    } finally {
         if (in != null)
             in.close();
         if (reader != null)
         reader.dispose();
    }
```

**Comment by danfickle** [comment]
Hi @mariohb,

I thought that the only place it could throw is in the ```createImageInputStream``` call, in which case there is nothing to close.

Is this not correct? In any cases it could be changed to a try-with-resources. I’ll do that once I switch back to the main branch.
