### ISSUE TITLE
pdf not generated from html

### ISSUE THREAD

**Issue by mctdi** [danfickle/openhtmltopdf#325]
I have a html content when i try to convert it with rc17 get this in the browser

`%PDF-1.4 %öäüß 1 0 obj << /Type /Catalog /Version /1.7 /Pages 2 0 R >> endobj 3 0 obj << /CreationDate (D:20190202103213-05'00') /Producer (openhtmltopdf.com) /Title () >> endobj 2 0 obj << /Type /Pages /Kids [4 0 R 5 0 R] /Count 2 >> endobj 4 0 obj << /Type /Page /MediaBox [0.0 0.0 612.0 792.0] /Contents 6 0 R /Resources 7 0 R /Parent 2 0 R >> endobj 5 0 obj << /Type /Page /MediaBox [0.0 0.0 612.0 792.0] /Contents 8 0 R /Resources 9 0 R /Parent 2 0 R >> endobj 6 0 obj << /Length 908 /Filter /FlateDecode >> stream xœ•—MoÛ0†ïú>n‡jú $k(vX— tè°;;m¶¦Hš5i±¿?ÚŽmJ¦\A‹_>z-Sð“PRÙàª¿ÂT—BUB«êJüøY©êNX_ç«p¡»Ú¶WÖ7IPãÐæ£nÖ½ø.Q®ù~0W­Žj¯¶ÝDišûýõ½øÕÝÔAzŒFLkîÃnº®%˜nØÍÇNñÞÊˆ5 hídt$´¥!cºÒH#ÕO+-¨;žq8äHc"NB=U&Cˆ¦å§Âˆ®/DiM¶@ëµö2LWØÏ$l“UÉt™C"OÈè%O ‡™VHðÈ‚ Zã½q:QL£ƒj›œy°d6˜AÍ.ðrªtýW)c%.X¨¥™¸F{eƒ4 óh£MæbÎD…R…"7¯<=Ž¯˜qOœòŒvíµ‘G*Ö2ŸpsN%*„*¹yíäYr„|ÅŒ›z‚2qÃ·Í–J: Û£M& œ5I>5áT¨LÉ'OŽãË ¸ùÚ)è‰±ƒéÖlG<…Œt1=Æmˆïšÿ0ònöì€"¡ž*“aŽ¢ P¦Âuh®ñ ±Q°oÒÙ û™„m²ê!™.sHä =æLšàåjLO.u¸1JT‡¾œ.›Ì¦ 3ˆ!£Ù^N•=™ÖL“ïÅ¥ž6FGeÚ‹SÈ|BÌ¹“¨BªPäæµçËió½¸Ôâ<³3h/N=!ó 7çT¢B©B‘›×.œO,w¦]èÎ¥>:JÒ¦œYÑ$PÎš$Ÿšp*T¦ä…‡‹›kçG^‚Ï"1v4JWâÝRW˜ëª¾Öí‘®4~4ÕøÝ¥«`¼Ô5¾­«8Î9ˆp?g€ ð±‚†…ƒÓ%,ð§±´ûP­ÄbÕ×Ñ†ViÎ†¦ ü›oÇÍãúýÛ¹§»· ÒÌ¯Ïg‹—ãóÍíýz6= !­QzfµÉŸ÷³9ÚâF¬CûphÚåþå0›h”’`C^îj¿9ÎçùZÆÓn 

‰K,ø¸9×¯Ô­¥WJåù×‡ýÝËæyÞ_Ü Ø›'¹_ÿ¬o77Ûysµm[Gü:œutóî‚?™”¦½âllJ5”ÿ“…+Êƒö6€_ú…Q¦v€û]ûE°æ¾ª:øE4qvÛè{Ç–ëÍúpXWöÌív=Öñ„ÿ¢g’ endstream endobj 7 0 obj << /Font 10 0 R >> endobj 8 0 obj << /Length 913 /Filter /FlateDecode >> stream xœ•—Mo1†ïþ{„‹ñ÷ª8P’C¥¢¢¦â€8”6ÐTiB*þ>³ŸÛã­P„XÏzÞyü®wÜ}f‚ímó—©æ‚‰æ‘IÑ\²oßÑÜ3ío]óÄ¬ï¯¶Ý•vm’ 0Ôù¨ŸõÀ¾²Èµ¿Ã/fÔ¤#&öÊreaÐÝ®ØÏþ¦ÒÜy#¤µ÷§a?]nT?ìgŸÆ­Lq.ò¤´œhÜ\;?ò|‰°£Uú¸bï–²QŠÛf¯u÷E$ M¾»dãµâ2ÀÛºzbgÆk­‰æ~V c”?«‘faÍpgið“PÚ~hVl±ëH…«´gC€¯3ð£•ssÜìÖïßÎ¥X!FÿPæ™5^¹¥‹@ûÉ*øÎÊE€˜õzÁÃ‹×¶–; îuŸ÷³RÃÎ¾;ÛqÚÅþå0›¨ÞhŸ—»ÜoŽóy.ð8ü1—Pp·9×¯Ô5Rr'„Èó¯ûû—ÍŸyÃak@³.r¯¯ï6·ÛÙ\/¹oW« Á‰2ºywLJÓ^q6¶¥ZÊÿÉ‚W(/tf¤ÓÞÀfZ(¡B·±¤[tK8éÝ"ª8»¥tãk›°\ßþØ®›«õáéön¿Á¾°gø÷È1m¡ endstream endobj 9 0 obj << /Font 11 0 R >> endobj 10 0 obj << /F1 12 0 R >> endobj 11 0 obj << /F1 12 0 R >> endobj 12 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Times-Roman /Encoding /WinAnsiEncoding >> endobj xref 0 13 0000000000 65535 f 0000000015 00000 n 0000000179 00000 n 0000000078 00000 n 0000000242 00000 n 0000000354 00000 n 0000000466 00000 n 0000001448 00000 n 0000001482 00000 n 0000002469 00000 n 0000002503 00000 n 0000002536 00000 n 0000002569 00000 n trailer << /Root 1 0 R /Info 3 0 R /ID [<6F1F5A2BE9A21FDC95C60AFE6014BF80> <6F1F5A2BE9A21FDC95C60AFE6014BF80>] /Size 13 >> startxref 2669 %%EOF `

html code is https://pastebin.com/pUKNyRhX

**Comment by danfickle** [comment]
Hi @mctdi

Your server needs to output a mime (media) type of ```application/pdf```

**Comment by danfickle** [comment]
I'm assuming this is solved. Please reopen if required.
