### ISSUE TITLE
SVG Example doesnt work

### ISSUE THREAD

**Issue by madanagopal** [danfickle/openhtmltopdf#330]
Kudos to the project. I love it. 

I am able to generate pdf from html page but need svg support as well. 

I followed the below example with the simplified svg and it doesnt work for me. I am using R17 and have tried R16 as well.

https://github.com/danfickle/openhtmltopdf/wiki/Plugins:-SVG-Images

```
<html>
<body>

<svg xmlns="http://www.w3.org/2000/svg" height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg> 
 
</body>
</html>

public static void main(String... args) throws Exception { 
        try (OutputStream os = new FileOutputStream("/Users/me/Documents/pdf-issues/output/circle.pdf")) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.withUri("file:///Users/me/Documents/pdf-issues/circle.html");
            builder.toStream(os);
            builder.useSVGDrawer(new BatikSVGDrawer()); // Load SVG support plugin
            builder.run();
        }
}
```

**Comment by madanagopal** [comment]
I had some other 3rd party jars that caused issues with svg rendering. I was able to resolve this issue. thanks. closing this issue

**Comment by ElectricWound** [comment]
@madanagopal : I can reproduce this issue in my current project. Do you remember which Jars caused the problem? How did you find them and how did you resolve the problem?

**Comment by Reconion** [comment]
For anyone still winding up here. For me it was the flying saucer dependency. Removed that and generated an svg with success

**Comment by kiranduba** [comment]
Hi All, 
Thank for your comments which helped, but Im still not able to render SVG in PDF. Added following libraries
<dependency>
			<groupId>com.openhtmltopdf</groupId>
			<artifactId>openhtmltopdf-core</artifactId>
			<version>1.0.6</version>
		</dependency>
		<dependency>
			<groupId>com.openhtmltopdf</groupId>
			<artifactId>openhtmltopdf-pdfbox</artifactId>
			<version>1.0.6</version>
		</dependency>
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.13.1</version>
		</dependency>

Code -
-----
 final OutputStream os = new FileOutputStream(outputPdf);
        final PdfRendererBuilder builder = new PdfRendererBuilder();
        builder.withUri(outputPdf);
        builder.toStream(os);

        builder.withW3cDocument(doc, baseUri);
        builder.run();

Can you please help here?

**Comment by wolfomat** [comment]
> Hi All, Thank for your comments which helped, but Im still not able to render SVG in PDF. Added following libraries com.openhtmltopdf openhtmltopdf-core 1.0.6 com.openhtmltopdf openhtmltopdf-pdfbox 1.0.6 org.jsoup jsoup 1.13.1
> 
> ## Code -
> final OutputStream os = new FileOutputStream(outputPdf); final PdfRendererBuilder builder = new PdfRendererBuilder(); builder.withUri(outputPdf); builder.toStream(os);
> 
> ```
>     builder.withW3cDocument(doc, baseUri);
>     builder.run();
> ```
> 
> Can you please help here?

try to add:

builder.useSVGDrawer(new BatikSVGDrawer());

**Comment by kiranduba** [comment]
Still no luck @wolfomat 
 private static final String PDF_OUTPUT = "C:\\Codebase\\spring\\pdf\\src\\main\\java\\pdfbox\\Final.pdf";

    private static final String SVG_URL = "https://upload.wikimedia.org/wikipedia/commons/1/11/Test-Logo.svg";

    public static void main(final String[] args) {

        final String content = "<!DOCTYPE HTML>\r\n" + "<html><body>\r\n"
                + "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"> \r\n"
                + "<image x=\"20\" y=\"20\" width=\"300\" height=\"80\" xlink:href=\"https://upload.wikimedia.org/wikipedia/commons/1/11/Test-Logo.svg\" />\r\n"
                + "</svg>\r\n" + "</body></html>";

        final PdfRendererBuilder builder = new PdfRendererBuilder();

        builder.withHtmlContent(content, null);
        builder.useSVGDrawer(new BatikSVGDrawer());

        try {
            builder.toStream(
                    new FileOutputStream("C:\\Codebase\\spring\\pdf\\src\\main\\java\\pdfbox\\FinalSVG.pdf"));
            builder.run();
        } catch (final Exception e) {
            e.printStackTrace();
        }

    }

Note : I tried here to use some test SVG file as URI

Error = com.openhtmltopdf.exception WARNING:: Tried to fetch external resource from SVG. Refusing. Details: https://upload.wikimedia.org/wikipedia/commons/1/11/Test-Logo.svg, null
com.openhtmltopdf.exception WARNING:: Couldn't draw SVG.

**Comment by wolfomat** [comment]
In my case the svg has been rendered using:

`<img src="data:image/svg+xml;base64,{BASE64 encoded svg-without <?xml version="1.0" encoding="UTF-8" standalone="no"?> element}">`

remove { ... } and just paste the base64 in there.

Should be working with the 1.0.10 Version

**Comment by kiranduba** [comment]
Thank you @wolfomat you suggestion worked. Im able to get SVG in my PDF, but its not rendering in the defined width and height. I checked [this ](https://github.com/danfickle/openhtmltopdf/issues/592)issue which is fixed to handle this issue, but not working for me.



  public static void main(final String[] args) {

        final String content = "<!DOCTYPE HTML>\r\n" + "<html><body>\r\n"
                + "<img src=\"data:image/svg+xml;base64,PHN2ZwogICB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHZlcnNpb249IjEuMCIKICAgd2lkdGg9Ijc4Mi42MTg1MyIKICAgaGVpZ2h0PSIzNTguODkzMTMiCiAgIGlkPSJzdmcyODA3Ij4KICA8ZGVmcwogICAgIGlkPSJkZWZzMjgwOSIgLz4KICA8ZwogICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKC00OC43NjI5NiwtNDA5LjkxNjgpIgogICAgIGlkPSJsYXllcjEiPgogICAgPGcKICAgICAgIGlkPSJnMzA4NSI+CiAgICAgIDxwYXRoCiAgICAgICAgIGQ9Ik0gNDguNzYyOTU4LDQwOS45MTY4MiBMIDgzMS4zODE1LDQwOS45MTY4MiBMIDgzMS4zODE1LDc2OC44MDk5NSBMIDQ4Ljc2Mjk1OCw3NjguODA5OTUgTCA0OC43NjI5NTgsNDA5LjkxNjgyIHogIgogICAgICAgICBzdHlsZT0iZmlsbDojZGEyMDI4O2ZpbGwtcnVsZTpub256ZXJvO3N0cm9rZTpub25lIgogICAgICAgICBpZD0icGF0aDI2MzUiIC8+CiAgICAgIDxwYXRoCiAgICAgICAgIGQ9Ik0gNDAxLjI4ODYyLDU5NS4xNTE5OSBMIDM1MS41MDY2Nyw1OTQuNTczMTMgQyAzNTEuNTA2NjcsNTc3Ljc4NjIgMzU0Ljk3OTgzLDU1MC41Nzk3NyAzNzYuMzk3NjQsNTUwLjU3OTc3IEMgMzk3LjgxNTQ4LDU1MC41Nzk3NyA0MDEuMjg4NjIsNTc4Ljk0MzkxIDQwMS4yODg2Miw1OTUuMTUxOTkgeiBNIDczNy4wMjczNyw2NjEuMTQyMDIgTCA3MzcuMDI3MzcsNjQ4LjQwNzEgTCA2OTUuOTI4MzIsNjQ4LjQwNzEgTCA2OTUuOTI4MzIsNjcxLjU2MTQ4IEMgNjk1LjkyODMyLDY3Ny45Mjg5NSA2OTMuMDM0MDEsNjg1LjQ1NDEzIDY4NS41MDg4Miw2ODUuNDU0MTMgQyA2NzcuOTgzNjQsNjg1LjQ1NDEzIDY3NS42NjgyMiw2NzcuOTI4OTUgNjc1LjY2ODIyLDY3Mi43MTkyMiBMIDY3NS42NjgyMiw1NTkuMjYyNjcgTCA3MzIuOTc1MzUsNTU5LjI2MjY3IEwgNzMyLjk3NTM1LDUxNC4xMTE1OSBMIDY3NS42NjgyMiw1MTQuMTExNTkgTCA2NzUuNjY4MjIsNDQ0LjY0ODQzIEwgNjM3LjQ2MzQ3LDQ0NC42NDg0MyBDIDYzNi44ODQ1OSw0NzguMjIyMyA2MjkuOTM4MjksNTE0LjExMTU5IDU4OS40MTgwOSw1MTQuMTExNTkgTCA1ODkuNDE4MDksNTE0LjExMTU5IEMgNTg1Ljk0NDkzLDUxNC4xMTE1OSA1ODIuNDcxNzYsNTE0LjExMTU5IDU3OC40MTk3NCw1MTQuMTExNTkgQyA1NzYuMTA0MzIsNTE0LjExMTU5IDU3NC4zNjc3Miw1MTQuMTExNTkgNTcyLjA1MjMsNTE0LjExMTU5IEwgNTcyLjA1MjMsNTIxLjA1NzkyIEMgNTU4LjE1OTY0LDUxMi4zNzUwMyA1NDUuNDI0NzMsNTA2LjU4NjQ0IDUyOC4wNTg5NCw1MDYuNTg2NDQgQyA0ODcuNTM4NzQsNTA2LjU4NjQ0IDQ2Mi42NDc3Nyw1NDAuNzM5MTcgNDYyLjY0Nzc3LDU3OC45NDM5MSBDIDQ2Mi42NDc3Nyw2NjUuNzcyODkgNTU4LjE1OTY0LDYyMC42MjE4MiA1NTguMTU5NjQsNjY4LjA4ODM0IEMgNTU4LjE1OTY0LDY4Mi41NTk4MiA1NTEuMjEzMzUsNjkxLjI0MjcyIDUzNi4xNjI5OCw2OTEuMjQyNzIgQyA1MTQuMTY2MzEsNjkxLjI0MjcyIDUwNS40ODM0Miw2NjcuNTA5NDYgNTA0LjMyNTY4LDY0OC40MDcxIEwgNDYzLjgwNTUxLDY0OC40MDcxIEwgNDYzLjgwNTUxLDcyNy4xMzIwNCBMIDUwNC4zMjU2OCw3MjcuMTMyMDQgTCA1MDQuMzI1NjgsNzE4LjQ0OTE1IEMgNTE5Ljk1NDksNzI1LjM5NTQ0IDUzNS4wMDUyNyw3MzMuNDk5NDggNTUyLjk0OTkxLDczMy40OTk0OCBDIDU4OS40MTgwOSw3MzMuNDk5NDggNjE2LjA0NTYzLDY5NC43MTU4OCA2MTYuMDQ1NjMsNjU5Ljk4NDMgQyA2MTYuMDQ1NjMsNjU1LjkzMjI4IDYxNi4wNDU2Myw2NTIuNDU5MTIgNjE0Ljg4NzkyLDY0Ny44MjgyNSBDIDYxMC4yNTcwNSw2MTguODg1MjUgNTkyLjg5MTI2LDU5Ni44ODg1NiA1NjMuOTQ4MjYsNTkxLjA5OTk3IEMgNTQ3Ljc0MDE4LDU4OC4yMDU2NiA1MjAuNTMzNzYsNTg4LjIwNTY2IDUyMC41MzM3Niw1NjYuMjA5IEMgNTIwLjUzMzc2LDU1Ni4zNjgzOSA1MjguMDU4OTQsNTQ2LjUyNzc1IDUzNy44OTk1OCw1NDYuNTI3NzUgQyA1NTkuMzE3MzksNTQ2LjUyNzc1IDU2OC4wMDAyOCw1NjUuMDUxMjggNTY4LjAwMDI4LDU4My41NzQ3OCBMIDYwNy4zNjI3NCw1ODMuNTc0NzggTCA2MDcuMzYyNzQsNTU5LjI2MjY3IEwgNjIzLjU3MDgyLDU1OS4yNjI2NyBMIDYyMy41NzA4Miw2NjguMDg4MzQgQyA2MjMuNTcwODIsNzAxLjA4MzM2IDY0Mi42NzMyLDczNC42NTcyMyA2NzkuNzIwMjQsNzM0LjY1NzIzIEMgNzE3LjM0NjEyLDczNC42NTcyMyA3MzcuMDI3MzcsNjk1LjI5NDc0IDczNy4wMjczNyw2NjEuMTQyMDIgeiBNIDQ2MC4zMzIzNSw2MzYuODI5OSBDIDQ2MC4zMzIzNSw2MzUuNjcyMTkgNDU5Ljc1MzQ5LDYzMy45MzU1OSA0NTkuNzUzNDksNjMyLjc3Nzg4IEMgNDU5Ljc1MzQ5LDYzMC40NjI0MiA0NjAuMzMyMzUsNjI3LjU2ODE1IDQ2MC4zMzIzNSw2MjUuMjUyNjkgQyA0NjAuMzMyMzUsNTczLjE1NTMyIDQzOC4zMzU2NSw1MDYuMDA3NTUgMzc1LjIzOTkzLDUwNi4wMDc1NSBDIDM3MC42MDkwNiw1MDYuMDA3NTUgMzY2LjU1NzA0LDUwNi41ODY0NCAzNjEuOTI2MTYsNTA3LjE2NTMgQyAzMTYuMTk2MjMsNTEyLjM3NTAzIDI5My4wNDE4Myw1NzEuNDE4NzMgMjkzLjA0MTgzLDYxMy4wOTY2MyBDIDI5My4wNDE4Myw2MjQuMDk0OTggMjk0LjE5OTU3LDYzNy40MDg3NSAyOTUuMzU3MjgsNjUwLjE0MzY3IEwgMjY0LjA5ODgzLDY1MC4xNDM2NyBMIDI2NC4wOTg4Myw2NzQuNDU1NzkgQyAyNjQuMDk4ODMsNjgwLjgyMzI2IDI2MS43ODM0MSw2OTAuMDg1MDEgMjUzLjY3OTM3LDY5MC4wODUwMSBDIDI0NS41NzUzMyw2OTAuMDg1MDEgMjQyLjY4MTAyLDY4Mi41NTk4MiAyNDIuNjgxMDIsNjc2LjE5MjM4IEwgMjQyLjY4MTAyLDU2MC40MjA0MSBMIDI5Ny42NzI3LDU2MC40MjA0MSBMIDI5Ny42NzI3LDUxNC4xMTE1OSBMIDI0Mi4xMDIxNyw1MTQuMTExNTkgTCAyNDIuMTAyMTcsNDQ0LjY0ODQzIEwgMjA0LjQ3NjI2LDQ0NC42NDg0MyBMIDIwNC40NzYyNiw0NDguMTIxNTcgQyAyMDQuNDc2MjYsNDg0LjU4OTc1IDE4Ny42ODkzMyw1MTUuMjY5MzQgMTQ3Ljc0Nzk5LDUxNS4yNjkzNCBMIDE0Ny43NDc5OSw1NjEuNTc4MTIgTCAxODguODQ3MDQsNTYxLjU3ODEyIEwgMTg4Ljg0NzA0LDY2Mi44Nzg1OCBDIDE4OC44NDcwNCw3MDIuODE5OTIgMjAzLjg5NzQsNzM5LjI4ODEgMjQ5LjYyNzM1LDczOS4yODgxIEMgMjc4LjU3MDM1LDczOS4yODgxIDMwMi4zMDM2MSw3MTIuNjYwNTMgMzA0LjYxOTAzLDY4NS40NTQxMyBDIDMxNi4xOTYyMyw3MTQuOTc1OTggMzQ1LjEzOTIzLDczNC42NTcyMyAzNzcuNTU1MzksNzM0LjY1NzIzIEMgNDI3LjMzNzMzLDczNC42NTcyMyA0NTMuMzg2MDIsNjk0LjEzNzAzIDQ1OC4wMTY4OSw2NDguNDA3MSBMIDQxNC42MDI0Miw2NDguNDA3MSBDIDQxNC42MDI0Miw2NjUuNzcyODkgNDA0LjE4MjkzLDY4NS40NTQxMyAzODQuNTAxNjgsNjg1LjQ1NDEzIEMgMzcxLjc2Njc3LDY4NS40NTQxMyAzNjEuMzQ3MzEsNjc3LjM1MDA5IDM1Ny4yOTUyOSw2NjUuNzcyODkgQyAzNTQuNDAwOTgsNjYxLjE0MjAyIDM1Mi42NjQ0MSw2NTMuMDM3OTggMzUyLjY2NDQxLDY0OC40MDcxIEwgMzUyLjY2NDQxLDYzNi44Mjk5IEwgNDYwLjMzMjM1LDYzNi44Mjk5IgogICAgICAgICBzdHlsZT0iZmlsbDp3aGl0ZTtmaWxsLXJ1bGU6bm9uemVybztzdHJva2U6bm9uZSIKICAgICAgICAgaWQ9InBhdGgyNjM3IiAvPgogICAgPC9nPgogIDwvZz4KPC9zdmc+\" width=\"400\" height=\"200\"/>\r\n"
                + "</body></html>";

        final PdfRendererBuilder builder = new PdfRendererBuilder();

        builder.withHtmlContent(content, null);
        builder.useSVGDrawer(new BatikSVGDrawer());



com.openhtmltopdf.general WARNING:: Invalid integer passed as dimension for SVG: 782.61853
com.openhtmltopdf.general WARNING:: Invalid integer passed as dimension for SVG: 358.89313

------------------------------------------------------------------------------------------------------------------------------------
<img width="608" alt="SVG issue" src="https://github.com/danfickle/openhtmltopdf/assets/17720995/d063e199-86bc-41e5-9079-d9b1dc380807">

**Comment by pjotar** [comment]
> builder.useSVGDrawer(new BatikSVGDrawer());

that helped, version 1.0.10
