### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by mctdi** [danfickle/openhtmltopdf#335]
hi

I use spring boot 2, my image is located in resources/static/img

In a html file, I do

`<img src="/resources/static/img/mermacon-xsm.png"/>`

I don't have any image displayed by openhtmltopdf

tried also

```
<img src="/static/img/mermacon-xsm.png"/>
<img src="/img/mermacon-xsm.png"/>
<img src="img/mermacon-xsm.png"/>

```
same result

thanks

**Comment by zimmi** [comment]
Here is a self contained example that should work in production and development mode. Make sure the paths are relative inside your HTML.

```java
@SpringBootApplication
@RestController
public class DemoApplication {

    @GetMapping(path = "/", produces = "application/pdf")
    public void index(ServletOutputStream out) throws Exception {
        var builder = new PdfRendererBuilder();
        builder.useFastMode();

        var html = "<html><body><img src='my/relative/path/logo.png'/></body></html>";
        var baseUrl = getClass()
                .getProtectionDomain()
                .getCodeSource()
                .getLocation()
                .toString();
        builder.withHtmlContent(html, baseUrl);
        builder.toStream(out);
        builder.run();
    }

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

}
```

Edit: So in your case, assuming `resources` is the standard Maven directory `src/main/resources`, the HTML needs to contain `<img src="static/img/mermacon-xsm.png"/>`. The important bit is the `baseUrl` you pass to `PdfRendererBuilder::withHtmlContent`.
