### ISSUE TITLE
useFont and withW3cDocument together: Font metrics not available. Probably a bug.

### ISSUE THREAD

**Issue by paflov** [danfickle/openhtmltopdf#341]
Hi,
I try to convert a HTML to PDF with JSoup. I try to embed a custom font

            final W3CDom w3cDom = new W3CDom();
            final Document w3cDoc = w3cDom.fromJsoup(Jsoup.parse(readFile()));
            final OutputStream outStream = new FileOutputStream("hallo.pdf");
            final PdfRendererBuilder pdfBuilder = new PdfRendererBuilder();
            pdfBuilder.useFastMode();
            pdfBuilder.useFont(new File(main.class.getClassLoader().getResource("fonts/SourceSansPro-Regular.ttf").getFile()), "source-sans", 700, BaseRendererBuilder.FontStyle.NORMAL, false);
            pdfBuilder.withW3cDocument(w3cDoc, "/");
            pdfBuilder.toStream(outStream);
            pdfBuilder.run();
            outStream.close();

From pom.xml:

    <dependencies>
        <dependency>
            <groupId>com.openhtmltopdf</groupId>
            <artifactId>openhtmltopdf-pdfbox</artifactId>
            <version>0.0.1-RC18</version>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.11.2</version>
        </dependency>
    </dependencies>

I get a lot of warnings and the font is not used. 

    com.openhtmltopdf.load INFO:: Loading font(source-sans) from InputStream supplier now.
    com.openhtmltopdf.exception WARNING:: bad URL given: /fonts/SourceSansPro-Regular.ttf
    com.openhtmltopdf.exception WARNING:: Could not load @font-face font: /fonts/SourceSansPro-Regular.ttf
    com.openhtmltopdf.exception WARNING:: Font metrics not available. Probably a bug.
    com.openhtmltopdf.exception WARNING:: Font metrics not available. Probably a bug.
    com.openhtmltopdf.render WARNING:: Font is null.
    com.openhtmltopdf.render WARNING:: Font is null.
    com.openhtmltopdf.render WARNING:: Font is null.
    com.openhtmltopdf.render WARNING:: Font is null.
    com.openhtmltopdf.render WARNING:: Font is null.
    com.openhtmltopdf.render WARNING:: Font is null.
    com.openhtmltopdf.render WARNING:: Font is null.

I get some warnings for example; and among them "Font metrics not available. Probably a bug." Is it a bug? Am I doing something wrong? Thanks in Advanced for any help!

--

See [here](https://stackoverflow.com/questions/55339298/openhtmltopdf-embed-a-custom-font-into-pdf-created-out-of-html) for complete example program.

**Comment by zimmi** [comment]
Your font can't be found. The second parameter of `pdfBuilder.withW3cDocument` needs to be a proper URL, see [this example](https://github.com/danfickle/openhtmltopdf/issues/335#issuecomment-472581322).

**Comment by paflov** [comment]
Thank you, Zimmi, that helped a lot. It works now!
