### ISSUE TITLE
img tag dont work

### ISSUE THREAD

**Issue by ellouze** [danfickle/openhtmltopdf#343]
i add this code in my html file : <div><img src="toto.png"></img></div>
but i obtain this error
ERROR:  'The element type "img" must be terminated by the matching end-tag "</img>".'

i used the last version 0.0.1-RC19

**Comment by danfickle** [comment]
Hi @ellouze,

Not sure what is going on here, but typically, the img tag is self-closing:
`<img src="test.jpg" alt="Test picture" />`

Please put code between four backticks at start and end.

**Comment by danfickle** [comment]
Assumed resolved. Please reopen with more details if required.

**Comment by yellowjian** [comment]
> Hi @ellouze,
> 
> Not sure what is going on here, but typically, the img tag is self-closing:
> `<img src="test.jpg" alt="Test picture" />`
> 
> Please put code between four backticks at start and end.

will get the same error ,  the message show need < img >< /img >, but in html file, img element will ingore  
</img> or />,  only < img src="" >.

**Comment by danfickle** [comment]
Hi @yellowjian 

We accept only XML in something approaching xhtml, but browsers will accept just about anything, known as HTML5. In general, you can think of XML/xhtml as a much stricter version of HTML.

Fortunately, although I recommend writing valid XML from the start, there are a number of ways to convert HTML to valid XML or even directly to a w3c document object (which the builder also accepts). One of these, jsoup, is mentioned in the integration guide on the wiki.
