### ISSUE TITLE
Page Shows "Now Loading" instead of content

### ISSUE THREAD

**Issue by proyectosjavaperu** [danfickle/openhtmltopdf#346]
How can I increase the timeout settings so I won't see the "now loading" image but the content itself.

**Comment by danfickle** [comment]
I'm sorry, this project is not a headless web browser. Specifically, it does not evaluate javascript and is not aware of some modern CSS standards such as grid and flex box. It needs carefully crafted templates to be used successfully.

You may have more success with a [wrapper around a headless browser](https://github.com/jhonnymertz/java-wkhtmltopdf-wrapper).
