### ISSUE TITLE
Release schedule of a stable version.

### ISSUE THREAD

**Issue by freeCode4Fun** [danfickle/openhtmltopdf#35]
Hi Danfickle
Currently I using flyingsauser and ITEXT 2.1.2 in my project and I like change those libraries to openhtmltopdf including the pdfbox integration.

I’m interesting to get more information about your release schedule. Is there a plan when this library will be released to a stable version?

**Comment by danfickle** [comment]
Hi @freeCode4Fun - there is no plan yet for a stable release, however I'd like a stable release to at least include a complete svg implementation and html forms, also possibly null flow analysis to make everything more robust. In the near term I plan to finish the forms support and integrate the outstanding pull requests. Also waiting for pdfbox 2.0.3 to release before the next rc release.

Thanks for your interest and apologies for the lack of recent progress on the project. My side project motivation has laid elsewhere but I will get back to this project.

Regards,
Dan.

**Comment by gasdia73** [comment]
We are anxiously waiting for the next release that will hopefully allow us to render checkbox controls in PDF.
Is there a way to be notified when a new release happens ?
Thank you.

**Comment by danfickle** [comment]
@gasdia73 - I just synced `0.0.1-RC5` to maven central. If you subscribe to issue #7 - I will post in there when a new release is made.

**Comment by gasdia73** [comment]
wow that is fantastic! thank you very much, I will try it and subscribe to
the issue immediately.

Il giorno mer 28 set 2016 alle ore 05:59 danfickle notifications@github.com
ha scritto:

**Comment by danfickle** [comment]
Closing this in favor of #170
