### ISSUE TITLE
Support multi line text in header and footer?

### ISSUE THREAD

**Issue by ieugen** [danfickle/openhtmltopdf#352]
Hi,

The current page implementation does not support multi-line text in header or footer. 
This is needed for longer lines put in header or footer. So they are seen nicely.

My proposal is to allow String formatting (string format) subsitutions like:
- \n for newline
- \t for tab
- maybe even %4.5d for decimals ??

```
@page {
  @bottom-left {
    text-align: left;
    content: "Copyright © 2018 ACM Very long name hererLtd. \nThis should be on a second line";
  }
}
```
[1] https://github.com/danfickle/openhtmltopdf/wiki/Page-features

**Comment by danfickle** [comment]
Hi again @ieugen,

Unless I've misunderstood you, this is what running elements are for:
````html
<html>
<head>
<style>
@page {
  margin: 50px 20px;
  @bottom-left {
    content: element(whatever);
  }
}
</style>
</head>
<body>
<div style="position: running(whatever);">
  This is some <strong>richly</strong> styled html!<br/>
  <span style="color: red;">This is another line.</span>
</div>

<h1>Rest of content</h1>

<p>Etc, etc, etc...</p>

</body>
</html>
````

Yes, we need better documentation!

**Comment by ieugen** [comment]
This works great, thanks!
