### ISSUE TITLE
For table starting at bottom of the page,it breaks right after table header.

### ISSUE THREAD

**Issue by SimranDilon** [danfickle/openhtmltopdf#354]
Hi Please refer to the image attached for the issue.

![image](https://user-images.githubusercontent.com/50938383/58224789-67029400-7d62-11e9-95e4-23eb11d1302d.png)

i have tried everything like page-break-after:avoid , -fs-page-break-min-height on thead.

**Comment by rototor** [comment]
Did you try -fs-page-break-min-height on the table itself? Can you provide a HTML minimal example showing the problem?

**Comment by danfickle** [comment]
Working on this in #399 and fixed in PR #418. So I'll close this as a duplicate.
