### ISSUE TITLE
can i download pdf file in client side

### ISSUE THREAD

**Issue by yellowjian** [danfickle/openhtmltopdf#359]
1. how can i download pad file in client side?  
2. how can i know which time start download pdf or which time finish download pdf in server side
it is difficult for this solution :  client side form submit and server side receive js and css string to download pdf.

**Comment by ieugen** [comment]
This is a Java library that allows you to generate PDF files in an application.
It is not a full featured solution (server app) for generating reports. 
You have to implement that on your own. You have instructions in the wiki.

**Comment by danfickle** [comment]
1. To download a PDF on the client you have two options:
  + Force a download when the PDF is first generated using http headers. This is easiest to implement but may annoy users who are used to viewing a PDF in the browser. See `Content-Disposition` header.
  + Be prepared to handle two GET requests on the PDF URL. The first is for view in browser, the second is in case the user decided to download the PDF from in browser viewer. Setting correct cache headers may reduce instance of second request but not eliminate it. To allow the PDF to be requested twice you either have to store the PDF itself or store the information required to generate it and build the PDF for each request. An example of the second approach is in pretty resume project linked from readme.

2. Not sure of what you’re asking but most web frameworks will have a way of collecting timing metrics. As @ieugen says, this is beyond the scope of this project.

Also be aware that this project should only be used with trusted HTML/css/svg. Only the text in the HTML can be untrusted.
