### ISSUE TITLE
<img> can not work fine

### ISSUE THREAD

**Issue by yellowjian** [danfickle/openhtmltopdf#362]
https://sandbox.openhtmltopdf.com/
add img in body.
< img src="https://www.w3schools.com/images/w3schools_green.jpg" alt="W3Schools.com"></img >
<img src="https://www.w3schools.com/images/w3schools_green.jpg" alt="W3Schools.com"></img>
can not generate pdf. get the error message like below.
The element type "img" must be terminated by the matching end-tag "</img>".

**Comment by danfickle** [comment]
Images and other external content are disabled in the sandbox, to avoid reflected attacks. Also you need to use a self closing tag as noted in other issue.
