### ISSUE TITLE
Footnotes not supported

### ISSUE THREAD

**Issue by a-leithner** [danfickle/openhtmltopdf#364]
The [CSS Generated Content for Paged Media Level 3 Working Draft (May 2014)](https://www.w3.org/TR/css-gcpm-3/) and also the [Editor's Draft (March 2019)](https://drafts.csswg.org/css-gcpm/) provide support for [footnotes](https://www.w3.org/TR/css-gcpm-3/#footnotes) using the following HTML and CSS:

```html
<style>
@page {
    counter-reset: footnote 0;
}

@page {
    @footnote {
        float: bottom;
    }
}

span.footnote { float: footnote; }
.footnote::footnote-call { content: counter(footnote) " "; }
.footnote::footnote-marker { content: counter(footnote) ". "; }
</style>
<!-- ... -->
<p>
    This text needs some footnotes.<span class="footnote">This is a footnote.</span>
</p>
```
This should yield a result like this:

![Footnote illustration](https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/c8703cde-60dd-4725-88ce-320fd9c55dc6/6-image-footnotes-large-opt.jpg)  
[Source](https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/)

However, the content of the footnote element will be displayed right behind the text it should augment, as if it was a normal span element (the `float: footnote;` property is being ignored).

This makes it hard to use this library to create PDFs for (ex.) scientific papers (or most other documents where sources for citations are common to be placed in the footnotes section), which I would like to.

**Comment by danfickle** [comment]
Hi @a-leithner,

I think the page features are the strength of this project so I'd definitely like support for float bottom and footnotes. The bad news is that it will probably not be implemented in the near future, as I've still got to fix up the column support before moving onto other layout issues.

**Comment by igoratsok** [comment]
Hi @danfickle 

This is such an amazing lib that's helping me a lot. Thanks! The only problem for me is: I can't figure out how to make footnotes.
Do you know if from now (May 24, 2021), there's a way to implement footnotes somehow? Thank you so much!

**Comment by danfickle** [comment]
I've opened pr #711. Comments welcome.
