### ISSUE TITLE
PDF/A1a or PDF/A2a

### ISSUE THREAD

**Issue by benhurqc** [danfickle/openhtmltopdf#368]
Trying to validate a PDF/A with https://www.pdf-online.com/osa/validate.aspx created using recommendations on https://github.com/danfickle/openhtmltopdf/wiki/PDF-A-Standards-Compliance is still getting

File
application-44450   (17).pdf
Compliance pdfa-2a
Result
Document   does not conform to PDF/A.
Details
Validating  file "application-44450 (17).pdf" for conformance level pdfa-2a
dc:title/*[0]   :: Missing language qualifier. 
dc:description/*[0]   :: Missing language qualifier.   The   document does not conform to the requested standard.
The  document's meta data is either missing or inconsistent or corrupt.
The  document does not conform to the PDF/A-2a standard. 
Done.

**Comment by benhurqc** [comment]
I found out that by opening in notepad there seem to have extra lang attribute in these metadatas and that maybe the problem
<dc:title>
        <rdf:Alt>
          <rdf:li lang="x-default">Application Summary</rdf:li>
        </rdf:Alt>
      </dc:title>
      <dc:description>
        <rdf:Alt>
          <rdf:li lang="x-default">Temporary Resident (TR) Application</rdf:li>
        </rdf:Alt>
      </dc:description>
I noticed the're none for dc:creator
I removed title tag in xhtml and description, the dc:description still got generated but the dc:title error was gone.

**Comment by danfickle** [comment]
Hi @benhurqc,

I could not replicate the validation failure. My [test documents](https://github.com/danfickle/openhtmltopdf/tree/open-dev-v1/openhtmltopdf-pdfa-testing/src/test/resources/html) validated fine online as well as with VeraPDF validation library.

Could you perhaps provide a sample (personal info removed) that fails the online test?

Also make sure you are using the latest version of this library (0.0.1-RC21) and `builder.useFastMode()` of course.

Also make sure you don't have an old version of PDFBOX/XMPBOX brought in by another project that is overriding the latest version we are using.

You can see the head section from the test document below:

````html
<html lang="EN-US">
<head>
  <title>All-in-one PDF/UA Testcase</title>
  <meta name="subject" content="PDF/UA all-in-one"/>
  <meta name="author" content="openhtmltopdf.com team"/>
  <meta name="description" content="An example containing everything for easy testing"/>
````

**Comment by benhurqc** [comment]
Thank you Dan, I don't know if my colleague changed something but it is now validating fine.
