### ISSUE TITLE
can't get simple font example working

### ISSUE THREAD

**Issue by zoth** [danfickle/openhtmltopdf#37]
running this HTML:

`<html> <head> <STYLE type="text/css"> body {  font-family: Sans-Serif; } </STYLE> </head> <body> <p>Sample text</p> </body> </html>`

on OSX 10.10.5 with java version "1.8.0_40" openhtmltopdf 0.0.1-RC5-SNAPSHOT
using com.openhtmltopdf.testcases.TestcaseRunner
the output is not san serf

**Comment by danfickle** [comment]
The XML parser is case sensitive. Therefore, you can use lowercase `style` tag. Also remember that the built-in fonts only support Western European character glyphs. For other scripts you will need to embed a font via the font-face rule. Thanks for using this project.

**Comment by zoth** [comment]
thanks...I know I was getting something simple wrong :-)
