### ISSUE TITLE
Trademark HTML entity becomes a hash mark

### ISSUE THREAD

**Issue by kipstafoo** [danfickle/openhtmltopdf#375]
I'm converting HTML files to PDFs but when the converter encounters a &trade; HTML entity the resultant PDF has a # instead of the expected TM symbol.

**Comment by syjer** [comment]
hi @kipstafoo , it's because the font don't contains the ™ character (I guess the default one don't have it?).

See the wiki (https://github.com/danfickle/openhtmltopdf/wiki/Fonts) for integrating a custom font.

**Comment by danfickle** [comment]
Thanks @syjer. Closing as assumed solved. Reopen as required.
