### ISSUE TITLE
SVG width and height not respected

### ISSUE THREAD

**Issue by distabiolijze** [danfickle/openhtmltopdf#378]
I have set the SVG width and height in the CSS file but what the image is not rendered in the expected dimension

**Comment by weissjeffm** [comment]
I've noticed this issue too, but it's more widespread than that - the SVG elements don't use anything at all set in CSS. It has to be embedded within the SVG element markup itself.

**Comment by danfickle** [comment]
I can confirm there is a problem with svg width and height in some circumstances. As a workaround, you could try using `min-width`, `max-width` (and height).

**Comment by danfickle** [comment]
I hope this issue is fixed. Anyway, please reopen with an example if not fixed. Thanks.
