### ISSUE TITLE
Emojis are not being displayed 😊 

### ISSUE THREAD

**Issue by distabiolijze** [danfickle/openhtmltopdf#379]
Emoji's are not being displayed and all I see is the '#'.
I use Roboto fonts from google fonts. I assume since I can see the emojis even in the source code editor then there must be a system font than can be used to render it. What do I have to do to be able to display emojis like this 😊

**Comment by zimmi** [comment]
You could try [Noto Color Emoji](https://www.google.com/get/noto/help/emoji/), download [here](https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip).

**Comment by danfickle** [comment]
I've added a page on the wiki with one option: [Emoji Support](https://github.com/danfickle/openhtmltopdf/wiki/Emoji-Support).

Result:
![emoji-screenshot](https://user-images.githubusercontent.com/1415728/63208345-312d3b80-c116-11e9-8683-3462a061fa61.png)

**Comment by distabiolijze** [comment]
@danfickle Thanks! Is it that the library is not compatible with coloured emoji fonts? 
I mean, I've tried with the  Noto font (black and white) which is quite flaky but the Noto color emoji font never displays.

**Comment by danfickle** [comment]
No, I don't think the PDF format itself supports multi-color fonts so they would have to be converted to drawing operations anyway.

**Comment by lylala8** [comment]
@distabiolijze  Have you solved your problem? There are icons in my xml file, but they cannot be displayed when exporting, and Noto Color Emoji is also loaded, but it does not work. The # sign is still displayed.
