### ISSUE TITLE
s3 presigned url

### ISSUE THREAD

**Issue by cmc0912** [danfickle/openhtmltopdf#381]
Hi, I created a s3 presigned url inside <img> tag.
https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURLJavaSDK.html
e.g.:
`<img alt="" src="https://${bucket}.s3.amazonaws.com/${key}?AWSAccessKeyId=${secretKey}&Expires=${date}&Signature=${signature}">`

Below exception occurs when builder.run():
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: The reference to entity "Expires" must end with the ';' delimiter.
ERROR:  'The reference to entity "Expires" must end with the ';' delimiter.'
com.openhtmltopdf.exception WARNING:: Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 313; columnNumber: 176; The reference to entity "Expires" must end with the ';' delimiter.
com.openhtmltopdf.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 313; columnNumber: 176; The reference to entity "Expires" must end with the ';' delimiter.

off-topic(but may be related): [https://forums.aws.amazon.com/thread.jspa?threadID=61474]Possible bug in HIT parser.

PS: used work-around as follows: Note: I'm using freemarker to fill-in.
`String encodedStr = Base64.getEncoder().encodeToString(FileUtils.readFileToByteArray(file));`
`String imageSrc = "data:" + "image/png" + ";base64," + encodedStr;`
`hashMap.put("imageSrc", imageSrc);`

PSPS: tried using file:/// but it gives file not found when I had two img src that uses it.
`hashMap.put("imageSrc", file.toURI());`

**Comment by danfickle** [comment]
Hi @cmc0912,

Apparently, freemarker does not auto escape string literals, so you'll have to do it yourself. Replace the `&` symbol with its escaped version, `&amp;`

Note: Typically you would also have to encode uri components before xhtml escaping the entire attribute. However, I doubt that your interpolated strings contain any characters that need encoding in a URL component value.

**Comment by danfickle** [comment]
Assumed solved, please reopen if required.
