### ISSUE TITLE
page-break-after/before not supported on <section> element

### ISSUE THREAD

**Issue by michaelborn** [danfickle/openhtmltopdf#382]
I noticed that `page-break-before: always` did nothing in my generated PDF, and after testing a bit I boiled it down to this: `page-break-before: always` is not supported on a `<section></section>` element.

Ditto for `page-break-after: always`.

A simple workaround is changing the `<section class="break-before"></section>` HTML to `<div class="break-before"></div>`.

I thought I'd document this here.

**Comment by danfickle** [comment]
Thanks @michaelborn,

I think what's going on here is that `section` is not mentioned in the renderer's default style sheet so defaults to inline display where page break properties are not supported.

We should modernise the stylesheet, but in the meantime you can add `display: block` to `section` in your styles.
