### ISSUE TITLE
Allow users to provide FSSupplier<PDFont> in PdfBoxFontResolver to avoid duplicate fonts/subsets

### ISSUE THREAD

**Issue by DSW-PS** [danfickle/openhtmltopdf#383]
Hi @danfickle 

what do you think about adding a method to the **PdfBoxFontResolver** that allows users to use their own **FSSupplier<PDFont>**?

This way it would be possible to avoid having duplicate fonts (or fonts with several subsets) in the PDF by using some sort of font-cache.

This quite easily happens if you have _openhtmltopdf_ produce the output in a **PDDocument** where you also manually add some text which uses (some of) the same fonts as the html.
In this case it would be up to the implementation of **FSSupplier** to either load the **PDFont** or serve a already loaded one.

I can provide a pull-request for this.

**Comment by danfickle** [comment]
Hi @DSW-PS,

I wouldn't be opposed to a pr. However, i think i'd prefer a method on the PDF builder if that's possible. In the meantime, you may be able to get added fonts from the page resource dictionary of the pddocument.

**Comment by DSW-PS** [comment]
Hi @danfickle,
I created the pr.

I wasn't too keen on reordering the method parameters to keep the **FSSupplier<PDFont>** directly in the method as it would clash with the ones that use **FSSupplier<InputStream>**.
Instead I moved the **PDFontSupplier** from **PdfBoxFontResolver** to a seperate class that can be extended.
