### ISSUE TITLE
Base URI Resolving Problem

### ISSUE THREAD

**Issue by davidbauernfeind** [danfickle/openhtmltopdf#390]
Hi, 

I have an issue with she simplest example actually (I just replaced the paths):

```
public static void generatePdf() throws Exception
    {
        try (OutputStream outputStream = new FileOutputStream(
                "/Users/david/Library/Mobile Documents/com~apple~CloudDocs/projects/test/spring-boot-mysql/src/main/testcases/htmltopdftest.pdf")) {

            PdfRendererBuilder builder = new PdfRendererBuilder();
            
            builder.withUri("file:///Users/david/Library/Mobile Documents/com~apple~CloudDocs/projects/test/spring-boot-mysql/src/main/testcases/htmltopdftest.html");

            builder.toStream(outputStream);
            builder.run();
        }
    }
```

When I just copy & paste it and try to run it I run into this exception:

```
com.openhtmltopdf.exception WARNING:: When trying to load uri(***HTML-file-path***) with base URI(null), one or both were invalid URIs.
com.openhtmltopdf.load INFO:: URI resolver rejected loading XML resource at (**HTML-file-path***)

java.lang.NullPointerException
```

What's the problem here?

Also: Can't I set the BaseURI somehow? Because I can't use withUri with a "relative" URI...

Many thanks in advance for your time guys!

Yours
David

**Comment by danfickle** [comment]
Hi @insanemagic,

The issue is caused by the invalid space character in the url. If you encode the space with `%20` it should work (I've tested this):
````
/Users/david/Library/Mobile%20Documents/com~apple~CloudDocs/etc/etc.htm
````
When you use a URI for the document, the base URI is derived from this automatically.

Also, for new projects, remember to use:
````java
builder.useFastMode();
````

Regards,
Daniel.

**Comment by davidbauernfeind** [comment]
Thanks a lot Dan! It works! It's a little weird, though. Because when I get the URI by calling a getPath-method, it saves the URI with a space and not a "%20" character, so I can't use the method withHtmlContent(...) easily...

**Comment by danfickle** [comment]
Remember a file path is not necessarily a valid URL. You need to encode the path after getting it. For example the `Path` class has a `toURI` method.

**Comment by danfickle** [comment]
Assumed resolved. Please re-open as required.
