### ISSUE TITLE
Dont' work

### ISSUE THREAD

**Issue by onexile** [danfickle/openhtmltopdf#392]
Hi, I'm new of this tool.
With java I try to convert an html to pdf.

I import in my project all jar, because this project non use maven.
_openhtmltopdf-pdfbox-1.0.0.jar
openhtmltopdf-latex-support-1.0.0.jar
openhtmltopdf-java2d-1.0.0.jar
openhtmltopdf-slf4j-1.0.0.jar
openhtmltopdf-mathml-support-1.0.0.jar
openhtmltopdf-jsoup-dom-converter-1.0.0.jar"
openhtmltopdf-svg-support-1.0.0.jar"
openhtmltopdf-core-1.0.0.jar"_

this my code exampe 
```
OutputStream os = new FileOutputStream("d:\\outPDF.pdf");
File inputHtml  = new File("d:\\testHtml.html");
PdfRendererBuilder builder = new PdfRendererBuilder();
builder.useFastMode();
builder.withFile(inputHtml);
builder.toStream(os);
builder.run();
``` 

error: 
java.lang.NoClassDefFoundError: org/apache/xmpbox/type/AbstractField
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:63)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:39)

**Comment by ieugen** [comment]
It means that you are missing a jar on the classpath 
Try https://mvnrepository.com/artifact/org.apache.pdfbox/xmpbox . 

You should use maven or gradle or another build tool to download dependencies. It will get transitives as well.

**Comment by danfickle** [comment]
Assumed solved. Thanks @ieugen. As always, reopen if required.
