### ISSUE TITLE
SLF4j implementation not published to bintray

### ISSUE THREAD

**Issue by louisparks** [danfickle/openhtmltopdf#393]
'com.openhtmltopdf:openhtmltopdf-slf4j:1.0.0' doesn't seem to be published with all the other artifacts on bintray.  Can some please check the publishing.

great lib, thanks...

**Comment by danfickle** [comment]
My bintray claims the files are there. What error are you getting?

**Comment by louisparks** [comment]
Thanks for responding.  I think we must have had a typo or something because it’s resolving for me now.

You can close this issue.

Again thanks for responding and thanks for the truly wonderful lib.
