### ISSUE TITLE
<canvas> tag in html and javascript support

### ISSUE THREAD

**Issue by amalmys** [danfickle/openhtmltopdf#398]
It's not supporting <canvas> tag and simple javascript code embedded in <script> tag in HTML

**Comment by danfickle** [comment]
Hi @amalmys,

This project is a static HTML renderer, not a headless web browser. As such, it is unlikely to ever support JavaScript. I'd take a look at puppeteer, a headless version of chrome.

**Comment by amalmys** [comment]
> Hi @amalmys,
> 
> This project is a static HTML renderer, not a headless web browser. As such, it is unlikely to ever support JavaScript. I'd take a look at puppeteer, a headless version of chrome.

Thanks for your time....i would like to confirm whether it supports the canvas tag in html

**Comment by danfickle** [comment]
No support for canvas. How would it be useful without script support? However, if you want to draw from Java code into a PDF, that is definitely supported with custom object drawers. Although, not well documented.

**Comment by danfickle** [comment]
Closing now. Re-open if required.

**Comment by anchal0997** [comment]
Hi @danfickle , 
When you say the <script> tag is not supported, does it mean it bypasses all the script tags while conversion to PDF?

**Comment by zacharysiegel** [comment]
1. Scripts inside tags will not be evaluated.
2. If you use the built-in XML parser rather than Jsoup, the parser will not understand the script contents and may fail
