### ISSUE TITLE
Does openhtmltopdf support transform: rotate?

### ISSUE THREAD

**Issue by onriv** [danfickle/openhtmltopdf#40]
Does openhtmltopdf support css3 like this?

```
.pic-box a.nth-of-type_1 {
    transform: rotate(-6deg);
    -ms-transform: rotate(-6deg);
    -moz-transform: rotate(-6deg);
    -webkit-transform: rotate(-6deg);
    -o-transform: rotate(-6deg);
    z-index: 2;
}
```

I removed CSS Pseudo-classes because I can got it by CSS2.1

**Comment by rototor** [comment]
Not yet, I plan to implement it (see #38) but at the moment I can not give an ETA when it will be ready.

**Comment by danfickle** [comment]
Closing this in favor of #38 
The project does support pseudo classes.
