### ISSUE TITLE
Display hyphen when breaking words

### ISSUE THREAD

**Issue by sbrunecker** [danfickle/openhtmltopdf#403]
I need to generate documents with German strings that tend to be quite long. Before generating the html I separate words into syllables and add soft hyphens.

Consider the following example:

```html
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Spalte 1</th>
        <th>Spalte 2</th>
        <th>Spalte 3</th>
        <th>Spalte 4</th>
        <th>Spalte 5</th>

    </tr>
    </thead>
    <tbody>

    <tr>
        <td>Haft&shy;pflicht&shy;ver&shy;si&shy;che&shy;rung</td>
        <td>Bun­des­aus­bil­dungs­för­de­rungs­ge­setz</td>
        <td>Gleich­ge­wichts­dich­te­gra­di­en­ten­zen­tri­fu­ga­tion</td>
        <td>Hähn­chen­mast</td>
        <td>Er­trags­scha­den­ver­si­che­rung Mast­ge­flü­gel</td>
    </tr>
    </tbody>
</table>
```

In Chrome, a hyphen is displayed when printing this example:

![image](https://user-images.githubusercontent.com/33121464/68495847-5337e500-0251-11ea-9da7-2f4ad27d1aae.png)

When generating with openhtmltopdf, no hyphen is displayed:

![image](https://user-images.githubusercontent.com/33121464/68496222-19b3a980-0252-11ea-9bf0-369919d48fe3.png)

How can I get hyphens as in Chrome?

**Comment by danfickle** [comment]
Thanks @sbrunecker,

Your concise and useful sample, as well as screenshots, allowed me to focus on implementing soft-hyphens rather than coming up with test cases. It should all work now including justification and letter-spacing support.

I'm planning a release in the near future unless something comes up.

Dan.
