### ISSUE TITLE
Huge amount of +~JF****.tmp files created in the /tmp folder causing system to crash

### ISSUE THREAD

**Issue by olayinkasf** [danfickle/openhtmltopdf#405]
I'm not sure exactly why these files are being created. From s simple google search it seems like they are related to JasperReports and I don't understand why or why. The files seems to also be font files and they contain content related to [Klim Type Foundry](https://klim.co.nz/blog/licensing-information/)

**Comment by leonorader** [comment]
Hi @olayinkasf,
Could you please describe the problem with a bit more details?
What are you trying to achieve? Is there any code samples and input files you could share?

**Comment by sureshkumar-ramalingam** [comment]
I got the same issue created Huge amount of +~JF****.tmp files created in the /tmp folder causing system to crash

![image](https://user-images.githubusercontent.com/67437117/100238883-b842a380-2f56-11eb-8d66-8f0630753f78.png)

when I look for the solution, I was navigated to the below link.

https://stackoverflow.com/questions/38783010/huge-amount-of-jf-tmp-files-in-var-cache-tomcat7-temp

Any help will be really appreciated.

**Comment by olayinkasf** [comment]
I found out that the issue originated from the `BatikSVGDrawer ` that we were using and every time `BatikSVGDrawer#importFontFaceRules` was called these font files were created in the tmp folder. Since we are not using any font in our SVG, I decided to override the method and left it blank.

``` java
    private static final class NoFontSvgDrawer extends BatikSVGDrawer {

        @Override
        public void importFontFaceRules(final List<FontFaceRule> fontFaces, final SharedContext shared) {
        }

    }
```
