### ISSUE TITLE
PdfRendererBuilder.class.run throws Exception

### ISSUE THREAD

**Issue by jadams74** [danfickle/openhtmltopdf#406]
This is a bad practice. 

https://github.com/danfickle/openhtmltopdf/blob/340f488d7b8ab37cf6b144eadae090f83428538b/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfRendererBuilder.java#L36

It should throw throw render.createPDF()'s IOException instead.

**Comment by leonorader** [comment]
Merging #460 should close this issue.
