### ISSUE TITLE
Support for setting form field size

### ISSUE THREAD

**Issue by scoldwell** [danfickle/openhtmltopdf#41]
Please add support for allowing the width and height of form field elements to be set.

**Comment by danfickle** [comment]
For now, we can use CSS to set field size, but I can certainly process the size attribute. I think rows and cols is already done for textareas.

**Comment by scoldwell** [comment]
Sorry I misunderstood one of your comments from #24.  I was able to set the size of the fields using CSS.  You can close this issue.  Thanks!
