### ISSUE TITLE
my style inside html not working correctly when convert to pdf 

### ISSUE THREAD

**Issue by omarismail95** [danfickle/openhtmltopdf#419]
Hello 
i have this style inside my html 

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style type="text/css">
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    body {
        width: 384px;
        height: 576px;
        overflow: hidden;
        border: 1px solid;
        font-family: Arial, Helvetica, sans-serif;
    }
    
    .page {
        display: flex;
        flex-wrap: wrap;
    }
    
    .section {
        width: 100%;
        display: flex;
        justify-content: center;
    }
    
    .menu {
        height: 80px;
    }
    
    .content {
        height: 180px;
        clear: both;
    }
    
    .sign-up {
        background-color: #D6E9FE;
    }
    
    .feature-1 {
        background-color: #F5CF8E;
    }
    
    .feature-2 {
        background-color: #F09A9D;
    }
    
    .feature-3 {
        background-color: #C8C6FA;
    }
    
    .section-30 {
        width: 33%;
    }
    
    .section-50 {
        width: 50%;
        height: 100%;
    }
    
    .box {
        padding: 15px;
        height: 100%;
    }
    
    .label {
        font-weight: bold;
    }
    
    .internal-barcode {
        width: 100%;
        margin-top: 20px;
    }
    
    ul {
        list-style-type: none;
        display: block;
        height: 100%;
    }
    
    li {
        float: left;
        width: 100%;
    }
    
    li.value {
        font-size: 13px;
    }
    
    li.label {
        font-size: 13px;
        font-weight: bold;
        margin-top: 5px;
    }
    
    li.li-50 {
        width: 50% !important;
        margin-bottom: 0px !important;
        margin-top: 5px !important;
    }
    </style>
</head>

<body>
    <div class='page'>
        <div class='section content'>
            <div class="section-50">
                <div class="box">
                    <h4>Sender</h4>
                    <ul>
                        <li class='label'>
                            Name
                        </li>
                        <li class='value'>
                            ${0}
                        </li>
                        <li class='label'>
                            Phone
                        </li>
                        <li class='value'>
                            ${1}
                        </li>
                        <li class='label'>
                            Address
                        </li>
                        <li class='value'>
                            ${2}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="section-50">
                <div class="box">
                    <h4>Waybill: WSX871</h4>
                    <img src="${3}" width="100%" class="internal-barcode" />
                </div>
            </div>

        </div>
        <div class='section content'>
            <div class="section-50">
                <div class="box">
                    <h4>Reciever</h4>
                    <ul>
                        <li class='label'>
                            Name
                        </li>
                        <li class='value'>
                            ${4}
                        </li>
                        <li class='label'>
                            Phone
                        </li>
                        <li class='value'>
                            ${5}
                        </li>
                        <li class='label'>
                            Address
                        </li>
                        <li class='value'>
                            ${06}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="section-50">
                <div class="box">
                    <h4>Load</h4>
                    <ul>
                        <li class='label li-50'>
                            Boxes
                        </li>
                        <li class='value li-50'>
                            ${7} Box
                        </li>
                        <li class='label li-50'>
                            Weight
                        </li>
                        <li class='value li-50'>
                            ${8} KGs
                        </li>
                        <li class='label'>
                            Description
                        </li>
                        <li class='value'>
                            ${9}
                        </li>
                        <li class='label'>
                            Service Type
                        </li>
                        <li class='value'>
                            ${10}
                        </li>
                    </ul>
                </div>
            </div>

        </div>

        <div class='section content'>
            <div class="section">
                <div class="box">
                    <h3>External Reference</h3>
                    <h4>Refrence Id: WSX872</h4>
                    <img src="${11}" width="100%" class="internal-barcode" />
                    <h4>Sequence Id: WSX873</h4>
                    <img src="${12}" width="100%" class="internal-barcode" />
                </div>
            </div>

        </div>

    </div>
</body>

</html>

look like this  : 
![image](https://user-images.githubusercontent.com/37205779/69490941-34636080-0e97-11ea-85c0-df8a3fe8f44e.png)

but after add my data and convert it to pdf 
the style not working as on the html 
look like this : 

![image](https://user-images.githubusercontent.com/37205779/69490962-6aa0e000-0e97-11ea-9fb4-6cfc73cb7bcf.png)

so please i need to solve this ? 
why this happened ?

**Comment by danfickle** [comment]
Hi @OmarAllouzi95,

We don't support `display: flex` so you will have to use floats or a table or absolute positioning, etc.

**Comment by danfickle** [comment]
Assumed solved. Please reopen if required.
