### ISSUE TITLE
Problem with display cyrillic characters as #

### ISSUE THREAD

**Issue by MichaelZaleskovsky** [danfickle/openhtmltopdf#422]
Hi! I have the problem with cyrillic characters with openhtmltopdf.
I want to get PDF from html, which contains cyrillic. I use this library in servlet.
But the cyrillic simbols converted to #

I use pdfBulider in this way:
pdfBuilder
.useFastMode()
.withHtmlContent(html, "/")
.toStream(stream)
.run();
and html string contains:

`<style> 
  @font-face { 
    font-family: "PT Sans"; src: url("https://fonts.googleapis.com/css?family=PT+Sans&subset=cyrillic"); 
  } 
  body { 
    font-family: 'PT Sans', Geneva, Arial, Helvetica, sans-serif; 
  } 
</style>`
But it doesn't help me.
Could you help me - what is the problem?

**Comment by syjer** [comment]
hi @MichaelZaleskovsky ,

I don't think openhtmltopdf support the css generated by fonts.googleapis.com. You need to follow the guide https://github.com/danfickle/openhtmltopdf/wiki/Fonts#css-font-embedding-example .

So basically, you download your font (in TTF format) and define your "PT Sans" font as:

```css
@font-face {
font-family: 'PT Sans';
src: url(fonts/PTSans-Regular.ttf);
font-weight: normal;
font-style: normal;
}
```

the url is where your font is :)

Alternatively, you can register your font programmatically as described in https://github.com/danfickle/openhtmltopdf/wiki/Fonts#programatically-adding-fonts so you can avoid to define using `@font-face` .

https://fonts.google.com/specimen/PT+Sans?selection.family=PT+Sans -> you need to download the font, in the zip you will find `PTSans-Regular.ttf` which you can then use.

**Comment by danfickle** [comment]
Assumed solved, reopen if you need to.
