### ISSUE TITLE
Don't download fonts that are not actually used

### ISSUE THREAD

**Issue by danfickle** [danfickle/openhtmltopdf#43]
Currently fonts in font-face rules or fonts added programmatically are automatically downloaded even if they are never used. They don't make it into the PDF, but most browsers don't download unused fonts and we should aim to copy this behavior.

This will be a possibly breaking change, because currently if a font-weight or font-style isn't provided in the font-face rule, the font is processed and these values are taken from the font data. That will clearly be impossible if we do not download the font until we get a match.

Note that non subset fonts will continue to be embedded even if they are not used.

**Comment by danfickle** [comment]
Hi @aleksandr-m 

Unfortunately, the new way of adding fonts will break your code. However, it will improve performance significantly in the case where a font is added but not used. I've added a new method to the builder to add a font. It can be used something like this:

``` java
             builder.useFont(new FSSupplier<InputStream>() {
                @Override
                public InputStream supply() {
                    try {
                        System.out.println("Requesting font");
                        return this.getClass().getResourceAsStream("noto.ttf");
                    } catch (FileNotFoundException e) {
                        // log missing file.
                        return null;
                    }
                }
             }, "noto", 400, FontStyle.NORMAL, true); 
```

Let me know if you have any issues with this new method.

Thanks,
Daniel.

**Comment by aleksandr-m** [comment]
Can we have overloaded `useFont(FSSupplier<InputStream> supplier, String fontFamily)` method?

I'll take a closer look when the next version is released or when I have time to build it myself. :)
Thanks for the heads-up!
