### ISSUE TITLE
issue using Geometric Shapes UTF-8 characters

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#431]
Hello,

When my html document contains any character from the Geometric Shapes group, it renders as "#".
I'm using the arialuni font wich includes these characters.

Is it coming from pdfbox like in #112 ?

**Comment by syjer** [comment]
hi @JulienAuge , do you have a sample html file so we can try it?

**Comment by ghost** [comment]
Hi, @syjer we solved our problem, it was just encoding .
You can close the issue
