### ISSUE TITLE
Arabic mixed with English or Integers not rendering properly

### ISSUE THREAD

**Issue by haziq-k** [danfickle/openhtmltopdf#432]
I am trying to create a pdf which has Arabic, English and integers.

This is my sample string = انا استخدم  100 مترجم جوجل

After pdf creation, the text is not proper, pls check the output.
Output is attached as response.pdf
I am passing the string html.

Code I am using: 

` String html = new String("<html>\n" +
                    "<meta charset=\"UTF-8\"/>\n" +
                    "    <head>\n" +
                    "        <title>DIV Font</title>\n" +
                    "\n" +
                    "        <style>\n" +
                    "            .my_text\n" +
                    "            {\n" +
                    "                font-family:    Arial Unicode MS,Arial, Helvetica, sans-serif;\n" +
                    "                font-size:      40px;\n" +
                    "                font-weight:    bold;\n" +
                    "            }\n" +
                    "        </style>\n" +
                    "    </head>\n" +
                    "\n" +
                    "    <body>\n" +
                    "        <div class=\"my_text\">انا استخدم  100 مترجم جوجل  </div>\n" +
                    "    </body>\n" +
                    "</html>\n");
       
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.withHtmlContent(html, GeneratePDF.class.getResource("/root.htm").toExternalForm());
            builder.useUriResolver(new UriResolver());
            
            // For Right to Left display support
            builder.useUnicodeBidiSplitter(new ICUBidiSplitter.ICUBidiSplitterFactory());
            builder.useUnicodeBidiReorderer(new ICUBidiReorderer());
            
            builder.useFont(new FSSupplier<InputStream>() {

                @Override
                public InputStream supply() {
                    return this.getClass().getResourceAsStream("/font/arialuni.ttf");
                }
            }, "Arial Unicode MS");

            builder.toStream(os);
            builder.run();`

[response.pdf](https://github.com/danfickle/openhtmltopdf/files/4085312/response.pdf)

**Comment by ieugen** [comment]
Could you please describe the issue in more detail? 
To me it looks good but I don' speak Arabic: 
![Captură de ecran de la 2020-01-21 11-38-26](https://user-images.githubusercontent.com/1050920/72793108-b88d5680-3c42-11ea-8359-c2f570c5efc9.png)

You might have a font issue.

**Comment by haziq-k** [comment]
@ieugen If you compare the sample string and output..you will know the difference. The words before 100 should be after 100 and vice-versa

**Comment by ieugen** [comment]
That is a serious issue and we might hit it as well in our reports. We have some reports, layout ready for Arabic inspection. I do hope we don't run into these kind of issues.

**Comment by haziq-k** [comment]
@ieugen  Thanks for confirming.

**Comment by ieugen** [comment]
Just to be clear. I did not confirm that we have seen the issue. I've sent the reports we are building to our Arabic speaking partners and they did not mention any layout issue. So it seems in our case we are ok. 

This is the template we use. Have you tried setting `dir=` attribute ? Maybe this is what is causing the situation. See <body/>

```
<!DOCTYPE html>
<html lang="{locale}">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta name="theme-color" content="#000000"/>
  <meta name="description" content="Report"/>
  <title>{title}</title>
  <link rel="stylesheet" href="static/css/main.css"/>
</head>
<body dir="{dir}">
{report}
</body>
</html>
```

**Comment by ieugen** [comment]
@haziq-k : Did you try the direction attribute? We can generate proper arabic reports with tables and everything ( we manually reverse table columns ).

**Comment by danfickle** [comment]
Hi @haziq-k,

As others have mentioned, you will have to use `dir="auto"` or `dir="rtl"` in your document. If it is still not working, could you have a look at the [bidi test output](https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-examples/src/main/resources/visualtest/expected/text/arabic-bidi.pdf) and tell me if it is also wrong? [Source document here](https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-examples/src/main/resources/visualtest/html/text/arabic-bidi.html)

I don't read Arabic, so just use lorem-ipsum text and compare output with Chrome, so there is a possibility that I've got it wrong.

**Comment by ieugen** [comment]
We deliver reports to native speaking Arabs and using `<body dir="rtl"  />` does the trick with the known limitations: tables are not working ok. We do them manually. 

@danfickle : We use react and to have the tables in Arabic we render the columns and then we do a `reverse()` on the array. I thought this might be useful :) .

**Comment by danfickle** [comment]
Thanks @ieugen,
I think we can close this then. Reopen as required.

**Comment by a-leithner** [comment]
@danfickle - Is the `dir="rtl"` attribute only supported on `<body>` tags? I'm trying to generate PDFs with mixed Arabic, Farsi and German and having enclosed the mixed lines with `<span dir="rtl"><!-- Arabic mixed with German --></span>` yields to the two sentence halves being switched around the German sentence parts (just like what was described by @haziq-k with integers in the original issue)...

If needed, I can provide sample input and outputs (as well as expected outputs), but I'll have to get an OK at work before.

**Comment by a-leithner** [comment]
OK, so I have fixed this problem - after having read [the MDN article on `<bdi>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi).

For future reference (could this be documented somewhere? -- maybe in the Wiki, to expand the RTL/Bidi-Support passage), when embedding LTR text in RTL sentences, first wrap the complete line or text in a tag with `dir="rtl"` and the LTR passages in `dir="ltr"`, which did the trick for me. Pseudo-code example:
```html
<span dir="rtl">
    <!-- Some RTL here -->
    <span dir="ltr">
        <!-- Some LTR here -->
    </span>
    <!-- Some more RTL here -->
</span>
```

This will provide correct output as seen when composing mixed text with Word and the like. However, when copy-pasting the sentences into the HTML file, I have had some trouble putting the spans at the right places, but everything went to plan after that.
