### ISSUE TITLE
Not able to find documentation for my use case.

### ISSUE THREAD

**Issue by rja907** [danfickle/openhtmltopdf#435]
Hi,

I want to use this library to make PDFs in my Spring project. 

The reason why I think this would be a good idea is because I am planning on populating an html template with about 200-300 rows of table data. 

Is there an example where I see someone populating a templated html and then using this library to convert it into a PDF?

If there is not a concrete example, could you tell me some libraries for templated HTML that work well with openhtmltopdf?

**Comment by danfickle** [comment]
I use Thymeleaf (for both html pages from Spring and html fed to this library), which works well. Untested code to setup Thymeleaf below:

````java
// 1. Set up the global thread safe template engine.
ClassLoaderTemplateResolver resolver = new ClassLoaderTemplateResolver();
resolver.setTemplateMode(TemplateMode.XHTML);
resolver.setPrefix("/templates/"); /* Wherever you store templates under src/main/resources */
resolver.setSuffix(".html");

TemplateEngine templateEngine = new TemplateEngine();
templateEngine.setTemplateResolver(resolver);


// 2. Use the template engine.
Context ctx = new Context();
ctx.setVariable("msg", "world");
String res = templateEngine.process("template-name-without-suffix-or-prefix", ctx);
// Pass res to this library.
````

````
<html>
<body>
Hello <span th:text="${msg}"></span>
</body>
</html>
````

**Comment by rja907** [comment]
Thanks, I ended up using [Mustache templates](https://mvnrepository.com/artifact/com.github.jknack/handlebars). It is pretty similar to Thymeleaf. 

I will close this issue now.
