### ISSUE TITLE
Inline CSS ignored during PDF generation

### ISSUE THREAD

**Issue by schausson** [danfickle/openhtmltopdf#436]
Hi, 
I would like to generate a PDF based on below html file, but I obtain the styles definition in resulting file (cf attached input html file and resulting pdf file).
Is there a way to avoid this behavior, either by using style definition is possible or ignore it if wrongly defined ?
Thanks for your help
Sebastien

[example_file.pdf](https://github.com/danfickle/openhtmltopdf/files/4117458/example_file.pdf)

[example_file.tar.gz](https://github.com/danfickle/openhtmltopdf/files/4117455/example_file.tar.gz)

**Comment by VictorAtPL** [comment]
```
<style type="text/css">
...
</style>
```
must be b/w `<head>` and `</head>` tags.

Also, `type="text/css"` is not necessary (look here: [https://github.com/danfickle/openhtmltopdf/wiki/Page-features](https://github.com/danfickle/openhtmltopdf/wiki/Page-features)).

**Comment by danfickle** [comment]
@VictorAtPL is right, we don't support `<style>` tags outside the `<head>` section. You could ignore them by adding this to your style (in head):
````css
body style {
  display: none;
}
````

**Comment by danfickle** [comment]
Assumed solved. Reopen as required.
