### ISSUE TITLE
How to add dynamic headers and footers?

### ISSUE THREAD

**Issue by rja907** [danfickle/openhtmltopdf#437]
I have a pretty complex document that I need to make using this library. 

The document will have a left, a center and a right header and a left, a center and a right footer.

Some of these contain hardcoded stuff but some in some of these, I need to add dynamic information. 

For eg: in the center footer, I need to have `Page 2 of 10 Document ID: {{documentId}}`. I don't think I can import the handlebar values in the CSS property `content`. How can I achieve this?

I looked into the CSS Paged media docs and it also using the `content` property to populate stuff.

**Comment by danfickle** [comment]
Hi @rja907, 
If your template language does not support CSS encoding, you should be able to use running elements. Untested sample below. Please note the `hdr` identifier can be any valid CSS identifier.
````html
<html>
<head>
<style>
  @page {
    margin: 2cm 1cm; /* Whatever to fit running element */
    @bottom-center {
      content: element(hdr);
    }
  }
  .page-number:after {
    content: "Page " counter(page) " of " counter(pages);
    color: red;
  }
</style>
</head>
<body>
  <div style="position: running(hdr);">
     <span class="page-number"></span> <span>Document ID:  {{documentId}}</span>
  </div>

  Rest of body content...
</body>
</html>
````

**Comment by danfickle** [comment]
Assumed solved, please reopen if required.
