### ISSUE TITLE
CSS background:linear-gradient(red,yellow); not working

### ISSUE THREAD

**Issue by rja907** [danfickle/openhtmltopdf#439]
I just tried to use this library to generate PDFs using HTML templates.
Here is some code:
CSS
```
.thank-you-background {
  height: 20px;
  background: linear-gradient(red, yellow);
}
```
HTML
```
<div class="thank-you-background">
   <p><strong>THANK YOU FOR YOUR BUSINESS!</strong></p>
</div>
```
I have also tried using `background-image: linear-gradient(red, yellow);` but that gave an explicit error saying `com.openhtmltopdf.css-parse WARNING:: (./#inline_style_1) Value for background-image must be an identifier or a URI at line 76. Skipping declaration.`.

The HTML renders it correctly but the library does not show the gradient background.

**Comment by VictorAtPL** [comment]
I might be wrong, but `linear-gradient` looks to be introduced in CSS3 specification.

> Open HTML to PDF is a pure-Java library for rendering arbitrary well-formed XML/XHTML (and even HTML5) using CSS 2.1 for layout and formatting, outputting to PDF or images.

This is from _overview_ section in this repo's readme file.

There are supported some CSS3 features, like rotate or columns, but `linear-gradient` looks not to be implemented. I'd suggest just using image background.
