### ISSUE TITLE
SECURITY ISSUE - Prevent XXE attacks

### ISSUE THREAD

**Issue by danfickle** [danfickle/openhtmltopdf#44]
Big thanks to @lillesand for bringing to my attention that Flying Saucer and OpenHTMLtoPDF are vulnerable to XXE attacks. You may be vulnerable if you use either project and allow the user to supply arbitrary XHTML (which I don't recommend at this stage).

Links:
https://www.gracefulsecurity.com/xml-external-entity-injection-xxe-vulnerabilities/
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

I am about to commit a fix and then release RC6 so people can update promptly.

**Comment by danfickle** [comment]
This was fixed in the RC7 release.

**Comment by lillesand** [comment]
Kudos for fixing this so quickly, @danfickle! 👏
