### ISSUE TITLE
page first

### ISSUE THREAD

**Issue by bhaskermca** [danfickle/openhtmltopdf#441]
How can i show some dynamic content before footer always using @page:first 

I have already footer in the page where i have bootom-left and the content will spread from total page left to right.

Here is my struggle to show some data above the footer only in the first page.

 @page {
            size: 8.5in 11.69in;
            -fs-page-orientation: portrait;
            margin-left: 25px;
            margin-right: 25px;
            margin-top: 125px;
            margin-bottom: 25px;
            margin-bottom:[[${@helper.getBottomMargin(payDistributions,80)}]]px;
            @bottom-left {
                text-align: right;
                content: element(footer) <br/>  counter(page) ' of ' counter(pages)
            }

            @top-center{
                content: element(header)

            }

        }

@page:first{

@bottom-midle{
content:'<<Some Dynamic content>>'
}

}

        running {
            position: running(footer) ;
        }

The Problem is the content is spreading entire page left to right and it is overriding in the first page.

**Comment by danfickle** [comment]
Hi @bhaskermca,

I'm not sure I understand the problem, but have you tried `display: inline-block` if you don't want the running element to spread from left-to-right?

**Comment by danfickle** [comment]
Assumed solved, please re-open as required.
