### ISSUE TITLE
Z-index is not working in the pdf rendering

### ISSUE THREAD

**Issue by bhaskermca** [danfickle/openhtmltopdf#442]
I have a requirement where i have a header with some content at the right corner but when have a DIV below to that there is always space at left and center.

My Div always has the content at the center so i have used margin-top:-120px with z-index but the div data is hidden by the header

**Comment by danfickle** [comment]
Generally, z-index can only be used with absolutely positioned block elements. If that is not the problem, could you perhaps provide a minimal sample of the problem?

**Comment by bhaskermca** [comment]
Thanks for the response below are the details . for the same

Below are the HTML and generated PDF for the same.
[TEST.pdf](https://github.com/danfickle/openhtmltopdf/files/4259600/TEST.pdf)

[pdf copy.txt](https://github.com/danfickle/openhtmltopdf/files/4259605/pdf.copy.txt)


I have attached both html and pdf documents.

where the donut in the PDF should be attached to horizontal line.

I have one more issue ( which is similar in html it is working properly ) box-shadowing property is not working properly

**Comment by danfickle** [comment]
Closing for now. Please reopen if required.
