### ISSUE TITLE
W3CDom::fromJsoup breaks inputs in HTML forms

### ISSUE THREAD

**Issue by testinfected** [danfickle/openhtmltopdf#445]
Hi there, 

Previously we were using the now removed DOMContent (in openhtmltopdf-jsoup-dom-converter) to convert HTML 5 using jsoup to a w3c DOM representation.

We've upgraded to 1.0.1 and use the latest jsoup as recommended in the integration guide, i.e. 

```
...
var doc = Jsoup.parse(html);
var dom = new W3CDom().fromJsoup(doc);
...
```

Unfortunately it breaks our form inputs, which no longer appear in the generated pdf. It works with HTML tags with a corresponding closing tag (e.g. `textarea`), but apparently not with other tags.

Works fine with 1.0.1 and the old `openhtmltopdf-jsoup-dom-converter`

**Comment by danfickle** [comment]
Hi @testinfected,

I suspect this could be an issue with namespaces. Are you able to try with a document that specifies no namespace? Something like:

````html
<html>
<body>
<form>
  <input type="text" name="firstName">
</form>
</body>
</html>
````

**Comment by testinfected** [comment]
Hi @danfickle 

We don't have any namespace in our document. It's a plain HTML 5 document. 
```
<!DOCTYPE html>
<html lang="en">
...
```

We have the same issue with the example at https://github.com/danfickle/openhtmltopdf/wiki/Form-Controls

Cheers,

**Comment by danfickle** [comment]
Thanks @testinfected,

I've worked around the behavior of Jsoup converter now. It took a lot of debugging to find the root cause.

**Comment by testinfected** [comment]
Thanks @danfickle, that's great news!
