### ISSUE TITLE
:lang CSS selector support?

### ISSUE THREAD

**Issue by fungc** [danfickle/openhtmltopdf#446]
Hi guys, 
I am trying to produce a PDF, but my HTML has <style> with the :lang CSS selector.
https://www.w3schools.com/cssref/sel_lang.asp

And I have the html attribute like <html lang="de" xml:lang="de">
https://www.w3schools.com/tags/att_global_lang.asp

However, the produced PDF is ignoring styles in body:lang(de) {}

Is there someway I can make this work? Thanks!

**Comment by fungc** [comment]
Ok I think I might have found the bug
https://github.com/danfickle/openhtmltopdf/blob/c520a52498346b3d1f08af794802bc99c5e18e76/openhtmltopdf-core/src/main/java/com/openhtmltopdf/css/newmatch/Condition.java#L380

Suppose we have 
<html lang="ja"> <body></body></html>

attRes.getLang(e) with return "ja" for the html element, but return empty string "" for the body element.

This means getLang is not looking up the parent lang attribute.

Is that expected?

**Comment by danfickle** [comment]
I finally found example 30 from [Selectors Level 4](https://drafts.csswg.org/selectors-4/#lang-pseudo) which suggest our behavior is wrong:

> In this HTML example, only the BODY matches ''[lang|=fr]'' (because it has a LANG attribute) but both the BODY and the P match :lang(fr) (because both are in French). The P does not match the ''[lang|=fr]'' because it does not have a LANG attribute.
````html
<body lang=fr>
  <p>Je suis français.</p>
</body>
````

I'll commit a fix that looks up the parent chain for a lang attribute. In the meantime, if you know the element the lang attribute is set on, you could of course use a descendant selector.

````css
html:lang(ja) body { }
````

**Comment by fungc** [comment]
From reading the source code I found that this works with the current version
`            <meta http-equiv="Content-Language" content="de" />
`
But yes it would be better to have a fix
