### ISSUE TITLE
box-shadow css property not rendering in PDF

### ISSUE THREAD

**Issue by bhaskermca** [danfickle/openhtmltopdf#449]
PDF is not rendering the boox-shadow property below is the code i am using.

.card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 40%;
}

 <div class="card">

                <div class="container">
                    <h4><b>John Doe</b></h4>
                    <p>Architect Engineer</p>
                </div>

            </div>

**Comment by danfickle** [comment]
Hi @bhaskermca,

Sorry, `box-shadow` property is not implemented. For that matter, neither is `rgba` with alpha value. If someone was to figure out how to implement box-shadow correctly in PDF, perhaps by looking at some of the other HTML to PDF renderers, I would be interested in adding it.

**Comment by danfickle** [comment]
Discussion (with no good solution here):

https://github.com/Kozea/WeasyPrint/issues/13

**Comment by bhaskermca** [comment]
Thank you very much for the reply we have tried with other approach using div borders and images it is good

**Comment by cabaji9** [comment]
i had to use this box-shadow and after several tries this worked for me; <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Box-shadow alternative — nested filled borders (OpenHTMLtoPDF friendly)</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background: white;
      padding: 60px;
    }

    /* Optional offset so shadow falls bottom-right */
    .section-body {
      padding: 0 3px 3px 0;
    }

    table.section-card-shadow,
    table.section-card-shadow table {
      width: 100%;
      border-collapse: separate;
      border-spacing: 0;
    }

    /* Outermost = softest; inner layers darken toward the card */
          td.section-card-shadow-1 {
            background: #fdfdfd;
            border: 1px solid #fdfdfd;
            border-radius: 16px;
            padding: 1px;
        }

        td.section-card-shadow-2 {
            background: #fafafa;
            border: 1px solid #fafafa;
            border-radius: 14px;
            padding: 1px;
        }

        td.section-card-shadow-3 {
            background: #f7f7f7;
            border: 1px solid #f7f7f7;
            border-radius: 12px;
            padding: 1px;
        }

        td.section-card-shadow-4 {
            background: #f4f4f4;
            border: 1px solid #f4f4f4;
            border-radius: 10px;
            padding: 1px;
        }

    .card {
      background: #ffffff;
      border-radius: 8px;
      padding: 24px 28px;
      
    }

    .card h2 {
      margin: 0 0 8px;
      font-size: 16px;
      color: #222;
    }

    .card p {
      margin: 0;
      font-size: 13px;
      color: #666;
      line-height: 1.6;
    }
  </style>
</head>
<body>

  <div class="section-body">
    <table class="section-card-shadow" cellpadding="0" cellspacing="0">
      <tr>
        <td class="section-card-shadow-1">
          <table cellpadding="0" cellspacing="0">
            <tr>
              <td class="section-card-shadow-2">
                <table cellpadding="0" cellspacing="0">
                  <tr>
                    <td class="section-card-shadow-3">
                      <table cellpadding="0" cellspacing="0">
                        <tr>
                          <td class="section-card-shadow-4">
                            <div class="card">
                              <h2>Card Title</h2>
                              <p>
                                Faux shadow using 4 nested filled borders.
                                Works in browsers and OpenHTMLtoPDF (no box-shadow, no SVG filters).
                              </p>
                            </div>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>

</body>
</html>
