### ISSUE TITLE
Auto font detection? 

### ISSUE THREAD

**Issue by fungc** [danfickle/openhtmltopdf#454]
Hello,

I was using fop earlier for PDF generation, and it had a way to import fonts with auto-detect:
https://xmlgraphics.apache.org/fop/2.4/fonts.html#bulk

Is it possible to do something similar with openhtmltopdf? It becomes a long list of fonts after a while, and lots of addFont in code.

Thanks!

**Comment by danfickle** [comment]
Something like (untested):

````java
        // List all font files from directory.
        List<Path> fontFiles = 
        Files.list(Paths.get("/your/files"))
             .filter(path -> path.endsWith(".ttf"))
             .collect(Collectors.toList());

        // Add all as normal weight fonts.
        for (int i = 0; i < fontFiles.size(); i++) {
            File file = fontFiles.get(i).toFile();
            builder.useFont(file, "f" + i);
        }
        
        // Create a CSS font-family value.
        // Use it in the template to use fonts added above.
        String cssFontFamily = 
        IntStream.range(0, fontFiles.size())
                 .mapToObj(i -> "'f" + i + "'")
                 .collect(Collectors.joining(","));
````

**Comment by fungc** [comment]
What about different styles? Like bold italic etc.

Also, doesn’t useFont need the name of the font family, if you need to
change font style? Would there be a way to auto detect the font family name?

Thanks!

**Comment by sungmore** [comment]
> ```java
> builder
> ```

Hi，sorry to bother you. when use  "builder.useFont(file, "f" + i);", how do I combine it with PdfConverterExtension.exportToPdf("~/flexmark-java.pdf", html,"", OPTIONS)， thanks.

**Comment by NewWorldNewCode** [comment]
> Something like (untested):
> 
> ```java
>         // List all font files from directory.
>         List<Path> fontFiles = 
>         Files.list(Paths.get("/your/files"))
>              .filter(path -> path.endsWith(".ttf"))
>              .collect(Collectors.toList());
> 
>         // Add all as normal weight fonts.
>         for (int i = 0; i < fontFiles.size(); i++) {
>             File file = fontFiles.get(i).toFile();
>             builder.useFont(file, "f" + i);
>         }
>         
>         // Create a CSS font-family value.
>         // Use it in the template to use fonts added above.
>         String cssFontFamily = 
>         IntStream.range(0, fontFiles.size())
>                  .mapToObj(i -> "'f" + i + "'")
>                  .collect(Collectors.joining(","));
> ```

Hi，sorry to bother you. when use "builder.useFont(file, "f" + i);", how do I combine it with PdfConverterExtension.exportToPdf("~/flexmark-java.pdf", html,"", OPTIONS)， thanks.

**Comment by ieugen** [comment]
I think it would be nice to have some functionality around this.

We have implemented it like this and you can use the code here. It wold be nice to be available inside the builder. 

You give it a list of extensions to look for and it will register all fonts it finds. 

```

// Here we call the font registration process
    if (registerFonts) {
      registerFonts(builder);
    }
    return builder;
----

  void registerFonts(PdfRendererBuilder builder) throws IOException {
    Path fonts = Paths.get(config.getBasePath(), "report-assets", "fonts");
    log.trace("Loading fonts from {}", fonts.toAbsolutePath().toString());
    FileVisitor<Path> fileProcessor = new FontFileProcessor(builder);
    Files.walkFileTree(fonts, fileProcessor);
  }
---

package com.gr8pi.reportgen.openhtmltopdf;

import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Arrays;
import java.util.List;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.experimental.FieldDefaults;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public final class FontFileProcessor extends SimpleFileVisitor<Path> {

  List<String> validExtensions;
  PdfRendererBuilder builder;

  public FontFileProcessor(PdfRendererBuilder builder) {
    this.validExtensions = Arrays.asList("ttf");
    this.builder = builder;
  }

  @Override
  public FileVisitResult visitFile(Path font, BasicFileAttributes attrs) throws IOException {
    log.trace("Processing file: {}", font);

    if (attrs.isRegularFile() && isValidFont(font)) {
      try {
        String familyName = readFontFamilyName(font);
        log.trace("Loading font {} - {}", font.toString(), familyName);
        builder.useFont(font.toFile(), familyName);
      } catch (FontFormatException ffe) {
        log.warn("Ignoring font with invalid format {}", font);
        log.debug("Exception is ", ffe);
      }
    }

    return FileVisitResult.CONTINUE;
  }

  private boolean isValidFont(Path font) {
    return validExtensions.stream()
        .filter(ext -> font.toString().endsWith(ext))
        .findFirst()
        .isPresent();
  }

  @Override
  public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
    log.info("Processing directory: {}", dir);
    return FileVisitResult.CONTINUE;
  }

  private String readFontFamilyName(Path font) throws IOException, FontFormatException {
    Font f = Font.createFont(Font.TRUETYPE_FONT, font.toFile());
    return f.getFamily();
  }
}


```

**Comment by danfickle** [comment]
I've fleshed out the code sample kindly provided by @ieugen (thank you!) on the [wiki under AutoFont](https://github.com/danfickle/openhtmltopdf/wiki/AutoFont).

I did not put it in the builder for a few reasons:

+ It is not as robust as I'd like. Specifically it uses heuristics to determine if a font is bold or italic.
+ It should only be run once, for performance, rather than on every builder invocation.
+ You may need its results to use in the template for `font-family` property.

Please re-open this issue if required.
