### ISSUE TITLE
Cancel automatically generating title sequence number

### ISSUE THREAD

**Issue by NewWorldNewCode** [danfickle/openhtmltopdf#455]
Sorry to bother you, how to set md to PDF and cancel automatically generating title sequence number

**Comment by sungmore** [comment]
Another question is ：when I render '中文字符' in codeblock  on markdown ,how should I specify the font?

**Comment by danfickle** [comment]
Surely this is an issue with the Markdown converter you are using? If it is doing the title counter via CSS, you may be able to override it. Can you investigate the CSS the Markdown converter is using?

**Comment by NewWorldNewCode** [comment]
> Surely this is an issue with the Markdown converter you are using? If it is doing the title counter via CSS, you may be able to override it. Can you investigate the CSS the Markdown converter is using?

Yes, I solved it by override the default.css, thanks
