### ISSUE TITLE
it doesn't support other language.

### ISSUE THREAD

**Issue by LiQingMuBai** [danfickle/openhtmltopdf#46]
this is my html.
`<html>
<meta charset="UTF-8" />
<body>
<p>WHITE 白い(default)</p>
</body>
</html>
`

but when i run TestcaseRunner, the pdf display
WHITE ##(default)

**Comment by danfickle** [comment]
Hi @IBYoung - Outside of Western European languages you need to provide a font for PDFs. Fortunately, Google has organised noto fonts for most scripts. Unfortunately, they are only in otf format which this project does not support. So I searched the web, and found someone had nicely converted the cjk preview of noto to ttf which this project does support.

Long story short, you can download cjk fonts from [noto-sans-cjk](https://djmilch.wordpress.com/2016/01/19/free-font-noto-sans-cjk-in-ttf/) and use them like so:

``` html
<html>
<head>
<style>
@font-face {
    font-family: 'cjk';
    src: url(NotoSansCJKtc-Regular.ttf);
}
</style>
</head>
<body>
<p style="font-family: 'cjk';font-size: 40px;">WHITE 白い(default)</p>
</body>
</html>
```

and you will get this:
![cjk-screenshot](https://cloud.githubusercontent.com/assets/1415728/19848814/03c6b9e6-9fa4-11e6-959e-166f028e275e.png)

**Comment by song7619072** [comment]
Can you paste the java code?

Thanks
