### ISSUE TITLE
RTL and LTR in the same sentence

### ISSUE THREAD

**Issue by fieldbit** [danfickle/openhtmltopdf#463]
When creating a PDF of something which has both RTL (Arabic, Hebrew) and a number or English in the same paragraph, the output is not according to the right order.

Using the latest (v1.0.2) and RTL support.

**Comment by AnanasPizza** [comment]
Funny, I wanted to open up an issue about this aswell right now.
Most of it you can resolve bei using dir="auto" on the element. 
What I did at some points was to use a span around those things inline, that have the opposite direction and used direction: ltr; unicode-bidi: embed; on that span-tag.

**Comment by danfickle** [comment]
Hi @fieldbit,

Can you please provide a minimal HTML example and your builder config, preferably using open-source fonts? Thanks.

**Comment by fieldbit** [comment]
Actually, when I added dir = "auto" it worked great.
Thanks everyone!
