### ISSUE TITLE
The entity name must immediately follow the '&' in the entity reference

### ISSUE THREAD

**Issue by neesonqk** [danfickle/openhtmltopdf#468]
```
<tr>
<td style="font-size: 12px;">Human Anatomy & Physiology Marieb, Human Anatomy & Physiology -Hardcover</td>                
</tr>
```
Due to `&` in the content, it throws,

```
com.openhtmltopdf.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 159; columnNumber: 66; The entity name must immediately follow the '&' in the entity reference.
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:274)
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.access$100(XMLResource.java:168)
```

**Comment by syjer** [comment]
hi @neesonqk , you need to pass valid xml to openhtmltopdf, so basically, in your case, `&` should be the entity `&amp;`. You can use a html5 parser (like https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide#html5-parser-support ) to handle it.

**Comment by danfickle** [comment]
As @syjer said, valid XML is required or use a HTML parser. But even with HTML, user content must be escaped. This is usually done with the template engine, but there are standalone HTML escaper methods in various libraries.

**Comment by neesonqk** [comment]
Well noted with thanks!
