### ISSUE TITLE
a href mailto not working

### ISSUE THREAD

**Issue by mndzielski** [danfickle/openhtmltopdf#469]
Hi @danfickle

Could you provide support for links with mailto?

````
<html>
<head>
<style>
</style>
</head>
<body>

user@gmail.com

<br /><br />

<a href="mailto:user@gmail.com">Send a message!</a>

</body>
</html>
````

I would like to customize text on email links.

**Comment by syjer** [comment]
hi @mndzielski , you are right, the mailto: protocol is not supported, I've submitted a PR #470
