### ISSUE TITLE
Can I run openhtmltopdf RC17 with Java 7?

### ISSUE THREAD

**Issue by jonasatmonday** [danfickle/openhtmltopdf#471]
Hello,

just as the header says - can I run openhtmltopdf RC17 with Java 7? The documentation states that as of RC18, Java 8 is required. Does that mean that I can run RC17 with Java 7?

**Comment by syjer** [comment]
hi @jonasatmonday , yes, rc17 run on java7. But I would advise to upgrade to the latest version as the dependencies (pdfbox & co) may have security issues.

**Comment by jonasatmonday** [comment]
Hello @syjer, thank you for your feedback! Do you know of any specific security issues the dependencies may have? Unfortunately, Java 7 is a given for now but I will upgrade openhtmltopdf as soon as we upgrade our Java version.

**Comment by syjer** [comment]
hi @jonasatmonday , https://www.cvedetails.com/product/33936/Apache-Pdfbox.html?vendor_id=45 . 

But I think you could try to force the pdfbox versions to the latest while keeping the rc17 of openhtmltopdf.

**Comment by danfickle** [comment]
Also, PDFBOX has recently moved to Java 8 too, so check which is the latest version you can use.

**Comment by jonasatmonday** [comment]
Hi @syjer and @danfickle , thank you a lot! I forced PDF Box to 2.0.19 (latest version possible for openhtmltopdf RC17) and it works :) I close this ticket.
