### ISSUE TITLE
Pdf Page features - boxes to sit in the right margin area of the page are not being styled

### ISSUE THREAD

**Issue by sandre1** [danfickle/openhtmltopdf#473]
Hello guys,
I am trying to have a fixed width margin with a blue background color for the pdf pages, and for that i am styling the page side boxes ( https://github.com/danfickle/openhtmltopdf/wiki/Page-features). For the same css rules as for the left side, by some reason, the boxes to sit in the right margin of the generated page don't have the same css style.
I can achieve the expected result (partially) by increasing the page margin-right but this is not good because the page margin overlaps the html body elements ( i just want the red circle absolutely positioned, to be on top of the blue margin in the right side as it is in the left side).
![Captură de ecran de la 2020-05-03 18-29-12](https://user-images.githubusercontent.com/33352772/80918274-c9368800-8d6c-11ea-81cc-4b6a70c283fd.png)

i have provided the sample code to be used in the sandbox: [https://sandbox.openhtmltopdf.com/?file=page-features.htm]

`<html>
<head>
<style>
@page {
  size: a4 portrait;
  margin-right: 30px;
  margin-left: 5px;
  margin-top: 80px;
  @top-left-corner {
    content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @left-top {
  content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @left-middle {
   content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @left-bottom {
  content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @bottom-left-corner {
  content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }

  @top-right-corner {
content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @right-top {
  content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @right-middle {
   content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @right-bottom {
content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
  @bottom-right-corner {
content: '.';
    color: blue;
    background-color:blue;
    padding: 0 15px;
  }
}
body {
margin-left: 60px;
}
.container {
position: relative;
}
.ltr-bullet {
width: 50px;
  height: 50px;
  box-sizing: border-box;
  border-radius: 50%;
  text-align: center;
  display: inline-block;
  background-color: red;
  position: absolute;
  left: -60px;
  top: 8px;
}
.rtl-bullet {
width: 50px;
  height: 50px;
  box-sizing: border-box;
  border-radius: 50%;
  text-align: center;
  display: inline-block;
  background-color: red;
  position: absolute;
  right: -15px;
  top: 8px;
}

</style>
</head>
<body>
<div class="container">
<div class="ltr-bullet"></div>
<div class="rtl-bullet"></div>
Line 1<br/>
Line 2<br/>
Line 3<br/>
Line 4<br/>
Line 5<br/>
Line 6<br/>
Line 7<br/>
Line 8<br/>
Line 9<br/>
Line 10<br/>
Line 11
</div>
</body>
</html>`

**Comment by mndzielski** [comment]
You should use z-index with elements having absolute position

**Comment by sandre1** [comment]
Increasing the page margins cutts off the html body width, so the z-index works only with html elements, not the @page itself. 
Using z-index does not resolve the issue.

**Comment by danfickle** [comment]
Hi @sandre1,

`linear-gradient` support was introduced in the latest version (1.0.2 and later) so you can do as below. This will not work in the sandbox as it is lagging versions.

````html
<html>
<head>
<style>
@page {
  margin: 80px 50px;
  @left-top {
     content: element(left-margin);
     background-image: linear-gradient(to right, blue, blue 50%, white 50%, white);
  }
  @left-middle {
     content: " ";
     background-image: linear-gradient(to right, blue, blue 50%, white 50%, white);
  }
  @left-bottom {
     content: " ";
     background-image: linear-gradient(to right, blue, blue 50%, white 50%, white);
  }

  @right-top {
    content: element(right-margin);
    background-image: linear-gradient(to left, blue, blue 50%, white 50%, white);
  }
  @right-middle {
     content: " ";
     background-image: linear-gradient(to left, blue, blue 50%, white 50%, white);
  }
  @right-bottom {
     content: " ";
     background-image: linear-gradient(to left, blue, blue 50%, white 50%, white);
  }

  @top-left-corner {
    content: " ";
    background-image: linear-gradient(to right, blue, blue 50%, white 50%, white);
  }
  @bottom-left-corner {
    content: " ";
    background-image: linear-gradient(to right, blue, blue 50%, white 50%, white);
  }

  @top-right-corner {
    content: " ";
    background-image: linear-gradient(to left, blue, blue 50%, white 50%, white);
  }
  @bottom-right-corner {
    content: " ";
    background-image: linear-gradient(to left, blue, blue 50%, white 50%, white);
  }
}

div.l-margin {
  position: running(left-margin);
}
div.l-margin-inner {
  position: absolute;
  width: 100%;
}
div.l-margin-bullet {
  width: 40px;
  position: relative;
  left: 5px;
  background-color: red;
  border-radius: 50%;
  height: 40px;
}

div.r-margin {
  position: running(right-margin);
}
div.r-margin-inner {
  position: absolute;
  width: 100%;
}
div.r-margin-bullet {
  width: 40px;
  position: relative;
  right: -5px;
  background-color: red;
  border-radius: 50%;
  height: 40px;
}
</style>
</head>
<body>

<div class="l-margin">
 <div class="l-margin-inner">
  <div class="l-margin-bullet"></div>
 </div>
</div>

<div class="r-margin">
 <div class="r-margin-inner">
  <div class="r-margin-bullet"></div>
 </div>
</div>

<!-- Just to see where the right margin is -->
<div style="background-color: orange; height: 20px;"></div>

Line<br/>
Line<br/>
Line<br/>
Line<br/>
Line<br/>
Line<br/>
Line<br/>
Line<br/>

</body>
</html>
````

![bullets-in-page-margin](https://user-images.githubusercontent.com/1415728/80942239-a2895780-8e27-11ea-891b-86264e19d192.png)

Alternatively, you can use your original solution, but reduce the right page margin and increase the body right margin to compensate.

**Comment by danfickle** [comment]
Closing for now. Please reopen if required.
