### ISSUE TITLE
NPE in layout when a problem occurs decoding an embedded image

### ISSUE THREAD

**Issue by AlexisCothenet** [danfickle/openhtmltopdf#474]
Hello,

It seems that if there is an embedded image inside a html and that cannot be decoded for some reason, an NPE occurs because, then, the resource.getImage() will be null:
https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxUserAgent.java#L77
and 
https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxFastOutputDevice.java#L788

Shouldn't the image be ignored instead ?

**Comment by syjer** [comment]
@AlexisCothenet  you are right, I'll do a PR to fix them. Do you have an example so I can try to reproduce the issue on my side?

**Comment by AlexisCothenet** [comment]
Hello @syjer ,

One has to include inside a html content:
`<img src="data:image/png;base64, YOUR_BASE_64_FALSE_ENCODING>`

example:
`<img src="data:image/png base64,iVBORw0KGgoAAAANSUhEUgAAAKcAAABZCAYAAABb@zimbra">`

Thank you
Alexis
