### ISSUE TITLE
 Base 64 encoded SVG does not load in pdf

### ISSUE THREAD

**Issue by adrianrodfer** [danfickle/openhtmltopdf#484]
Hi,

I have an image with a Base 64 encoded "svg" in my html file, like this:

`<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2...">`

 I need to have the image in a pdf. But I get the following error:

```
com.openhtmltopdf.load WARNING:: Unrecognized image format for: data:image/svg+xml;base64,PD94bWwgdmV...
com.openhtmltopdf.exception WARNING:: Can't read XHTML embedded image.
```

Is there any way to insert a Base64 encoded svg?

Thanks,
Adrian

**Comment by syjer** [comment]
hi @adrianrodfer , at the moment it's not supported. But I'll provide a pull request asap.

**Comment by rekhubs** [comment]
> hi @adrianrodfer , at the moment it's not supported. But I'll provide a pull request asap.

I need this too.... Thank you!

**Comment by vasilyevia** [comment]
Hi @syjer. Is it possible to support plain text svg data like the following?
`data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="9" height="12" viewBox="0 0 9 12"><path ...`

**Comment by syjer** [comment]
hi @vasilyevia , it should not be hard, could you open a new issue as a feature request so I can track it? Thank you.

**Comment by vasilyevia** [comment]
> 
> 
> hi @vasilyevia , it should not be hard, could you open a new issue as a feature request so I can track it? Thank you.

Thanks. Created a new issue. Not sure how to mark it as a feature request.
https://github.com/danfickle/openhtmltopdf/issues/583

**Comment by Abhinandan578** [comment]
I am still facing the same issue. SAVG Images are not getting loaded. I am using docx4j-ImportXHTML (11.4.8) which is calling openhtmltopdf-core(1.0.10). Can someone please help here.

**Comment by jeong-donghee** [comment]
I resolved it by using a workaround of converting the SVG to PNG.
