### ISSUE TITLE
How do I give an image a working clickable HREF?

### ISSUE THREAD

**Issue by fancellu** [danfickle/openhtmltopdf#495]
```
<html>
    <body>

        <a href="http://google.com">
            <img src="https://www.101dogbreeds.com/wp-content/uploads/2018/08/Flat-Coat-Retriever-Pictures.jpg" width="150px"></img>
        </a>

    </body>
</html>
```
[oddlink.pdf](https://github.com/danfickle/openhtmltopdf/files/4701485/oddlink.pdf)

Doesn't work properly. The link is only clickable on lower half of image

Am using 1.0.3

Thanks

**Comment by syjer** [comment]
hi @fancellu , edit: ~~seems to be the same error as #494 :).~~ actually not.

I'll have a look, I would guess this is due to the fact  the height of the image is not specified explicitly.

edit: wrong guess on my side, looks like setting the height explicitly is not enough.

**Comment by syjer** [comment]
hi @fancellu , as a workaround, you can set `display: inline-block` on the link, like that:

```html
<html>
<body>

<a href="http://google.com" style="display:inline-block;border:1px solid blue">
    <img src="https://www.101dogbreeds.com/wp-content/uploads/2018/08/Flat-Coat-Retriever-Pictures.jpg" width="150px"></img>
</a>

</body>
</html>
```

I've added the blue border to make it more visible the difference. If you remove the display: inline-block, the link box will have the height of the line.

**Comment by fancellu** [comment]
Ok thanks. However I see some whitespace, under the image but inside the blue border

[whitespace.pdf](https://github.com/danfickle/openhtmltopdf/files/4706034/whitespace.pdf)

And if I take out the whitespace, i.e. 

`<a href="http://google.com" style="display:inline-block;border:1px solid blue"><img src="https://www.101dogbreeds.com/wp-content/uploads/2018/08/Flat-Coat-Retriever-Pictures.jpg" width="150px"></img></a>`

I then see a blue line under the image

[blueline.pdf](https://github.com/danfickle/openhtmltopdf/files/4706037/blueline.pdf)

**Comment by danfickle** [comment]
If you don't want the text decoration, you can turn off with `text-decoration: none`.

**Comment by fancellu** [comment]
Yep

```<a href="http://google.com" style="display:inline-block;text-decoration: none"><img src="https://www.101dogbreeds.com/wp-content/uploads/2018/08/Flat-Coat-Retriever-Pictures.jpg" width="150px"></img></a>```

Gives me a properly clickable image without any mystery spaces or underlines. Might be an idea to put that in the docs as I imagine many people would like this

**Comment by fancellu** [comment]
BTW, just published a little Scala project to show this in action. You might want to link to it in the docs somewhere

https://github.com/fancellu/play-openhtmltopdf

**Comment by danfickle** [comment]
I've finally created the [FAQ Tips](https://github.com/danfickle/openhtmltopdf/wiki/FAQ---Tips) page on the wiki with this tip to start with. Thanks everyone.
