### ISSUE TITLE
Error running OpenHtmlToPdf in an Azure Function in a Linux App Service plan

### ISSUE THREAD

**Issue by dfin98** [danfickle/openhtmltopdf#498]
I've got and Azure Function that uses OpenHtmlToPdf to convert HTML to PDF. It works fine locally and in a Windows App Service plan, but if I try to run it in a Linux App Service plan I get the below error.

Should this work?

Thanks.

System.ComponentModel.Win32Exception (13): Permission denied at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32&amp;amp; stdinFd, Int32&amp;amp; stdoutFd, Int32&amp;amp; stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) at OpenHtmlToPdf.HtmlToPdfConverterProcess.Convert(ConversionSource conversionSource) at OpenHtmlToPdf.Pdf.DocumentBuilder.ReadContentUsingTemporaryFile(String temporaryFilename) at GeneratePDF.GeneratePDF.Run(HttpRequestMessage req, Stream quotepdf, ILogger log) in C:\Users\David\Source\Repos\PDFTest\PdfTest.cs:line 151

**Comment by danfickle** [comment]
Sorry, wrong project. See:
https://github.com/vilppu/OpenHtmlToPdf

**Comment by SatishBoddu-MSFT** [comment]
@dfin98 Have you been able to resolve this issue ? We see the same question posted in [Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/questions/30731/index.html) , Just checking back, could you please let us know if you need further help in this matter.
