### ISSUE TITLE
Issue With Images Overflowing to Next Page

### ISSUE THREAD

**Issue by alex-plouff** [danfickle/openhtmltopdf#499]
Hi,

Our images are currently overflowing to the next page and I'm not seeing much documentation around working with images.

We have a very basic implementation - on the back end this is it

```
try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withW3cDocument(html5ParseDocument(link), baseUrl);
            builder.toStream(outputStream);
            builder.useSVGDrawer(new BatikSVGDrawer());
            builder.run();

            return Response
                        .ok(outputStream.toByteArray(), PDF_MEDIA_TYPE)
                        .header(DISPOSITION_HEADER, "attachment; filename=\"" + getPdfTitle(node) +"\"")
                        .build();

        }
```

And are using these libraries - version 1.0.2
```
    <dependency>
      <groupId>com.openhtmltopdf</groupId>
      <artifactId>openhtmltopdf-pdfbox</artifactId>
      <version>${htmlToPdfVersion}</version>
    </dependency>
```
```
    <dependency>
      <groupId>com.openhtmltopdf</groupId>
      <artifactId>openhtmltopdf-svg-support</artifactId>
      <version>${htmlToPdfVersion}</version>
    </dependency>
```
```
    <dependency>
      <groupId>com.openhtmltopdf</groupId>
      <artifactId>openhtmltopdf-java2d</artifactId>
      <version>${htmlToPdfVersion}</version>
    </dependency>
```

And in css 
```
img {
      display: block;
      page-break-inside: avoid;
      break-inside: avoid;
      height: auto;
    }
```

Are we missing some config or flag or does this need to be handled on the front end via css?

**Comment by syjer** [comment]
hi @alex-plouff , could you provide an example and describe the expected output?

Did you try to use `overflow:hidden` in the css?

**Comment by alex-plouff** [comment]
@syjer Thanks for getting back to me. 

The library doesn't seem to be detecting that there isn't enough space for the image at the bottom of the page and as a result the image runs over 2 pages. Ideally, each image would be output on the next page if the current one doesn't have room to display it. (which I'm pretty sure is how this library is supposed to work so I can't help but feel like we're doing something wrong on our end)

I've attached an image, in it you can see the image is starting at the bottom of one page and the rest is being output on the next.

I will give the overflow attribute a shot and let you know if that fixes it

<img width="935" alt="Screen Shot 2020-06-05 at 11 16 16 AM" src="https://user-images.githubusercontent.com/46270849/83899469-20d66380-a71e-11ea-948e-2cab2b7a8edb.png">

**Comment by syjer** [comment]
hi, @alex-plouff  ok, I see what you mean, then overflow: hidden is not what you need.

**Comment by syjer** [comment]
I would also think that `page-break-inside: avoid;` should do what you are expecting. I'll have a look to understand why it fail.

Could you try to set explicitly the height if it change something?

As an alternative, maybe you could also try: `-fs-page-break-min-height: ...px`, but you need to know the height of the image.

**Comment by alex-plouff** [comment]
Thanks @syjer 
I will relay this and get back to you soon!

**Comment by alex-plouff** [comment]
@syjer 
It sounds like `-fs-page-break-min-height: ...px` was exactly what we were looking for/
Thanks so much for your help!

**Comment by zhaoyongli2018** [comment]
@alex-plouff 
How did you finally solve the problem of spilling the picture onto the next page?

**Comment by alex-plouff** [comment]
@zhaoyongli2018 -fs-page-break-min-height: ...px 
is how we solved this, closing the ticket now, thanks for your help @syjer
