### ISSUE TITLE
Unable to convert ∀∃∅∇∗∝∠ ∩∪∈∉∋∧∨∼≈≅ and japanese font support.

### ISSUE THREAD

**Issue by adilxoxo** [danfickle/openhtmltopdf#500]
I have multilingual html page that has all type of special characters like ∀∃∅∇∗∝∠ ∩∪∈∉∋∧∨∼≈≅. These special characters come under mathematical operators. and are showing "#" in generated PDF.

Also need a help with japanese language font support as it also show as "#".

Can you please help.

Thanks,
Adil

**Comment by syjer** [comment]
hi @adilxoxo, if you are getting '#' characters, it mean you are not loading a font that can represent it.

See the font wiki page: https://github.com/danfickle/openhtmltopdf/wiki/Fonts .

Basically, you need to select a font that can represent the "extra" characters, register it (in the java code and on the css side) and then it should work.

**Comment by adilxoxo** [comment]
Can you please suggest which fonts are suitable to register for same...

I have tried "Arial Unicode MS" , "japanese" and "math" still got same error

Please help if you have any idea.

Thanks,
Adil

**Comment by syjer** [comment]
hi @adilxoxo , as described in the wiki page, the Noto font family is quite extensive and it has japanese fonts: https://fonts.google.com/specimen/Noto+Sans+JP?preview.text_type=custom&subset=japanese#standard-styles

For the math font, have you tried the STIX font packaged here: https://github.com/danfickle/openhtmltopdf/issues/161 ?

**Comment by adilxoxo** [comment]
Thanks for the details @syjer . I had everything at my disposal but not getting things clear. so solution is

While working with japanese and ∀∃∅∇∗∝∠ ∩∪∈∉∋∧∨∼≈≅ you need to add font family such that 

tabel{
font-family : Calibri, Arial Unicode MS, Symbol ( For math )
}

and 

also need to do 

builder.useFont() for all specified font families. 

For Calibri - Calirbi.ttf
For Japanese - Arialuni.ttf
For Math - maths.ttf

Thanks for all the information btw. @syjer
