### ISSUE TITLE
Deep HTML pages cause StackOverflow

### ISSUE THREAD

**Issue by eralmansouri** [danfickle/openhtmltopdf#503]
Hello,

I have an HTML page that is automatically generated and essentially all the styles are inline and the tags can get very nested.

The function createChildren in BoxBuilder ends up throwing a StackOverflow error. 

> 
> java.lang.StackOverflowError
> 	at com.openhtmltopdf.layout.SharedContext.getStyle(SharedContext.java:487)
> 	at com.openhtmltopdf.layout.BoxBuilder.createChildren(BoxBuilder.java:1100)
> 	at com.openhtmltopdf.layout.BoxBuilder.createChildren(BoxBuilder.java:1163)
> 	at com.openhtmltopdf.layout.BoxBuilder.createChildren(BoxBuilder.java:1163)
> 	at com.openhtmltopdf.layout.BoxBuilder.createChildren(BoxBuilder.java:1163)
> 	at com.openhtmltopdf.layout.BoxBuilder.createChildren(BoxBuilder.java:1163)
> 	at com.openhtmltopdf.layout.BoxBuilder.createChildren(BoxBuilder.java:1163)
> 

I'm not on your latest build but I can see that the function is still calling itself recursively so the issue in your latest code. It looks like the issue only happens if the style is inline, which is the case for this auto generated page. The page has many tables inside a row inside a table inside a row inside a table inside a div inside a row inside a table, etc. Unfortunately I cannot provide the actual HTML page but I hope this helps narrow down the issue.

Thanks.

**Comment by syjer** [comment]
hi @eralmansouri 

>Unfortunately I cannot provide the actual HTML

Could you provide a minimal example that reproduce the error? 

If not, could you provide the `style` used on the elements and how many elements deep it goes?

**Comment by eralmansouri** [comment]
Ok so this is a lot deeper than the one that causes an issue for me, but I'm running on a low-resources server so that might be the reason. I generated this part in Python and putting it into my HTML page causes the PDF generation to fail. 

These are the opening tags, repeated over and over, followed by a short text and then closing all of them. If putting the content in my uploaded file into an HTML page doesn't break it, just generate a deeper one. It doesn't take much on my crap server but it might take a lot more to trigger the issue for you.

``` 
<span style="display:inline;font-family: Tahoma;">
<font face="Verdana">
<span style="display:inline;font-size: 14px;">
<strong>
```

[test_question.txt](https://github.com/danfickle/openhtmltopdf/files/4799800/test_question.txt)

Thank you.

**Comment by syjer** [comment]
Ok, I see what you mean. Looking at the [code](https://github.com/danfickle/openhtmltopdf/blob/af899b4bd82608d339c368a7f948bb5de4a487aa/openhtmltopdf-core/src/main/java/com/openhtmltopdf/layout/BoxBuilder.java#L1191), removing the recursion will be quite hard if even possible without a big rewrite...

**Comment by syjer** [comment]
As a workaround, you could try to increase the stack size of the jvm, for example: `-Xss4096k`.

**Comment by eralmansouri** [comment]
Thanks that did work for me for my current application but hopefully that can be something that gets fixed some time down the road.

**Comment by danfickle** [comment]
I'm going to close this for now as unfixable. The whole boxing and layout code is based on recursion.
