### ISSUE TITLE
How to generate pdf with img?

### ISSUE THREAD

**Issue by LLazyness** [danfickle/openhtmltopdf#504]
I tried to test https://sandbox.openhtmltopdf.com/, here my code
```
<html>
<head>
<style>
/* The following fonts are installed on the server: */
.handwriting {
  font-family: 'handwriting', serif;
}
.arabic {
  font-family: 'arabic', serif;
}
.deja {
  /* Contains glyphs for many languages. */
  font-family: 'deja-sans', sans-serif;
}
.cjk {
  /* Chinese, Japanese, Korean */
  font-family: 'cjk';
}
/*
Also you can use the PDF built-in fonts: 
 - sans-serif
 - serif
 - monospace
*/
body {
  /* Fallback fonts are supported. */
  font-family: 'handwriting', 'deja-sans', 'cjk', 'arabic', sans-serif, serif;
}
</style>
</head>
<body dir="auto">

<div style="text-align:center;font-size: 90px;color:orange;">
Hello World!
</div>

<div>
<img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"></img>
</div>


</body>
</html>
```
But result is empty document

**Comment by danfickle** [comment]
The sandbox doesn't support external resources for security reasons. However, when I renew the sandbox after the next release, I'll add some local images for testing with.

**Comment by LLazyness** [comment]
I have already used code, but now the problem is my print page doesn't show any images. 
My code
```
public static void main(String[] args) throws IOException, DocumentException {
        Converter.htmlToPDF("C:\\1.html", "C:\\1.pdf", "C:\\ARIALUNI.TTF", "Arial Unicode MS");
    }

    //1 param - where to get html file, 2 - where to load pdf file, 3 - where to get font file, 4 - Font name
    public static String htmlToPDF(String inputFile, String outputFile, String fontPath, String fontName) throws IOException, DocumentException {
        try {
            final W3CDom w3cDom = new W3CDom();
            final org.w3c.dom.Document w3cDoc = w3cDom.fromJsoup(Jsoup.parse(readFile(inputFile)));
            final OutputStream outStream = new FileOutputStream(outputFile);

            final PdfRendererBuilder pdfBuilder = new PdfRendererBuilder();
            pdfBuilder.useFastMode();
            pdfBuilder.withW3cDocument(w3cDoc, "/");


            pdfBuilder.useFont(new File(fontPath), fontName);
            pdfBuilder.toStream(outStream);
            pdfBuilder.run();
            outStream.close();
            return null;

        } catch (Exception e) {
            return "PDF could not be created: " + e.getMessage();
        }
    }
```
html also in attachment
[1.html.txt](https://github.com/danfickle/openhtmltopdf/files/4799123/1.html.txt)
The problem exist when I tried to get an image from https server

versions, that I use 
![изображение](https://user-images.githubusercontent.com/25137491/85032506-99123f80-b188-11ea-9558-b93f9b664aa0.png)

**Comment by danfickle** [comment]
That is a svg image. You will have to use the batik svg plugin detailed in the wiki, but be careful about loading images from external websites.

**Comment by LLazyness** [comment]
ah, okay, understood. What about png? Do I need anything? Get an empty page when trying to print this barcode. Java code is the same.

![GenerateBarcode](https://user-images.githubusercontent.com/25137491/85034349-acbea580-b18a-11ea-8234-120acfeae830.png)
[1.html.txt](https://github.com/danfickle/openhtmltopdf/files/4799249/1.html.txt)

**Comment by danfickle** [comment]
Png images should work, although in rare cases some pngs use colour spaces that java doesn't natively support. Are you using an up to date jre of at least version 8? Older versions of the java 8 jre didn't have the necessary certificates to load let's encrypt ssl certificates. Self signed certificates will also be rejected.

**Comment by LLazyness** [comment]
Thank you for your support, the problem is processed. Adding a server ssl certificate to java cacerts helps.
