### ISSUE TITLE
PDAnnotationFileAttachment support

### ISSUE THREAD

**Issue by lindamarieb** [danfickle/openhtmltopdf#508]
Is there any way to indicate that an anchor is a link to an attached file?

I can add annotations manually in my Java code to the attachment using PDAnnotationFileAttachment but I need to place the links in my html.

**Comment by syjer** [comment]
Hi @lindamarieb , as far as I know, currently there is no support for this feature, unfortunately.

I'll have a look and try to provide a pull request.

**Comment by syjer** [comment]
I did a first prototype, it's a little bit viewer dependent:

(note: I've been able to hide the icon in Evince, sumatrapdf and Adobe reader)

 - embedded pdf viewer from chrome and mac os: does not work, you see the text ("test") but it does nothing on click
 - evince (pdf viewer from gnome, linux), it works, but as you can see the text is hidden by the icon: 
  ![Screenshot from 2020-07-08 14-53-15](https://user-images.githubusercontent.com/498146/86921196-06cbde80-c12b-11ea-8e1b-36fca76c8805.png)
 - embedded viewer in edge/ie (windows):
   ![Capture_png](https://user-images.githubusercontent.com/498146/86921267-2400ad00-c12b-11ea-9749-9b08424fe6e7.PNG)
 - sumatrapdf (windows):
   ![Capture2_png](https://user-images.githubusercontent.com/498146/86921349-48f52000-c12b-11ea-8a20-531b3bc05106.PNG)
 - adobe:
   <img width="406" alt="Capture_3" src="https://user-images.githubusercontent.com/498146/86921668-c6b92b80-c12b-11ea-8da1-1ad2517a6eca.png"> 


It does not seems possible to hide the icon as far as I know. It's a little bit ugly unfortunately.

**Comment by syjer** [comment]
code: https://github.com/syjer/openhtmltopdf/commit/cdb50764827c1001a22354ef72a933a528066589

example of input file:

```
<html>
<head>
<style>
</style>
</head>
<body>
<a href="https://user-images.githubusercontent.com/498146/86921196-06cbde80-c12b-11ea-8e1b-36fca76c8805.png" data-embed-file="true" data-content-type="application/octet-stream">Test</a>
</body>
</html>
```

the presence of `"data-embed-file"` attribute on a `a` element, will trigger the download of the linked resource (could be a local file, or a custom protocol).

**Comment by syjer** [comment]
note: I've been able to find a way to generally hide the icon. Only the embedded viewer from ie/edge persist to show it.

**Comment by lindamarieb** [comment]
Thanks for the fast response and work on my request @syjer  and @danfickle !!

The files I need to attach to my pdf are stored encrypted on AWS S3; they do not have public access. I will need to download them first in order for openhtmltopdf to have access to them for embedding.

I have some questions regarding this:
1. Will the  file:// protocol work in the download attribute for attaching the local files?
2. What is difference between embedding and attaching? 
3. Will the "embedded" files show up in the attachments panel of the pdf?

**Comment by syjer** [comment]
hi @lindamarieb : 

1. yes any supported protocol will work. In your case, you could even have a "custom" protocol that will fetch from S3, decrypt and return an InputStream so you don't even need to interact with the file system. (see the `useProtocolsStreamImplementation` https://github.com/danfickle/openhtmltopdf/blob/e44fb8646590b613d1b6d31341ecf81299b46650/openhtmltopdf-core/src/main/java/com/openhtmltopdf/outputdevice/helper/BaseRendererBuilder.java#L178 )
2., 3.no idea :), I'll check and let you know if they appear in the attachments panel (I didn't know about that feature)

**Comment by danfickle** [comment]
Support now merged into main branch.

[File embed documentation](https://github.com/danfickle/openhtmltopdf/pull/640#issuecomment-770819471).

**Comment by lindamarieb** [comment]
Thank you so much guys! I have not had time to test this, but will do in the near future :-)
