### ISSUE TITLE
Add OSGI bundle metadata to MANIFEST.MFs

### ISSUE THREAD

**Issue by zspitzer** [danfickle/openhtmltopdf#510]
Can you add in the OSGI metadata to the build process?

**Comment by syjer** [comment]
hi @zspitzer , what should we add exactly as I'm not really knowledgeable about the OSGI world :). Do you have any doc that could help us?

**Comment by zspitzer** [comment]
See https://github.com/srikanth-lingala/zip4j/issues/89

**Comment by zspitzer** [comment]
Here's an example from Lucee which uses OSGI,  which I'm advocating upgrading to openhtmltopdf https://luceeserver.atlassian.net/browse/LDEV-2968 

It currently still uses FS, which also doesn't include OSGI bundles metadata, so it has to re-wrap 

https://github.com/lucee/osgi-bundle-flyingSaucerPDF/blob/master/pom.xml
