### ISSUE TITLE
page margin content encoding

### ISSUE THREAD

**Issue by pawelalikowski** [danfickle/openhtmltopdf#511]
![Zaznaczenie_031](https://user-images.githubusercontent.com/6155457/87163451-a920c900-c2c7-11ea-815e-6b3e678a38ad.png)

polish characters in page margin content are displayed as hash (#)

**Comment by danfickle** [comment]
That example uses the PDF built in fonts which are limited. See fonts Wiki page for more. You could set the `font-family` to `deja-sans` which is installed on the server and has better coverage.

**Comment by pawelalikowski** [comment]
my mistake, thank you very much for help, closing issue
