### ISSUE TITLE
inline CSS

### ISSUE THREAD

**Issue by shubham-467** [danfickle/openhtmltopdf#513]
Hi,

iam facing warnings while generating html to pdf

"com.openhtmltopdf.css-parse WARNING:: (file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration_out.html) Value for left must be an identifier, length, or percentage at line 1. Skipping declaration."

does it supports inline css

**Comment by syjer** [comment]
hi @shubham-467 , yes openhtmltopdf support inline css. But it does not support _all_ the css :).

Could you provide the problematic inline css so we can check if it's the case ?

**Comment by shubham-467** [comment]
Hi,

thanks for replying,

IMPORT:- import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
CODE:-
         OutputStream os = new
FileOutputStream("C:\\Users\\appadmin\\git\\SoharPDF\\template\\sample2.pdf");
         PdfRendererBuilder builder = new PdfRendererBuilder();
         builder.useFastMode();

 builder.withUri("file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration.html");
         builder.toStream(os);
         builder.run();


below i attached HTML snippets which consists of inline CSS and PDF output
also.

Thanks,
Goswamy Subham Giri.

**Comment by shubham-467** [comment]
console log is pic attached below.

Thanks

**Comment by syjer** [comment]
hi, @shubham-467  there are no attached files. I don't think github allow to display them when replying via email.

You must copy paste the html/css code.

**Comment by shubham-467** [comment]
ok

HTML CODE:-

<div class="pos" id="_100:170" style="top:170;left:100">
<span id="_15.9" style=" font-family:Times New Roman; font-size:15.9px;
color:#000000">
In accordance with the definition provided below by Article 36 of Combating
Money Laundering </span>
</div>
<div class="pos" id="_100:191" style="top:191;left:100">
<span id="_15.9" style=" font-family:Times New Roman; font-size:15.9px;
color:#000000">
and Terrorism Finance Law promulgated in Royal Degree (30/2016)
(&#147;<span style="font-weight:bold; font-family:Arial"> the law</span>
&#148;), please confirm </span>
</div>
<div class="pos" id="_99:211" style="top:211;left:99">
<span id="_15.3" style=" font-family:Times New Roman; font-size:15.3px;
color:#000000">
whether yourself, or any of your family members are in close association of
PEP. </span>
</div>


PDF:-

[image: pdf.PNG]

CONSOLE LOGS:-

com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser):
com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser):
com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: Loaded document in ~24ms
com.openhtmltopdf.load INFO:: TIME: parse stylesheets  66ms
com.openhtmltopdf.match INFO:: media = print
com.openhtmltopdf.match INFO:: Matcher created with 161 selectors
com.openhtmltopdf.css-parse WARNING::
(file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration.html)
Value for top must be an identifier, length, or percentage at line 1.
Skipping declaration.
com.openhtmltopdf.css-parse WARNING::
(file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration.html)
Value for left must be an identifier, length, or percentage at line 1.
Skipping declaration.
com.openhtmltopdf.css-parse WARNING::
(file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration.html)
Value for top must be an identifier, length, or percentage at line 1.
Skipping declaration.
com.openhtmltopdf.css-parse WARNING::
(file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration.html)
Value for left must be an identifier, length, or percentage at line 1.
Skipping declaration.
com.openhtmltopdf.css-parse WARNING::
(file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration.html)
Value for top must be an identifier, length, or percentage at line 1.
Skipping declaration.
com.openhtmltopdf.css-parse WARNING::
(file:///C:/Users/appadmin/git/SoharPDF/template/selfDeclaration.html)
Value for left must be an identifier, length, or percentage at line 1.
Skipping declaration.
.
.
.

Thanks

**Comment by danfickle** [comment]
`top:211;left:99`

You need to use units, probably `px`. This project is generally less forgiving of invalid css compared to browsers.

**Comment by shubham-467** [comment]
Hi Danfickle,

Thanks alot for helping me. But started facing a few other issues.

Html Input:-
[image: page2.PNG]

PDF Output:-
Iam facing WIDTH issue of o/p pdf on every other form.


[image: pdf1.PNG]

Thanks & Regards
Goswamy Subham Giri.

**Comment by syjer** [comment]
hi @shubham-467 , the images are not visible. You must modify your message from the github web interface if you want to attach them.

**Comment by shubham-467** [comment]
Html Input:-
![page2](https://user-images.githubusercontent.com/60915835/87679027-4c2a8480-c799-11ea-9763-8964592f34ea.PNG)

PDF Output:-
Iam facing WIDTH issue of o/p pdf on every other form.


![pdf1](https://user-images.githubusercontent.com/60915835/87679060-58aedd00-c799-11ea-808c-ec45b29df405.PNG)

**Comment by syjer** [comment]
hi @shubham-467

about the width issue: you should not expect to have a 100% exact output from what you see in your browser of choice. So you will need to modify your html/css. In this specific case, it seems to be cut by the margin of the page?

about the missing font on the right: you must add them, see the wiki page:  https://github.com/danfickle/openhtmltopdf/wiki/Fonts

**Comment by shubham-467** [comment]
Hi,

i used font NotoNaskhArabic-Regular.tiff for this ARABIC مشترك/شخصي حساب فتح طلب(Shared / personal account opening request) and pdf O/P is  بلط حتف باسح يصخش / كرتشم(Tuft Bastah Bashah rustles / Krchem) which is completely different . so which font should i use correctly.

HTML CODE:-
`@font-face {
  font-family: 'noto';
  /* Note: No trailing format tag is allowed. */
  src: url(font/NotoNaskhArabic-Regular.ttf);
  font-weight: normal;
  font-style: normal;	
}`
PRESENT HTML LINE:-
`  <div class="p" id="p12" style="top:242.56401pt;left:111.8445pt;line-height:34.632004pt;font-family:noto;font-size:26.0pt;font-weight:bold;width:83.90202pt;">مشترك</div>
            `
PREVIOUS HTML LINE:-
`<div class="p" id="p12" style="top:242.56401pt;left:111.8445pt;line-height:34.632004pt;font-family:WLOYRJ+GESSTextBold-Bold;font-size:26.0pt;font-weight:bold;width:83.90202pt;">مشترك</div>
            `

JAVA CODE:-
`	OutputStream os = new FileOutputStream(temp_path + op_file);
	PdfRendererBuilder builder = new PdfRendererBuilder();
        builder.useFastMode();
        builder.defaultTextDirection(TextDirection.RTL);
        builder.withUri("file:///"+temp_path+src_name);
        builder.toStream(os);  
        builder.run();`


Please Help.

**Comment by syjer** [comment]
hi @shubham-467 ,  I'm not versed in arabic scripts, but if it's an issue of text shaping, you need to use the ICU support as described in the wiki: https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide#support-for-bi-directional-rtl-and-shaped-text .

You will need to import:

```
<dependency>
  		<!-- Optional, leave out if you do not need right-to-left or bi-directional text support. -->
  		<groupId>com.openhtmltopdf</groupId>
  		<artifactId>openhtmltopdf-rtl-support</artifactId>
  		<version>${openhtml.version}</version>
  	</dependency>
```

If it's a font problem, then you must select another one, like maybe https://www.google.com/get/noto/#sans-arab ?

**Comment by shubham-467** [comment]
Hi,



> hi @shubham-467
> 
> about the width issue: you should not expect to have a 100% exact output from what you see in your browser of choice. So you will need to modify your html/css. In this specific case, it seems to be cut by the margin of the page?
> 
> about the missing font on the right: you must add them, see the wiki page: https://github.com/danfickle/openhtmltopdf/wiki/Fonts

I tried aligning HTML,CSS but the content is huge in HTML file which will take alot of time.

Is there is any possibility of reducing default margins of generated PDF.Please help
HTML FILE:-
![actualHTMLFile](https://user-images.githubusercontent.com/60915835/87873797-08768b80-c9e2-11ea-98d8-cb721a40a1d2.PNG)

PDF File:-

![InkedgeneratedPDF_LI](https://user-images.githubusercontent.com/60915835/87873751-91d98e00-c9e1-11ea-88e1-bf93b998a974.jpg)

**Comment by danfickle** [comment]
You can use a `@page` rule in your css. You can also set the page size if you wish.

````css
@page {
  size: 10cm 20cm;
  margin: 20px 5px;
}

````

**Comment by danfickle** [comment]
Assume solved. Please reopen as required.
