### ISSUE TITLE
Adobe Reader promts for saving

### ISSUE THREAD

**Issue by aleksandr-m** [danfickle/openhtmltopdf#52]
Trying to close generated PDF in Adobe Reader gives `Do you want to save changes to 'some.pdf' before closing?` dialog.
Tested with rc7 and rc8. Worked fine with rc4.

Found [this post](http://stackoverflow.com/q/19033261/1700321).

**Comment by danfickle** [comment]
The post you link to suggests this could be a malformed PDF. Does the HTML include forms?

**Comment by aleksandr-m** [comment]
Nope. Simple `<div>hello</div>` yields same result.

**Comment by danfickle** [comment]
So it is related to forms. I have stopped the code from outputting an acroform in the case where the document contains no forms. However, I'm not sure it should be asking when the document contains an unchanged form, so I'll leave this issue open until I have investigated further.

**Comment by aleksandr-m** [comment]
@danfickle Well, original issue is fixed in RC9. Thanks.

**Comment by danfickle** [comment]
Closing now. Please reopen if required.

**Comment by coolblades** [comment]
Hi
Tried the simple html form

<html lang="en">
	<head>
		<style>
		</style>
	</head>
	<body>

                                <form action="http://localhost/form.php" method="POST">
                                    <input type='checkbox' name='aa' value='1'/>
                                    <input type='checkbox' name='aa' value='2'/>
                                </form>

	</body>
</html>

and when I generate the pdf from the it, and open it in Adobe Acrobat and try to close it without click on anything, it prompts me to save changes.
