### ISSUE TITLE
Issue with the table when trying to convert HTML to PDF

### ISSUE THREAD

**Issue by godha-s** [danfickle/openhtmltopdf#520]
I'm trying to convert the html string taken from an HTML file and converting through the provided examples.
But getting the alignment issues when the tables are present in the HTML.
I'm attaching both HTML and converted PDF before.
[0d7c92c9-f22e-418a-95f9-4447ca3469db.pdf](https://github.com/danfickle/openhtmltopdf/files/5000233/0d7c92c9-f22e-418a-95f9-4447ca3469db.pdf)

Attaching the html content below in a text File
[html Content.txt](https://github.com/danfickle/openhtmltopdf/files/5000251/html.Content.txt)

**Comment by danfickle** [comment]
Hi @shanmuka-chowdary,

The fips information in that html has been formatted with columns and not a table. I'd strongly recommend converting it to a HTML table as it is tabular data.

**Comment by godha-s** [comment]
Thanks @danfickle  I'll try to check that and get back to you.
Basically our use case is- we are trying to convert the below(docx) document into HTML and then we are editing the HTML in our editor and saving as PDF. That's the reason the html is formatted with the columns .
[996a.docx](https://github.com/danfickle/openhtmltopdf/files/5000650/996a.docx)
