### ISSUE TITLE
Issue While dealing with HTML

### ISSUE THREAD

**Issue by java-Selva** [danfickle/openhtmltopdf#522]
Hi! 
   I am facing issue while append the table rows, It added twice by mistakenly.

Java Code for append

`			for (int i = 0; i < csri_tax_dao.getCsr_table_residence_list().size(); i++) {
				CRS_Table_Residence__DAO temp_tble_res = csri_tax_dao.getCsr_table_residence_list().get(i);
				table_residence.appendElement("<tr><td>" + temp_tble_res.getCountry() + "<td>"
						+ temp_tble_res.getTin() + "<td>" + temp_tble_res.getReason() + "</td>");
			}`

Json input 
` "csr_table_residence_list": [
        {
            "country": "India",
            "tin": "124532",
            "reason": "A"
        },
        {
            "country": "US",
            "tin": "9444414",
            "reason": "B"
        },
        {
            "country": "India",
            "tin": "93254",
            "reason": "C"
        }
    ],`

Output
![image](https://user-images.githubusercontent.com/4180051/89112833-7614c400-d486-11ea-9b22-6038dba41280.png)

**Comment by syjer** [comment]
hi @java-Selva , most likely you have some problem in your html.

For example, in your for loop, you are not closing the <td> tags correctly.

```java
 table_residence.appendElement("<tr><td>" + temp_tble_res.getCountry() + "<td>" + temp_tble_res.getTin() + "<td>" + temp_tble_res.getReason() + "</td>")
```
your are not closing the `td` after the `temp_tble_res.getCountry()` and ` temp_tble_res.getTin()`.

Additionally, you are not closing the `tr`

**Comment by danfickle** [comment]
Assumed solved, though you should also remember to escape text content. Please reopen this issue as required.

**Comment by java-Selva** [comment]
> Assumed solved, though you should also remember to escape text content. Please reopen this issue as required.

Hi Denfickle!   Thanks for your reply. Yes we did fix the issue.
