### ISSUE TITLE
useless schemas/dtd in openhtmltopdf-core/src/main/resources/resources  ?

### ISSUE THREAD

**Issue by syjer** [danfickle/openhtmltopdf#523]
Hi @danfickle , I've noticed in `openhtmltopdf-core/src/main/resources/resources` we have some dtd/schema that are not referenced in the project:

 - `openhtmltopdf-core/src/main/resources/resources/schema/docbook/`
 - `openhtmltopdf-core/src/main/resources/resources/schema/html-4.01/`
 - `openhtmltopdf-core/src/main/resources/resources/schema/xhtml/`

Do they have any use? Removing them does not seems to cause any issue in the build/tests.

**Comment by danfickle** [comment]
Yes, I think they are ancient cruft that could be removed.

**Comment by syjer** [comment]
I'll provide a PR then :).
