### ISSUE TITLE
using withHtmlContent method result #### in Arabic

### ISSUE THREAD

**Issue by yalmuhaidib** [danfickle/openhtmltopdf#53]
I'm using thymeleaf to process the HTML page that would be then passed to openhtmltopdf to generate a PDF with Arabic content.
the issue if I'm trying to generate using
`withHtmlContent(String html, String baseUri)`
then:

- the PDF will have `####` for any Arabic Content. 
- what is `baseUri` and how I should set it?
- if I just pass the HTML page location using `withUri(String uri)`,  Arabic is rendered, the issue with this is I need to process the HTML to be dynamic "generate a purchase order"

check below sample code:
```
public void generateOpenPDF() throws Exception {
    String htmlContent = "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/><style>@font-face{font-family: noto; src: url('NotoNaskhArabic-Regular.ttf');}body, body *{font-family: 'noto', sans-serif;}</style></head><body><div class=\"border\"><h1>عربي</h1></div></body></html>";

   ByteArrayOutputStream os = new ByteArrayOutputStream();
   PdfRendererBuilder builder = new PdfRendererBuilder();
   builder.useUnicodeBidiSplitter(new ICUBidiSplitter.ICUBidiSplitterFactory());
   builder.useUnicodeBidiReorderer(new ICUBidiReorderer());
   builder.defaultTextDirection(TextDirection.RTL); // OR RTL
	    
   builder.withHtmlContent(htmlContent, "/tmp");
        
   builder.toStream(os);
   builder.run();
   byte[] pdfAsBytes = os.toByteArray();
   os.close();
   Path file = Paths.get("/tmp/the-file-name.pdf");
   Files.write(file, pdfAsBytes);
}
```

**Comment by danfickle** [comment]
Hi @yalmuhaidib 
Sorry for the late reply. You use a relative link to the font in the HTML, so you need a base URL to resolve relative URLs. Try using a ````file://```` URL.
````java
builder.withHtmlContent(htmlContent, "file:///absolute/path/to/font/dummy.html");
````

**Comment by JimTheod** [comment]
hi!

Same problem with greeks  i can not understand the content of the dummy.html
Any example would be usefull.
When i use the  **builder.withUri(url);** and in the html there is the reference to the font works fine.
I can not do to work with  **builder.withHtmlContent(htmlContent...**

thanx

**Comment by JimTheod** [comment]
Solved!
One solution is to add  
```
<style>
@font-face {
    font-family: 'cjk';
    src: url('file:///d:/deleme/java/webServices/WebServicesTools/resources/Calibri.ttf');
}

body
{
font-family:cjk;
}
</style>
```
inside htmldata and leave the second arg of withHtmlContent ""

**Comment by danfickle** [comment]
Hi @JimTheod 
Yes, using complete paths is one solution. However, you should be able to use relative paths. The ````dummy.html```` doesn't actually have to exist. It's the path to your relative resources that is important. Sorry for the confusion. So in your case:
````html
<style>
@font-face {
    font-family: 'cjk';
    src: url('Calibri.ttf');
}

body
{
font-family:cjk;
}
</style>
````
and
````java
builder.withHtmlContent(htmlContent, "file:///file:///d:/deleme/java/webServices/WebServicesTools/resources/dummy.htm");
````
I've tested this, but on a mac, maybe it is not working in Windows?

**Comment by JimTheod** [comment]
Thanx for quiq reply!

Yes you are right if i use

```
<style>
@font-face {
    font-family: 'cjk';
    src: url('Calibri.ttf');
}

body
{
font-family:cjk;
}
</style>
```

and then set _**only**_ the path works fine

`builder.withHtmlContent(htmlContent, "file:///file:///d:/deleme/java/webServices/WebServicesTools/resources/"); `

**Comment by ieugen** [comment]
@danfickle , @JimTheod : This seems to be solved. No reason to keep the issue open.

**Comment by CristinaBo85** [comment]
Hi I met the same issue that Arabic result in ####:
Here is how I used it:
HTML code:
```
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <style type="text/css">
        @font-face {
            font-family: 'Bismillahscript';
            src: url("fonts/Bismillahscript-4ByyY.ttf");
        }
        .agreement-content {
            font-family: 'Bismillahscript';
        }
    </style>
</head>
<body>
    <div class="agreement-content">
        هذا هو اختبار المحتوى العربي مع English بداخله
    </div>
</body>
</html>
```
And JAVA code:
```
private void htmlToPdf(org.w3c.dom.Document doc, String outputPdfPath) throws IOException {
		String baseUri = "file:/Users/cristina/workspace/projects/git/myproject/src/main/resources/";
		ByteArrayOutputStream os = new ByteArrayOutputStream();

		PdfRendererBuilder builder = new PdfRendererBuilder();
		builder.useFastMode();
		builder.withW3cDocument(doc, baseUri);
		builder.toStream(os);
		builder.run();

		byte[] pdfAsBytes = os.toByteArray();
		os.close();
		Path file = Paths.get(outputPdfPath);
		Files.write(file, pdfAsBytes);
		System.out.println("PDF creation completed");
		os.close();
	}
```
I got follow log so the font should load ok, but it's not working.

<img width="714" alt="Screen Shot 2022-06-16 at 22 53 55" src="https://user-images.githubusercontent.com/93360897/174098369-2dbf993e-49d7-4487-a553-c851bf1f21c7.png">

And I am using openhtmltopdf:1.0.6. Could you please help to take a look? Thanks!
