### ISSUE TITLE
Entity value map to html input? 

### ISSUE THREAD

**Issue by alanvsalan95** [danfickle/openhtmltopdf#530]
I need to generate a banking receipt in pdf. May I know how to set the banking information values from my model entity object to the html text boxes? Anyone can help?

**Comment by alanvsalan95** [comment]
@danfickle

**Comment by syjer** [comment]
hi @alanvsalan95 , you use a template engine(for example https://github.com/samskivert/jmustache)  for generating the html that you then pass to this library.

**Comment by danfickle** [comment]
There are many Java templating libraries. Another good one is Thymeleaf.

**Comment by alanvsalan95** [comment]
Thanks all!!
