### ISSUE TITLE
Can the corresponding label be added to support the resolution of QR code and barcode

### ISSUE THREAD

**Issue by pipti** [danfickle/openhtmltopdf#532]
Can the corresponding label be added to support the resolution of QR code and barcode
thank you

**Comment by syjer** [comment]
hi  @pipti , could you explain what is the issue? Give an example of what is wrong and what would be the expected result?

**Comment by pipti** [comment]
for example  \<div etype='barcode' value='1234563' format='CODE_39'/\> ,Pdf shows the corresponding bar code
Barcode and QR code may be used to identify some contract templates
thank you

**Comment by syjer** [comment]
ok I see what you mean, it can be implemented in a transparent way by registering a custom Object drawer: https://javadoc.io/doc/com.openhtmltopdf/openhtmltopdf-core/latest/com/openhtmltopdf/outputdevice/helper/BaseRendererBuilder.html#useObjectDrawerFactory(com.openhtmltopdf.extend.FSObjectDrawerFactory)

See the https://github.com/danfickle/openhtmltopdf/tree/open-dev-v1/openhtmltopdf-objects subproject that implement the jfreechart integration (see wiki page for use https://github.com/danfickle/openhtmltopdf/wiki/Plugins:-JFreeChart )

**Comment by syjer** [comment]
For your information, I've created a pull request that integrate zxing. See #533 .

You can copy the code of the `ZXingObjectDrawer.java` if you don't want to wait :).

**Comment by pipti** [comment]
Thank you very much
