### ISSUE TITLE
Can the parsed style of HTML fragment be embedded in the specified position of PDF.

### ISSUE THREAD

**Issue by pipti** [danfickle/openhtmltopdf#534]
Can the parsed style of HTML fragment be embedded in the specified position of PDF.
for example
html fragment
\<div style="color:red"\>insert text to pdf \</div\>
file :a.pdf

the red font “insert text to pdf” insert into the first page(It can be any page) of the a.pdf and the position is x=100 y=100

**Comment by syjer** [comment]
you can use the css: "position: absolute;top:100px;left:100px".

You can try it by copy/pasting:

```html
<html>
<body>
<div style="color:red;position:absolute;top:100px;left:100px">insert text to pdf </div>
</body>
</html>
```

in the sandbox:

https://sandbox.openhtmltopdf.com/

**Comment by danfickle** [comment]
You can use `position:absolute; top: 100px; left: 100px;` for example. Is that what you mean? See above.

**Comment by pipti** [comment]
What I mean is to insert the styled content presented by HTML fragment into an existing PDF

**Comment by danfickle** [comment]
You could perhaps generate a PDF with this library and then merge it with another using PDFBOX. But not out of the box.

**Comment by pipti** [comment]
I found itext had the method :
--------------------------------------
ByteArrayOutputStream pageNumPdfOs = generatePdfStream(childDoc.html(),null);
PdfReader pageNumReader = new PdfReader(pageNumPdfOs.toByteArray());

PdfImportedPage impPage = content.getPdfWriter().getImportedPage(pageNumReader, 1);

Image image = Image.getInstance(impPage);
image.setAbsolutePosition(pos.getX(), pos.getY()*-1);
                                                    
content.addImage(image);
pageNumPdfOs.flush();
pageNumPdfOs.close();
---------------------------------------
but pdfbox didn't find it

If you understand the relevant method, help to answer it, thank you very much

**Comment by danfickle** [comment]
We do have something like that where you can use another PDF as a background. See [this comment](https://github.com/danfickle/openhtmltopdf/issues/472#issuecomment-628836723).
