### ISSUE TITLE
about  column-count style

### ISSUE THREAD

**Issue by pipti** [danfickle/openhtmltopdf#535]
Can column layout styles be supported
for example：
\<div  style="column-count: 3;column-width: 233px;column-height: 930px;font-size: 10px;width:100%;column-gap:10px;margin-top:20px;"\>

thank you！

**Comment by danfickle** [comment]
I don't think `column-height` is supported. The rest should work. Why not try and see?

**Comment by danfickle** [comment]
OK, closing now. Please re-open as required.
