### ISSUE TITLE
PDF is generated in new session -> how can I use my current session / and user?

### ISSUE THREAD

**Issue by rider87** [danfickle/openhtmltopdf#537]
Hi all,

I´m using OpenHtml2PDF in combination with JSF. It´s a very great lib, but I have currently one big problem.

Please find below my code:
`
private org.primefaces.model.DefaultStreamedContent pdfFile;

/**
	 * Create PDF
	 */
	public void createPDFDialog(DocumentDesigner documentDesigner) {
		LOGGER.info("START createPDFDialog");

		try {

			String url = "http://myapp.com/page"
			pdfFile = null;

			PipedOutputStream os = new PipedOutputStream();
			PipedInputStream is = new PipedInputStream(os);

			managedExecutorService.submit(() -> {

				try {
					PdfRendererBuilder builder = new PdfRendererBuilder();
					XRLog.setLevel(XRLog.CSS_PARSE, Level.SEVERE);
					XRLog.setLoggingEnabled(false);

					Document doc = html5ParseDocument(url, 0);
					builder.withW3cDocument(doc, url);

					builder.toStream(os);

					builder.run();
					os.close();

				} catch (IOException e) {
					LOGGER.error(ExceptionUtils.getFullStackTrace(e));
				}
			});

			pdfFile = new DefaultStreamedContent(is, "application/pdf");

		}

		catch (XRRuntimeException e) {
			LOGGER.error(ExceptionUtils.getFullStackTrace(e));
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Etwas stimmt mit der Designspezifikation nicht!", ""));
		} catch (Exception e) {
			LOGGER.error(ExceptionUtils.getFullStackTrace(e));
			ErrorMessage.showErrorMessage();
		}

		LOGGER.info("END createPDFDialog");
		return;
	}

	/**
	 * Parsen um valides XML zu bekommen
	 * 
	 * @param urlStr
	 * @param timeoutMs
	 * @return
	 * @throws IOException
	 */
	public Document html5ParseDocument(String urlStr, int timeoutMs) throws IOException {
		
		URL url = new URL(urlStr);
		org.jsoup.nodes.Document doc;

		doc = Jsoup.parse(url, timeoutMs);
		
		// Should reuse W3CDom instance if converting multiple documents.
		return new W3CDom().fromJsoup(doc);
	}`

My problem is now: during this code:

**Problem 1**
doc = Jsoup.parse(url, timeoutMs); (in html5ParseDocument) my Application Server (Wildfly) is generated a new session in the background, but before I´m storing a object, which I need to use during rendering time at my function, which generated the HTML code.
But due the fact I will get a new session, this object is empty and not stored anymore.

**Problem2**
Due to the fact it´s rendering in a new session, my HTML page must be inside a public directory, because it will not use the current login user (because new session).

How can I solve this to use during rendering time the same session, so I can use also the object which I filled before I render the PDF?

Any ideas?

**Comment by syjer** [comment]
I would guess it would be better to ask a jsf forum, as it seems more a "jsf lifecycle" problem than related to openhtmltopdf.

Note: I know nothing about jsf, but, I find the `managedExecutorService.submit` a little bit strange, as it seems you are submitting in a new thread the generation of the pdf. I would expect to be done in the same one of the request of the user.

**Comment by zspitzer** [comment]
http session are cookie based, so wouldn't the solution be to allow passing in a collection of hostnames with cookies,
so that any http calls can re-use the existing session(s) by passing in the cookies?

**Comment by danfickle** [comment]
Generally I setup the template engine separately rather than trying to load a URL. However, this is well outside the scope of this library.
