### ISSUE TITLE
External font not working

### ISSUE THREAD

**Issue by cloooze** [danfickle/openhtmltopdf#541]
I know there are plenty of questions about this topic out there but really I couldn't get things working.

I'm trying to programatically use an external  font, but without success.

I get no errors in the logs, the pdf is succesfully generated, but with the standard font Times New Roman

    builder.useFastMode();
    builder.withHtmlContent(html, null);
    builder.useFont(new File("src/main/resources/fonts/Roboto-Light.ttf"), "roboto");
    builder.toStream(os);
    builder.run();

Question 1: should I then use my new font in the template? somewhere in the style tag?

Question 2: is there a way to use the standard Arial font without using an external font file? Arial would be ok as alternative.

Thanks a lot!

**Comment by syjer** [comment]
hi @cloooze , could you show us the html too ? :)

When you `useFont` the "roboto" font on  the java side, you will need to declare it in the css too, like the following fonts:  'handwriting', 'deja-sans', 'cjk', 'arabic' in the sandbox (https://sandbox.openhtmltopdf.com/) .

So you will need at least:

```html
<style>
body {
 font-family: 'roboto'
}
</style>
```

From the java side, it should be correct.

Out of the box, you have the following fonts:

 - sans-serif
 - serif
 - monospace

So sans-serif would be the one more similar to Arial, but please note that embedding the font is generally a good idea, especially if your  pdf will have  non western alphabets.

**Comment by cloooze** [comment]
Hi @syjer 
thank you for your answer, I've got it working, I was putting the font file in a wrong path! shame on me :(

You can delete the post.

Regards
