### ISSUE TITLE
[Java2DRendererBuilder] text-align is not working properly with foreign languages

### ISSUE THREAD

**Issue by saisuryakat** [danfickle/openhtmltopdf#545]
I'm using the library for generating image with HTML content, this is the code I'm using 
```java
var outputStream = new ByteArrayOutputStream();

var java2DRendererBuilder = new Java2DRendererBuilder();

Graphics2D layoutGraphics = processor.createLayoutGraphics();
java2DRendererBuilder.withHtmlContent(htmlString, BASE_PATH_FOR_RESOURCE_RESOLUTION)
    .useLayoutGraphics(layoutGraphics)
    .useFastMode()
    .toPageProcessor(processor)
    .runPaged();
layoutGraphics.dispose();

return outputStream.toByteArray();
```
Everything works fine except the text-align on <td> elements which has foreign text, if English text is used, width calculation is done correctly, but if foreign text(Thai in my scenario) width is not properly calculated resulting in broken UI

![image](https://user-images.githubusercontent.com/62474785/91943942-8c34cf00-ed27-11ea-970a-5459b43d74e0.png)

I've declared the Thai font in css file(included with link in HTML), and tried using it with `.useFont(File, Font-Family)` but it still doesn't work

Could you please suggest how to solve the issue

**Comment by danfickle** [comment]
Hi @saisuryakat,

I think what is happening may be that the Java2d api is doing its own layout and so we get a problem of double layout. I think what we need to do is use the api differently so it doesn't do layout.

Do you have minimal HTML and a link to the font so I can debug this issue?

**Comment by saisuryakat** [comment]
@danfickle I found the issue, problem was with my code itself, I forgot to specify fallback font in the css class with which I'm applying the `text-align: right`

I found the info from other issues, where it was said that special characters and foreign languages width is calculated from the font file, I just found the code for that in `com.openhtmltopdf.java2d.Java2DTextRenderer.getWidth()` and figured it out while debugging that the thai text **บาท** was always getting 0 width and then I went to check my css file and found the root cause. **But it was tricky because text is displayed so I could never think that the issue is with the font**.

Is it possible to get these problems highlighted better by logging or another way?
 
**html**
```html
<body>
  <table>
    <tr>
      //some content before
    </tr>
    <tr class="space-divider">
    </tr>
    <tr>
      <td class="label">จำนวนเงิน</td>
      <td class="value">1000.0 baht</td>
    </tr>
    <tr>
      <td class="label">ค่าธรรมเนียม</td>
      <td class="value">50.0 baht</td>
    </tr>
    <tr>
      <td class="label">รวมทั้งสิ้น</td>
      <td class="value">1050.0 บาท</td>
    </tr>
  </table>
</body>
```
**css**
Thonburi Font as requested https://github.com/potyt/fonts/blob/master/macfonts/Thonburi/ThonburiBold.ttf
Before:
```css
table .value {
  text-align: right;
  font-family: SanFrancisco;
}
```

Now:
```css
table .value {
  text-align: right;
  font-family: SanFrancisco, Thonburi;
}
```
