### ISSUE TITLE
How to use a  font metrics to cache fonts?

### ISSUE THREAD

**Issue by mndzielski** [danfickle/openhtmltopdf#548]
Hi,

I've some fonts that I use in my project. I create PdfRendererBuilder each time, my java code:

```    

private FSCacheEx<String, FSCacheValue> fsCacheEx = new FSDefaultCacheStore();

private void generatePdf(OutputStream os, String xhtml) throws Exception {
        PdfRendererBuilder builder = new PdfRendererBuilder();
        builder.useFastMode();
        builder.useSVGDrawer(new BatikSVGDrawer());
        for (String font : FONT_NAMES) {
            builder.useFont(() -> {
                try {
                    final String path = String.format("fonts/%s.ttf", font.replace(" ", "-"));
                    return FileUtils.openInputStream(storageService.loadFile(path));
                } catch (IOException e) {
                    log.error("Cannot use font " + font, e);
                }

                return null;
            }, font);
        }

        builder.useCacheStore(PdfRendererBuilder.CacheStore.PDF_FONT_METRICS, fsCacheEx);

        builder.withHtmlContent(xhtml, "");
        builder.toStream(os);
        builder.run();
}
```

For first time I got log info:

com.openhtmltopdf.load INFO:: Missed key(font-metrics:Roboto:400:normal) from cache.
com.openhtmltopdf.load INFO:: Hit key(font-metrics:DejaVuSans:400:normal) from cache.
com.openhtmltopdf.load INFO:: Loading font(Roboto) from InputStream supplier now.
com.openhtmltopdf.load INFO:: Putting key(font-metrics:Roboto:400:normal) in cache.
com.openhtmltopdf.general INFO:: Using fast-mode renderer. Prepare to fly.

And next time font is also loading despite having one in cache:

![image](https://user-images.githubusercontent.com/38613340/92325398-af72bd80-f04a-11ea-9e7d-31cc8434ea8a.png)

com.openhtmltopdf.load INFO:: Hit key(font-metrics:Roboto:400:normal) from cache.
com.openhtmltopdf.load INFO:: Hit key(font-metrics:DejaVuSans:400:normal) from cache.
com.openhtmltopdf.load INFO:: Loading font(Roboto) from InputStream supplier now.
com.openhtmltopdf.general INFO:: Using fast-mode renderer. Prepare to fly.

So is this font cached or not?

**Comment by danfickle** [comment]
Say you have:
`font-family: 'en-font', 'Chinese-font', 'Korean-font';`

Without the font metrics cache all the fonts will have to be loaded for font size settings, even if only English characters are used. With the cache full, only the first font is loaded, if the document doesn't need Chinese or Korean characters.

**Comment by mndzielski** [comment]
Ok, I think I understand Thanks @danfickle
