### ISSUE TITLE
format html with no ending tags

### ISSUE THREAD

**Issue by bilak** [danfickle/openhtmltopdf#55]
Hello,
is it possible to format html with no ending tags?

something like this html file:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//CZ">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1250">
</HEAD>
<BODY TOPMARGIN="10" MARGINWIDTH="10" LEFTMARGIN="10" MARGINHEIGHT="10" BGCOLOR="White" TEXT="Black">
<FONT FACE="Courier New CE, Courier New, Courier CE, Courier, monospaced">
-------------------------------------------------------------------------<BR>
this is just the test
characters: +ľščťžýáíé <br>
</FONT>
</BODY>
</HTML>
```

thanks

**Comment by Lawa9** [comment]
Unrelated to the question you asked, try "XHTML 1.0 Strict" and UTF-8. Oh and get rid of everything with \<font\>... everywhere!

**Comment by danfickle** [comment]
You can parse html5 that is not valid xml with jsoup. This is covered in the integration guide. However most deprecated style attributes are not supported so you'll have to use CSS. Sorry for the delay and let us know how you get on.

Thanks,
Daniel.
