### ISSUE TITLE
Is there a way to avoid printing this log "com.openhtmltopdf.css-parse WARNING:: (.) Value windowtext is not a recognized identifier at line 1. Skipping declaration."

### ISSUE THREAD

**Issue by sunithapremkumar** [danfickle/openhtmltopdf#555]
Am seeing this log very frequently as I understand that some of the styles may not be available/parsable. But I prefer to stop bombarding the log which fills up very fast.
com.openhtmltopdf.css-parse WARNING:: (.) Value windowtext is not a recognized identifier at line 1. Skipping declaration.
com.openhtmltopdf.css-parse WARNING:: (.) Value windowtext is not a recognized identifier at line 1. Skipping declaration.
com.openhtmltopdf.css-parse WARNING:: (.) Value windowtext is not a recognized identifier at line 1. Skipping declaration.
com.openhtmltopdf.css-parse WARNING:: (.) Value windowtext is not a recognized identifier at line 1. Skipping declaration.

I tried adding this in my log4J config but didn't help. Any clue on how to stop this log?
    <logger name="com.openhtmltopdf" level="ERROR"/>

**Comment by syjer** [comment]
hi @sunithapremkumar ,

you can increase the log level for the logger:

```
XRLog.setLevel(XRLog.CSS_PARSE, Level.SEVERE);
```

Should do the trick.

For configuring with log4j (I hope 2), I would guess that you need to have the http://logging.apache.org/log4j/2.x/log4j-jul/index.html included, then in theory you should be able to configure it through your log4j config.

**Comment by sunithapremkumar** [comment]
XRLog.setLevel(XRLog.CSS_PARSE, Level.SEVERE);  - This doesn't seem like working.. Am still seeing the log.

static{
        XRLog.setLevel(XRLog.CSS_PARSE, Level.SEVERE); //setting it to avoid css warnings in log
}
private byte[] convertHtmlToPdf(byte[] htmlFile) throws Exception {
        //clean the html if the html contains any non closing tags as the conversion library expects it to be in proper format
        String cleaned_html = cleanHtml(htmlFile);
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        PdfRendererBuilder builder = new PdfRendererBuilder();
        builder.useFastMode();
        //setting fonts
        setFonts(builder);
        builder.withHtmlContent(cleaned_html, ".");
        builder.toStream(os);
        builder.run();

        return os.toByteArray();
    }

**Comment by syjer** [comment]
well, that's strange, as it work for me. 

To be noted I didn't call `XRLog.setLevel` in a static {} block but just before calling `new PdfRendererBuilder()`.

(But in theory, doing as you did in a static {} block should have configured it correctly)

**Comment by sunithapremkumar** [comment]
I tried that as well calling it right before PDFRendererBuilder(). No luck there as well.

**Comment by syjer** [comment]
I guess the simplest way to understand why it continue to log is to put a debug point here https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-core/src/main/java/com/openhtmltopdf/util/XRLog.java#L122  and follow the flow.


Are you using some kind of logging framework as you mentioned log4j? If yes, which version? Maybe there are some strange interactions with java.util.logging as they often provide their bridges.


Btw, have you simply tried to disable the logging to see if it has any effect?

Calling `XRLog.setLoggingEnabled(false)` in a static block should work (I hope)

**Comment by danfickle** [comment]
Thanks all. Please reopen if required.
