### ISSUE TITLE
Page features example 500 error in sandbox

### ISSUE THREAD

**Issue by mndzielski** [danfickle/openhtmltopdf#558]
Hi,
Example on page https://github.com/danfickle/openhtmltopdf/wiki/Page-features throws an exception:

 The element type "thead" must be terminated by the matching end-tag "</thead>".

The problem is that tag that caused this exception is placed in CSS comment.

```
        .continued:before {
            /**
             * For repeated table headers (<thead> elements), show " - Continued"
             * before each table header repeat on subsequent (not initial) pages.
             * See https://github.com/danfickle/openhtmltopdf/pull/32
             */
            content: " - Continued";
            visibility: -fs-table-paginate-repeated-visible;
        }

```

**Comment by syjer** [comment]
Hi @mndzielski , I fixed the wiki, thank you for reporting it :)
