### ISSUE TITLE
How to add all font support?

### ISSUE THREAD

**Issue by adilxoxo** [danfickle/openhtmltopdf#560]
Can you please help me with this thing?

I need to do this as user is manupulating fonts from editor where multiple fonts are supported.

I am having issue with MS Gothik and Helvetika as its showing  ???  at the place of such font characters.

**Comment by syjer** [comment]
hi @adilxoxo , see https://github.com/danfickle/openhtmltopdf/wiki/Fonts#programatically-adding-fonts .

If you see "???" it mean you are not loading a font that is able to display the character.

**Comment by adilxoxo** [comment]
So it means I have to figure out what fonts are being used then add each one of them programatically?

Is there any way to add all font support at once programatically?

**Comment by syjer** [comment]
@adilxoxo , yes.

If you have a directory full of fonts, you can add them all, see https://github.com/danfickle/openhtmltopdf/wiki/AutoFont .

But you must have the fonts used in your document installed on your computer.

**Comment by adilxoxo** [comment]
Ok got it.

Thanks! @syjer

**Comment by syjer** [comment]
your welcome, by the way you will need to ensure the names of the font family when the fonts are imported match the one used in the html/css.

**Comment by adilxoxo** [comment]
Yeah! 

I think line below from AutoFont snippet return me all font families for used ttf files.

`String fontFamily = AutoFont.toCSSEscapedFontFamily(fonts);`

So will use this string in my template in font family property. @syjer

**Comment by danfickle** [comment]
Thanks all, closing now. Re-open as required.
