### ISSUE TITLE
Consider rendering to XSL-FO on some intermediate format understood  by apache fop.

### ISSUE THREAD

**Issue by alpapad** [danfickle/openhtmltopdf#561]
Instead of rendering a pdf directly, one could transform the html to XSL-FO and feed it to apache fop which:

- Supports many more features (like x column tables)
- Supports many more export formats

The output will be much more "profesional" and possibly much faster. Apache FOP is known to be able to render 20k page documents.

Just an idea

**Comment by danfickle** [comment]
This sounds like an interesting stnadalone project, but it is outside the scope of this project. Thanks for the suggestion though.
