### ISSUE TITLE
After converting richtext data some symbols were replaced by # character

### ISSUE THREAD

**Issue by aneesh093** [danfickle/openhtmltopdf#562]
Hello I have used pdfbox and openxhtmltopdf to generate the pdf. while generating some symbols (for example, ȹ and ▲ ) are replaced by # character.  I have used Arial-Unicode-ms font while converting. Is there any solution to fix the above problem.

**Comment by syjer** [comment]
If you see the '#' character it mean you don't have loaded the correct font for the missing characters. 

I would not be surprised if for "ȹ" and "▲"  you will need to load another font (See the wiki page at https://github.com/danfickle/openhtmltopdf/wiki/Fonts#programatically-adding-fonts ).

**Comment by aneesh093** [comment]
Thank you I have added missing font's and it is now coming properly
