### ISSUE TITLE
Really strange box rendering with OBJ characters?

### ISSUE THREAD

**Issue by achuinard** [danfickle/openhtmltopdf#564]
I've used this library for a long time but recently one of my customers informed me that their PDFs are rendering with a strange box with the letters OBJ inside:

![image](https://user-images.githubusercontent.com/469647/94880940-10af6600-042a-11eb-8922-893c600db2af.png)

I don't understand what could possibly be rendering that OBJ. The user's data in Firebase looks perfectly normal:

![image](https://user-images.githubusercontent.com/469647/94880977-2886ea00-042a-11eb-9691-94471c004e41.png)

The funny thing is, if I delete this property from their Firebase node and re-add it with the same text, it now renders fine without that OBJ:

![image](https://user-images.githubusercontent.com/469647/94881016-46ece580-042a-11eb-8df9-dd8318344385.png)

But the data is literally the exact same in Firebase before I deleted and re-added:

![image](https://user-images.githubusercontent.com/469647/94881026-510ee400-042a-11eb-8af1-70f4ef3c442a.png)

Is there some strange character in there that Firebase isn't rendering and is causing messed up rendering on the PDF?

**Comment by danfickle** [comment]
I think your theory is correct. It appears to be copy and pasted text.

https://en.wiktionary.org/wiki/%EF%BF%BC

Sample of usage:
https://developer.apple.com/documentation/businesschatapi/messages_sent/adding_attachment_metadata_to_a_message

It will also depend on whether the font has this character. Maybe we should filter it out with something like #549?

**Comment by achuinard** [comment]
@danfickle you are great. Thanks for fixing this!
