### ISSUE TITLE
0.0.1-RC9 is not in maven repository

### ISSUE THREAD

**Issue by wangdamu** [danfickle/openhtmltopdf#57]
The jar 0.0.1-RC9 is not in maven repository. Can you upload them to maven repository?

**Comment by danfickle** [comment]
The fix applied in rc9 only applies when you try to load invalid images. It is fixed for normal images in rc8. Sorry for the delay over Christmas. Let me know if you really need the fix (possibility of invalid images) and If so I'll try to make a release this week.

Happy holidays,
Daniel.

**Comment by turiot** [comment]
Could you please deploy RC9 to maven central as it solves issue 52 for me.
Thanks for all.

**Comment by danfickle** [comment]
Hi @turiot 
RC9 is now in Maven Central.

**Comment by turiot** [comment]
Thank you !
