### ISSUE TITLE
when html img tag src is local path ，the image is not display in pdf

### ISSUE THREAD

**Issue by pipti** [danfickle/openhtmltopdf#573]
thanks

**Comment by syjer** [comment]
hi @pipti , it should work, could you please provide an example?

**Comment by pipti** [comment]
example:
\<img src="/Users/eric/Downloads/e097e851f4f94d9e87a64f58481acd0d.png"/\>
the path "/Users/eric/Downloads/e097e851f4f94d9e87a64f58481acd0d.png" of the image is the local path，but pdf is not display.

**Comment by danfickle** [comment]
Hi @pipti,

When using absolute paths, you need to use URIs rather than a raw path. For example, you could prepend your path with `file://`. If you have special characters in the path, you will have to use `new File("/Users/eric/Dow...").toURI()`.

**Comment by pipti** [comment]
thanks so much

**Comment by danfickle** [comment]
OK, assumed solved, re-open if required.

**Comment by NoraTheExplorer** [comment]
with the new lib, you can also use the base64 image string instead of a path to a file
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCA....." />`
