### ISSUE TITLE
how to send created pdf file

### ISSUE THREAD

**Issue by ruji704** [danfickle/openhtmltopdf#579]
Hi. 

I want to upload the pdf file I created to another store like S3,
but I need a "File" object or "InputStream" to do so.

here is my code

`
 try (
PDDocument doc = new PDDocument()) {
  
            Document doc2 = Jsoup.parse(new File("C://Path//example.html"),"UTF-8");
            String html = doc2.outerHtml();
         
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.defaultTextDirection(BaseRendererBuilder.TextDirection.LTR);
            builder.useDefaultPageSize(210, 297, BaseRendererBuilder.PageSizeUnits.MM);      
         
            builder.withHtmlContent(html,"");
            builder.useSVGDrawer(new BatikSVGDrawer());
            builder.usePDDocument(doc);

            PdfBoxRenderer renderer = builder.buildPdfRenderer();
            renderer.createPDFWithoutClosing();

           doc.save(os); // **want to send file except save pdf** 

`

thank you for your service

**Comment by rototor** [comment]
If you have the memory you could use a ByteArrayOutputStream to write the PDF to and then create a ByteArrayInputStream for uploading.

I.e.
```
ByteArrayOutputStream out = new ByteArrayOutputStream();
doc.save(out);
ByteArrayInputStream inputStream = new ByteArrayInputStream(out.toByteArray());
... now use inputStream for upload ...
```

If you don't have the memory (i.e. the max memory given to the JVM is rather small), you might need to use a temporary file.

==> We can not provide an InputStream for reading directly, but instead we can only write to output streams. So you have to use something like this.

**Comment by danfickle** [comment]
Closed as assumed solved. As always re-open if required.
