### ISSUE TITLE
How to modify elements position after render?

### ISSUE THREAD

**Issue by abozanona** [danfickle/openhtmltopdf#581]
One of the issues listed in the Form controls documentation is that it's not **transform aware**.  
https://github.com/danfickle/openhtmltopdf/wiki/Form-Controls#open-issues

Is it possible to modify form control elements position manually in JAVA?

I'm trying to do something like this:

    PdfBoxRenderer renderer = builder.buildPdfRenderer();
    renderer.layout();
    modifyFields(renderer.getRootBox());
    private void modifyFields(Box box) {
        if(box.getElement() != null && box.getElement().getTagName() != null){
            String tagName = box.getElement().getTagName().toLowerCase();
            if("input".equals(tagName) || "button".equals(tagName) || "textarea".equals(tagName)){
                box.setAbsX(0);
                box.setTx(0);
            }
        }
        for (int i = 0; i < box.getChildren().size(); i++) {
            modifyFields(box.getChild(i));
        }
    }

In the code, I'm trying to change form fields position, but it's not working.

How can I modify form fields position and size from java?

**Comment by danfickle** [comment]
The box position in our model stays the same at this level, we just output the transform before outputting the box, letting the PDF viewer determine the final box position. I think you may have more luck moving the input widget in the PDF model provided by PDFBOX. Below is a sample that does just this. 

The reason I have not added code to do this in the project is that PDF annotations (such as input widgets) do not support arbitrary rotation or skew (as far as I can tell), meaning it would not support most transforms.

NOTE: Borders and background is output as a normal box, you only have to move the widget annotation to match.

````java
package com.example;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.List;

import com.openhtmltopdf.pdfboxout.PdfBoxRenderer;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.interactive.annotation.PDAnnotationWidget;
import org.apache.pdfbox.pdmodel.interactive.form.PDField;

public class App6 {
    private final static String HTML = 
    "<form>" +
    "<div style=\"transform: translateY(1in);\">" +
    "  <input type=\"text\" name=\"myinput\" />" +
    "</div>" +
    "</form>";

    public static void main(String... args) throws IOException {
        try (OutputStream os = new FileOutputStream("C:\\Users\\me\\Desktop\\res.pdf")) {
            PdfRendererBuilder builder = new PdfRendererBuilder();

            builder.useFastMode();
            builder.withHtmlContent(HTML, null);

            try (PdfBoxRenderer renderer = builder.buildPdfRenderer()) {
                renderer.createPDFWithoutClosing();

                PDDocument doc = renderer.getPdfDocument();
                List<PDField> fields = doc.getDocumentCatalog().getAcroForm().getFields();

                // Get the field by name, then its widget.
                PDAnnotationWidget widget = 
                       fields.stream()
                             .filter(w -> w.getPartialName().equals("myinput"))
                             .findFirst()
                             .orElseThrow(null)
                             .getWidgets()
                             .get(0);

                // It's current location.
                PDRectangle rect = widget.getRectangle();

                // Here we move the widget rect down 1 inch.
                // PDFs use 1/72 inch units and botttom up coordinate system.
                PDRectangle adjustedBox = new PDRectangle(
                    rect.getLowerLeftX(), rect.getLowerLeftY() - 72, rect.getWidth(), rect.getHeight());

                widget.setRectangle(adjustedBox);

                doc.save(os);
            }
        }
    }
}
````
