### ISSUE TITLE
base64 image in html convert to pdf. I get error :( Please helps me!

### ISSUE THREAD

**Issue by cscsala** [danfickle/openhtmltopdf#582]
The source:

	@Override
	public ByteArrayOutputStream topdf(byte[] htmlBytes) throws Exception {		
		try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
			String html = new String(htmlBytes, Charsets.UTF_8);
			PdfRendererBuilder builder = new PdfRendererBuilder();
			builder.useDefaultPageSize(210, 297, BaseRendererBuilder.PageSizeUnits.MM);
			builder.useFastMode();			
			
                       //builder.withHtmlContent(html, HtmlToPdfDao.class.getResource("/imgs/").toString());
			builder.withHtmlContent(html, "");
			
			builder.toStream(os);
			builder.run();
			return os;
		}
	}

The html file:
[kutya_test2.zip](https://github.com/danfickle/openhtmltopdf/files/5407093/kutya_test2.zip)
I get error:
**com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: The markup in the document following the root element must be well-formed.
ERROR:  'The markup in the document following the root element must be well-formed.'
com.openhtmltopdf.exception WARNING:: Unhandled exception. Can't load the XML resource...**

If I set the image sourece  in html :
`<img src="test.png"  height="20"> </img>`

and I copy test.png into the imgs/ folder   and I use  
`builder.withHtmlContent(html, HtmlToPdfDao.class.getResource("/imgs/").toString());`
then created pdf. 

How can set I set the image in base64?   
It's possible to set images in base64 and convert to pdf?

brg.: Csaba

**Comment by danfickle** [comment]
Hi @cscsala,

XML needs a root element so just surround your current document with `<body>` and `</body>` tags and it works (I tested, fork and knife image seen).

**Comment by cscsala** [comment]
Thank you for your help! 
It's works very well.
:)
