### ISSUE TITLE
How can I get the DPI?

### ISSUE THREAD

**Issue by abozanona** [danfickle/openhtmltopdf#584]
Is there a way I can get DPI and (Dot per pixel) for the PDF?

Is there a default value for them?

Can I manually set them?

**Comment by danfickle** [comment]
Hi @abozanona,

I think PDF is a vector format so typically only inserted images which do not have a specific size set use DPI. The default and only DPI in this library in that case is 96dpi.

NOTE: Image files are not resized before being inserted in the PDF, so you can achieve whatever DPI you need. For example, if you wanted a 300dpi image and your image is 900 pixels across by 600 pixels high, just size it using CSS to 3 inches by 2.
