### ISSUE TITLE
HTML Escaped Latin Characters Not Rendering - "&Auml;" Ä, "&eacute;" é (and probably others)

### ISSUE THREAD

**Issue by swillis12** [danfickle/openhtmltopdf#595]
Using the following HTML file, observe that HTML-escaped characters are not rendered in the resulting PDF: 
[characters_missing.html.txt](https://github.com/danfickle/openhtmltopdf/files/5513011/characters_missing.html.txt)

Note that the escaped characters were escaped using [StringEscapeUtils.html#escapeHtml(java.lang.String)](https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringEscapeUtils.html#escapeHtml(java.lang.String)) in my program where I first observed this behavior.

Result: 
![image](https://user-images.githubusercontent.com/35236833/98589965-f8313780-2282-11eb-9a08-95199988cbba.png)

HTML input (snippet):
```
<div>Escaped: &Auml;gypten Br&eacute;sil</div>
<div>Not Escaped: Ägypten Brésil</div>
```

Test code: 
```
public class App {
    public static void main(String[] args) throws Exception {
        long start = System.currentTimeMillis();
        try (OutputStream os = new FileOutputStream("test.pdf")) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withFile(new File("characters_missing.html"));
            builder.toStream(os);
            builder.run();
        }
        System.err.println((System.currentTimeMillis() - start) + "ms");
    }
}
```

**Comment by swillis12** [comment]
I may try to work around this for now by selectively escaping only the dangerous HTML characters ('"&<>) based on [this stackoverflow comment](https://stackoverflow.com/questions/1265282/recommended-method-for-escaping-html-in-java#comment47636364_1265289).

**Comment by danfickle** [comment]
You could try our doctype with entities:

https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-examples/src/main/resources/documentation/documentation.md#character-entities

If you are feeling helpful, feel free to add the character entities section to the integration guide on the wiki.

**Comment by danfickle** [comment]
Finally added section in integration guide on character entities.
