### ISSUE TITLE
How to use maven tool to depend this project

### ISSUE THREAD

**Issue by xu-weize** [danfickle/openhtmltopdf#600]
Sorry,i am the first time to use your project,and  i want to ask some questions. In your context introduce,i cannot get information about how to builde this project and if i want to directly depend on this project by maven tools how to do it?

**Comment by syjer** [comment]
Hi @xu-weize , see the integration guide: https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide .

As a dependency for maven, you will need at least:

```xml
<dependency>
  <!-- Required for PDF output. -->
  <groupId>com.openhtmltopdf</groupId>
  <artifactId>openhtmltopdf-pdfbox</artifactId>
  <version>1.0.4</version>
</dependency>
```

See the minimal usage section for the code: https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide#minimal-usage .

**Comment by danfickle** [comment]
Thanks @syjer. @xu-weize please reopen if required.
