### ISSUE TITLE
Image scaling issue beyond page size

### ISSUE THREAD

**Issue by ntripathy** [danfickle/openhtmltopdf#602]
I have the following image tag in my html content. When converted to PDF the output PDF contains a blurred image with right side truncated and spanned across two pages.

img height="100%" src="../images/myimage.jpg" alt="image"

Is there a way I can customize or override the image scaling properties (height and width) based on the image size and PDF page size?

**Comment by danfickle** [comment]
Hi @ntripathy,

The standard fix for this is to use `max-width: 100%;` on the `img` element.

**Comment by ntripathy** [comment]
Thanks @danfickle.
I had to adopt the following custom code to fix this issue. But it would have been better if we could override this after extending PdfBoxReplacedElementFactory class.

> private void scaleOutImageIfNeeded(PdfBoxRenderer renderer, Element imageElement) {
        ImageResource imageResource = renderer.getSharedContext().getUserAgentCallback().getImageResource(imageElement.attr("src"));

        if (null != imageResource && null != imageResource.getImage()) {
            FSImage fsImage = imageResource.getImage();
            float origImageWidth = (fsImage.getWidth());
            float origImageHeight = (fsImage.getHeight());

            /*For A4 size the page width would be 595 points and page height would be 841 points*/
            float maxWidth = PageSize.A4.getPageWidth().getFloatValue(CSSPrimitiveValue.CSS_MM) * (float)(DEFAULT_PDF_POINTS_PER_INCH/INCH_IN_MM);
            float maxHeight = PageSize.A4.getPageHeight().getFloatValue(CSSPrimitiveValue.CSS_MM) * (float)(DEFAULT_PDF_POINTS_PER_INCH/INCH_IN_MM);
            float scaleRatio = DEFAULT_DOTS_PER_PIXEL * maxWidth / origImageWidth;
            float heightScaleRatio = DEFAULT_DOTS_PER_PIXEL * maxHeight / origImageHeight;
            if (heightScaleRatio < scaleRatio) {
                scaleRatio = heightScaleRatio;
            }
            if (scaleRatio > 1F) {
                scaleRatio = 1F;
            }
            imageResource.getImage().scale((int) (fsImage.getWidth() * scaleRatio), (int) (fsImage.getHeight() * scaleRatio));
        }
    }

**Comment by danfickle** [comment]
I still don't understand why you can't use `max-width` but I'm glad you solved your issue. Please reopen if required.
