### ISSUE TITLE
Problem with Image it doesn´t load on pdf

### ISSUE THREAD

**Issue by zyrius124** [danfickle/openhtmltopdf#619]
Hi,

I took the code from the question "Base 64 encoded Images does not load in PDF" and it doesn't work in the sandbox. it just shows a red box. here is the code again:

    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" style="border:1px solid red; height:100px; width:100px"/>

if I take the code and open it in the broswer, it shows me a red box with a cross in it.
could anyone explain to me what's wrong?

**Comment by syjer** [comment]
hi @zyrius124 , you can check the "Logs" button, you will get the reason of the failure:

```
SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
Loaded document in ~3ms
TIME: parse stylesheets 0ms
media = print
Matcher created with 164 selectors
Hit key(font-metrics:handwriting:400:normal) from cache.
Hit key(font-metrics:arabic:400:normal) from cache.
Hit key(font-metrics:deja-sans:400:normal) from cache.
Hit key(font-metrics:cjk:400:normal) from cache.
URI resolver rejected loading image at (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
URI resolver rejected loading image at (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
Loading font(handwriting) from InputStream supplier now.
Using fast-mode renderer. Prepare to fly.
```

The `URI resolver rejected loading image at (data:image/png;base64,iVBO` is the reason.

This as far as I know has been fixed. 
To be noted: the sandbox may have a stricter configuration.

**Comment by danfickle** [comment]
Yes, at the moment, the sandbox rejects all uris, even data uris.
