### ISSUE TITLE
Empty PDDocument when getting it from PdfBoxRenderer

### ISSUE THREAD

**Issue by amrfaissal** [danfickle/openhtmltopdf#62]
I'm using `PdfRendererBuilder` to create a PDF with HTML5 input:
```
String htmlDoc = "<h1>Hello World</h1>"
OutputStream os = new FileOutputStream("output/StaticWebSite.pdf");
Document htmlDoc = XMLResource.load(new ByteArrayInputStream(HTML_DOC.getBytes(StandardCharsets.UTF_8)))
                    .getDocument();
PdfBoxRenderer pdfBoxRenderer = new PdfRendererBuilder().withW3cDocument(htmlDoc, null).toStream(os).buildPdfRenderer();
doc = pdfBoxRenderer.getPdfDocument();
doc.save(os);
```
The code base above produces an empty PDF document, but If I directly invoke the builder's `run()` it works just fine.

I am not sure if the interaction between `openhtmltopdf` and `pdfbox` was taken into consideration when designing the library, so I'd really appreciate any pointers.

**Comment by danfickle** [comment]
Hi @amrfaissal 
I've tried the following code and it works. Note the call to ````layout```` and ````createPDF```` after creating the renderer.

````java
	    String HTML_DOC = "<h1>Hello World</h1>";
	    OutputStream os = new FileOutputStream("output/StaticWebSite.pdf");
	    Document htmlDoc = XMLResource.load(new ByteArrayInputStream(HTML_DOC.getBytes(StandardCharsets.UTF_8)))
	    		                    .getDocument();
	    PdfBoxRenderer pdfBoxRenderer = new PdfRendererBuilder().withW3cDocument(htmlDoc, null).buildPdfRenderer();
	    pdfBoxRenderer.layout();
	    pdfBoxRenderer.createPDF(null, false);
	    PDDocument doc = pdfBoxRenderer.getPdfDocument();
	    doc.save(os);
	    pdfBoxRenderer.cleanup(); // Should be in finally block!
````

**Comment by amrfaissal** [comment]
Hi @danfickle 
Thank you for your reply. Is this future proof? It would be great if you can also highlight how to switch back and forth between `openhtmltopdf` and `PDFBox`.

The example above works fine for now, but I'm concerned about API changes.
Thanks again!

**Comment by danfickle** [comment]
I think the whole project is unfortunately stable at the moment! I think you should be right, at least until we have to do something about Java 9 modules down the track.
