### ISSUE TITLE
How to render image?

### ISSUE THREAD

**Issue by achimmihca** [danfickle/openhtmltopdf#620]
From the tests I found this [xhtml](https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/tests/diff/background/image/basic.xhtml) where img-tag is used as usual.
However, this does not seem to work. When I render my PDF, the image is always missing.

Also I wonder *how* this should work. The documentation does not say anything about images and the [example](https://github.com/danfickle/openhtmltopdf/wiki/Page-features) does not make use of them.

- Is the renderer trying load a file with this given local path?
    - If yes, then relative to which location?
- What if my image is in a Java "resource" directory (already packed inside the JAR)? 
    - I would expect that I can feed the renderer with image data that I have already loaded in memory. Is this possible (I guess this is the goal of #91)?

Anyway, I also tried `<img src="data:..."` to provide the image data directly with the xhtml. This also has been done in #619 and is said to work. However, I still see no image in my PDF.

I don't have any error output from the renderer. The PDF is generated but without the image.
As a result, I have no idea what the problem is. Is there a way to get more verbose output to find the root cause?

OpenHtmlToPDF Version: 1.0.5

**Comment by achimmihca** [comment]
To test this, I used the following:

```
<html>
<head>
    <style>
        @page {
            size: A4;
        }
    </style>
</head>

<body>
    Hello world!
    <img style="width: 2cm; height: 2cm;"
         src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAE2klEQVRoge2Za0xbZRjH/x0wbmMggzIQmFTAYYjD6WSr2eUD29R42eIy2eYlojHTaEycuuiSRWN08QNZBJIZx2VGg1GJjhh1cZMi47K5sDBXx7gOCi1QbqVSRunaxw/zAuSc95z3LeZI0t+n5rz/5/k///a05/Q9OiLCYmaJ1gP4SyCA1gQCaE0ggNYs+gDBIkWuUbScxFgvHFZ4PQrioBDEGZCQieQc6DNE7JjouK/EDiuqDsBYgJV3IDoJQSEKeu8MRq5hqA29zbC3IzgUGZuxLh8h4cJDz4G46DxLZXtouIuvajZeDzV/Tcd3U0M5zUyJ9/kbngAddfTps+R2+e/6b4xznxH5/OmkOoC9g8r2Lsz0/+D1UG0JVb1O9g66clqsh7oAE4N0fDeNWcQ8FLj8A320jeo+FqtW9zNqKkbea7glZWG+dvPIfhBxaUi5W6xaRYDOeuiA23LFDJTxXMdQm3C1UgDyoe4Ytr4hbAAA432sVZsZU+MIWirWWylAYwWy8hAeLStoq8HJt1mXM+cQirYDQGO5tIAI9z+PlBzFWSVhBhjrRXcT1j/D0lyqRss3aK/FQKtsE/LhyL1orxUbkQ07gAVpudAxNSNdAPDVq+g8Ky24ef6ER2PwKipfFJuSAfNeaMyC2FSW4A87nHYAIB9yHpPWxKcjNhVjFgSFoN0kOqcszHfXOYgoPUsQpcfKLIQtxz1PICpBWpO8BssT/3qdsVloSBbMT2DwKjbuV2iw4320mWAwsjSb9iMxCz3n8fA7vPMpwgww40JopEKDmGTkPqWgMWyAYYP8sg7kU+ggj/wp5LuBkDDhvhwk3on+FuFq+QCjvYhdJdyXg9BIeKaFq+UDuEYRuUK4Lx8r0oTvJvj/E4/3ofWMmJks0Ym4PiFWyh/A68GFStxwi/ktOPIBImLg6Jc4HmfAXY/AVPzfzcSFfAB9JqYcGOmWWMrZiYkBNJ0QMexuEqmSh3kKbXsTP34AyW2LXYWwmdFVz21Yd4y7hAkzQJwBhvVoqpBe3X4QphI4rBxuk8P+XLMkUfoSGwvQ8yuunZNYWhaPR9/Dd4c53DrqsGYHh14FSgF0S7DzQ5iKpFf1GbjdiG8PwudV5db6EzI2SRxXWS6Fip/R8GgkrEbHL9KrxueQlI3qQ8p9rpzCMr3E7a3Diq4GJGYpd5BE1d7FtJNK99DEgKzgzFEyFbM6jPZIbytNDFBpPtk7VY0hheqNLZuZqg6wBDVFVLaXLlXT9OSc424XNZRRxZM03D2/xHKRSvP92qgk4tncrT6ErK3I3CIrmBzBhUrYzHNuzoJDkb4Ra3dhacQccVcDGsvxeCEiYrhPm9lwhHW7qOJpGmj15w0jIiIfNZTRFy8tyEYl5+60c5BK88k1Lm7odtGXr5CphHxe8Saz4AxARJZm+vwFQXvnEJXvo7YakVoZ+AMQUWMFnS7krrKaqTSfeptFHOXhf0Jzk1NHEBaFLS+rElsvw1SE4FA88BZibhWxk0c0ANRlIB/qP4Htdzx0GFHxgkZM/AgA4Pt3EZ+O+/bNPz45jP7f0HMeNjNW58FY4M+IbPwL4JnGz0fRd3HOEzufF5GxWLUOSdlIXev/iGz8C/A/YNE/6A4E0JpAAK0JBNCaQACtCQTQmkAArQkE0Jo/AaHeXcfZZth5AAAAAElFTkSuQmCC"
         alt="Smiley"/>
</body>
</html>
```

This works in a browser.

**Comment by achimmihca** [comment]
Found a solution:

it works when using an **absolute path** to the image and `file://` protocol (but you have to use three slashes also on Windows, so `file:///`)

`<img src="file:///D:/repos/local-projects/ExportExperiments/smiley.png"
          alt="Smiley"/>`

**Comment by syjer** [comment]
hi @achimmihca , for the base64 image:

`data:image/png;base64, iVB`, if you remove the space after the `,` , it will work.

For the file, you can use relative path if you want, but you must pass the base uri.
