### ISSUE TITLE
How to add font using InputStream ?

### ISSUE THREAD

**Issue by TGhoul** [danfickle/openhtmltopdf#625]
My application is a jar file, only use `getResourceAsStream()`  to read font files, Is there a way for this？

**Comment by danfickle** [comment]
Hi @TGhoul,

You can use the builder methods:
````java
        // Longhand method lets you specify font weight and style.
        builder.useFont(() -> App8.class.getResourceAsStream("/font-bold-italic.ttf"), "my-font-family", 700, FontStyle.ITALIC, true);

        // Shorthand method assumes font is normal weight and style.
        builder.useFont(() -> App8.class.getResourceAsStream("/font.ttf"), "my-font-family");
````

Note: It is not recommended to use input streams if using SVG or Java 2D output. See #613.

P.S. If this answers your question, feel free to close this issue.

**Comment by TGhoul** [comment]
Thank you for your answer, I got a lot of inspiration.

**Comment by okhandur** [comment]
You are the man!

**Comment by yasarutkuu** [comment]
thank you very much. it's life saving tip. we spent lots of time to import fonts.

ADAMSIN. KRALSIN. @danfickle @TGhoul
