### ISSUE TITLE
Add support for tiff images

### ISSUE THREAD

**Issue by abozanona** [danfickle/openhtmltopdf#626]
How can I make openhtmltopdf support rendering `tiff` images?

```
<!DOCTYPE html>
<html>
<head>
	<title>Lorem Ipsum</title>
</head>
<body>
	<h1>SAMPLE TIFF PAGE</h1>
	<img src="https://file-examples-com.github.io/uploads/2017/10/file_example_TIFF_1MB.tiff"/>
</body>
</html>
```

**Comment by rototor** [comment]
If you want to include tiff images you need to use [TwelveMonkeys](https://github.com/haraldk/TwelveMonkeys) in your project. Just depend on com.twelvemonkeys.imageio:imageio-tiff, as soon as this is in your class path it should work. Note: The images will be loaded and re-encoded. At the moment neither OpenHtmlToPDF nor PDFBox support directly embedding tiff images (which would in theory be possible).
