### ISSUE TITLE
Documentation: Example for Pluggable HTTP Client Implements Deprecated Interface

### ISSUE THREAD

**Issue by slarti-b** [danfickle/openhtmltopdf#629]
The example code under [Pluggable HTTP Client](https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide#pluggable-http-client) in the Integration Guide implements the `HttpStreamFactory` interface.  However, when trying it out I get a deprecation warning for that interface.  The comment in the code says to use `FSStreamFactory` instead (major kudos for actually saying what to use instead, ubnlike many projects which just deprecate stuff and let you guess what replaced it!).  Changing to use `FSStreamFactory` seems to work, so i guess the documentation should be updated to reflect that.

Wasn't sure if you wanted anyone else to just edit the wiki so decided to raise an issue.  Happy to fix directly if you want.

**Comment by danfickle** [comment]
Thanks for doing the detective work! Feel free to change to the correct interface on the wiki. Happy new year!

**Comment by danfickle** [comment]
OK, I've made changes in the wiki. I've also added a note about the `useProtocolsStreamImplementation` method which is similar but allows the user to specify protocols to use with the stream factory.

I'll close this issue now, but please reopen as required.
