### ISSUE TITLE
'The element type "img" must be terminated by the matching end-tag "</img>".'

### ISSUE THREAD

**Issue by erostefano** [danfickle/openhtmltopdf#634]
I am using this libary to create a valid html:

```
<!-- https://mvnrepository.com/artifact/com.j2html/j2html -->
<dependency>
    <groupId>com.j2html</groupId>
    <artifactId>j2html</artifactId>
    <version>1.4.0</version>
</dependency>
```

The img tag looks like this:
`<img src="image.png">`

When converting I get this error:
`'The element type "img" must be terminated by the matching end-tag "</img>".'`

According to Mozilla https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img the img element doesnt need to be closed. 

Is there a workaround?

**Comment by syjer** [comment]
hi @erostefano , this library accept only well formed xml. So for your case, if you have html as input, you need to use a html5 parser that return a DOM, see the documentation: https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide#html5-parser-support

**Comment by danfickle** [comment]
Closing now. Thanks @syjer. Re-open as required.

**Comment by kdekooter** [comment]
When your library is called "Open HTML" it should accept valid HTML.
