### ISSUE TITLE
Support for PDF/A-3

### ISSUE THREAD

**Issue by vader** [danfickle/openhtmltopdf#636]
A request to add support for PDF/A-3 which only differs from PDF/A-2 in one regard: it allows embedding of arbitrary file formats (such as XML, CSV, CAD, word-processing documents, spreadsheet documents, and others) into PDF/A conforming documents. 
I noticed there is some A-3 support in PDFAFlavour.PDFA_3_U. 

I am looking to embed an XML file in the PDF as an attachment. 

I would be happy to help with some pointers and assistance.

**Comment by danfickle** [comment]
Hi @vader,

We have PR #508 (also #528) which I think may do what you are looking for. It is not yet ready for merge, but I'll have a look at what it will take to get it merged.

**Comment by danfickle** [comment]
Support now merged into main branch.

[File embed documentation](https://github.com/danfickle/openhtmltopdf/pull/640#issuecomment-770819471).
