### ISSUE TITLE
How to apply hover effect

### ISSUE THREAD

**Issue by bdot** [danfickle/openhtmltopdf#643]
Tried this [hover example](https://github.com/danfickle/openhtmltopdf/blob/801780ba03537d004b3423485a3ac7692a09bb95/openhtmltopdf-examples/src/main/resources/demos/hover.xhtml) in the [Sandbox](https://sandbox.openhtmltopdf.com/) but can't see the affect. Any idea, what's missing?

Thanks!

**Comment by syjer** [comment]
As the example reference flying saucer, I would guess it may be a lost feature during the refactoring/changes to pdfbox.

I'll have a look what would be the cause.

**Comment by danfickle** [comment]
Sorry, the example is obsolete.

In PDFs, the only interactive features we support are links and form controls.
In Java2D output, the product is a raster image, so no interactive content is produced.

Even in FlyingSaucer project, I think the hover support is for Swing Java components, so not relevant to the web.

**Comment by bdot** [comment]
Understood. Thanks for the clarification.
