### ISSUE TITLE
Numbered lists: numbers rendered after text in RTL languages

### ISSUE THREAD

**Issue by johnnyaug** [danfickle/openhtmltopdf#645]
Related to #270 - which dealt with a similar issue with bulleted lists, and was solved. 

Reproduce:
Take the following html:
```html
<html dir="rtl">
   <body dir="rtl">
   <ol>
      <li>דבר ראשון</li>
      <li>דבר שני</li>
      <li>דבר שלישי</li>
   </ol>
   </body>
</html>
```

And render it with the following code:
```java
try (OutputStream os = new FileOutputStream("output.pdf")) {
    PdfRendererBuilder builder = new PdfRendererBuilder();
    builder.useUnicodeBidiSplitter(new ICUBidiSplitter.ICUBidiSplitterFactory());
    builder.useUnicodeBidiReorderer(new ICUBidiReorderer());
    builder.defaultTextDirection(BaseRendererBuilder.TextDirection.RTL);
    builder.withUri("file:///path/to/html");
    builder.toStream(os);
    builder.run();
} catch (URISyntaxException e) {
    e.printStackTrace();
}
```

Get the following PDF:
![image](https://user-images.githubusercontent.com/3149885/107087407-10720d80-6804-11eb-9729-5df44f1f2cb7.png)

The numbers are expected to be to the right of the text, like so:
![image](https://user-images.githubusercontent.com/3149885/107033953-b438ca80-67be-11eb-9cb9-a60f9651060b.png)

**Comment by johnnyaug** [comment]
I can try to solve this issue with a little guidance: I tried to do it by simply calculating the width similar to what was done in #271. However this is not enough here: the order also needs to change. e.g. `1. ` should be rendered as ` .1`

**Comment by syjer** [comment]
hi @johnnyaug ,

the "1. " is generated in the method `makeTextMarker` of `BlockBox`:

https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-core/src/main/java/com/openhtmltopdf/render/BlockBox.java#L372

The open point is: do we have the information that we are in a RTL context? :)

**Comment by syjer** [comment]
ok, you can get the direction by calling: ` getStyle().getDirection()` inside the `makeTextMarker` method :)

**Comment by danfickle** [comment]
Technically, we should be doing BIDI on the list marker text.
