### ISSUE TITLE
Different behavior for text and elements for margin boxes

### ISSUE THREAD

**Issue by eburlaka** [danfickle/openhtmltopdf#661]
Components with text content are placed on every page, but components where content is element are shown only on the last page. How to add  html content to the footer on every page?

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style type="text/css">
    @page {
      size: 620px 877px;
      margin: 50px;
      font-size: 30px;

      @bottom-left {
        content: element(bottom-left-content);
        background: blue;
      }

      @bottom-right {
        content: 'BOTTOM RIGHT CONTENT';
        background: red;
      }
    }

    .page {
      font-size: 70px;
      line-height: 600px;
      text-align: center;
      border: 1px solid gray;
      page-break-inside: avoid;
    }
    .footer-left {
      position: running(bottom-left-content);
    }
  </style>
</head>
<body>
  <div class="page">1</div>
  <div class="page">2</div>
  <div class="footer-left">
    <b>BOTTOM LEFT CONTENT</b>
  </div>
</body>
</html>
```

<img width="641" alt="1" src="https://user-images.githubusercontent.com/5116104/109355934-a8ee3180-7888-11eb-8c9a-17a3138a2eac.png"><img width="641" alt="2" src="https://user-images.githubusercontent.com/5116104/109355938-aa1f5e80-7888-11eb-8716-7fda65453c64.png">

**Comment by danfickle** [comment]
I think this is the same regression as #614. Anyway, about to start debugging...

**Comment by danfickle** [comment]
Disregard my previous comment. It turns out that if you add the running elements as first children of the `body` element it works. I'm still debugging why this is, but given the easiness of the workaround, the "fix" might end up be adding a note to the page features doc on the wiki.

**Comment by danfickle** [comment]
OK, after debugging, it seems this is by-design and as per the (somewhat confusing) [paged media spec](https://www.w3.org/TR/css-gcpm-3/#element-syntax).

The idea is that the value returned can be updated with multiple elements using the one running position. Take this html for example:
````html
<html>
<head>
<style>
@page {
  size: 200px 200px;
  margin: 20px;
  @bottom-left {
    background: blue;
    content: element(footer);
  }
  @bottom-right {
    background: red;
    content: 'FOOTER-R';
  }
}
.footer {
  position: running(footer);
}
</style>
</head>
<body>
  PAGE 1

  <div class="footer">
    FOOTER1
  </div>

  <div style="page-break-before: always;">PAGE 2</div>

  <div class="footer">
    FOOTER2
  </div>

  <div style="page-break-before: always;">PAGE 3</div>

  <div class="footer">
    FOOTER3
  </div>
</body>
</html>
````
When shown on the first page 'FOOTER1' is shown. On page 2, we reassign the footer running position to 'FOOTER2' and this is shown and so on. Therefore, if we remove 'FOOTER1', we can say that the running position for footer is unassigned on the first page and nothing is shown on that page.

I did not know it worked this way so it's been a learning experience.

I'll add a note to the wiki page.

**Comment by danfickle** [comment]
[Re-assigning running elements on wiki](https://github.com/danfickle/openhtmltopdf/wiki/Page-features#re-assigning-running-elements)

**Comment by eburlaka** [comment]
@danfickle, first of all, thanks for the quick reply
and if I have a long table with dynamic data (1-3 pages) and a footer should be placed on each of the pages, is there a way to do this?

**Comment by danfickle** [comment]
Just add the footer element just after the opening `body` tag and it should work for all pages.

**Comment by eburlaka** [comment]
> Just add the footer element just after the opening `body` tag and it should work for all pages.

After being placed at the beginning of the body tag it works, thanks!
