### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by wung-stavvy** [danfickle/openhtmltopdf#665]
Is there a timetable on the next release? I would like to use the file embedding feature. Feel free to close this to clean up clutter. Thanks :)

**Comment by danfickle** [comment]
Hi @wung-stavvy,

Hopefully, the overdue release will be in 24 hours!

**Comment by danfickle** [comment]
@wung-stavvy,

I owe you an apology for making a release promise that I could not keep. Anyway, 1.0.7 has just been released. Finally!

**Comment by wung-stavvy** [comment]
woo hoo! Thank you so much :)
