### ISSUE TITLE
How to Make text non selectable while using ObjectDrawerFactory for Watermark

### ISSUE THREAD

**Issue by bhaskermca** [danfickle/openhtmltopdf#677]
I am able create watermark using objectdrawer but thing is , I am able select and copy water mark text, is there any way we can't select watermark text.

Is there any way to make text non selectable in PDF

**Comment by rototor** [comment]
The text will not be selectable if you convert it to vector shapes. But this may bloat the PDF. 

To do so, in your `drawObject()` you can cast to Graphics2D and set a vector only font drawer. i.e.

```
output.drawWithGraphics( .... 

// Override the default text drawer, which would draw using fonts with an vector only drawer
((PdfBoxGraphics2D)g2d).setFontTextDrawer(new PdfBoxGraphics2DFontTextDrawer());

... draw your watermark ...
```

But you might be better off by using a background PDF you create with some draw program with your watermark and merge it into the background. This way the same PDXForm would be reused for all pages and the PDF would not get that bloated. See also [MergeBackgroundPdfDrawer](src/main/java/com/openhtmltopdf/objects/pdf/MergeBackgroundPdfDrawer.java) for this.

**Comment by danfickle** [comment]
Thanks @rototor. Closing now. Please reopen as required.
