### ISSUE TITLE
@page bottom-centre CSS property doesn't repeat for each page when used with running element

### ISSUE THREAD

**Issue by sophon-aniketos** [danfickle/openhtmltopdf#690]
I have a SO question here. I think this maybe a problem with the library? Anyway I'm creeating an issue here:

https://stackoverflow.com/questions/67090796/page-bottom-centre-css-property-doesnt-repeat-for-each-page-when-used-with-run

**Comment by danfickle** [comment]
I think this is a repeat of #661. If that is the case, remember to answer your own question on SO so others can benefit.

TLDR:
Put page margin elements just below the opening `<body>` tag if you want them visible on all pages. This is how the relevant CSS standard works.

**Comment by danfickle** [comment]
Assumed solved, please re-open if required.
