### ISSUE TITLE
input type="date" not rendering in PDF

### ISSUE THREAD

**Issue by wicksmr** [danfickle/openhtmltopdf#693]
Hello @danfickle ,

Thanks for taking time to review this.

I'm unable to get date-inputs to render in the PDF. I've provided a "stripped down" markup below. There's a textbox (sanity check) that renders fine, and then two date inputs with varying date format that I can't get either to render in the PDF.

`<html><body><form><div><input type="text" id="text1" name="text1" value="Text that works" /><input type="date" id="date1" name="date1" value="2021-04-29" /><input type="date" id="date2" name="date2" value="04-29-2021" /></div></form></body></html>`

Any insights would be _greatly_ appreciated! 

Thanks,
Mike

**Comment by danfickle** [comment]
Hi @wicksmr,

Unfortunately a date picker/field is not part of the PDF standard (as of version 1.7). There is a tool floating around that embeds a datepicker by using a lot of javascript which can be executed by some PDF readers. I believe Acrobat Pro does the same. Unfortunately the javascript is not opensource and not part of this project.

Currently the closest you can get to a date picker is probably three select boxes (day 1-31, month and year).

https://stackoverflow.com/questions/32398094/acrobat-pdf-form-with-date-picker
https://helpx.adobe.com/au/acrobat/kb/support-for-image-and-date-fields-in-acroforms.html

**Comment by danfickle** [comment]
Closing as not within scope of this project. Please reopen if required.
