### ISSUE TITLE
Print big table without trace

### ISSUE THREAD

**Issue by LLazyness** [danfickle/openhtmltopdf#696]
How to prevent this table trace between pages if I use table with css property page-break-inside: avoid;
![image](https://user-images.githubusercontent.com/25137491/117155867-d47c2380-adc5-11eb-94b5-8d5bed60d51d.png)

**Comment by danfickle** [comment]
That is ugly! Can you provide a minimal sample that reproduces?

**Comment by danfickle** [comment]
Closing in favor of #759 where a minimal sample is provided. Thanks for reporting.
