### ISSUE TITLE
Unable to load background-image url

### ISSUE THREAD

**Issue by sridharchalimeti** [danfickle/openhtmltopdf#699]
I am using images in two places inside my html content

`background-image: url("background.png");`

`<img src="logo.png"/>`

generating pdf file by using 

`builder.withHtmlContent(html, "/templates")`

where both image files are inside templates directory in my file system. After generating pdf file logo.png is displayed but background.png is not displayed.  

Got below warnings two times
`com.openhtmltopdf.exception WARNING:: Bad URL given: /background.png`

Can anyone help me how to solve this issue?

**Comment by danfickle** [comment]
Try using `builder.withHtmlContent(html, "/templates/fake-doc.htm")`. See javadoc for `withHtmlContent`:
````java
	/**
	 * Provides a string containing XHTML/XML to convert to PDF.
	 * Note that baseDocumentUri can be null if there are no relative resources, otherwise
	 * should be a uri to a (possibly fake) document that is used to resolve relative resources.
	 * Examples:
	 *   <code>file:///Users/user/my-dummy-doc.html</code>,
	 *   <code>file:/C:/Users/me/Desktop/dummy.html</code>
	 *
	 * @param html the HTML text to use.
	 * @param baseDocumentUri the base document URI to resolve future relative resources (e.g. images)
	 * @return this for method chaining
	 */
````

**Comment by danfickle** [comment]
Or even `file:///templates/fake-doc.htm` as its meant to be a uri.

**Comment by danfickle** [comment]
OK, closing now. Please reopen if required.
