### ISSUE TITLE
Unicode character Issue

### ISSUE THREAD

**Issue by abhi0476** [danfickle/openhtmltopdf#70]
If html contains some character like  → ,it shows # instead.
Can you please suggest a fix

**Comment by danfickle** [comment]
Hi @abhi0476 

You need to provide a font that can render the character in question. This font file is specified via a font-face rule. It can be the primary font for the given text or one of the fallback fonts.

**Comment by danfickle** [comment]
Example at [font-face example](https://github.com/danfickle/openhtmltopdf/issues/20#issuecomment-210754469)

**Comment by abhi0476** [comment]
@danfickle 
Thanks for the reply. Fixed it using the method: builder.useFont
However it takes some time to load the font.

**Comment by kumarvgit** [comment]
Hello,
We are sing the great FOSS openhtmltopdf :) thanks for providing.
Currently we are using verdana font but greater than equal to symbol is not printer rendered PDF. \u2264 and \u2265.

**Comment by taras19921** [comment]
Hi all,

I have a problem with unicode characters. In PDF file I see "#"  instead of "ă" or "ș" .
How I can fix it? Thank you.

**Comment by taras19921** [comment]
I have ocrb10 font in my html template. @font-face { font-family: ocrb10; src: url('${host}/ocrb10.ttf') } I've tried to add 'unicode-range: U+?????;' to this font-face but it doesn't work. I still see "#"  instead of "ă" or "ș" I can not find ocrb10 font in Unicode.

**Comment by danfickle** [comment]
Hi,

```unicode-range``` is not supported. Things to check:

+ The embedded font is true type and contains the missing characters.
+ The element where the missing characters are used actually is using the embedded font in its ```font-family``` property.

For other tips, see the fonts wiki page:
https://github.com/danfickle/openhtmltopdf/wiki/Fonts

**Comment by MichaelZaleskovsky** [comment]
Hi! I have same problem now with openhtmltopdf.
I want to get PDF from html, which contains cyrillic. I use this library in servlet.
But I have same result - the cyrillic simbols converted to # 

I use pdfBulider in this way: 
            pdfBuilder
                    .useFastMode()
                    .withHtmlContent(html, "/")
                    .toStream(stream)
                    .run();
and html string contains:
<style>
                @font-face {
                    font-family: "PT Sans";
                    src: url("https://fonts.googleapis.com/css?family=PT+Sans&amp;subset=cyrillic ");               
                }
                body {
                    font-family:  'PT Sans', Geneva, Arial, Helvetica, sans-serif;
               }
</style>
But it doesn't help me.
Could you help me - what is the problem?

**Comment by alexvrv** [comment]
Any tips for this problem? I have the same problem, can't get rid of #....

com.openhtmltopdf.exception WARNING:: Bad URL given: /ocrb10.ttf => java.net.URISyntaxException:: missing protocol for URI: /ocrb10.ttf
