### ISSUE TITLE
The entity name must immediately follow the '&' in the entity reference.

### ISSUE THREAD

**Issue by fensefernando** [danfickle/openhtmltopdf#705]
Hi!

I have problem with '&' character. do you have an idea how to solve this?

**Comment by danfickle** [comment]
In xml and html the & character marks the beginning of an escape sequence known as an entity. Typically, your template engine should take care of converting user input text into escaped xml. If not, you can use an escape method[1] from the commons-text library[2].

Of course, you should know how to write xml/HTML yourself. There are five characters you need to remember to escape[3].

This INVALID xml:
````
<div>
A quote is "hello" & that is < 'world' but > apple.
</div>
````

becomes:
````xml
<div>
A quote is &quot;hello&quot; &amp; that is &lt; &apos;world&apos; but &gt; apple.
</div>
````
[1]https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringEscapeUtils.html#escapeXml10(java.lang.String)
[2]https://commons.apache.org/proper/commons-text/
[3]https://en.m.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

**Comment by danfickle** [comment]
OK, assumed solved. Re-open as needed.
