### ISSUE TITLE
nbsp and other HTML entities cause the parser to stop rendering with an INFO only

### ISSUE THREAD

**Issue by Jo3McCarthy** [danfickle/openhtmltopdf#71]
Hi, All;

Running the minimal use example against some markup will not complete successfully.  The parser will occasionally notify, but invariably fail on HTML entities.

One example: 
`...&nbsp;`
Causes this:
> com.openhtmltopdf.load INFO:: Reference to undefined entity: nbsp

And, although it is only an INFO the parsing stops and no further content is rendered.  Has anyone encountered and/or fixed this?

Thanks,

Jo3

**Comment by danfickle** [comment]
Currently HTML entities are not supported by default. Only XML entities. Agreed, this needs to be fixed so please leave issue open. In the mean time, you could use numeric character entities. Or you could try the jsoup parser.

**Comment by davidbio** [comment]
@Jo3McCarthy 
As a temporary workaround and if you can modify or extend the source HTML:
You can add your own entities in the DOCTYPE tag and the library will convert them accordingly:
```xml
<!DOCTYPE definition [
<!ENTITY reg "&#174;">
<!ENTITY diams "&#9830;">
]>
<definition name="dashboard" extends="base.definition">
    <put-attribute name="title" value="Dashboard - CMS &diams; &reg; Galactic NetOne" />
    <put-attribute name="body" value="/WEB-INF/views/dashboard.jsp" />
</definition>
```

Inspired by: http://stackoverflow.com/questions/15858914/entity-was-referenced-but-not-declared
Lists of entities you may want to include: https://www.w3.org/TR/xhtml1/dtds.html#h-A2

**Comment by rahulgurnani** [comment]
Apparently, replacing by "nbsp" by "#160" doesn't help or adding nbsp entity doesn't help

**Comment by danfickle** [comment]
See documentation on doctype here:
https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-examples/src/main/resources/documentation/documentation.md

This documentation needs to be moved to the wiki.

**Comment by rahulgurnani** [comment]
Thanks for the quick response.

**Comment by danfickle** [comment]
Finally added section in integration guide on character entities.
