### ISSUE TITLE
Despite that table defined with the RTL direction, the table still aligned LTR

### ISSUE THREAD

**Issue by mrbora** [danfickle/openhtmltopdf#710]
The tables aren't rendered in the right direction. 

![צילום מסך 2021-05-28 160011](https://user-images.githubusercontent.com/8150625/119987667-f421f880-bfcd-11eb-9938-96fe25800257.png)

**Comment by danfickle** [comment]
Yes, by popular request I will work on tables, especially RTL after the next release. Anyway closing this issue as a duplicate of #123.
