### ISSUE TITLE
Inconsistent font and table cell spacing/sizing/wrapping

### ISSUE THREAD

**Issue by tomatkloudville** [danfickle/openhtmltopdf#714]
Hello,
I currently have dozens of templates designed in HTML and use another tool which generates PDFs which match the HTML styling without any significant differences.   I'd like to switch to using openhtmltopdf embedded in my application but the generated results seem to have issues with font and table cell wrapping, spacing, padding.  I've attached a sample HTML with the generated result from both openhtmltopdf and evo.   You'll notice at least the following differences between the PDF generated with openhtmltopdf vs. Evo/HTML:

1) The margin above the table seems larger
2) Text is wrapping early with openhtmltopdf
3) The table width seems a slight bit larger
4) the background does not cover the whole PDF
5) the image alt text is not displaying

Here is the code I'm using to generate the PDF.  Any suggestions on would be appreciated.

    ByteArrayOutputStream os = new ByteArrayOutputStream();
    PdfRendererBuilder builder = new PdfRendererBuilder();
    builder.useFastMode();
    org.jsoup.nodes.Document d = Jsoup.parse(html);
    W3CDom w3cDom = new W3CDom();
    builder.withW3cDocument(w3cDom.fromJsoup(d), null);
    builder.toStream(os);
    try (PdfBoxRenderer renderer = builder.buildPdfRenderer()){
	    SharedContext context = renderer.getSharedContext();
	    context.setMedia("print");
	    renderer.layout();
	    renderer.createPDF();
    }
    os.toByteArray();

[orderheader.zip](https://github.com/danfickle/openhtmltopdf/files/6571269/orderheader.zip)

Thanks,
Tom

**Comment by danfickle** [comment]
Hi @tomatkloudville,

We do not support these body attributes:
`<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"`. However, you can achieve the same with CSS:

````
<head>
  <style>
    @page {
      margin: 0;
    }
    body {
      margin: 0;
    }
  </style>

</head>
````

Once you have added that and compare with Chrome, it is similar, with only the earlier text wrap and not outputting alt text for broken images being different. Evo outputs everything smaller than this project or Chrome.

As a general note, this project and most paged HTML to PDF renderers will need some tweaking of the HTML passed to them (our readme needs updating!). For example, we do not support `display: flex` or grid layout which have become common.

**Comment by danfickle** [comment]
Closing for now. Please re-open if required.
