### ISSUE TITLE
Replace printStackTrace() in OpenHtmlGvtFont with proper logging

### ISSUE THREAD

**Issue by tfo** [danfickle/openhtmltopdf#715]
Hello,

While analyzing a problem in our system where we use the **openhtmltopdf** re noticed that our logs are heavily polluted with stacktraces that are created through a _e.printStackTrace()_ in in the **OpenHtmlGvtFont** class. Because of our setup we are not able to redirect STDOUT and STDERR into our logging framework. Although the corresponding exception should not happen (according to the code) it would be great if it would be logged using a proper logger and not STDERR.

`
	public OpenHtmlGvtFont(byte[] fontBytes, GVTFontFamily family, float size, Float fontWeight, Float fontStyle) throws FontFormatException {
		Font font;
		
		try {
			font = Font.createFont(Font.TRUETYPE_FONT, new ByteArrayInputStream(fontBytes)).deriveFont(toFontWeight(fontWeight) | toStyle(fontStyle) , size);
		} catch (IOException e) {
			// Shouldn't happen
			e.printStackTrace(); // Although it should not happen, it would be great to use a logger here.
			font = null;
		}

		this.baseFont = font;
		this.fontFamily = family;
	}
`

**Comment by syjer** [comment]
hi @tfo , you are right, I've submitted a PR for fixing this issue ( https://github.com/danfickle/openhtmltopdf/pull/716 ).
