### ISSUE TITLE
Href target="_blank"

### ISSUE THREAD

**Issue by philip-neill** [danfickle/openhtmltopdf#717]
Hello,

first of all i want to thank all of you for the really great Project and it is so easy to use!

My issue is, that i want to have an href in my PDF Doc, which opens a new tab in my Browser.
Is there any way to archieve this?

What i tried so far:
target="_blank"
 onclick="window.open(''https://google.com'', ''_blank'');"

The first try just results in a normal href and the second try is a complete fail.

Thank you so much for your help!

Phil

**Comment by syjer** [comment]
hi @philip-neill , I don't think it's really possible to have a consistent behaviour with the various pdf viewer with the opening of a browser window/tab.

As you are most likely talking about the one embedded in chrome/ff/safari, they all have different behaviour: see https://community.adobe.com/t5/acrobat/open-hyperlinks-inside-embedded-pdf-in-a-new-window/td-p/9975201 .

**Comment by philip-neill** [comment]
Hey @syjer ,
thank you for your response! That clears it up for me, i mean its not nice, but i guess there is no other option and we have to just live with it^^
So i'm closing this, because it isnt a issue with the converter! :)
