### ISSUE TITLE
How to set PDF to horizontal？

### ISSUE THREAD

**Issue by WangYunT** [danfickle/openhtmltopdf#719]
**requirement：**
At present, I have realized to read HTML and export to PDF file, but the format of PDF file is vertical version, do I need to convert it to horizontal version display? What should I do?

**code：**
```
PdfRendererBuilder builder = new PdfRendererBuilder();
        builder.useFastMode();
        builder.testMode(true);
        builder.withHtmlContent(s,"");
        builder.toStream(os);
        builder.useFont(new File("/simsun.ttc"),"SimSun");
        builder.run();
```

**Comment by slovelo** [comment]
Assuming horizontal you mean landscape format, then for my project I added this CSS to my HTML page and this correctly orientated (oriented) my PDF.

```
@page {
    size: A4 landscape;
}
```

**Comment by WangYunT** [comment]
Thank you very much， it worked now. And I output a horizontal PDF file。
