### ISSUE TITLE
[PDF/UA] Marking images as decorative

### ISSUE THREAD

**Issue by JJdeGroot** [danfickle/openhtmltopdf#723]
It would be great if support was added to mark images as decorative.

Right now, alt-text is required for all images. But in some cases, images can be used purely as decoration. In this case, there is no alt-text requirement and they should be marked as decorative.

As far as I know, there is currently no way to do so. If anyone knows a way, please let me know. If there is no way, consider adding support, e.g. having no alt-text attribute or empty alt-text attribute marks the image as decorative.

The PDF specification allows images to be marked as "artifacts" as defined in Section 14.8.2.2 (Real Content and Artifacts) in PDF 1.7 (ISO 32000-1). An artifact is explicitly distinguished from real content by enclosing it in a marked-content sequence with the `/Artifact` tag.

For more information, see: https://www.w3.org/TR/WCAG20-TECHS/PDF4.html

**Comment by danfickle** [comment]
Hi @JJdeGroot,

You can use background images, which are marked as artifacts.

````html
  <div style="background-image: url(../images/image.jpg); background-size: contain; background-repeat: no-repeat; width: 500px; height: 300px;"></div>
````

**Comment by JJdeGroot** [comment]
Hi @danfickle, thanks for the heads up, will start using background-images for images with no alt-text.
