### ISSUE TITLE
com.openhtmltopdf.layout WARNING:: No content limit found

### ISSUE THREAD

**Issue by sophon-aniketos** [danfickle/openhtmltopdf#724]
Hi, I'm having the above warning when rendering the PDF. What could be the cause? It happens when rendering multi page pdf ~and whenever it occurs, it seems like the renderer is using an old cached version of my html template, but only for the last page. Restarting the program doesn't help.~

**Comment by danfickle** [comment]
You have encountered a bug in the table layout code. It usually occurs in complex nested table situations, but we have not been able to create a minimal reproduction. I'm going to work on tables in the near future so any info or sample you can provide that triggers this problem would be helpful.

**Comment by sophon-aniketos** [comment]
@danfickle Thanks for the fast reply. I don't use nested table, I don't think my table is complex, other than I'm using a table in a running element (so that it repeats each page). I can share you some files. How do I contact you privately?

**Comment by sophon-aniketos** [comment]
Update to this issue: The issue mentioned in the first post is actually caused by another bug (I didn't notice I duplicated some parts of the file). After fixing that, the warning seems to be just warning without visible problem.

**Comment by danfickle** [comment]
I'll close now as the content limit warning is covered in other issues. Thanks. Please re-open as required.
