### ISSUE TITLE
run function in PdfRendererBuilder takes long time

### ISSUE THREAD

**Issue by dg8fv2010** [danfickle/openhtmltopdf#726]
I am now using version 1.0.8, and html file is only 8kb. While I'm using openhtmlto pdf, I find run function in PdfRendererBuilder takes about 132321ms to finish, why it takes so much time?

My code for pdf generation is as follow:

            try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
                PdfRendererBuilder builder = new PdfRendererBuilder();
                builder.useFastMode();
                builder.useFont(new FSSupplier<InputStream>() {
                    @Override
                    public InputStream supply() {
                        return this.getClass().getClassLoader().getResourceAsStream("static/fonts/PingFang-SC-Medium.ttf");
                    }
                }, "PingFang-SC-Medium", 400, BaseRendererBuilder.FontStyle.NORMAL, true);
                String htmlName = UUID.randomUUID().toString() + ".html";
                FileUtils.writeStringToFile(new File(htmlName), htmlContent, Charset.defaultCharset());
                file = new File(htmlName);
                builder.withFile(file);
                builder.toStream(os);
                long c1 = System.currentTimeMillis();
                builder.run();
                long c2 = System.currentTimeMillis();
                log.info("c1c2 time:" + (c2 - c1)); // c1c2 time is 132321ms
            } catch (IOException e) {
                FileUtils.deleteQuietly(file);
            }

I also find that when it first run, there are some logs:

> New fonts found, font cache will be re-built
Building on-disk font cache, this may take a while
Finished building on-disk font cache, found 124 fonts
Using fallback font LiberationSans for base font Symbol
Using fallback font LiberationSans for base font ZapfDingbats

Is it because I lack some fonts, are there any ways to make this funchtion faster?

Thank you very much.

**Comment by danfickle** [comment]
132 seconds is extremely slow! Did you manage to solve this?
