### ISSUE TITLE
OpenHTMLToPDF Text has no space in generated PDF

### ISSUE THREAD

**Issue by allabhanuprakashreddy** [danfickle/openhtmltopdf#731]
I am using OpenHTMLToPDF library to generate PDF from HTML.
Few words in my PDF generated doesn't have space in between letters. For example **And** **Certificate**.

![and](https://user-images.githubusercontent.com/55139196/123376930-ed74aa00-d5a8-11eb-81e5-233949c9bc47.png)

![cert](https://user-images.githubusercontent.com/55139196/123376762-a4bcf100-d5a8-11eb-91a4-4d7879455ef5.JPG)

There is no space between letters **A & n**, **r & t**

Below is my sample c# code and the styles I have applied to my HTML.

![code](https://user-images.githubusercontent.com/55139196/123376997-0715f180-d5a9-11eb-9964-fa28cbfc1e87.png)

![Certstyles](https://user-images.githubusercontent.com/55139196/123376820-bd2d0b80-d5a8-11eb-8df0-f5a894ac5379.JPG)

**Comment by syjer** [comment]
hi @allabhanuprakashreddy , I think you opened the issue in the wrong project, this is the *java* version :).

It seems you are using c#, so it's most likely here: https://github.com/vilppu/OpenHtmlToPdf
