### ISSUE TITLE
IMAGE fail to display in the converted PDF

### ISSUE THREAD

**Issue by immanewel** [danfickle/openhtmltopdf#735]
I am having trouble creating a document with an image,  I have gone through the conde sandbox at https://sandbox.openhtmltopdf.com/ and noticed that the image needs to be prefixed with a keyword image: 

 **&lt; img src="image:qr.png" alt="Visiting aliens (friendly)" /&gt;**
but it has not worked for me.
I got a warning **com.openhtmltopdf.exception WARNING:: Bad URL given: image:qr.png**. 

I also tried using base64  **&lt; img src='data:image/png;base64,"+sign+"' alt='Red dot' / &gt;** without success.

The list of dependencies follows

        **<dependency>
            <groupId>com.openhtmltopdf</groupId>
            <artifactId>openhtmltopdf-core</artifactId>
            <version>1.0.9</version>
        </dependency>

        <dependency>
            
            <groupId>com.openhtmltopdf</groupId>
            <artifactId>openhtmltopdf-pdfbox</artifactId>
            <version>1.0.9</version>
        </dependency>**

Any help would really be appreciated

**Comment by danfickle** [comment]
Hi @Emma-Jay,

In the sandbox the `image:` protocol is a specially registered stream handler. It is not a standard URL protocol and won't work generally (I must add a comment about this in the sandbox example). However, you should be able to use other protocols such as `file:`, `http:` and `data:` in your own projects. If a particular image is not working, please try a few others to see if that particular image is not supported or if it something not working with all images.

**Comment by immanewel** [comment]
@danfickle, 
thank you so much for the clarification it works fine now.
