### ISSUE TITLE
In line font color not printing specified color code,

### ISSUE THREAD

**Issue by mgabhishek06kodur** [danfickle/openhtmltopdf#736]
I'm tried to print font with color it is not printing specified font color, in inline style

import org.jsoup.Jsoup;
import org.jsoup.helper.W3CDom;
import org.w3c.dom.Document;
import com.lmats.oms.reports.pdfreports.PdfReportUtils;
import com.lmats.oms.reports.pdfreports.ReportPage;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;

	private static String htmlToPdf(String inputHTML, String outputPdf) throws IOException {
		Document doc = html5ParseDocument(inputHTML);
		String baseUri = FileSystems.getDefault().getPath(AppConstants.GENERAL_SECTION5TEMP).toUri().toString();
		OutputStream os = new FileOutputStream(outputPdf);
		PdfRendererBuilder builder = new PdfRendererBuilder();
		builder.withUri(outputPdf);
		builder.toStream(os);
		builder.useFont(new File(AppConstants.FOLDER_FONTS + "Calibri.ttf"), "Calibri");
		builder.withW3cDocument(doc, baseUri);
		builder.run();
		logger.debug("PDF generation completed in html to pdf");
		os.close();
		return outputPdf;
	}

	private static Document html5ParseDocument(String inputHTML) throws IOException {
		org.jsoup.nodes.Document doc;
		logger.debug("parsing ...");
		doc = Jsoup.parse(new File(inputHTML), "UTF-8");
		logger.debug("parsing done ..." + doc);
		return new W3CDom().fromJsoup(doc);
	}

**Comment by mgabhishek06kodur** [comment]
[file:///C:/apps/lmats_tmp/filesDump/generalSection5-16-07-2021-10-03-42AM.htm](url)

**Comment by danfickle** [comment]
Could you post the HTML in question? It should look something like:

````
<span style="color: #f1f100;">some text</span>
````

**Comment by mgabhishek06kodur** [comment]
<html> 
 <head> 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
  <title>GENTest - Test observations and results</title> 
  <style type="text/css" media="print">

* {margin:10; padding:0; outline:2px dashed blue}
body {font-size:12px;font-family:'Calibri'; margin:25px; background:#fff; color:#091f30}
.testObservationsAndResults {font-size:12px;text-align:justify}
.testComments {font-size:12px;text-align:justify}
li{
font-weight:700;
 font-weight:normal;
 margin-left: 100px;
}
ol li ol li{
    margin-left: 20px;
}

@font-face {
  font-family: myFont;
}
.fontclass{
  font-family: myFont;
}
@Page {
  size: 8.5in 11in;
  margin: 1in;
}

@Page {
  size: 8.5in 11in;
  margin: 1in;
}

.content-box
{
	background-repeat:repeat-y;
	background-position: center;
	background-attachment:fixed;
	background-size:100%;
}
</style> 
 </head> 
 <body> 
  <div id="content" class="content-box" style="background-image:url('Draft.PNG')"> 
   <p style="font-weight:bold;font-size:12px;margin-bottom:15px;font-family:Calibri">Test observations and results </p> 
   <p class="testObservationsAndResults" style="font-weight:bold;font-size:12px;margin-bottom:15px;font-family:Calibri"> </p>
   <h1 style="box-sizing: inherit; margin-bottom: 1.5em;">?<span style="font-size: 24px;"><b>
      <strike>
       T
      </strike></b></span><span style="font-size: 18px;"><font color="#030338">racking and monitoring <span style="font-size: 9px;"><i>orders</i></span> is perhaps the most<span style="background-color: rgb(198, 123, 165);">
       <strike style="">
         fundamental aspect of any OMS
       </strike></span>. Once an ecommerce <u style="background-color: rgb(247, 198, 206);">brand grows</u> beyond </font><font color="#ff0000">the smallest size</font><font color="#030338">, it needs some kind of</font><i style=""><b style="background-color: rgb(255, 255, 0);"> system</b></i><font color="#030338"> to handle orders. </font><font color="#ff0000" style="background-color: rgb(255, 255, 0);">Even the most proficient</font><font color="#030338">, on-the-ball worker can?t keep all </font><font color="#00ff00">order details in their head</font><font color="#030338">.</font></span></h1>
   <ol>
    <li style="box-sizing: inherit; margin-bottom: 1.5em;"><span style="font-size: 24px; background-color: rgb(255, 255, 0);"><sup style="">At heart, an OMS is about making life easier for both a brand and its customers. The correct system can create a more seamless customer experience. It can also make inventory management, logistics, and more processes far more intuitive.</sup></span></li>
   </ol>
   <p class="" style="box-sizing: inherit; margin-bottom: 1.5em;"><span style="font-size: 14px;"><span style="background-color: rgb(255, 255, 255);"><font color="#0000ff">The placement and handling of orders impact many other elements of your business. Every order placed and fulfilled, for instance, affects your inventory.</font></span> Getting&nbsp;</span><a href="https://www.brightpearl.com/inventory-management" target="_blank" rel="noopener" data-wpel-link="internal" style="box-sizing: inherit;">inventory management</a><span style="font-size: 14px;">&nbsp;correct is vital for any ecommerce brand.</span></p>
   <p style="box-sizing: inherit; margin-bottom: 1.5em;"><span style="font-size: 18px;"><b><u><i>If you don?t have an accurate measure of your inventory, a range of issues can arise</i></u></b></span></p>
   <ul data-rte-list="default" style="box-sizing: inherit; margin-right: 0px; margin-bottom: 1.5em; margin-left: 0px; list-style-position: initial; list-style-image: initial; padding-left: 1.2rem;">
    <li style="box-sizing: inherit; margin-bottom: 0.5rem;"><p class="" style="text-align: center; box-sizing: inherit; margin-bottom: 0px;"><i><span style="box-sizing: inherit;">Overselling ?&nbsp;</span>Accepting orders for products of which you don?t have adequate stock to fulfill. Doing so leads to canceling those orders and disappointing customers.</i></p></li>
    <li style="box-sizing: inherit; margin-bottom: 0.5rem;"><p class="" style="text-align: center; box-sizing: inherit; margin-bottom: 0px;"><i><span style="box-sizing: inherit;">Overstocking ?</span>&nbsp;Thinking you?re short of a product and over-ordering replacement inventory. This means you waste valuable warehouse space and could get left with dead stock.</i></p></li>
    <li style="box-sizing: inherit; margin-bottom: 0px;"><p class="" style="text-align: center; box-sizing: inherit; margin-bottom: 0px;"><i><span style="box-sizing: inherit;">Inaccurate Forecasting ?</span>&nbsp;If you don?t have accurate inventory figures, it?s harder to understand customer demand. You may miss when there?s an uptick in desire for a particular product. That could see you run out of stock when you might have pre-empted the increased demand.</i></p></li>
   </ul> 
   <p></p> 
   <br>
   <br> 
   <p style="font-weight:bold;font-size:12px;margin-bottom:15px;font-family:Calibri">Test comments </p> 
   <p class="testComments" style="font-weight:bold;font-size:12px;margin-bottom:15px;font-family:Calibri"> </p>
   <h3 style="box-sizing: inherit; clear: both; margin: 0px 0px 1.2rem; font-family: bp-int-bold, -apple-system, BlinkMacSystemFont, Helvetica, Roboto, " segoe ui", arial, sans-serif; text-rendering: optimizelegibility; color: rgb(3, 3, 56); line-height: 1.5; font-size: 1.3125rem;"><b><i><span style="font-size: 24px; background-color: rgb(107, 173, 222);">Encompass Reverse Logistics </span></i></b></h3>
   <h3 style="text-align: justify; box-sizing: inherit; clear: both; margin: 0px 0px 1.2rem; text-rendering: optimizelegibility; line-height: 1.5;"><b>
     <strike>
      <font color="#e7d6de" style="background-color: rgb(165, 198, 206);">All ecommerce businesses know that returns are an inevitability. Approximately 30% of products bought online get returned. That?s as compared to less than 10% bought in-store. Handling returned items and dealing with the customers who sent them back is vital to order management. With the right OMS, reverse logistics becomes much more straightforward. A top-class system gives you many options in this regard. You may, for instance, be able to clone an original order to create a credit instantly. That makes it more straightforward to manage refunds, replacements or reorders. An OMS, too, makes it more intuitive to fold reverse logistics into inventory management. Depending on what?s returned, the system can give you a range of options. It may write off stock that?s sent back, quarantine it, or add it back to your inventory on-hand.</font>
     </strike></b></h3>
   <h3 style="box-sizing: inherit; font-family: inherit; font-weight: 500; line-height: 1.5; color: inherit; margin: 0px 0px 1.2rem; font-size: 24px; text-align: justify; clear: both; text-rendering: optimizelegibility;"><span style="box-sizing: border-box; background-color: rgb(255, 255, 0);"><font color="#e7d6de" style="box-sizing: border-box;">All ecommerce businesses know that returns are an inevitability. Approximately 30% of products bought online get returned. That?s as compared to less than 10% bought in-store. Handling returned items and dealing with the customers who sent them back is vital to order management. With the right OMS, reverse logistics becomes much more straightforward. A top-class system gives you many options in this regard. You may, for instance, be able to clone an original order to create a credit instantly. That makes it more straightforward to manage refunds, replacements or reorders. An OMS, too, makes it more intuitive to fold reverse logistics into inventory management. Depending on what?s returned, the system can give you a range of options. It may write off stock that?s sent back, quarantine it, or add it back to your inventory on-hand.</font></span></h3>
   <div style="box-sizing: border-box; text-align: justify;">
    <br style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
   </div>
   <h3 style="text-align: justify; box-sizing: inherit; clear: both; margin: 0px 0px 1.2rem; text-rendering: optimizelegibility; line-height: 1.5;"><span style="background-color: rgb(255, 255, 0);"><font color="#e7d6de"></font></span></h3>
   <div style="text-align: justify;">
    <br>
   </div> 
   <p></p> 
  </div>  
 </body>
</html>

**Comment by mgabhishek06kodur** [comment]
<font color="#e7d6de" style="background-color: rgb(165, 198, 206);">All ecommerce businesses know that returns are an inevitability. Approximately 30% of products bought online get returned. That?s as compared to less than 10% bought in-store. Handling returned items and dealing with the customers who sent them back is vital to order management. With the right OMS, reverse logistics becomes much more straightforward. A top-class system gives you many options in this regard. You may, for instance, be able to clone an original order to create a credit instantly. That makes it more straightforward to manage refunds, replacements or reorders. An OMS, too, makes it more intuitive to fold reverse logistics into inventory management. Depending on what?s returned, the system can give you a range of options. It may write off stock that?s sent back, quarantine it, or add it back to your inventory on-hand.</font>

**Comment by mgabhishek06kodur** [comment]
<p class="" style="box-sizing: inherit; margin-bottom: 1.5em;"><span style="font-size: 14px;"><span style="background-color: rgb(255, 255, 255);"><font color="#0000ff">The placement and handling of orders impact many other elements of your business. Every order placed and fulfilled, for instance, affects your inventory.</font></span> Getting&nbsp;</span><a href="https://www.brightpearl.com/inventory-management" target="_blank" rel="noopener" data-wpel-link="internal" style="box-sizing: inherit;">inventory management</a><span style="font-size: 14px;">&nbsp;correct is vital for any ecommerce brand.</span></p>

**Comment by mgabhishek06kodur** [comment]
[samplehtmltext.txt](https://github.com/danfickle/openhtmltopdf/files/6829200/samplehtmltext.txt)

**Comment by danfickle** [comment]
Hi @mgabhishek06kodur,

We don't support the attributes on the ancient `font` tag. However, if you can't use CSS instead in your template, you can use a DOM mutator to change the document at runtime. Here is one I just created:

````
        FSDOMMutator domChanger = (doc) -> {
            NodeList fontTags = doc.getElementsByTagName("font");

            for (int i = 0; i < fontTags.getLength(); i++) {
                Element fontTag = (Element) fontTags.item(i);

                if (fontTag.hasAttribute("color")) {
                    String color = fontTag.getAttribute("color");

                    if (!fontTag.hasAttribute("style")) {
                        fontTag.setAttribute("style", "color: " + color + ';');
                    } else {
                        String oldStyle = fontTag.getAttribute("style");
                        String newStyle = oldStyle + "; color: " + color + ';';

                        fontTag.setAttribute("style", newStyle);
                    }
                }
            }
        };
````

Then, you can register with:
````
builder.addDOMMutator(domChanger);
````

P.S. To paste code or HTML in comments, put it in a code block. A code block starts with four backticks on their own line, followed by the HTML, then four more backticks on their own line. This is a backtick: `

Also added [FAQ entry on dom mutators](https://github.com/danfickle/openhtmltopdf/wiki/FAQ---Tips#modifying-unsupported-html-at-runtime)

**Comment by danfickle** [comment]
Assumed solved. Please reopen as required.
