### ISSUE TITLE
Empty Tags

### ISSUE THREAD

**Issue by MichelFortes** [danfickle/openhtmltopdf#737]
Hello.

Some HTML empty tags (like <br> and <img>) are causing XRRuntimeException.
Is there a way to avoid that error? Maybe some configuration.
Thank you, guys.

**Comment by danfickle** [comment]
By default this library requires valid XML, which means end tags or self closing tags are required. If you can't satisfy that constraint you can use Jsoup to parse HTML5. See the [integration guide](https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide#html5-parser-support).

**Comment by MichelFortes** [comment]
The integration guide makes it all clear indeed.
I should have read it before asking for help. Sorry for that.
Thank you!
