### ISSUE TITLE
Support for element grouping

### ISSUE THREAD

**Issue by AndreasJacobsen** [danfickle/openhtmltopdf#738]
I am generating a very long pdf (100+ pages) and I want to group elements in this pdf using standard PDF grouping tags. 

These are _Part, Art, Sect, Div_ 

See [pdfa.org](https://www.pdfa.org/wp-content/until2016_uploads/2015/12/StructureElementsBestPracticeGuide_2016-01-19.pdf) for more information. 

I tried searching for any documentation on how to use standard PDF tags but found none, so I tried to guess the tags. I wrote the following HTML
```html
<html lang="EN-US">
<style>
                body {
    font-family: 'TestFont';
                }
    </style>
<body>
<h1>Testdokument</h1>
<section>
 <p>Section</p>
</section>
<Section>
 <p>Section</p>
</Section>
<sect>
 <p>sect</p>
</sect>
<Sect>
 <p>Sect</p>
</Sect>
<Art>
 <p>Art</p>
</Art>
<art>
 <p>art</p>
</art>
<part>
 <p>part</p>
</part>
<Part>
 <p>Part</p>
</Part>
</body>
</html>
```
This HTML produces the following tag tree, no section, part or art tags are present.
![tag tree showing none of the pdf tags used](https://user-images.githubusercontent.com/8527173/126978426-4ffea6b9-648f-4ef6-b0f2-6c1ea13ade84.png)

Attached bellow is a screenshot of a PDF that contains the use of the Sect-elemt, this is what I want.  
![Screenshot of tag tree with section tags](https://user-images.githubusercontent.com/8527173/126978673-0b8476f0-6e51-402d-a414-44847379fc10.png)

Are PDF tag grouping not supported? 
Grouping can drasticly increase ease of use, especially in long documents, for a wide range of users of assistive technologies. 

I've set my conformance level to PDFA_3_A
`builder.usePdfAConformance(PdfRendererBuilder.PdfAConformance.PDFA_3_A); `

**Comment by danfickle** [comment]
Hi @AndreasJacobsen,

I've just added support for art, part, sect, section (alias for sect), caption and blockquote tags in 7ab966e. You can use art currently with `<article>` and you may be able to use sect with `position: relative` CSS as it uses sect for out-of-flow content.

**Comment by AndreasJacobsen** [comment]
I'll make a pull request for the wiki once I have tested this, thanks danfickle! 

My Java skills are sadly pretty much non-existent so I'll wait till this is merged to main and I can update my maven packages to test and document.

**Comment by AndreasJacobsen** [comment]
Any idea when this will be available on Maven @danfickle? I don't want you to rush it, I just need to do some planning :)
