### ISSUE TITLE
Can't see images from html file on the pdf

### ISSUE THREAD

**Issue by JPizarro14** [danfickle/openhtmltopdf#739]
Hi all!
I'm using openhtmltopdf to generate a pdf from an html file.
The point is that I can't see the images on the pdf.

Here is my resources folder:
![image](https://user-images.githubusercontent.com/36504551/127469340-c07730f7-0cbc-40ae-a804-72dcc7918aea.png)

And here is the html code:
Example with src path:
```
<html>
  <body>
    <div>
        <img src="../img/logo.png" width="30%"/>
    </div>
  </body>
</html>
```

Example with image as B64 string:
```
<!DOCTYPE html>
<html>
  <body>
  	<div>
  		 <img src="data:image/png;base64, BASE64STRING" width="30%" />
  	</div>
  </body>
</html>
```

I see the logo properly on the html, but I don't see the image on the pdf.

To generate the pdf I'm using this example right here:
https://stackoverflow.com/a/64777489/6418839

Thank you very much!
Best regards!

**Comment by danfickle** [comment]
Hi @JPizarro14,

Could you try with the below code (modify paths as needed)/html/image and see if it works?

I'm using this code on Windows 10 with success:

````java
        try (OutputStream os = new FileOutputStream("C:\\Users\\me\\Desktop\\out\\app12.pdf")) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.withUri("file:///C:/Users/me/desktop/html/image.html");
            // Also works:
            // builder.withFile(new File("C:\\Users\\me\\Desktop\\html\\image.html"));
            builder.toStream(os);
            builder.useFastMode();
            builder.run();
        }
````

````html
<html>
<body>
<img src="../images/image.png" alt="My Image"/>
</body>
</html>
````

And this image:
https://commons.wikimedia.org/wiki/File:Example.png

**Comment by JPizarro14** [comment]
Hi Dan! 

I've solved the issue. The problem was that the resources target with all the images wasn't located on target folder. I've modified the pom.xml file and it works correctly.

Thank you very much for your response.
