### ISSUE TITLE
Charts in PDF / e.g. Charts from Primefaces

### ISSUE THREAD

**Issue by rider87** [danfickle/openhtmltopdf#741]
Hi all,

I tried that, but it´s not working.
I´m trying to render charts from Primefaces:

E.g. http://www.primefaces.org:8080/showcase/ui/chartjs/bar/bar.xhtml

In HTML content it´s generating:
`<canvas id="j_idt173:2:j_idt509_canvas" style="width: 1256px; height: 1256px; display: block;" width="1256" height="1256" class="chartjs-render-monitor"/>`

Is this possible? Do I need to enable something in the code?
If not: any alternatives? Any plan to integrate this?

Thanks

**Comment by syjer** [comment]
hi @rider87 , openhtmltopdf is not a web browser, it will not run javascript (and thus not understand the canvas element), you need to provide some custom made html.

So it's not possible to throw some canvas related code.

Alternatives:
 - use: https://github.com/danfickle/openhtmltopdf/wiki/Plugins:-JFreeChart
 - generate the charts as svg and enable the svg support: https://github.com/danfickle/openhtmltopdf/wiki/Plugins:-SVG-Images

**Comment by danfickle** [comment]
Thanks @syjer. Closing now as assumed solved. Please reopen as required.
