### ISSUE TITLE
'Greater/Less-than or equal to' Character Entities Not Printing

### ISSUE THREAD

**Issue by rossnewby** [danfickle/openhtmltopdf#746]
Using both the 'greater-than or equal to' and 'less-than or equal to' entity result in a '#' printed in the PDF. This is the case with both the character entities eg `& ge;` and HTML codes eg `& #8805;`

I am correctly using the special project doctype (https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide#character-entities), as other character entities such as the degree sign `& deg;` are working fine

**Comment by syjer** [comment]
hi @rossnewby , generally if you get a '#' symbol, it mean the current font does not support the character. Have you tried another font?

**Comment by danfickle** [comment]
Note: You can get the [Stix math fonts here](https://github.com/danfickle/openhtmltopdf/issues/161#issuecomment-365844595).

Closing now. Please reopen if required.
