### ISSUE TITLE
I have followed your guide for MINIMAL USAGE, and I get this error.

### ISSUE THREAD

**Issue by mrtauern** [danfickle/openhtmltopdf#751]
![Capture](https://user-images.githubusercontent.com/36842006/130780955-9530f8e9-093e-41a6-871c-b74245318807.PNG)

**Comment by syjer** [comment]
hi @mrtauern, most likely your pom.xml is not correct as you are missing the dependencies.

Ensure that you have:

```xml
<properties>
  		<!-- Define the version of OPEN HTML TO PDF in the properties section of your POM. -->  	       
  		<openhtml.version>1.0.9</openhtml.version>
  	</properties>

  	<dependency>
  		<!-- ALWAYS required, usually included transitively. -->
  		<groupId>com.openhtmltopdf</groupId>
  		<artifactId>openhtmltopdf-core</artifactId>
  		<version>${openhtml.version}</version>
  	</dependency>
  	
  	<dependency>
  		<!-- Required for PDF output. -->
  		<groupId>com.openhtmltopdf</groupId>
  		<artifactId>openhtmltopdf-pdfbox</artifactId>
  		<version>${openhtml.version}</version>
  	</dependency>
```
And the changes have been applied by Intellij Idea (which may not be automatic).

Your "External library" section should contains something like that:

![Screenshot from 2021-08-26 10-50-20](https://user-images.githubusercontent.com/498146/130932602-fac0315b-71f6-4772-80bf-b12bdb3c7743.png)

**Comment by danfickle** [comment]
Thanks again @syjer. Closing as assumed solved. Please reopen if required.
