### ISSUE TITLE
Latest version not published to Maven repo?

### ISSUE THREAD

**Issue by ThomHurks** [danfickle/openhtmltopdf#766]
Hi! First of all, thanks for working on this very useful library.

I’m not very well-versed in the Maven ecosystem, but if I look for this library on search.maven.org (which we use to sync a private repo), the latest version is not on there.

See: https://search.maven.org/search?q=g:com.openhtmltopdf%20AND%20a:openhtmltopdf-parent

The latest version there is 1.0.9. Is this an issue with publishing this library or is it the repo’s problem? Thanks!

**Comment by danfickle** [comment]
I'm sure it's there! I'm using it on the sandbox (which is built on a different machine). This maven search engine shows it:

https://mvnrepository.com/artifact/com.openhtmltopdf

**Comment by ThomHurks** [comment]
Thanks for your quick response! Is it an issue with the search engine (index?) at maven.org then? If it is and cannot be helped easily I would need to find some kind of workaround in my project.

**Comment by danfickle** [comment]
I think you should be able to read the metadata from the repo directly:

https://repo1.maven.org/maven2/com/openhtmltopdf/openhtmltopdf-parent/maven-metadata.xml

**Comment by ThomHurks** [comment]
Thanks! In the mean time the search index still only has 1.0.9 so I guess maven.org’s search index is pretty unreliable. We’ll find a workaround like what you suggested :)

**Comment by ThomHurks** [comment]
FYI, I raised an issue with Sonatype and they fixed the indices :) https://issues.sonatype.org/browse/MVNCENTRAL-6985
