### ISSUE TITLE
Table of Content does not support multi-line title

### ISSUE THREAD

**Issue by BenjaminVega** [danfickle/openhtmltopdf#771]
Hi!

Thanks for this amazing library. I am trying to generate a table of content using ´target-text´ text that I added months ago. like this:
`#five::after { content:  target-text(attr(href)) leader(dotted)  target-counter(attr(href), page); }`
`<a id="five" href="#title" style="display: inline-block;width: 100%;"></a>`
`<h1 id="title" style="font-size: medium">Title 1</h1>`
Resulting in :

Title 1 . . . . . . . . . . . . . . . . . 2

 It just happen that the targeted text was a very long and then I started having errors.

My expectations were to see the title line being broken into two or more lines but it did not happen. Actually it throw an exception saying something about a negative length. (java.lang.NegativeArraySizeException: -78). After investigating the exception, this is thrown while calculating how many dots to append before the page number . That happens because the Text line is longer than the space of the page. Then I realised I needed to break the lines. I tried it  like this:
![image](https://user-images.githubusercontent.com/34217810/135634388-4630e641-33fa-4261-ba1f-94a19b5a61a0.png)

As you can see, the title itself is not being broken into lines. I have tried adding '\A' and white-space: pre in the `target-text` function to break the line manually  when it extract the tex but it just print it literarily. 

Do you have any suggestion ?

Thanks

**Comment by danfickle** [comment]
Hi @BenjaminVega,

I've started work in PR #773 fixing this. You're right, it is completely broken in the case of multi-line text.

As for a workaround, perhaps you could try putting it in a div with border-bottom set and floating the page number to the right?

**Comment by BenjaminVega** [comment]
Thanks for the answer!

Looking forward togive a go to that PR. In the meanwhile, I will try with that solution.
