### ISSUE TITLE
PDF with multiple pages is generated with broken content

### ISSUE THREAD

**Issue by varshaldavda** [danfickle/openhtmltopdf#776]
I am using openhtmltopdf v1.0.2 . I am converting html to pdf. The generated PDF can be generated with multiple pages but content on the pages is broken, like table cell is divided into 2 pages. Here is my source code

```
try (OutputStream os = new FileOutputStream(file)) {
   PdfRendererBuilder builder = new PdfRendererBuilder(); //
   builder.useDefaultPageSize(210, 297, BaseRendererBuilder.PageSizeUnits.MM);
   builder.withHtmlContent(html, "UTF-8");
   builder.toStream(os);
   builder.run();			 
}
```

I am not defining any css property for A4 page size in html.

I am sharing PDF snapshot of the problem.

![image](https://user-images.githubusercontent.com/8014085/136356956-36105595-2140-45a7-bc0f-8acc9b31fc95.png)

**Comment by varshaldavda** [comment]
I could fix this issue by adding below css property in table cell.

```
page-break-inside: avoid; 
page-break-after: avoid; 
page-break-before: avoid
```

Closing this issue.


Thanks,
Varshal Davda

**Comment by christian-draeger** [comment]
Thx for sharing @varshaldavda. I had the same problem :)
