### ISSUE TITLE
Will openhtmltopdf-core be supported?

### ISSUE THREAD

**Issue by jansorg** [danfickle/openhtmltopdf#88]
Will the  openhtmltopdf-core module be kept and supported?
I'm wondering whether I could switch from flyingsaucer to openhtmltopdf but I'm not sure about the policy.
If Swing rendering won't be supported in the future it would be good to know.

**Comment by danfickle** [comment]
We were planning on removing the interactive features and just output to images and PDFs. Could I ask why you can not use Java 8's web view?

Regards,
Daniel.

**Comment by jansorg** [comment]
@danfickle Thanks. I've tried to use Java's webview but since I'm working on a Swing application the required JavaFX->Swing wrapper had some issues which prevent it's use (scrollbar, click handling and possibly others).
I'm closing this now.
