### ISSUE TITLE
Add a way to render directly to PDF/A 1-3

### ISSUE THREAD

**Issue by schmitch** [danfickle/openhtmltopdf#92]
Currently it would be great if there was a way to have a PDF/A-3 output without calling into PDFBox.

**Comment by ebruchez** [comment]
@schmitch I am curious to know if you found a way of creating PDF/A with Open HTML to PDF?

**Comment by schmitch** [comment]
@ebruchez sadly without patching openhtmltopdf it would not be possible.

Currently the only way to do it is to change the font loading to use `PDTrueTypeFont` instead of `PDType0Font` and use the WinAnsi Encoding. After that some needs to add a method, so instead of `run()` or `createPDF()` the `PDDocument` needs to be returned and metadata needs to be added.

**Comment by ebruchez** [comment]
@schmitch Thanks, those are good pointers though.

**Comment by harbulot** [comment]
Sorry, I don't know much about PDF/A, but I've noticed that the patch in PR #131 seems to break using CJK fonts.

I don't know whether [this validator](https://www.pdf-online.com/osa/validate.aspx) is correct, but I've tried a PDF generated with the latest commit (0c76faba77ee1735cd823281121273731e6d6049), without this PR, and it passes the validation.

This is the test, and I load both `OpenSans-Regular.ttf` and `cwTeXFangSong-zhonly.ttf`:

```html
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
* {
    font-family: 'Open Sans', cwTeXFangSong;
}
</style>
</head>
<body>
    <h2>Test: cwTeXFangSong</h2>
    <div style="width: 80%; border: 1px solid black;">
        <p>含有中文字符的html输出pdf有乱码</p>
        <p>有支持中文的计划吗？</p>
    </div>
</body>
</html>
```

This is what Adobe Reader sees for the embedded fonts:

![image](https://user-images.githubusercontent.com/80994/30607812-35b26e64-9d6e-11e7-8fd8-1cd04a775177.png)

Just out of curiosity, what's wrong with these fonts?

**Comment by schmitch** [comment]
the online validator is broken you either need to use https://github.com/veraPDF/veraPDF-library or have a Adobe Pro License. currently with PdfType0Font the CIDSet is incorrect for PDF/A actually you also need to change openhtmltopdf to render to a PDF/A

**Comment by danfickle** [comment]
I think the trouble is that PDF-box does not include a ````CIDSet```` entry which is required for PDF/A conformance, and not much else [1]. The correct solution would be to file a issue with PDF-box to get them to implement this feature, probably behind a flag.

We certainly can’t throw away support for non-Latin characters by using win ansi encoding.

As to the issue of the required meta data, I would be happy to add it if someone can compile a list.

[1] https://forums.adobe.com/thread/1559022

**Comment by schmitch** [comment]
Hm. I'm aware of the issue of non-Latin characters, but I guess as of now there is no way to do it without it, maybe we can change the whole font inclusion to support win ansi encoding font's, before pdfbox is fixed (an experimental feature maybe).

After that we need to set a color profile and I'm not sure if there is one that has a license that would match closely to the license of openhtml-to-pdf. 

And then we need to have a dependency on xmpbox to include xmp metadata.

**Comment by schmitch** [comment]
For the CIDSet issue we should probably await pdfbox 2.0.8 https://issues.apache.org/jira/browse/PDFBOX-3920

**Comment by zutnop** [comment]
PDFBox 2.0.8 has been released.

**Comment by schmitch** [comment]
Closing since it's possible to do with:
```java
            renderer.createPDFWithoutClosing();
            document = renderer.getPdfDocument();
            PDMetadata metadata = new PDMetadata(document);
            metadata.importXMPMetadata(createXMPMetaData("Titel"));
            document.getDocumentCatalog().setMetadata(metadata);

            // sRGB output intent
            InputStream colorProfile = PdfCreator.class.getResourceAsStream("sRGB.icc");
            PDOutputIntent intent = new PDOutputIntent(document, colorProfile);
            intent.setInfo("sRGB IEC61966-2.1");
            intent.setOutputCondition("sRGB IEC61966-2.1");
            intent.setOutputConditionIdentifier("sRGB IEC61966-2.1");
            intent.setRegistryName("http://www.color.org");
            document.getDocumentCatalog().addOutputIntent(intent);

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            document.save(baos);
```

and:
```java
private byte[] createXMPMetaData(String title) throws TransformerException {
        XMPMetadata xmp = XMPMetadata.createXMPMetadata();
        try {
            DublinCoreSchema dc = xmp.createAndAddDublinCoreSchema();
            dc.setTitle(title);
            dc.addCreator("openhtmltopdf");
            PDFAIdentificationSchema id = xmp.createAndAddPFAIdentificationSchema();
            id.setPart(3);
            id.setConformance("B");
            XmpSerializer serializer = new XmpSerializer();
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            serializer.serialize(xmp, baos, true);
            return baos.toByteArray();
        } catch (BadFieldValueException e) {
            // won't happen here, as the provided value is valid
            throw new IllegalArgumentException(e);
        }
    }
```

Basically it's also important to specify a font, to be 100% sure that it gets embedded.
I do not think that openhtmltopdf should add more options than the post-processing via `createPDFWithoutClosing`, because adding the correct color profile and the correct metadata should be done by the user of the library, especially that there is also ZugFerd which needs to further extend the schema.
