### ISSUE TITLE
Not able to Convert Html to Pdf

### ISSUE THREAD

**Issue by Ber1984** [danfickle/openhtmltopdf#930]
I'm trying to generate an pdf from html but i'm getting this error
`can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3; The markup in the document preceding the root element must be well-formed.`
Any ide? 

This is my html
```
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml"
      xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <title></title>
    <!--[if !mso]>
<!-- -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!--
	<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <style type="text/css">

        p {
            margin: 0;
            padding: 0;
        }

        .ft00 {
            font-size: 18px;
            font-family: Times New Roman;
            color: #000000;
        }

        .ft01 {
            font-size: 14px;
            font-family: Arial;
            color: #000000;
        }

        .ft02 {
            font-size: 14px;
            font-family: Arial, BoldItalic;
            color: #000000;
        }

        .ft03 {
            font-size: 14px;
            font-family: Arial, Bold;
            color: #000000;
        }

        .ft04 {
            font-size: 14px;
            font-family: Times New Roman;
            color: #000000;
        }

        .ft05 {
            font-size: 14px;
            font-family: Arial;
            color: #ff0000;
        }

        .ft06 {
            font-size: 10px;
            font-family: Arial, Bold;
            color: #000000;
        }

        .ft07 {
            font-size: 10px;
            font-family: Arial;
            color: #000000;
        }

        .ft08 {
            font-size: 18px;
            line-height: 20px;
            font-family: Times New Roman;
            color: #000000;
        }

        .ft09 {
            font-size: 14px;
            line-height: 17px;
            font-family: Arial;
            color: #000000;
        }

        .ft010 {
            font-size: 14px;
            line-height: 17px;
            font-family: Arial, BoldItalic;
            color: #000000;
        }

        .ft011 {
            font-size: 14px;
            line-height: 17px;
            font-family: Arial, Bold;
            color: #000000;
        }

        .ft012 {
            font-size: 14px;
            line-height: 16px;
            font-family: Arial;
            color: #000000;
        }

        .ft013 {
            font-size: 10px;
            line-height: 11px;
            font-family: Arial;
            color: #000000;
        }

        .ft014 {
            font-size: 10px;
            line-height: 12px;
            font-family: Arial;
            color: #000000;
        }

    </style>
</head>
<body>

<div id="page1-div" style="position:absolute;width:700px;text-align:left;">
    <img style="position:absolute;top:-20px;left:130px;width:600px;height:80px;"
         src="$RUTA_IMG/images/headerCarta.png"/>

    <p style="position:absolute;top:1px;left:127px;white-space:nowrap" class="ft09"><br/><br/>Bogotá $FECHA<br/>
        <br/>Sr (a)</p>
    <p style="position:absolute;top:223px;left:127px;white-space:nowrap" class="ft010"><i><b>$NOMBRE_CLIENTE<br/>$CIUDAD
    </b></i></p>
    <p style="position:absolute;top:309px;left:127px;white-space:nowrap" class="ft012"><br/><br/></p>
    <p style="position:absolute;top:309px;left:127px;white-space:nowrap" class="ft012">Estimado Sr (a) <br/><br/>Es un
        gusto darle la bienvenida a nuestra compañía y felicitarlo por su excelente decisión de contratar</p>
    <p style="position:absolute;top:361px;left:127px;white-space:nowrap" class="ft012">la <b>PÓLIZA DE SEGURO DE
        EMPLEADO PROTEGIDO CRÉDITO DE LIBRANZA</b> exclusivo para</p>
    <p style="position:absolute;top:378px;left:127px;white-space:nowrap" class="ft01">clientes de Bancolombia S.A.</p>
    <p style="position:absolute;top:378px;left:323px;white-space:nowrap" class="ft03"><b> </b></p>
    <p style="position:absolute;top:396px;left:127px;white-space:nowrap" class="ft012"><br/>Cardif Colombia Seguros
        Generales S.A, es una compañía de seguros perteneciente al grupo BNP <br/>Paribas, uno de los grupos financieros
        y aseguradores más importantes del mundo en el mercado <br/>de Bancaseguros. <br/> <br/></p>
    <p style="position:absolute;top:481px;left:127px;white-space:nowrap" class="ft03">La póliza de seguros
        <b>827$CREDITO_NUMERO</b> que ha adquirido contiene el compromiso de su protección por</p>
    <p style="position:absolute;top:499px;left:127px;white-space:nowrap" class="ft09">parte de nuestra compañía y es el
        punto de inicio de una relación en la que dedicaremos nuestro <br/>máximo esfuerzo para lograr su completa
        satisfacción. <br/> <br/>Adjunto encontrará el contrato del seguro que adquirió, al final de este documento
        podrá ubicar un <br/>link y un código QR para acceder al detalle de las coberturas y condiciones particulares de
        su seguro. <br/> <br/>Con el objetivo de acceder a los beneficios de su póliza le invitamos a seguir las
        siguientes <br/>indicaciones: </p>
    <p style="position:absolute;top:638px;left:155px;white-space:nowrap" class="ft04">- Lea su póliza detenidamente,
        beneficios, coberturas, términos y condiciones. Recuerde que <br/>es fundamental que usted esté informado de las
        características de su seguro. </p>
    <p style="position:absolute;top:672px;left:155px;white-space:nowrap" class="ft04">- Verifique que sus datos
        personales estén registrados correctamente. En caso de cualquier <br/>error solicite la corrección en las líneas
        de atención relacionadas en el contrato de seguro. </p>
    <p style="position:absolute;top:706px;left:127px;white-space:nowrap" class="ft09"><br/>Ante cualquier duda,
        información adicional ó ante la ocurrencia de un siniestro o novedad, le <br/>agradecemos se comunique con las
        líneas de atención indicadas en el contrato de seguro.</p>
    <p style="position:absolute;top:741px;left:731px;white-space:nowrap" class="ft05"></p>
    <p style="position:absolute;top:758px;left:127px;white-space:nowrap" class="ft012"><br/> <br/>Finalmente Agradecemos
        su preferencia y confianza en nosotros y esperamos seguir satisfaciendo <br/>sus necesidades de protección y las
        de su familia. <br/> <br/>Cordial saludo, <br/></p>
    <p style="position:absolute;top:780px;left:284px;white-space:nowrap" class="ft10">
        <img style="right: -27px;position:absolute;bottom:-49px;width:120px;height:80px;"
             src="$RUTA_IMG/images/firmaCarta.png"/>
    </p>
    <p style="position:absolute;top:804px;left:127px;white-space:nowrap" class="ft011"><b>Cardif Colombia Seguros
        Generales <br/> </b></p>
    <p style="position:absolute;top:808px;left:127px;white-space:nowrap" class="ft06"><b>Advertencia:</b> Cardif
        Colombia Seguros Generales S.A asume exclusivamente la responsabilidad del cumplimiento de las obligaciones del
    </p>
    <p style="position:absolute;top:820px;left:127px;white-space:nowrap" class="ft014">producto frente al consumidor
        financiero. Este producto es ofrecido por la red de Bancolombia S.A., limitándose única y exclusivamente al
        <br/>correcto cumplimiento de las instrucciones debidamente impartidas por Cardif Colombia Seguros Generales S.A
        para la prestación del servicio <br/>en dicha red.</p>
</div>
</body>
</html>
```

**Comment by costas80** [comment]
I'm assuming the `<!doctype html`? Maybe also then the namespace declarations and possibly the comments? The HTML must be in general well-formed and valid XHTML. If you need to support HTML that may not be well-formed (and that you cannot control and fix) you can add the `jsoup` dependency and configure it to parse the HTML (you can check the docs about how to do this):
```
builder.withW3cDocument(new W3CDom().fromJsoup(Jsoup.parse(htmlString)), "");
```
My general advice for this kind of thing however would be to first strip down the HTML and progressively add parts until you see what is causing the failure. You should be able to pinpoint the issue quite fast.

**Comment by Ber1984** [comment]
Hey man 
You weren't fucking kidding.
This was my solution.
I changed this line 
```
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml"
      xmlns:o="urn:schemas-microsoft-com:office:office">
```

by this one and worked well. 
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
```

However, your solution of parsing the HTML which is not be well-formed will also work to me. 
Thanks man. 
You're very kind.

**Comment by Ber1984** [comment]
Hey.  I had to use Jsoup to parse the XML but no i'm getting trailling spaces in the final PDF look.
I'm using text-align= justify in css

![image](https://github.com/danfickle/openhtmltopdf/assets/31042386/f6c6196c-342b-462b-a9eb-030116b6cbcf)

This is the code that i'm using 

```String content = this.writer.toString();

				Document parsedDocument = Jsoup.parse(content);
				parsedDocument.outputSettings()
						.syntax(Document.OutputSettings.Syntax.xml);

				PdfRendererBuilder builder = new PdfRendererBuilder();
				builder.toStream(baos);
				builder.withW3cDocument(new W3CDom().fromJsoup(parsedDocument), StringUtils.EMPTY);
				builder.run();

				byte[] pdfContent = baos.toByteArray();
				PDDocument document = PDDocument.load(pdfContent);
				PDDocumentInformation pdDocumentInformation = document.getDocumentInformation();
				document.setDocumentInformation(pdDocumentInformation);
				document.save(baos);
				document.close();```

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="font-family: Arial, Helvetica, sans-serif; font-size: 10pt;margin-left: 3%;margin-right: 3%;text-align: justify">

<table class="seccion_logos">
    <tr>
        <td>
            <img src="$RUTA_IMG/images/logo_bancolombia.png" alt="logo bancolombia"/>
        </td>
        <td align="right" style="width: 700px">
            <img src="$RUTA_IMG/images/logo_cardif.png" alt="logo cardif"/>
        </td>
    </tr>
</table>

<p class="encabezado_fecha" style="margin-top: 50px">$CIUDAD_CLIENTE, $FECHA_DESEMBOLSO</p>

<div class="seccion_cliente" style="display: block; margin-top: 15px">
    <div>
        Sr (a)
    </div>

    <div>
        <strong>$NOMBRE_CLIENTE</strong>
    </div>
    <div>
        <strong>CIUDAD</strong>
    </div>
</div>

<p class="seccion_estimado" style="margin-top: 20px">Estimado Sr (a)</p>

<p>
    Es un gusto darle la bienvenida a nuestra compañía y felicitarlo por su excelente decisión de contratar la <strong>
    PÓLIZA DE SEGURO DE EMPLEADO PROTEGIDO CRÉDITO DE LIBRANZA </strong> exclusivo para clientes de Bancolombia S.A.
</p>
<p>
    Cardif Colombia Seguros Generales S.A, es una compañía de seguros perteneciente al grupo BNP Paribas, uno de los grupos financieros y aseguradores más importantes del mundo en el mercado de Bancaseguros.
</p>
<p>
    La póliza de seguros <strong>827$NUMERO_CREDITO</strong> que ha adquirido contiene el compromiso de su protección por parte de nuestra compañía y es el punto de inicio de una relación en la que dedicaremos nuestro máximo esfuerzo para lograr su completa satisfacción.
</p>

<p>
    Adjunto encontrará el contrato del seguro que adquirió, al final de este documento podrá ubicar un link y un código QR para acceder al detalle de las coberturas y condiciones particulares de su seguro.
</p>

<p>
    Con el objetivo de acceder a los beneficios de su póliza le invitamos a seguir las siguientes indicaciones:
<ul>
    <li>
        Lea su póliza detenidamente, beneficios, coberturas, términos y condiciones. Recuerde que es fundamental que usted esté informado de las características de su seguro.
    </li>
    <li>
        Verifique que sus datos personales estén registrados correctamente. En caso de cualquier error solicite la corrección en las líneas de atención relacionadas en el contrato de seguro.
    </li>
</ul>
</p>

<p>
    Ante cualquier duda, información adicional ó ante la ocurrencia de un siniestro o novedad, le agradecemos se comunique con las líneas de atención indicadas en el contrato de seguro.
</p>

<p>
    Finalmente Agradecemos su preferencia y confianza en nosotros y esperamos seguir satisfaciendo sus necesidades de protección y las de su familia.
</p>

<p>
    Cordial saludo,
</p>

<img style="width: 170px; display: block; margin-top: -13px" src="$RUTA_IMG/images/firma_cardif.png" alt="logo bancolombia"/>

<p>
    <strong>Cardif Colombia Seguros Generales</strong>
</p>
<p class="pie_pagina" style="font-size: 7pt" >
    <strong>Advertencia:</strong> Cardif Colombia Seguros Generales S.A asume exclusivamente la responsabilidad del cumplimiento de las obligaciones del producto frente al consumidor financiero. Este producto es ofrecido por la red de Bancolombia S.A., limitándose única y exclusivamente al correcto cumplimiento de las instrucciones debidamente impartidas por Cardif Colombia Seguros Generales S.A  para la prestación del servicio en dicha red.
</p>

</body>
</html>
```

**Comment by costas80** [comment]
Can't tell. I would suggest you start with a vanilla text block without any styling in HTML and progressively add CSS to get closer to what you want. Trial and error basically until you find what is causing the issue.

**Comment by Ber1984** [comment]
Got it. let me work on it.

**Comment by Ber1984** [comment]
I solved it solving this code 

```
String content = this.writer.toString();

				Document parsedDocument = Jsoup.parse(content);
				parsedDocument.outputSettings()
						.syntax(Document.OutputSettings.Syntax.xml);

				PdfRendererBuilder builder = new PdfRendererBuilder();
				builder.toStream(baos);
				builder.withW3cDocument(new W3CDom().fromJsoup(parsedDocument), StringUtils.EMPTY);
				builder.run();

				byte[] pdfContent = baos.toByteArray();
				PDDocument document = PDDocument.load(pdfContent);
				PDDocumentInformation pdDocumentInformation = document.getDocumentInformation();
				document.setDocumentInformation(pdDocumentInformation);
				document.save(baos);
				document.close();

				logger.info("PDF generated successfully");
				logger.info(filePdf.getPath());
```
