### ISSUE TITLE
ThreadCtx.cleanup(): when to call?

### ISSUE THREAD

**Issue by rototor** [danfickle/openhtmltopdf#94]
I got a Tomcat warning because the ThreadLocal of ThreadCtx where not destroyed when my webapp unloaded. To silence this warning (and remove the potential memory leak) I call 				```ThreadCtx.cleanup();``` in my code after I generated the PDF. 

Should ```PdfBoxRenderer.cleanup()``` also remove the ThreadLocal? And should we document this somewhere, i.e. that you should call ```PdfBoxRenderer.cleanup()``` - at least in a web application?

**Comment by rototor** [comment]
Maybe PdfBoxRenderer should just be an AutoCloseable, so you can use try-with-resources?

**Comment by danfickle** [comment]
Thanks @rototor 
I think some people are still using this with Java 6 so auto close is out. This was definitely an oversight by me. It does say to call ````cleanup```` on the documentation for ````buildPdfRenderer````. I think that is the only way that most users will get an instance of a ````PdfBoxRenderer````.

**Comment by rototor** [comment]
@danfickle AutoCloseable is only available with JDK 1.7+, but Closeable exists since JDK 1.5. If PdfBoxRenderer would extend Closeable and use close() for the cleanup it would be AutoCloseable with JDK 1.7+, because Closeable extends AutoCloseable with JDK 1.7+.

**Comment by danfickle** [comment]
Implemented ```Closeable``` as suggested by @rototor. Thanks.
