### ISSUE TITLE
render \u2264 and \u2265 using verdana font.

### ISSUE THREAD

**Issue by kumarvgit** [danfickle/openhtmltopdf#96]
Hello,
We are using the great FOSS openhtmltopdf :) thanks for providing.
Currently we are using verdana font but greater than equal to symbol is not printer rendered PDF. \u2264 and \u2265.

**Comment by kumarvgit** [comment]
Adding to above point any character after \u00FF is not recognized. code snippet
`           os = new FileOutputStream(htmlFile);
            ITextRenderer renderer = new ITextRenderer((float) 96, 96);
            Document doc = XMLResource.load(new InputSource(url)).getDocument();
            renderer.setDocument(doc, url);
            renderer.layout();
            renderer.createPDF(os);
            os.close();
            os = null;`

**Comment by kumarvgit** [comment]
on little digging, there is a hunch, on opening the generated PDF by adobe it shows encoding as ANSI :( ; if the analogy is correct then how do i set encoding to UTF-8, currently i am using below
`renderer.getFontResolver().addFont("<PATH_TO> verdana.ttf", "utf-8", BaseFont.NOT_EMBEDDED);`

**Comment by danfickle** [comment]
It looks like you are using FlyingSaucer rather than this project. Also, most cases, you want to embed the subsetted font.

**Comment by kumarvgit** [comment]
@danfickle Yes, after the post i realized the same, anyways thank you for the same. Its resolved by adding
@font-face {
-fs-pdf-font-embed: embed;
-fs-pdf-font-encoding: Identity-H;
}
in CSS.
