### ISSUE TITLE
Paginated table header with border-collapse

### ISSUE THREAD

**Issue by Epimetheus89** [danfickle/openhtmltopdf#97]
Currently using `-fs-table-paginate: paginate;` as css property on a table overwrites the `border-collapse: collapse;` property. This causes the border in a header line to have spaces between the cells:
![screenshot from 2017-05-18 18-24-58](https://cloud.githubusercontent.com/assets/8805679/26212878/5b075cd4-3bf7-11e7-80b4-43d96245c845.png)
The reason for this can be found in this line:
https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-core/src/main/java/com/openhtmltopdf/css/style/CalculatedStyle.java#L1152
Is it possible to fix that issue or is there another solution to have collapsed borders in a repeated header row of a table?

**Comment by danfickle** [comment]
Hi @Epimetheus89 
I commented the second part of that line and table pagination with collapsed borders seems to work fine with my minimal example. See screenshot below. I'm somewhat confused as to why that second part is there but I'll comment it out so the onus is on the user to confirm that it works with their layout.

I'll also try to do a release for you. Thanks for finding the problematic line.

![table-pagination-with-collapsed-borders](https://cloud.githubusercontent.com/assets/1415728/26281874/7de60564-3e47-11e7-9234-3a9a782b6a70.png)

From this example:
````html
<html>
<head>
<style>
@page {
  size:  200px 80px;
  margin: 0;
}
table {
	-fs-table-paginate: paginate;
	border-collapse: collapse;
	font-size: 16px;
}
td, th {
	border-bottom: 2px solid red;
}
</style>
</head>
<body>

<table>
  <thead>
    <tr><th>H1</th><th>H2</th></tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>11</td></tr>
    <tr><td>2</td><td>12</td></tr>
    <tr><td>3</td><td>13</td></tr>
    <tr><td>4</td><td>14</td></tr>
    <tr><td>5</td><td>15</td></tr>
    <tr><td>6</td><td>16</td></tr>
    <tr><td>7</td><td>17</td></tr>
    <tr><td>8</td><td>18</td></tr>
    <tr><td>9</td><td>19</td></tr>
    <tr><td>10</td><td>20</td></tr>
  </tbody>
</table>

</body>
</html>
````

**Comment by rototor** [comment]
I just tested this with some rather complex multipage tables and it really seems to make no difference, i.e. this change does not break tables which had ```border-collapse:collapse``` specified, but also had table pagination activated. Strange, why was this disabled in the first place?

**Comment by Epimetheus89** [comment]
Thanks for fixing this! I also took a look into the implementation and could not explain or think of a scenario in that this line would make any sense.
The issue can now be closed if you like.
